rclone/rclone

oauthutil/oauthutil.go

I accidentally removed the link text.

Fix missing link text.

---

fs/filter.go
fs/filter_test.go
fs/operations.go

It's very useful to my usage. I'm use to move very old files to cheaper alternatives. I hope be useful to others.
Thank you

Add support to filter files based on their age

---

docs/content/docs.md
fs/config.go
fs/config_test.go
fs/operations_test.go
fs/testdata/enc-invalid.conf
fs/testdata/enc-short.conf
fs/testdata/enc-too-new.conf
fs/testdata/encrypted.conf
fs/testdata/plain.conf
fstest/fstests/fstests.go

See #317 for details.
Use `rclone config` to add/change/remove password.

Add configuration file encryption

---

local/local.go

Add mutex to "warned" map.

---

fs/hash.go
local/local.go

Fix incomplete local hashes.

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md
Makefile
README.md
bin/make_manual.py
cmd/cmd.go
crypt/cipher_test.go
docs/content/install.md
docs/content/licence.md
docs/content/privacy.md
docs/content/s3.md
docs/content/swift.md
docs/content/yandex.md
docs/layouts/chrome/footer.copyright.html
fs/redirect_stderr_windows.go
s3/s3.go

I took a quick comb through the HTTP links in the repository and changed them to HTTPS where HTTPS was functional

Update references from HTTP to HTTPS where possible

---

drive/drive.go

This fixes the note @ncw made in #1359 
Unsure if this is the most efficient way of writing this. Let me know if there's a better way. I've never written anything in Go before :-)

drive: only request owner field when using --drive-auth-owner-only

---

docs/content/dropbox.md

dropbox: typo

---

http/http.go

Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

fix for caddy web server

---

drive/drive.go

Reuses the same fields for all endpoints for simplicitys sake.
Should solve remaining part of #1346

drive: use explicit fields for all endpoints

---

s3/s3.go

Added Ohio and London S3 regions.

Add us-east-2 (Ohio) and eu-west-2 (London) S3 regions

---

docs/content/local.md
local/local.go

Let me know if I should go about this a different way. I based this on how `--copy-links` is implemented.
Fixes #1411

Add --local-no-unicode-normalization flag

---

docs/content/s3.md

cf.: https://github.com/ncw/rclone/issues/1455

Add section on required IAM permissions.

---

docs/content/s3.md

Current doc mentioned lack of ETag and metadata support
which since has been long fixed in many upstream Minio releases.

Minio supports ETags and metadata.

---

docs/content/docs.md

[docs] Clarify how 'move' may use server side copying

---

fs/config.go
fs/fs.go
fs/http.go

http: add --user-agent option. 

---

docs/content/drive.md
docs/content/overview.md
drive/drive.go
drive/drive_internal_test.go

This addresses Drive cleanup, listed in #575.
Cleanup empties the trash folder.

drive: implement cleanup (empty trash) - addresses #575

---

docs/content/sftp.md

Should probably specify something about simple password-based auth, to avoid #1743.

Copy edit the SFTP guide

---

docs/content/docs.md

Corrected default --log-level value in the usage documentation.

Corrected default log-level value

---

docs/content/about.md
docs/content/docs.md
docs/content/s3.md

An initial crack at docs for basic configuration and usage of DigitalOcean Spaces. See: #1750

Initial docs for usage with DigitalOcean Spaces.

---

fs/config.go

Deletes the console confirmation request.
An early interface
https://github.com/Ordissimo/rclone-ui-config

Add variable autoconfirm.

---

oauthutil/oauthutil.go

Added a return code, Corrected by ncw

---

cmd/mountlib/mount.go

Signed-off-by: Ernest Borowski <er.borowski@gmail.com>

mountlib: check if directory is not empty before mounting - fixes #1386

---

cmd/config/config.go
fs/config.go

Added a method to update the password.

---

docs/content/filtering.md
fs/filter.go
fs/filter_test.go
fs/fs.go
fs/operations.go
fs/operations_internal_test.go
fs/operations_test.go
fs/walk.go
fs/walk_test.go

creating --exclude-if-present

---

crypt/crypt.go

This change lets the crypt remote implement the DirChangeNotify when the wrapped file system implements it.

crypt: implement DirChangeNotify

---

cmd/all/all.go
cmd/touch/touch.go
cmd/touch/touch_test.go

I implemented touch command with two flags (-C and -t).
I also add simple tests.

Issue 1594 touch

---

docs/content/drive.md
drive/drive.go

This addresses #839 following the suggestions from @mwitkow in that thread.

Add service account support to drive backend

---

docs/content/install.md
docs/content/install.sh

Here are two scripts working on Linux/MacOS/BSD systems for install automation. I also added an information about them at the begging of install manual page.
Script was tested on Linux, MacOs and FreeBSD. If someone is willing, I'll be grateful for testing it on theirs machine and maybe report results here - especially for NetBSD and OpenBSD.

curl install for rclone #1856

---

cache/cache.go
cache/cache_internal_test.go
cache/cache_test.go
cache/cache_unsupported.go
cache/directory.go
cache/handle.go
cache/object.go
cache/plex.go
cache/storage_memory.go
cache/storage_persistent.go
cmd/cachestats/cachestats.go
cmd/cachestats/cachestats_unsupported.go
docs/content/cache.md
fstest/fstests/gen_tests.go

Some refactoring for `cache`. Want to validate first in a PR

cache: plex integration, refactor chunk storage and worker retries

---

docs/content/install.sh

As requested in #1881 , installation script now terminates before downloading if the latest version of rclone is already installed.

version check in curl installation

---

cache/cache.go
cache/cache_internal_test.go
cache/directory.go
cache/object.go
cache/storage_persistent.go

Testing out entries fixes before merge

cache: refactor entries caching pattern for #1904

---

cache/directory.go
cache/object.go

Checking test suite, it's a pretty deep chance even if it's a few lines only

cache: fix Windows separator issue for #1904

---

docs/content/pcloud.md
docs/content/swift.md
docs/content/webdav.md
qingstor/qingstor.go

qingstor: fix 'QingClound' typo

---

docs/content/install.sh

Implemented enhancement proposed in #1949 
I decided to run the check for the tool for extracting zips before checking if rclone is up to date - curl generates an output which could be confusing for the user. Since the user is using the script I think they should install that tool even if update is not necessary at the moment.
Also printing information with multiple lines now uses `printf` instead of `echo`.

Installation script check for a tool to extract zip archives #1949

---

backend/local/local.go
fs/fs.go

FireExists does not fail if permission is denied 

---

cmd/mountlib/mount.go
vfs/help.go

* Title cleanups
* Typos
* `rclone mount vs rclone sync/copy` update with `File Caching`

Clean up mount.go and vfs/help.go docs

---

backend/amazonclouddrive/amazonclouddrive.go

Use the [Amazon Drive Changes API](https://developer.amazon.com/public/apis/experience/cloud-drive/content/changes) to invalidate cache entries using the `DirChangeNotify` interface.
The initial retrieval of all changes without a checkpoint can take multiple minutes for large libraries, hence the latest retrieved checkpoint is stored in the config file to allow fast resumption after a restart.
From my experience the checkpoint tokens can be copied between rclone instances.

amazonclouddrive: implement DirChangeNotify

---

CONTRIBUTING.md

can someone kindly confirm that this indeed the best approach to run integration tests?

docs: Update integration testing guide

---

backend/sftp/sftp.go

As discussed in #1957  - don't consult the config file on each and every iteration.

sftp: performance: don't consult config file outside of Fs setup

---

backend/drive/drive.go

Use contains for name matching in list to work around #1675.

drive: use contains for name matching in list

---

backend/cache/cache.go

Trim "/" from the root path to fix "slice bounds out of range" panic in directory.go:98.
Fixes #1945

cache: clean root path

---

cmd/touch/touch_test.go

cmd: rewrite touch tests #1934

---

backend/cache/cache.go
backend/cache/storage_persistent.go
docs/content/cache.md
fstest/test_all/test_all.go

Just checking you are happy with this new flag @remusb 
I need it to fix the integration tests failing with simultaneous runs of the cache backend!

Cache db wait time

---

backend/cache/cache.go
backend/cache/cache_internal_test.go
bin/make_manual.py
cmd/all/all.go
cmd/cmd.go
cmd/rc/rc.go
cmd/serve/httplib/httpflags/httpflags.go
docs/content/cache.md
docs/content/docs.md
docs/content/rc.md
docs/layouts/chrome/navbar.html
fs/rc/internal.go
fs/rc/rc.go
fs/rc/rc_new.go
fs/rc/rc_old.go
fs/rc/rcflags/rcflags.go
fs/rc/registry.go

Hi @ncw 
I've added support for the RC module in cache and updated documentation. I'm opening as a PR to discuss if I can add something more in the RC. To me, it looks final as it has all the support I initially wanted to add too.
I've also updated the docs of rc with the params.
PS: This is on a new branch cause I wanted to rebase master.

cache rc support

---

backend/s3/s3.go
docs/content/about.md
docs/content/s3.md

Documentation on how to configure IBM COS using Rclone.

Documentation for IBM COS (S3) configuration.

---

fs/config.go
fs/config/configflags/configflags.go
fs/sync/sync.go
fs/sync/sync_test.go

> implemented --ignore-errors flag in config
> added unit test in sync

sync: implement --ignore-errors - fixes #642

---

cmd/ncdu/ncdu.go
docs/content/commands/rclone_ncdu.md

Added Control+L key to refresh screen. Not sure if this is the
best choice, but it appears to be somewhat common.

ncdu: added a "refresh" key - for #2174

---

backend/s3/s3.go
backend/swift/swift.go
docs/content/docs.md
docs/content/s3.md
docs/content/swift.md
fs/config.go
fs/config/configflags/configflags.go

I'm not much of a go programmer, but taking a crack at this one. I haven't added or run tests because I don't know how :)
refs #2199

Adds --user-server-modtime flag

---

docs/content/install.sh

Small fix to support easy install on arm arm64 systems like the Rock64

[install] Add arm64/aarch64 support

---

backend/webdav/api/types.go

WebDAV: Ignore Reason-Phrase in status line #2281

---

cmd/cmd.go

Fixed a typo

---

docs/content/onedrive.md

Adds a troubleshooting section that explains the "domain in unmanaged state" error.
I just noticed that my editor stripped all white spaces from line endings. Do you have a problem with that?
Partly fixes: #1975

onedrive: Add troubleshooting to docs

---

cmd/cmd.go
cmd/siginfo_darwin.go
cmd/siginfo_others.go

I am not sure if it is a correct place to put siginfo handler registration.

cmd: add siginfo handler

---

cmd/cmd.go
cmd/mountlib/mounttest/fs.go
fs/fs.go
fs/operations/operations.go
fs/operations/operations_test.go
fs/sync/sync_test.go
fstest/fstest.go
fstest/fstests/fstests.go
fstest/run.go

fs: calculate ModifyWindow each time on the fly instead of relying on global state - see #2319

---

cmd/cmd.go
docs/content/docs.md

this fixes #2339 
It is a simple addition to the Run command, upon testing it works for my use case as specified in the issue. while this is a simple code, I don't know if it works for other use cases  and if some other bugs sprout from the addition of this.

cmd: added retries-sleep flag

---

cmd/all/all.go
cmd/deletefile/deletefile.go

I think that's it. Please let me know if that's what you had in mind and if there are any changes or additions required.

cmd: deletefile command - fixes #2286

---

fs/config/config.go
fs/log/redirect_stderr_unix.go

I've came up with a fix for unix systems. On Windows the behaviour should remain the same, that is the prompt will still be going to Stderr.

password prompt in log unix #2220

---

docs/content/webdav.md

Added a paragraph about Macaroons; added link to script that obtains a Macaroon, as suggested at https://github.com/ncw/rclone/issues/2360#issuecomment-402519344

webdav.md: about Macaroons

---

fs/sync/sync.go
fs/sync/sync_test.go

This PR fixes an issue with the `--delete-empty-src-dirs` flag on move where not all empty dirs would not get delete on successful move.
Fixes - #2372

move: fix delete-empty-src-dirs flag - fixes #2372

---

backend/drive/drive.go
backend/drive/drive_internal_test.go

This change adds support for Google Docs when calling `Fs.list` with a `title` filter.
It does this by changing API query from `name='file.ext'` to `(name='file.ext' or name='file')` when `ext` is in the configured `Extensions`.
All functions calling `Fs.list` will now handle Google Docs when necessary.
Fixes #2399

drive: handle Google Docs in Fs.list

---

backend/webdav/webdav.go

this change adds the depth parameter to listAll and readMetaDataForPath.
this allows recursive calls of these methods with a different depth
header.
Sharepoint won't list files if the depth header is != 0. If that is the
case, it will just return a error 404 although the file exists.
Since it is not possible to determine if a path should be a file or a
directory, rclone has to make a request with depth = 1 first. On success
we are sure that the path is a directory and the listing will work.
If this request returns error 404, the path either doesn't exist or it
is a file.
To be sure, we can try again with depth set to 0. If it still fails, the
path really doesn't exist, else we found our file.
fixes #2426

webdav: sharepoint recursion with different depth

---

backend/drive/drive.go

This change implements `fs.ListRer` for `drive` by combining multiple `list` calls into a single API request.
This works by combining many `'%s' in parents` filters into one expression.
To list the contents of directories a, b and c, the the following requests will be send by the regular `List` function:
```
trashed=false and 'a' in parents
trashed=false and 'b' in parents
trashed=false and 'c' in parents
```
These can now be combined into a single request:
```
trashed=false and ('a' in parents or 'b' in parents or 'c' in parents)
```
The implementation of `ListR` will put up to 50 `parents` filters into one request.
It will  use the `--checkers` value to specify the number of requests to run in parallel.
In my tests, these batch requests were up to 20x faster than the regular method.
I …

drive: implement ListR

---

backend/onedrive/onedrive.go
docs/content/overview.md

This pull request implements DirMove for the OneDrive backend and should be able to fix (implement) #197 :)

onedrive: implement DirMove - fixes #197

---

fs/accounting/accounting.go
fs/accounting/stats.go

implements #2405 
added `rclone rc core/stats` to get stats output in JSON format

stats: added stats output for rc calls

---

backend/jottacloud/jottacloud.go

Add JMd5 header if MD5 is available

Jottacloud: Fix wrong error check

---

cmd/all/all.go
cmd/copyurl/copyurl.go
cmd/serve/restic/restic.go
fs/operations/operations.go
fs/operations/operations_test.go

cmd: add copyurl command

---

backend/jottacloud/api/types.go
backend/jottacloud/jottacloud.go

Stuff I forgot to implement in the initial pull request. In theory Jottacloud also supports link sharing but there is no up to date documentation on how to do it.

jottacloud: Implement MimeTyper and Abouter interface.

---

backend/local/local.go

Currently, when -L is enabled, listing a directory fails if a bad symlink is found.
This PR simply ignore dangling symlinks.

Fix directory listing when -L is enabled and a bad symlink is encountered

---

docs/content/docs.md
fs/log.go
fs/log/log.go

Show microseconds for easier finding performance bottlenecks.

log: Add --log-format flag #2424

---

backend/cache/cache.go
backend/cache/handle.go

This change adds a `cache/fetch` rc method to allow caching of specific file chunks.
The command is inspired by the feature request in #2407.
An example request to fetch the first 10 and the last chunk looks like this:
```
rclone rc cache/fetch chunks=:10,-1 file=hello file2=home/goodbye
```
The syntax for the `chunks` parameter is based on the Python slice syntax. It allows indexing from the beginning of the file using positive indices like `:10` and from the back with negative indices like `-10:`.

 cache: add cache/fetch rc method

---

fs/config/config.go

Avoid creating empty default configuration directory when user supplies path to config file

---

backend/cache/object.go

Improve cache backend performance.

cache: Not sending info request for cached chunk

---

CONTRIBUTING.md
backend/cache/cache.go
docs/content/cache.md

Also, added a minor fix for code format in `CONTRIBUTING.md`
Signed-off-by: Anagh Kumar Baranwal <anaghk.dos@gmail.com>

cache: documentation fix - Fixes #2519

---

backend/jottacloud/jottacloud.go
docs/content/jottacloud.md
docs/content/overview.md
fstest/test_all/test_all.go

Basic implementation. No paging mechanism, since the API method does not support it to my knowledge. Not tested for all kinds of operations, but ls and tree seem to work.

Implemented --fast-list for Jottacloud (#2532)

---

backend/jottacloud/jottacloud.go

Fixes TestIntegration/TestFsListRSubdir, discovered after merge of #2545.

jottacloud: fix for --fast-list

---

backend/azureblob/azureblob.go
backend/azureblob/azureblob_internal_test.go
cmd/all/all.go
cmd/settier/settier.go
fs/fs.go
fs/operations/operations.go
fstest/fstests/fstests.go

Added new command `settier` which changes object's tier on remote if supported, added optional interfaces to `SetTierer` and `GetTierer` to support this feature.

Add SetTier command 

---

backend/jottacloud/jottacloud.go
backend/jottacloud/replace.go
backend/jottacloud/replace_test.go

#2531 has been open long enough. Quick and simple fix for this.

jottacloud: Fix handling of reserved characters. fixes #2531

---

docs/content/rc.md
fs/rc/rc.go

Implemented basic CORS support as discussed in the #2575.
Tested with Angular-httpclient in Firefox and Chrome.
There is one TODO left I can't solve with my current 5minute GO skills, the writeError function.
I'll squash and rebase if this is solved.
Thank you for your time, any help is appreciated.

WIP: rc: basic CORS support #2575 

---

vfs/dir.go
vfs/dir_test.go
vfs/vfs.go

Reduce the number of nodes purged from the `dir-cache` when `ForgetPath` is called by `poll-interval`. This is done by only forgetting the cache of the received path and invalidating the parent folder cache by resetting `*Dir.read`.
The parent will read the listing on the next access and reuse the `dir-cache` of entries in `*Dir.items`.
This change is inspired by a discussion in the forums, but not argued otherwise.
https://forum.rclone.org/t/share-your-rclone-mount-command-here/4601/12

vfs: reduce directory cache cleared by poll-interval

---

README.md

Improvement of readme to match the website and better readability.
No.

Improved and updated the readme

---

backend/yandex/api/client.go

It simplifies the code by removing unnecessary nil checks.
No, the change is cosmetic.

backend: remove redundant nil checks around loop

---

bin/make_backend_docs.py
bin/make_manual.py
cmd/copy/copy.go
cmd/copyto/copyto.go
cmd/move/move.go
cmd/moveto/moveto.go
cmd/sync/sync.go

* Added the corresponding documentation
* Also fixed the python version for the `make_backend_docs.py` & `make_manual.py` scripts
Fixes #2507

Added docs to use the progress flag for real time statistics

---

docs/content/mega.md

Added docs to check for key generation on Mega
Closes #2480 
PS: Changes can be previewed @ https://fix-mega-docs--darthshadow-rclone.netlify.com/

Added docs to check for key generation on Mega

---

cmd/ncdu/ncdu.go
cmd/ncdu/scan/scan.go

This change allows the removal of directories or files in the ncdu mode. Deleted files or directories will update the in-memory cache to keep the listing up-to-date. The new Directory size and count is then populated upwards until the root directory is reached.
A whole new scan would have been really resource-intensive, so I added the remove option for the in-memory cache.
#2571

ncdu: delete option

---

README.md

I expanded the Installation & Docs section with links to the website and added a link to the full list of storage providers and features.

Added some more links for easier finding

---

backend/azureblob/azureblob.go

Manually setting TryTimeout value for Azure SDK to effectively an "infinite" amount of time (365 days) as rclone currently manages idle connection timeouts.  The default TryTimeout within the Azure storage blob SDK is only 1 minute and causes the Azure server side to forcefully close the HTTP connection when the time is met even though there is likely an active data transfer occurring.   See below for example of logging seen in this situation:
```
2018-11-04 12:13:00 NOTICE: cp123: Removing partially written file on error: context deadline exceeded
2018-11-04 12:13:00 DEBUG : cp123: Received error: context deadline exceeded - low level retry 1/10
2018-11-04 12:14:16 NOTICE: cp123: Removing partially written file on error: context deadline exceeded
2018-11-04 12:14:16 DEBUG : cp123: …
```

azureblob: Avoid context deadline exceeded error by setting a large TryTimeout value - Fixes #2647

---

docs/content/faq.md

Update PROXY section of the FAQ

---

backend/s3/s3.go

S3 : add Glacier storage class

---

docs/content/s3.md

s3 : update doc for Glacier storage class : related to #923

s3 : update doc for Glacier storage class

---

README.md

This PR fixes the broken link to the COPYING file in the README.
no.

readme: fix copying link

---

fs/accounting/stats.go
fs/operations/operations.go
fs/operations/operations_test.go

Add an additional information message to check command to add the total matching files count
No, AFAIK

fs/check: Add total matching files stats message

---

backend/jottacloud/jottacloud.go

Quick PR that implements support for 2fa to the jottacloud backend. Should also improve error handling during config a bit.

jottacloud: add support for 2-factor authentification fixes #2722

---

backend/b2/b2.go
backend/b2/upload.go

Add flag to disable computing file checksum in b2
https://github.com/ncw/rclone/issues/2892

b2: added disable sha1sum flag

---

docs/content/b2.md

docs: B2 Application Key usage clarifications

---

backend/b2/b2.go

Backblaze introduced free egress for B2 Cloud Storage when files are [downloaded through the Cloudflare network](https://www.backblaze.com/blog/backblaze-and-cloudflare-partner-to-provide-free-data-transfer/). This requires using a custom url or endpoint for downloads instead of the `downloadUrl` provided by `b2_authorize_account`.
https://github.com/ncw/rclone/issues/2808

b2: allow manual configuration of backblaze downloadUrl - fixes #2808

---

backend/jottacloud/jottacloud.go

Quick fix for the broken token refresh with Jottacloud.

jottacloud: fix token refresh

---

lib/atexit/atexit.go

This PR refines the `atexit` library mainly to provide the possibility for backends to gracefully cancel transfers when rclone is interrupted by the user.
Forum post that initiated this PR: https://forum.rclone.org/t/onedrive-tmp-issue/8263

[WIP] atexit: allow functions to be unregistered

---

backend/azureblob/azureblob.go

Enable MD5 checksums when uploading a multi-block (a.k.a. multipart) file to Azure Blob Storage
git git push  assuming that the API does not supports MD5 checksum in the `PutBlockList` call, but according to the doc it's supported (https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list) and actually it was already supported by the underlying API helpers:
* The azureblob backend propagates the headers when committing the block list: https://github.com/ncw/rclone/blob/b353c730d8d248c55ab86d9efd889427457b4ab9/backend/azureblob/azureblob.go#L1362
* Checksum is read from the headers in the `CommitBlockList` https://github.com/ncw/rclone/blob/b353c730d8d248c55ab86d9efd889427457b4ab9/vendor/github.com/Azure/azure-storage-blob-go/azblob/url_block_blob.go#L99
* Then the MD5 …

Enable MD5 checksums when uploading a multi-block file to Azure Blob

---

backend/onedrive/onedrive.go

This PR implements a workaround for two known issues related to some specific filenames.

onedrive: Always add trailing colon to path when addressing items - fixes #2720, #3039

---

docs/layouts/chrome/footer.copyright.html

docs: update copyright to current year

---

CONTRIBUTING.md
MANUAL.md
docs/content/alias.md
docs/content/b2.md
docs/content/cache.md
docs/content/commands/rclone_cat.md
docs/content/commands/rclone_config_update.md
docs/content/commands/rclone_copyurl.md
docs/content/docs.md
docs/content/drive.md
docs/content/filtering.md
docs/content/hubic.md
docs/content/install.sh
docs/content/s3.md
docs/content/swift.md
docs/content/union.md
docs/content/webdav.md

docs: fix typos

---

fs/operations/lsjson.go

- [x ] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

add encryptedPath to lsjson-  fixes 3094

---

docs/content/drive.md

doc: Fix "conververt" typo

---

backend/drive/drive.go

When trying to copy or move between a TeamDrive and normal GDrive the SupportsTeamDrive flag will not be set since the destination isnt aware of the Source
Nope

Fix move and copy from TeamDrive to GDrive

---

docs/content/commands/rclone_mount.md

Updated mount command docs

---

backend/mega/mega.go
docs/content/overview.md

Fixes #3138
Add `cleanup` support for Mega remote
#3138 
Also, I really need to remember to run golint.

mega: add cleanup support

---

fs/fserrors/error.go

This change uses the `lib/errors` in the `fs/fserrors` package to test for specific errors in an error chain.
All wrapped errors in the `fs/fserrors` package now have a `Cause() error` method to allow nested errors to be also checked with `errors.Walk()`.
Uses features introduced by #2962

fserrors: use errors.Walk for the wrapped error types

---

backend/ftp/ftp.go

Adds 60s timeout for the FTP List command.
#3086
- [ x ] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ x ] I have added tests for all changes in this PR if appropriate.
- [ x ] I have added documentation for the changes if appropriate.
- [ x ] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ x ] I'm done, this Pull Request is ready for review :-)

Add FTP list timeout

---

docs/content/docs.md
fs/accounting/stats.go
fs/config.go
fs/config/configflags/configflags.go

I coded to resolve #3075
I am making it now. It can be read at [this link](https://forum.rclone.org/t/timestamp-option-for-progress/9292)

Add --progress timestamp options

---

docs/content/sftp.md

Add documentation for sftp remote's `about` support.
No

docs: add sftp about documentation

---

backend/s3/s3.go

Wasabi has a EU Central endpoint for a couple months now, so add it to the list.
Signed-off-by: Robert Marko <robimarko@gmail.com>

s3: add config info for Wasabi's EU Central endpoint

---

backend/s3/s3.go
docs/content/s3.md

Fixes #3224
https://forum.rclone.org/t/suspected-bug-in-s3-or-compatible-sync-logic-to-glacier/10187

Fixes 3224

---

docs/content/onedrive.md

I think an option has been added and now the manual for OneDrive is off by one.
Documentation update.
No

Microsoft OneDrive now has the number 18

---

cmd/serve/httplib/httplib.go
cmd/serve/restic/restic.go
cmd/serve/restic/restic_appendonly_test.go
cmd/serve/restic/restic_privaterepos_test.go
cmd/serve/restic/restic_test_utils.go

This is WIP to make it easier to discuss changes.

cmd: add support for private repositories in `serve restic` - fixes #3247

---

bin/make_changelog.py

Update `make_changelog.py` to support semver which rclone started using from `v1.47.0` onwards.

Update make_changelog.py to support semver

---

fs/rc/job.go
fs/rc/job_test.go

Depends on #3257
Add additional call to HTTP server that would allow stopping an already running async job. This PR uses context to propagate stop signal to lower levels.

jobs: add ability to stop async jobs

---

go.mod
go.sum
vendor/github.com/jlaffaye/ftp/ftp.go
vendor/github.com/jlaffaye/ftp/parse.go
vendor/modules.txt

Fix an issue with symlinks on some FTP remotes.
Fixes #3283

Update github.com/jlaffaye/ftp to Fix Symlink Issue

---

cmd/ncdu/ncdu.go
go.mod
go.sum
vendor/github.com/atotto/clipboard/.travis.yml
vendor/github.com/atotto/clipboard/LICENSE
vendor/github.com/atotto/clipboard/README.md
vendor/github.com/atotto/clipboard/clipboard.go
vendor/github.com/atotto/clipboard/clipboard_darwin.go
vendor/github.com/atotto/clipboard/clipboard_unix.go
vendor/github.com/atotto/clipboard/clipboard_windows.go
vendor/github.com/atotto/clipboard/go.mod
vendor/modules.txt

Add support for either displaying or copying to clipboard the current path in ncdu.
#3265

ncdu: Display/Copy Current Path

---

backend/azureblob/azureblob.go
docs/content/azureblob.md

Addressing issue #3281 
Added support for azure storage emulator to test things locally
#3281 
https://forum.rclone.org/t/connecting-to-azure-emulator/10532
Tested manually

Azure Storage Emulator support

---

backend/swift/swift.go

Trying to capture segments info during upload to swift backend and delete if there is error duing upload object.
link question :[https://forum.rclone.org/t/rclone-does-not-delete-segments-when-move-object-fail-with-swift-openstack-backend/10618](https://forum.rclone.org/t/rclone-does-not-delete-segments-when-move-object-fail-with-swift-openstack-backend/10618)

Fix rclone does not delete segments when move object fail with swift Openstack backend

---

backend/b2/api/types.go
backend/b2/b2.go
docs/content/overview.md

b2: Implement link sharing #2178

---

fs/sync/sync_test.go

SyncSuffix test fix #3272

---

backend/b2/b2.go

make the download auth use the correct path
add a `hasPermission` func to check if the applicationkey can share files
add docs for `downloadurl` re public bucket
#3314

b2: Fix link sharing #3314

---

docs/content/webdav.md

Add missing documentation
Discussed via private email exchange with Nick

webdav: add docs for using bearer_token_command with oidc-agent

---

docs/content/docs.md
fs/config.go
fs/config/configflags/configflags.go
fs/operations/operations.go
fs/operations/operations_test.go
fs/sync/sync.go
fs/sync/sync_test.go

Implement rsync's --compare-dest & --copy-dest flags to complement the existing --backup-dir to help with incremental backup strategies.
Discussed in #3278 
This depends on my other PR #3272 to work with --backup-dir

Implement --compare-dest & --copy-dest

---

docs/content/filtering.md

Fixes some typos in the demonstration examples of the filtering commands. Most of them are trivial but the last three could cause some genuine confusion.
No

Docs: Fix typos in filtering demonstrations

---

fs/log.go

improvements for json logs to indicate information more precisely.
https://github.com/rclone/rclone/pull/3373
- [v] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [v] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [v] I'm done, this Pull Request is ready for review :-)

add object and objectType in json logs

---

docs/content/rc.md
fs/accounting/stats_groups.go
fs/rc/jobs/job.go
fs/rc/jobs/job_test.go

This adds ability to reset all or specific group of stats with a call to the server.

accounting: add call to clear stats

---

backend/b2/b2.go

fix the regression caused by #3377
move the directory check from the list function to the link function
**please run the integration test before merging**
this only fixes the symptoms, not the underlying problem, as noted in my email.
discussed in private email exchange

b2: link sharing

---

cmd/rcd/rcd.go
fs/rc/rc.go
fs/rc/rcflags/rcflags.go
fs/rc/rcserver/rcserver.go
fs/rc/rcserver/rcserver_test.go

1. Check if an update is requested by user before checking WebGUI Github releases for the latest version.
1. Add command-line argument to change the Access-Control-Allow-Origin.

Access control for CORS

---

fs/cache/cache.go

cache: correctly handle fs.ErrorIsFile in GetFn - fixes #3424

---

docs/content/about.md
docs/content/sftp.md

Closes #2152 
Add stub docs for C14
Also add link to rsync.net's own documentation for SFTP backend.
#2152 
- [ X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ X] I have added documentation for the changes if appropriate.
- [X ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).

2152 docs c14

---

docs/content/rc.md

- Added description for parameters for the web-gui.

Documentation update for web-gui

---

backend/fichier/api.go

Fix #3298 
#3298 
@ncw please check if I missed another code part where we need to replace or restore names, all tests succeed and the broken files I found work now, but I might have missed more.

fichier: fix filename character encoding

---

backend/local/fadvise_unix.go

It relates to #3419 and removes fadivise syscall from hot read path.
Before we issued an additional syscall periodically on a hot path.
This patch offloads the fadvise syscall to a dedicated go routine.

backend/local: fadvise run syscall on a dedicated go routine

---

cmd/help.go

Fixes "syntax error near unexpected token `<'" if bash is run with the posix mode on.
https://github.com/rclone/rclone/issues/3489

Make autocomplete compatible with bash's posix mode

---

docs/content/googlephotos.md

Spell out google photo download limitations

---

docs/content/install.md

Fix typo in documentation.
Yes: https://github.com/rclone/rclone/pull/3544#issuecomment-532503731

Fixed typo in Docker image doc.

---

backend/box/api/types.go
backend/box/box.go
docs/content/box.md
go.mod
go.sum
lib/jwtutil/jwtutil.go
vendor/github.com/youmark/pkcs8/.gitignore
vendor/github.com/youmark/pkcs8/.travis.yml
vendor/github.com/youmark/pkcs8/LICENSE
vendor/github.com/youmark/pkcs8/README
vendor/github.com/youmark/pkcs8/README.md
vendor/github.com/youmark/pkcs8/pkcs8.go
vendor/modules.txt

Allow passing in a Box config.json file when configuring a Box remote. Also potentially paves the way for JWT auth in other apps.
[2582](https://github.com/rclone/rclone/issues/2582)
Almost...

Allow JWT auth with Box

---

cmd/serve/httplib/serve/dir.go

Write the template to a buffer to catch render errors

---

cmd/rcd/rcd.go

Don't create files outside of target directory while unzipping in `cmd/rcd.go`.
Fixes #3529 reported by Nico Waisman at Semmle Security Team

cmd/rcd: Address ZipSlip vulnerability

---

backend/s3/s3.go

Try to Resolve https://github.com/rclone/rclone/issues/2375
Support copy large object in S3.
No, I think the PR is a better place to discuss the implementation.
---
This PR is almost done, but here are something need help. It seems that everything works expected except that the progress bar will not update for a multipart copy in S3, and I can't find a proper API to do this. Is there some hints to fix it? @ncw

WIP: backend/s3: support for multipart copy

---

MANUAL.html
MANUAL.md
MANUAL.txt
docs/content/faq.md
rclone.1

docs: fix spelling

---

docs/content/webdav.md

Enhance the WebDAV documentation with information regarding the flags that are required to make Rclone work correctly with SharePoint.
fixes #3564 
#3564

documentation: add sharepoint required flags fixes #3564

---

backend/webdav/odrvcookie/fetch.go

Currently, the sharepoint login doesn't parse an erroneous response returned by sharepoint.
This change tries to parse the returned XML into a second SharepointError struct which then
holds a detailed error message.
example output:
```
2019/10/02 15:40:30 Failed to create file system for "hs:": wst:FailedAuthentication: Authentication Failure (AADSTS50126: Invalid username or password.)
```
#3176 showcases an example where this error handling would have been useful.

webdav: parse and return sharepoint error response

---

README.md

- [X ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ X] I have added documentation for the changes if appropriate.
- [ X] I'm done, this Pull Request is ready for review :-)

Fix 1fichier link in Readme

---

cmd/serve/dlna/cds.go

When there is both a .nfo and a .mp4, they were being associated only with
the .nfo.
#3588

dlna: associate subtitles with all possible media nodes

---

docs/content/rc.md
fs/accounting/stats_groups.go

Adding quotes to fix the rendering issues in rc docs section

rc docs: fix code section not rendering properly due to missing quotes

---

docs/content/faq.md

typo fix
- [v] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [v] I have added tests for all changes in this PR if appropriate.
- [v] I have added documentation for the changes if appropriate.
- [v] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [v ] I'm done, this Pull Request is ready for review :-)

docs: typo fix in faq.md

---

backend/putio/error.go
backend/putio/fs.go

This PR completes a TODO item at: https://github.com/rclone/rclone/blob/41ed33b08e148084dd66f5ce1a147d5a049c37e7/backend/putio/fs.go#L342
No.

putio: add ability to resume uploads

---

fs/rc/internal.go
fs/rc/internal_test.go

Attempt to fix #3575 
yes, #3575

Added command core/quit

---

docs/content/dropbox.md

Add instructions to create your own dropbox app ID
No

docs: add instructions to create your own dropbox app ID

---

vfs/cache.go
vfs/cache_test.go
vfs/file.go
vfs/file_test.go
vfs/read_write_test.go

Finishing up the changes started in #3480.
#2907

Rename files in cache (add tests for pull request 3480)

---

backend/koofr/koofr.go

Make Koofr backend use rclone provided HTTP client.
No.

koofr: use rclone HTTP client.

---

backend/sftp/sftp.go

Increase stability of SFTP by retrying connection creation.
#3656 
Tried it out in real life - it fixes my problem.

sftp: Retry Creation of Connection - fixes #3656

---

backend/local/local.go
cmd/cmd.go
cmd/cryptcheck/cryptcheck.go
cmd/serve/dlna/dlna_util.go
cmd/serve/httplib/serve/dir.go
cmd/serve/restic/restic.go
fs/accounting/stats.go
fs/accounting/stats_test.go
fs/accounting/transfer.go
fs/config.go
fs/fserrors/error.go
fs/march/march.go
fs/operations/dedupe.go
fs/operations/operations.go
fs/sync/sync.go
fs/sync/sync_test.go
fs/walk/walk.go
fs/walk/walk_test.go

For few commands, RClone counts a error multiple times. This was fixed by
creating a new error type which keeps a flag to remember if the error has
already been counted or not.
#3650 
- [ x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

fix error counter - fixes #3650

---

backend/swift/swift.go

Hi @ncw,
Please help me review the change what i add code to handle reserve sgements if objects in the container what was enabled versioning.
Thank in advance,
Luan Nguyen Huu.

Reserve segments of dynamic large object when delete objects in container what was enabled versioning.

---

fs/accounting/stats.go

This change is about enabling showing deletes in stats output. 
Additionally it is omit zero stats.
https://github.com/rclone/rclone/issues/1034

stats: show deletes in stats

---

backend/drive/drive.go

Add --drive-use-shared-date to use date file was shared instead of modified date.
Fixes #3624

drive: add --drive-use-shared-date to use date file was shared

---

docs/content/gui.md

Correcting small typo

---

fs/asyncreader/asyncreader.go
fs/asyncreader/asyncreader_test.go

asyncreader: fix EOF error

---

README.md
backend/jottacloud/api/types.go
backend/jottacloud/jottacloud.go
docs/content/docs.md

Initial implementation for parsing OAuth endpoints from well-known-link. More changes may be required. Need testing from @nattycleopatra. Attempts to fix #3818

jottacloud: add support whitelabel versions

---

fs/accounting/stats_groups.go

Without the fix we can have a race, example:
```
Write at 0x00c000432039 by goroutine 187:
github.com/rclone/rclone/fs/accounting.(*StatsInfo).Error()
fs/accounting/stats.go:495 +0x3f1
github.com/rclone/rclone/fs/accounting.(*StatsInfo).Error-fm()
fs/accounting/stats.go:477 +0x55
github.com/rclone/rclone/fs/walk.listRwalk.func1()
fs/walk/walk.go:162 +0xd2
github.com/rclone/rclone/fs/walk.walk.func2()
fs/walk/walk.go:402 +0x30f
Previous read at 0x00c000432039 by goroutine 184:
github.com/rclone/rclone/fs/accounting.(*statsGroups).sum()
fs/accounting/stats_groups.go:351 +0xcae
github.com/rclone/rclone/fs/accounting.rcTransferredStats()
fs/accounting/stats_groups.go:132 +0x1f4
```
Fixes #3844

fs/accounting: Added StatsInfo locking in statsGroups sum function

---

backend/s3/s3.go
docs/content/s3.md

Support EKS iam role.
#3753 
I've tested this manually in a kops cluster with kube2iam deployed.

use aws web identity role provider

---

docs/content/docs.md

Fixed small typo

---

docs/content/docs.md
fs/fshttp/http.go

Fix #3872
Add a description about the http dump mislead.
#3872

doc: add desc about gzip and http dump

---

backend/swift/swift.go
docs/content/swift.md

There is a new endpoint `v3` which replaces `v2.0`.
The `v2.0` endpoint seems to cause some trouble, while `v3` is fine
#3890
- [-] I have added tests for all changes in this PR if appropriate.

swift: Update OVH API endpoint - #3890

---

backend/onedrive/onedrive.go

Add support "Retry-After" header to backend/onedrive.
No.

backend/onedrive: add support "Retry-After" header

---

fs/accounting/stats.go

Always Print Elapsed Time to the Tenth Place Seconds in Progress

---

.gitignore
README.md
backend/s3/s3.go
docs/content/about.md
docs/content/s3.md

Adds StackPath Object Storage as a S3 compatible Object Storage provider
No

s3: Add StackPath Object Storage Support

---

backend/jottacloud/jottacloud.go

jottacloud: use RawURLEncoding when decoding base64 encoded login token

---

backend/s3/s3.go

Currently each multipart upload allocated his own buffers, which after
file upload were garbaged. Next files couldn't leverage already allocated
memory which resulted in inefficent memory management. This change
introduces backend memory pool keeping memory chunks which can be
used during object operations.
#3967

backend/s3: use memory pool for buffer allocations

---

docs/content/mailru.md

Add information about requirements to disable 2FA because rclone currently does not support such accounts.
This requirement is described in issue https://github.com/rclone/rclone/issues/3637.

mailru: Describe 2FA requirements

---

fs/log/syslog_unix.go

Introduce support for syslog `LOCAL*` facilities
https://github.com/rclone/rclone/issues/4061

fs/log: add support for syslog LOCAL facilities - fixes #4061

---

docs/content/dropbox.md

Updates documentation when creating your own Dropbox App:
- https://github.com/rclone/rclone/issues/3815#issuecomment-599202942

Dropbox: Add info about required redirect url

---

backend/union/entry.go
backend/union/errors.go
backend/union/policy/all.go
backend/union/policy/epall.go
backend/union/policy/epff.go
backend/union/policy/eplfs.go
backend/union/policy/eplno.go
backend/union/policy/eplus.go
backend/union/policy/epmfs.go
backend/union/policy/eprand.go
backend/union/policy/ff.go
backend/union/policy/lfs.go
backend/union/policy/lno.go
backend/union/policy/lus.go
backend/union/policy/mfs.go
backend/union/policy/newest.go
backend/union/policy/policy.go
backend/union/policy/rand.go
backend/union/union.go
backend/union/union_test.go
backend/union/upstream/upstream.go
docs/content/union.md

Enable multiple write support for union backend
#2737 #3709 
- Scheme of upstream fs is changed
- Creates a lot of unnecessary requests for some command (eg. sync)
- Cannot report an error when deleting an object hosted only on read-only remote

Multiwrite union

---

backend/s3/s3.go

Previously we had a map of pools for different chunk sizes.
In practice the mapping is not very useful and requires a lock.
Pools of size other that ChunkSize can only happen when we have a huge file (over 10k * ChunkSize).
We need to have a bunch of identically sized huge files.
In such case most likely ChunkSize should be increased.
The mapping and its lock is replaced with a single initialised pool for ChunkSize, in other cases pool is allocated and freed on per file basis.
No

s3: use single memory pool

---

docs/content/docs.md

Fix documentation for --quiet. See #4132.
#4132

docs: fix description of --quiet - fixes #4132

---

cmd/copyurl/copyurl.go
docs/content/commands/rclone_copyurl.md
fs/operations/operations.go
fs/operations/operations_test.go
fs/operations/rc.go
fs/operations/rc_test.go

Add flag to raise error if file clobbering detected 
Discussed here #3950

copyurl: add no-clobber flag

---

backend/box/box.go

Refresh the auth token when using box, jwt and box config.json file
[#4091 ](https://github.com/rclone/rclone/issues/4091)

Box: Refresh token when using jwt auth - Fixes #4901 

---

fs/rc/rcserver/rcserver.go

Http server auth related configs should be made before the server is started.
Fix #4130.

rcd: fix misplaced http auth config

---

backend/googlecloudstorage/googlecloudstorage.go
docs/content/googlecloudstorage.md

To add the Google Cloud Storage ARCHIVE class to Help
No

googlecloudstorage: Add ARCHIVE storage class to help

---

backend/crypt/crypt.go
backend/drive/drive.go

drive: Added command to change service_account_file
crypt: Added decode/encode commands to replicate functionality of cryptdecode
Add command support for changing the service-account-file and encoding/decoding crypt file names.
forum.rclone.org/t/edit-service-account-while-mounted/15760

Backend Commands for Drive & Crypt

---

README.md
backend/all/all.go
backend/seafile/api/types.go
backend/seafile/object.go
backend/seafile/pacer.go
backend/seafile/seafile.go
backend/seafile/seafile_internal_test.go
backend/seafile/seafile_test.go
backend/seafile/webapi.go
bin/make_manual.py
docs/content/about.md
docs/content/docs.md
docs/content/overview.md
docs/content/seafile.md
docs/layouts/chrome/navbar.html
fstest/test_all/config.yaml
fstest/testserver/init.d/TestSeafile
fstest/testserver/init.d/TestSeafileEncrypted
fstest/testserver/init.d/TestSeafileV6
fstest/testserver/init.d/seafile/docker-compose.yml
go.mod
go.sum
vendor/github.com/coreos/go-semver/LICENSE
vendor/github.com/coreos/go-semver/NOTICE
vendor/github.com/coreos/go-semver/semver/semver.go
vendor/github.com/coreos/go-semver/semver/sort.go
vendor/modules.txt

Implementation of a backend for Seafile 
Fix #1877

New backend for seafile servers

---

backend/union/union.go

Fix Server-side Copy and Move for Union.
Fixes integration tests:  fs/operations and fs/sync
No

Fix server-side copy/move for union

---

backend/union/union.go

Implement fast list for union, enabled if all upstreams support.
#3000

union: implement --fast-list

---

backend/union/union.go

Enable fast list functions for union backend when:
- at least one of the upstreams supports fast list
- upstreams only consist of backends that support fast list and local backend.
#3000

union: enable ListR when upstreams contain local

---

docs/content/ftp.md

doc
https://forum.rclone.org/t/ftp-command-line-possible/16422/4

docs: Update ftp.md with example config-less

---

docs/content/onedrive.md

Update filesize limitations for OneDrive Personal

---

backend/seafile/seafile.go
backend/seafile/webapi.go
docs/content/seafile.md

Add support for two-factor authentication to Seafile backend
It was discussed during the beta testing of the backend:
https://forum.rclone.org/t/beta-testing-seafile-backend/16203

seafile: implement 2FA

---

docs/content/docs.md
docs/content/install.md

Just some minor things I noticed while looking at the docs.

Minor improvements to docs

---

docs/content/_index.md
docs/content/contact.md
docs/content/donate.md
docs/content/downloads.md
docs/layouts/chrome/menu.html
docs/layouts/section/commands.html
docs/layouts/shortcodes/monthly_donations.html
docs/layouts/shortcodes/one_off_donations.html

In PR #4257 @ncw wrote:
> I'm just in the process of redoing rclone's front page so I'd love your opinion on https://test.rclone.org/
I haven't looked at the current (old) web site, but I really like the new one.  It's a very clean design, is easy to navigate and has a lot of content.  I like the icons on the download page.  It looks modern and attractive.
I have a few cosmetic changes.  I also noticed a few issues in the docs (see PR #4274).  Unfortunately, I don't have time to read through all the docs right now.
There are some typos and I'm not sure where the text comes from since it's not on `master` or in any `.go` file on `new-docs`.  I wonder if you used an old version of rclone to generate the docs?  The build system should always use the newly built version.
Two examples are:
``` …
```

Improvements to new web site

---

docs/content/drive.md

doc: fix shortcut creation language

---

backend/b2/b2.go
backend/box/box.go
backend/crypt/crypt.go
backend/drive/drive.go
backend/dropbox/dropbox.go
backend/jottacloud/jottacloud.go
backend/koofr/koofr.go
backend/mailru/mailru.go
backend/mega/mega.go
backend/onedrive/onedrive.go
backend/premiumizeme/premiumizeme.go
backend/s3/s3.go
backend/seafile/seafile.go
backend/sugarsync/sugarsync.go
backend/yandex/yandex.go
cmd/link/link.go
fs/fs.go
fs/operations/operations.go
fs/operations/rc.go
fs/operations/rc_test.go
fs/rc/params.go
fs/rc/params_test.go
fstest/fstests/fstests.go

s3: implement link sharing

---

backend/putio/object.go

putio: fix panic on Object.Open #4315

---

backend/jottacloud/jottacloud.go

Jottacloud: bring back old authentification for whitelabel versions

---

backend/ftp/ftp.go
docs/content/ftp.md
go.mod
go.sum
vendor/github.com/jlaffaye/ftp/README.md
vendor/github.com/jlaffaye/ftp/ftp.go
vendor/github.com/jlaffaye/ftp/status.go
vendor/github.com/jlaffaye/ftp/walker.go
vendor/modules.txt

Add support for explicit FTP over TLS.
Fixes #4100
Add support for explicit FTP over TLS
#4100

ftp: add explicit tls support

---

cmd/serve/dlna/cds.go

dlna: samsung series 6+

---

docs/content/docs.md

docs: config create: document legal remote parameters
Was about to document #4355, but it happens the legal characters are also not documented.
Not entirely sure if it's the best page or place to add the text to, if the wording is the best, feel free to change.
No.

docs: config create: document legal remote parameters

---

CONTRIBUTING.md

Add how-to-squash. A few months ago, I couldn't get my head around git. Why not just have it there?
No.

Contributing squashing

---

docs/content/jottacloud.md

docs/jottacloud: add some info about the setup for whitelabel version

---

backend/box/box.go
docs/content/box.md
docs/content/overview.md

As it was discussed in #4326. It's not great but reasonably fast. I've added some notes about this limitation to the docs.

Box cleanup

---

docs/content/install.md

Updated install.md to reflect minimum go version

---

docs/content/drive.md

Update gdrive documentation

---

backend/local/local.go

Create a flag for local copy to stop RClone from setting the copied file's modification time after RClone has completed the copy.
https://forum.rclone.org/t/chtimes-error-on-local-mounted-copy/17784

local: Adding new no_set_modtime option to backend.

---

docs/content/install.md

Updated Docker Docs regarding usage of the RC API from outside the container
#4486

Updated Docker Docs

---

backend/sftp/sftp.go

The traditional OpenSSH `sftp` command supports specifying the SSH subsystem or the SFTP server via the `-s` option. This PR adds two options to the sftp backend: `subsystem` and `server_command`. 
The `subsystem` option is useful if the target server has multiple SFTP subsystems defined for users.
The `server_command` option can be useful if `sudo` is required to elevate the user sftp session, without the need to SSH as root user.
The new `newSftpClient()` function is essentially a just reimplementation of [sftp.NewClient](https://godoc.org/github.com/pkg/sftp#NewClient) to support custom subsystem or execution of a custom SFTP server on the remote host.
It was briefly discussed in 2017 in issue #1801.

sftp: add options for subsystem and server_command - fixes #1801

---

fs/rc/webgui/plugins.go

Fixes missing error handle I noticed through [static code analysis](https://lgtm.com/projects/g/rclone/rclone/). Now properly logs error in the unlikely event the error occurs.
- [] I have added tests for all changes in this PR if appropriate.
- [] I have added documentation for the changes if appropriate.

webgui: fixes previously unhandled error in JSON marshall 

---

fs/rc/rcserver/rcserver.go
fs/rc/webgui/plugins.go
fs/rc/webgui/rc_test.go
fs/rc/webgui/webgui.go

The earlier PR #4309, broke the working of WebGUI because of a missing condition check while implementing refferer based redirect. This PR attempts at fixing it.

webui: Fix broken webui because of plugins redirection

---

docs/content/onedrive.md

Adds alternative workaround to known issue
Issue #2036

docs: Add alternative workaround for issue #2036

---

docs/content/overview.md

docs: Updated overview with Opendrive support of dupes

---

docs/content/docs.md

docs: Updated --track-renames docs

---

docs/content/bugs.md

docs: Cleaned up and corrected bugs docs verbiage

---

fs/rc/webgui/webgui.go

This change will check if there is an available update to the webui and notify the user about it.
No

webui: Prompt user for updating webui if an update is available

---

MANUAL.md
README.md
backend/s3/s3.go
docs/content/_index.md
docs/content/s3.md

Add Tencent COS to s3 provider list.
https://github.com/rclone/rclone/issues/4468
https://github.com/rclone/rclone/issues/4480

docs: add Tencent COS to s3 provider list - fixes #4468

---

backend/dropbox/dropbox.go

To be merged after the shared folder PR. Had been missing for a long time and makes the shared folder stuff slightly cleaner.

dropbox: implement IDer

---

cmd/mount2/fs.go

Fix bug in the mount2 code where UID / GID is swapped

Fix the swapped UID / GID values in mount2

---

backend/mailru/mailru.go

The mailru backend has had internal flags (`quirks`) reserved for troubleshooting from the very beginning.
Now that backend matures, deprecated quirk flags can be safely removed by this PR:
- `retry400` - the connected issue has not appear anymore
- `insecure` - planned as an aid in protocol sniffing, but in fact `--dumps=headers,bodies` is enough for that
- `gzip` - could have been used as a means to improve transfer speed, but appeared ineffective/irrelevant
No, it's internal detail of backend implementation
Mini integation suite passed: https://github.com/ivandeex/rclone/runs/1138191342?check_suite_focus=true

mailru: remove deprecated protocol quirks

---

backend/sftp/sftp.go
docs/content/sftp.md

Current behaviour is insecure.  If the user specifies this value then we
switch to validating the server hostkey and so can detect server changes
or MITM-type attacks.
Based on Issue 4087
https://github.com/rclone/rclone/issues/4087

sftp: Allow user to optionally check server hosts key to add security

---

backend/s3/s3.go

Added missing regions for AWS S3
https://forum.rclone.org/t/please-add-af-south-1-region-to-rclone-config/19512

s3: Add missing regions for AWS

---

backend/sftp/sftp.go

Defer asking the user for their password, so if the connection fails (eg bad known_hosts entry; server down; whatever...) they don't have to type their password in.  It's better UX and better security
Unexpected side effect: a wrong password allows for the user to retry!
Issue: 4660
https://github.com/rclone/rclone/issues/4660

sftp: defer asking for user passwords until the SSH connection succeeds

---

cmd/mountlib/mount.go

Correction of repeated word

---

backend/sftp/sftp.go

After switching to a password callback function, if the ssh connection
aborts and needs to be reconnected then the user is-reprompted for their
password.  Instead we now remember the password they entered and just give
that back.  We do lose the ability for them to correct mistakes, but that's
the situation from before switching to callbacks.  We keep the benefits
of not asking for passwords until the SSH connection succeeds (right
known_hosts entry, for example).
https://github.com/rclone/rclone/issues/4660#issuecomment-705502792

sftp: remember entered password in AskPass mode

---

cmd/dedupe/dedupe.go

dedupe will not delete equal files if they are located in another folder.
Clarify that dedupe will not delete equal files (with the same hash) if they are located in another folder.
https://forum.rclone.org/t/duplicate-objects/19733/4
- [x ] I have added tests for all changes in this PR if appropriate.

dedupe: minor clarification in docs

---

backend/drive/drive.go

Added flag to stop transfers when the download limit is exceeded
N/A

drive: Added flag to stop when the download limit is exceeded

---

backend/jottacloud/jottacloud.go

jottacloud: avoid double url escaping of device/mountpoint - fixes #4697

---

cmd/genautocomplete/genautocomplete_bash.go
cmd/genautocomplete/genautocomplete_fish.go
cmd/genautocomplete/genautocomplete_test.go
cmd/genautocomplete/genautocomplete_zsh.go
docs/content/commands/rclone_genautocomplete_bash.md
docs/content/commands/rclone_genautocomplete_fish.md
docs/content/commands/rclone_genautocomplete_zsh.md
go.sum

Fix issue #3423 
Yes, https://github.com/rclone/rclone/issues/3423
- [`x`] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [`x`] I have added tests for all changes in this PR if appropriate.
- [`x`] I have added documentation for the changes if appropriate.
- [`x`] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [`x`] I'm done, this Pull Request is ready for review :-)

genautocomplete: add support to output to stdout

---

cmd/mountlib/mount.go

Inform about mount command options not in use on Windows.
According to the following comment from the WinFsp author the `--allow-other` is useless on Windows:
> The allow_other option is actually ignored on WinFsp, because the concept of root and other users makes little sense on Windows.
(https://github.com/billziss-gh/winfsp/issues/138#issuecomment-407212400)
It was also discussed and tested with rclone in this forum thread:
https://forum.rclone.org/t/what-does-allow-other-do/12366
As indicated above the situation is same with `--allow-root`, although could not find any 100% definitive statements confirming this..

mount: docs: add note that allow-root and allow-other is not relevant on windows

---

backend/mailru/mailru.go

When mailru requests contents of a mailru folder, server returns _kind_ field for resource items. Currently the mailru backend supports only two kinds: _file_ and _folder_. As users report in https://github.com/rclone/rclone/issues/4025, mailru can return other kinds, and this makes such operations as _ls_ or _size_ fail even if unknown resource lies deep below requested directory.
Further investigation shows (see manual test procedure in a comment below) that all currently known kinds mark special types of folders: _camera-upload_ is a directory created by the mailru mobile application for automatically synchronized photos, _shared_ is a directory that was shared by owner with other mailru cloud users. The sister open-source project …

mailru: accept special folders eg camera-upload (fixes #4025)

---

cmd/ncdu/ncdu.go

Add keyboard shortcut 'A' for ncdu which sort by average size in directory.
Fixes #4699

ncdu: add sort by average size in directory

---

cmd/ncdu/ncdu.go

It is possible to sort by average size in directory in ncdu but there is no option to toggle this average size in ncdu, so it could be confusing for people. This pull request add toggle option and the average size in directory can be viewed if the key 'a' is pressed. 
This feature was discussed in issue: #4699

Ncdu - add toggle for average size in a directory 

---

docs/content/jottacloud.md

Minor doc improvement: Add heading to the example section so that it does not seem to be part of the legacy setup section.

jottacloud: docs: add heading to the example section

---

backend/drive/drive.go

Implements cleanup for team drives. It works by recursively walking through the the drive and looking for files/folders that are marked explicitly deleted and will hard delete them. Similar to the workaround discussed in #2418 but shouldn't leave the folders.

drive: implement CleanUp workaround for team drives - fixes #2418

---

cmd/serve/ftp/ftp.go

Enable TLS on serve ftp command
Yes
Fixes #3640

ftp: add options to enable TLS - fixes 3640

---

cmd/delete/delete.go
cmd/purge/purge.go
cmd/rmdir/rmdir.go
cmd/rmdirs/rmdirs.go

Update documentation of commands delete,purge,rmdir,rmdirs. Mostly some "cross-referencing" between them because the distinction between these closely related commands can be a bit confusing, and it is easy to miss for example the "rmdirs" variant since it is not in the main "Commands" dropdown on rclone.org.
Not directly, but several forum posts discusses the usage of these commands.

docs: update documentation of commands delete,purge,rmdir,rmdirs

---

docs/content/webdav.md

Updated streaming/rcat Nextcloud situation

---

docs/content/googlephotos.md

"which are uploaded" -> "which were uploaded" (minor peeve)

Fixed verbal tense

---

backend/jottacloud/jottacloud.go
docs/content/overview.md

jottacloud: don't erroniously report support for writing mime types

---

fs/march/march.go

Signed-off-by: zhuc <zhucan.k8s@gmail.com>
support multi-threads to head dst object with flag '--files-from' and '--no-traverse'
#4808

fs/operations: collect operation objects concurrently

---

.github/workflows/build_publish_docker_image.yml
.github/workflows/build_publish_release_docker_image.yml

Upgrade buildx action, in order to fix some bugs
Nope

Buildx action upgrade

---

docs/content/faq.md

Fix typo in faq.md doc.
No
- [ X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ X] I have added tests for all changes in this PR if appropriate.
- [ X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).

faq.md - fix typo

---

fs/rc/rcserver/rcserver.go
fs/rc/webgui/plugins.go
fs/rc/webgui/rc.go
fs/rc/webgui/rc_test.go

Create plugins related files only if webui is enabled.
#4600  #4592

plugins: Create plugins files only if webui is enabled.

---

backend/s3/s3.go

Support AWS S3 [Requester Pays](https://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html) as a configurable option.
Yes - https://github.com/rclone/rclone/issues/301.

s3: add requester pays option - fixes #301

---

backend/azureblob/azureblob.go
go.mod
go.sum

See https://github.com/Azure/azure-storage-blob-go/blob/master/ChangeLog.md#version-0120

azureblob: update azure-storage-blob-go to v0.12.0

---

cmd/ncdu/ncdu.go
cmd/ncdu/scan/scan.go

* Make ncdu command handle errors reading directories.
* Highlight directories with errors in UI.
Yes, issue #4014

Make ncdu more robust in case of errors

---

fs/accounting/accounting.go
fs/config/configflags/configflags.go
fs/operations/operations.go

operations + accounting: add stats to --dry-run

---

MANUAL.html
MANUAL.md
MANUAL.txt
cmd/dedupe/dedupe.go

Fixing a typo in the docs.
It wasn't. I came across the typo going trough the manual.

Fix a typo in the doc: "duplicate names" instead of "duplicates names"

---

MANUAL.md

Spelling error. the faq.md in docs/ is correct, but this one was not.
No

small spelling nit, file -> find.

---

backend/compress/compress.go

This should fix the build. As mentioned in #4941 @ncw

compress: check type assertion in SetTier - fixes #4941

---

cmd/cryptdecode/cryptdecode.go
docs/content/crypt.md

Add additional links to crypt/cryptdecode docs.

docs: Updated crypt/cryptdecode docs with additional info

---

docs/content/ftp.md

Was the change discussed in an issue or in the forum before?
https://forum.rclone.org/t/copy-or-sync-from-ftp-server-results-in-source-directory-not-found/20636
Purpose
To reflect information that is in the forum inot the documentation

update ftp.md with note about active mode

---

docs/content/union.md

Updates documentation for Union remote to reflect the correct paths and upstreams
No.

docs: fix references to upstreams in union example

---

docs/content/crypt.md

Extend main description of crypt remote.
There have been several questions in the forum about the basics of the crypt remote, so I have extended the top section of the doc page to try to explain some of the most relevant consepts in one place. Much of the text is taken from various forum posts and other documentation. Perhaps it became a bit too long, and it repeats several of the things that are explained further down the page.. Let me know what you think.
https://github.com/rclone/rclone/pull/4765#issuecomment-730681973
https://forum.rclone.org/t/encryption-at-rest-untrusted-destination-server/20539
https://forum.rclone.org/t/is-was-a-security-auditing-procedure-in-place-for-crypt/450
https://forum.rclone.org/t/how-to-correctly-setup-the-salt-for-the-crypt-remote/4273

crypt: docs: extended description

---

fs/rc/jobs/job.go
fs/rc/jobs/job_test.go

Creates new method in jobs package to allow notifications in case job is finished. Can be used for more optimal status checks.
- [] I'm done, this Pull Request is ready for review :-)

rc/jobs: add finished job listener

---

cmd/cat/cat.go
cmd/check/check.go
cmd/copy/copy.go
cmd/delete/delete.go
cmd/ls/lshelp/lshelp.go
cmd/mountlib/mount.go
cmd/move/move.go
vfs/help.go

This is probably incomplete but a good start.
I don't have a Go environment so this is not tested.

docs: fix markup of arguments

---

backend/s3/v2sign.go

Signed-off-by: zhuc <zhucan.k8s@gmail.com>
s3/v2Auth: copy multipart failed with 'SignatureDoesNotMatch'
#4961

s3/v2Auth: copy multipart failed with 'SignatureDoesNotMatch'

---

backend/local/local.go

This PR introduces the new flag --local-zero-size-links
Assume the Stat size of links is zero (and read them instead)
On some virtual filesystems (such ash LucidLink), reading a link size via a
Stat call always returns 0.
However, on unix it reads as the length of the text in the link. This may
cause errors like this when syncing:
Failed to copy: corrupted on transfer: sizes differ 0 vs 13
Setting this flag causes rclone to read the link and use that as the size of
the link instead of 0 which in most cases fixes the problem.
Fixes #4950
Fix #4950
Yes :-)

local: new flag --local-zero-size-links to fix sync on some virtual filesystems

---

backend/swift/swift.go
backend/swift/swift_test.go

The PR is create with some purpose:
- Add '_' char to white list when encode url.
- Unify the util check and get manifest for DLO or SLO to common function.
- Using delete bulk during delete segments.
- Using the atexit package to handle unexpected error during sync cache to remote backend
[link request https://github.com/rclone/rclone/issues/4889](https://github.com/rclone/rclone/issues/4889)

Modifying code handle swift backend

---

backend/onedrive/onedrive.go
backend/onedrive/onedrive_test.go

Add full support for 21vianet in a better, non-intrusive way.
see #3973 #4072 #4131 #3804

New OneDrive 21vianet / National implementation

---

vfs/vfscache/cache.go

When using the [:backend:](https://rclone.org/docs/#backend-path-to-dir) syntax for creating remote on the fly, the cache will try to create a directory with name ":backend", which contains illegal character in Windows.
Example:
```
rclone mount :webdav: Z: --fuse-flag --VolumePrefix=\server\home --vfs-cache-mode writes --webdav-url https://live.sysinternals.com
```
This fix will trim off the leading ":".
There is a workaround:
Set environment variable `RCLONE_CONFIG_name_TYPE=backend`, which will create an actual remote with specified name, and then use "name:" as the remote.
Example:
```
set RCLONE_CONFIG_MYREMOTE_TYPE=webdav&&rclone mount myremote: Z: --fuse-flag --VolumePrefix=\server\home --vfs-cache-mode writes --webdav-url https://live.sysinternals.com
```
**Note/question:**
After …

vfs: fix invalid cache path on windows when using :backend: as remote

---

docs/content/changelog.md

Correct a link to Digitalis in the changelog for v1.54.0

Changelog: Correct link to Digitalis

---

docs/content/filtering.md

Correction per @x0b from 
https://forum.rclone.org/t/max-age-min-age-rfc3339-format-rejected/22204
Correction identified by forum user @x0b
https://forum.rclone.org/t/max-age-min-age-rfc3339-format-rejected/22204

Docs: Update filtering.md - correct rfc3339 example

---

docs/content/filtering.md

Add an example pinched from rclone forum
https://forum.rclone.org/t/need-help-to-understand-filtering-commands/22196
Credit to @asdffdsa
Add an example to filtering page drawn from a real world support request.
https://forum.rclone.org/t/need-help-to-understand-filtering-commands/22196

Docs: Update filtering.md - remote root example

---

docs/content/filtering.md

Typos from prior major rewrite
Small typo fixes to complete the earlier rewrite. No attempt to change meaning.
No

Docs: Update filtering.md - typos

---

backend/ftp/ftp.go
docs/content/docs.md
docs/content/flags.md
fs/config.go
fs/config/configflags/configflags.go
fs/fshttp/dialer.go
fs/fshttp/http.go

Allow specifying DSCP value for connections. Avoid dominating the bandwidth when doing long time operation.
#755

Add DSCP support

---

fs/operations/operations.go

For the copy operation, if `Put()` or `Update()` functions of any backend are called, the backends use `CallNoRetry` for the actual upload operation since the retry is supposed to be done using the low level retry, not using the pacer so that the file may be re-opened. If a `pacer.retryAfterError` is returned by the backend, Rclone will not retry the error. This MR fixes that.
https://forum.rclone.org/t/copy-low-level-retry-does-not-respect-pacer-retryaftererror/22183

operations: Made copy and sync operations obey a RetryAfterError

---

docs/content/zoho.md

Mainly the reference to firewalls didn't make sense. Tried to make more precise. Left z in authorize.
Tidy up wording encountered whilst reading docs.
No.

Docs: Zoho WorkDrive authorisation reword

---

docs/content/filtering.md

Docs: badly formed link

---

docs/content/cache.md

Attempt to eliminate a dead link from the docs so new dead ones will be easier to spot. This relates to the obsolete cache back end but it is a straightforward low risk change.
No

Docs:Convert bogus example link to code

---

docs/content/sftp.md

Fix broken hyperlink in sftp docs
No.

Docs:Fix broken link in sftp page

---

cmd/mountlib/mount.go

https://github.com/rclone/rclone/issues/4997

mount: docs: document the new FileSecurity option in WinFsp 2021

---

docs/content/crypt.md

fixed typo

---

docs/content/rc.md

Remove dead link in rc docs
https://github.com/rclone/rclone/issues/5033#issuecomment-780854447

Docs: Remove dead link from rc docs

---

backend/webdav/webdav.go
backend/webdav/webdav_test.go
docs/content/webdav.md
go.mod
go.sum

webdav: add support for sharepoint NTLM auth

---

backend/dropbox/dropbox.go

This fixes the polling implementation for Dropbox, particularly when using a scoped app. This also adds a lower end check for the timeout, as I forgot to include that in the original implementation.
https://github.com/rclone/rclone/issues/5089

dropbox: fix polling support for scoped apps - fixes #5089

---

backend/drive/drive.go
backend/opendrive/opendrive.go
fs/dir.go
fs/fs.go
fs/operations/dedupe.go

dedupe: make largest directory primary

---

docs/content/overview.md

The features table had quite a few mistakes this fixes them. We should really autogenerate this table.

docs: cleanup optional feature table

---

docs/content/install.md

Mention self-update in the install instructions
https://github.com/rclone/rclone/pull/5096#discussion_r593743239 said
> PS I think the install instructions should probably mention self-update too

docs: mention rclone selfupdate in quickstart

---

CONTRIBUTING.md

Update setup instructions in contributing guidelines for the latest go version.
* https://forum.rclone.org/t/unable-to-follow-setup-instructions-in-contributing-guidelines/23272

contributing.md: update setup instructions for go1.16

---

cmd/mountlib/mount.go

docs: WinFsp 2021 is out of beta

---

cmd/about/about.go
cmd/copyurl/copyurl.go

docs: minor cleanup of space around code section

---

docs/content/docs.md

docs: fixed some typos

---

backend/ftp/ftp.go

PR #4266 modified ftpConnection to make ftp library into using
a custom dial function which is QoS aware and takes care of TLS.
([edfe183ba,ftp.go:222](https://github.com/rclone/rclone/commit/edfe183ba2f95120062596c98f23fe91e615b6f7#diff-cf7209b00e4d37b7cba2a369884faf762795e7860dbb6d6a417635e8b3b778e7R222))
However the ServerConn.Login function from the ftp library also needs TLS config passed explicitly
as a trigger for sending PSBZ and PROT options to FTP server.
([jlaffaye/ftp,ftp.go:311](https://github.com/jlaffaye/ftp/blob/master/ftp.go#L311))
This was not taken care of resulting in failure to connect via FTP with implicit TLS.
This PR fixes that and slightly refactors custom dialer.
Fixes #5210
Successfully tested against FileZilla server with _Require TLS session resumption_ …

backend/ftp: fix implicit TLS after PR #4266

---

cmd/mountlib/mount.go
docs/content/install.md

Documenting how to set up autostart of rclone, e.g. for mount or serve commands.
Mostly focus on Windows.
TODO:
- Currently appended to the install page. Don't know if it should be on a separate page.
- Windows:
- Uncertainties around user accounts and mounts, see discussions in this PR comments!
- Anyone with experience with running rclone as service or scheduled task? What works good/bad?
- Linux:
- Did included a section for Linux, but could need some extension if anyone with experience wants to fill in...
- macOS
- Nothing about mac included for now...
Sources:
- https://docs.syncthing.net/users/autostart.html#autostart-windows-startup
Related to this PR: https://github.com/rclone/rclone/pull/4953

Document autorun

---

cmd/ncdu/ncdu.go

Fixes to cases in which `ncdu` would crash with an out-of-range error.
1. when attempting to delete a file even though there aren't any)
2. attempting to delete a file when none is selected. (could happen after deleting the last entry in the list)

cmd/ncdu: fix out of range panic in delete

---

lib/oauthutil/oauthutil.go

This should improve the situations reported in #4139.
Normally we can automatically renew the OAuth access token with the refresh token, but in some cases we don't have the refresh token and there's no way we can recover from it I guess.

oauthutil: raise fatal error if token expired without refresh token

---

bin/make_manual.py

fix missing comma for doc build commit cd69f9e
unnecessary

docs: fix missing comma for doc build - commit cd69f9e

---

backend/compress/compress.go

May or may not be enough to fix # 5260

compress: fix compressed name regexp

---

.github/workflows/build.yml
.github/workflows/build_publish_docker_image.yml
.github/workflows/build_publish_release_docker_image.yml

Fix #5272: Only run workflow script in rclone repsoitory, not forks

---

docs/content/docs.md

from "Check the integrity of an encrypted remote." to "Check the integrity of a crypted remote."
corrected spelling in documentation
no

corrected spelling

---

fs/accounting/stats.go

Replaces the `accounting.startTime` package var with a field on `StatsInfo`, initialized on construction and reset along with `ResetCounters`.
https://github.com/rclone/rclone/issues/5282

Deglobalize StatsInfo startTime/elapsedTime.

---

vfs/vfsflags/vfsflags_unix.go

vfs: fix that umask option cannot be set as environment variable

---

cmd/serve/sftp/connection.go
cmd/serve/sftp/sftp.go

I'd like to expose a subdirectory `photos` in my home directory to a semi-trusted device, over SFTP.
To do this, I'd add the following to ~/.ssh/authorized_keys:
```
restrict,command="rclone serve sftp --stdio ./photos" ssh-rsa ...
```
I have tested this against OpenSSH_8.5p1 and I am able to expose just my `photos` directory.
https://github.com/rclone/rclone/issues/5311

serve sftp: add --stdio flag to serve via stdio

---

backend/jottacloud/jottacloud.go

The link command would return an invalid url with a missing first slash: `https:/www.jottacloud.com/s/...`
Reason was it used `path.Join` to concat base url with relative url, and that implicitely performs `path.Clean` on the result which removes any duplicate path separators - because it is intended for filesystem paths and not urls.
Fixes #5370

jottacloud: fix invalid url in output from link command

---

docs/content/drive.md

To amend the step-by-step instructions to include the requirement to "Publish App" to avoid hitting a 403 error.
Issue 5393: https://github.com/rclone/rclone/issues/5393

drive documentation: 'publish app' in step-by-step: fixes 5393

---

fs/config/configflags/configflags.go

fs/config: make --dump imply -vv

---

docs/content/commands/rclone_mount.md

OSX -> macOS

---

docs/layouts/_default/baseof.html
docs/layouts/chrome/navbar.html
docs/static/js/search.js

Add google search widget to https://rclone.org :-)
https://github.com/rclone/rclone/issues/4784#issuecomment-861740589
@ncw @albertony Please review

Add google search widget to rclone.org

---

backend/fichier/api.go

1fichier seems to have a small processing delay until uploaded files are available for download. During this time, the `get_token` API does respond with a valid `GetTokenResponse` and HTTP status 200, but the status will be `KO`  instead of `OK` and the link field may or may not be filled. This will then cause the actual download to fail with a 404 error. We should therefore check the status `getDownloadToken` and retry if it isn't ok.

fichier: check that we actually got a download token and retry if we didn't

---

docs/content/onedrive.md

To facilitate a great tip to users experiencing extensive throttling or blockage by SharePoint (OneDrive Business).
Yes, see issue #5404.

docs: added tip to reduce SharePoint throttling - fixes #5404

---

backend/s3/s3.go

update s3(Alibaba OSS) backend endpoint.
No.

update Alibaba OSS endpoint

---

docs/content/onedrive.md

clarification of the process for creating custom client_id

---

cmd/serve/http/http.go
lib/http/http.go

http: fix serve http exits directly after starting

---

docs/content/drive.md

Documentation fix
Yes, issue #5499

docs: fix instructions for Google Drive auto config

---

docs/content/commands/rclone_mount.md

DOC: "OS X" -> "macOS"

---

docs/content/s3.md

fix a typo in the documentation
no

doc: fix typo in s3 documentation

---

docs/content/authors.md

Add Greg Sadetsky to contributors

---

docs/content/drive.md

fix documentation re: gdrive
yes, #5499

doc: fix instructions regarding gdrive

---

.github/workflows/build.yml

Fix build for Android
https://github.com/rclone/rclone/pull/5567#issuecomment-911207182

build: update Go to 1.16 and NDK to 22b for android/any

---

docs/content/authors.md

Hello `rclone` team,
This is a tiny PR updating the email.

Tweak the email

---

bin/.ignore-emails

This PR follows up from the comment here https://github.com/rclone/rclone/pull/5586#issuecomment-917408535

Update the ignored email as per #5586

---

docs/content/swift.md

Added documentation for OVH Cloud Archive, provides information on how to restore/unfreeze/download objects.
Issue #3041
- [] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).

OVH Cloud Archive Documentation

---

backend/crypt/crypt.go
docs/content/crypt.md

Grammar. Readability
Don't know

Grammar/readability: 2 messages now in 2 sentences

---

docs/content/authors.md

Add Jonta to contributors

---

backend/jottacloud/jottacloud.go

Implementing SetModTime function of Jottacloud backend, to add support for `rclone touch` on existing file, modtime-only changes of files in mounts etc.
Note: With the existing backend implementation's use of the allocate API, with its deduplication/resume features, whenever rclone wants to upload an identical file with changed timestamp, then it will be reduced to a "SetModTime" operation anyway: The allocate request updates the timestamp and returns that file is already COMPLETED, no need to upload data with a following update request. So in that sense, adding support for SetModTime does not change anything for regular sync/copy operations. What it does do is add support for modtime-only operations that does not resort to "re-upload".
Implementation note: Updates both Created and …

jottacloud: implement SetModTime to support modtime-only changes

---

cmd/serve/http/http.go

This may want to be moved to each individual service.
Resolves https://github.com/rclone/rclone/issues/5620
https://github.com/rclone/rclone/issues/5620

lib/http: Add auth to http service

---

cmd/mountlib/help.go

docs/mount: add note that to execute programs one must set custom filesystem permissions

---

librclone/python/rclone.py

Utilize the recently added `RcloneFreeString` API function to release memory of allocated strings in the Python example.
Haven't really verified that the memory is actually released, but the code runs without throwing, so I guess it works.
Also added a tiny tweak to default to librclone.dll instead of librclone.so when on Windows.
- Uses f-strings, Python 3, don't know if this is a problem?
Related to https://github.com/rclone/rclone/pull/5703

Librclone python free

---

librclone/README.md

librclone: Add mention of Rust bindings for `librclone`

---

docs/content/overview.md

Add note about S3 compatible services

---

cmd/serve/sftp/connection.go

Fix typo in connection.go (SFPT -> SFTP)
No

serve sftp: fix typo

---

lib/encoder/encoder_test.go

Some day in the past the Slash encode option was added to Onedrive
encoder so it began to encode slashes in file names rather then treat
them as path separators.
This patch adapts benchmark test cases accordingly.
Fixes #5659
#5659

lib/encoder: fix benchmarks

---

backend/s3/s3.go

This PR is WIP, since it was only manually tested against real AWS S3 endpoints.
Additional research is required to check if a fallback from `ListObjectsV2` to `ListObjects` is required for S3-compatible storage, either automatic, through a cli switch or default per s3 backend type.
It would also be great to get feedback from @ncw on what is the preferred option.
Using `ListObjectsV2` with a continuation token is about **5-6x faster** than `ListObjects` with a marker.
No, but there were several posts related to slow listings, which usually resolved around using `--no-modtime` or `--use-server-modtime`, but using `ListObjectsV2` API massively speeds up the response time from the AWS S3 API.
Example:
```shell
$ time sudo -iu rclone /usr/bin/rclone ls s3:my-large-bucket --fast-list …
```

WIP / RFC: s3: Use ListObjectsV2 for much faster listings

---

docs/content/s3.md

Improve description for SeaweedFS
N/A

Improve description for SeaweedFS

---

fstest/fstests/fstests.go

Closes #5420. I thought it would've been possible to test the type of the fs with type cast but that actually created a import cycle which is forbidden for tests...

fstests: treat accountUpgradeRequired as success for OneDrive PublicLink

---

fs/operations/operations.go

To show progress of server-side operations by adding server-side moves to stats.
A server-side move will then show the same stats as a server-side copy of the same file.
A server-side move/rename of a folder will (still) not count in the stats - imagine the stats after an (almost) instant rename of a top-level folder with TBytes of data.
Issue: https://github.com/rclone/rclone/issues/5430
Forum post: https://forum.rclone.org/t/help-with-stats-logging/25023
These examples illustrates the stats of server-side operations **before** the change:
```
./rclone copy GoogleDrive:testfolder1/testfile1 GoogleDrive:testfolder2 --log-level=INFO --stats=1s 
2021/08/04 14:17:50 INFO  : 
Transferred:              0 / 110.125 MiByte, 0%, 0 Byte/s, ETA -
Transferred:            0 / 1, 0%
Elapsed time: …
```

fs/operations: add server-side moves to stats - fixes #5430

---

docs/content/pcloud.md

Fix a grammar mistake in the documentation.
No.

docs: fix typo

---

docs/content/commands/rclone_config_create.md

enhanced documentation
#5825
- [ x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).

docs: more explicit doc for --all with params

---

backend/b2/b2.go

Indicate how the B2 `download_url` configuration setting should be like.
No.

docs: add a note about the B2 download_url format

---

backend/jottacloud/jottacloud.go

To update the jottacloud backend to use a better performing api for the ListR() call. The current api `mode=list` has poor time to first byte and poor support for very large trees. The `mode=liststream` is better in both of those. 
No.

backend:jottacloud change api used by ListR ( --fast-list )

---

backend/pcloud/pcloud.go
fstest/test_all/config.yaml

The change adds ListR support for PCloud.
No, it's a minor feature that implements a 4 year old fixme.

pcloud: add support for recursive list

---

backend/s3/s3.go
docs/content/s3.md

Adding support for Glacier Instant Retrieval storage class: https://aws.amazon.com/s3/storage-classes/#Instant_Retrieval
No

s3: Add GLACIER_IR storage class

---

docs/content/rc.md

docs: fix links to rc data types section

---

docs/content/s3.md

Fixed a typo in s3.md

---

backend/onedrive/quickxorhash/quickxorhash.go

onedrive: minor opt of quickxorhash

---

docs/content/commands/rclone_dedupe.md
fs/operations/dedupe.go

dedupe: add quit as a choice in interactive mode

---

README.md

Use White Logo on GitHub's Dark Theme to improve visibility of Logo.
No

docs: Use Adaptive Logo in README

---

docs/content/commands/rclone_serve_sftp.md

Fix broken test_proxy.py link

---

docs/content/drive.md

"and this it may require you to unblock it temporarily" -> "and it may require you to unblock it temporarily"

DOC: fix a typo

---

README.md
backend/koofr/koofr.go
docs/content/_index.md
docs/content/docs.md
docs/content/koofr.md
docs/layouts/chrome/navbar.html
fstest/test_all/config.yaml

Renamed the Digi Storage provider according to their wishes.

koofr: renamed digistorage to exclude the romania part.

---

README.md
backend/all/all.go
backend/netstorage/netstorage.go
backend/netstorage/netstorage_test.go
bin/make_manual.py
cmd/serve/restic/restic-test.sh
cmd/test/info/all.sh
docs/content/_index.md
docs/content/docs.md
docs/content/overview.md
docs/layouts/chrome/navbar.html
fstest/test_all/config.yaml
lib/rest/rest.go

This change is to add official support for Akamai Netstorage to include as a new backend.
Adding Akamai Netstorage as a new backend [#5343](https://github.com/rclone/rclone/issues/5343)

Adding Akamai Netstorage as a new backend.

---

docs/content/onedrive.md

web files (.html, .aspx, etc.)

Add file type to "item not found"

---

backend/putio/error.go
backend/putio/object.go

adds support to multi-thread-streams on putio backend
#6079

putio: add status code 206 - fixes #6079

---

backend/googlecloudstorage/googlecloudstorage.go

Adds a configuration option to the GCS backend to allow skipping the
check if a bucket exists before copying an object to it, much like
f406dbb added for S3.
This is essentially a GCS-y version of the fix for #4449

googlecloudstorage: add --gcs-no-check-bucket to minimise transactions and perms

---

fs/rc/js/loader.js

I was experimenting with rclone running in WebAssembly and saw the name in the RC call was wrong.
No. This is a small change so I don't think we need to discuss.

fs/rc/js: correct RC method names

---

docs/content/drive.md

docs/drive: mention that google docs count as empty files in directory totals

---

backend/jottacloud/jottacloud.go

From commit messages:
1. A strange feature (probably bug) in the api used by the server-side copy implementation in Jottacloud backend is that if the destination file is in trash, the copy request succeeds but the destination will still be in trash! When this situation occurs in rclone, the copy command will fail with "Failed to copy: object not found" because rclone verifies that the file info in the response from the copy request is valid, and since it is marked as deleted it is treated as invalid. This PR works around this problem by looking for this situation in the response from the copy operation, and send an additional request to a built-in deduplication endpoint that will restore the file from trash.
2. Now using the utility function for deduplication that was newly implemented to …

Jottacloud: Fix issue with server-side copy when destination is in trash

---

docs/content/docs.md

Add --multi-thread-streams note to --transfers.
Add --multi-thread-streams note to --transfers.
https://github.com/rclone/rclone/issues/6057

Improve docs

---

docs/content/faq.md

faq: small grammar fix

---

docs/content/bisync.md

Minor grammar fix

---

backend/jottacloud/jottacloud.go

This fixes the failing integration test: TestIntegration/FsMkdir/FsPutFiles/FsIsFile
Previously there was a discrepancy:
```
rclone ls "remote:Archive/rclone-test-tozewob2qibivak0cucuxip9/hello? sausage/êé/Hello, 世界/ \" abc"
0 Archive/Archive/rclone-test-tozewob2qibivak0cucuxip9/hello? sausage/êé/Hello, 世界/ " abc/z.txt
rclone ls "remote:Archive/rclone-test-tozewob2qibivak0cucuxip9/hello? sausage/êé/Hello, 世界/ \" abc" --disable ListR
0 z.txt
```
The latter is correct, and with this fix both returns this result.
No. Detected by integration test TestIntegration/FsMkdir/FsPutFiles/FsIsFile.

Jottacloud: Fix listing output of remote with special characters

---

docs/content/_index.md
docs/content/amazonclouddrive.md
docs/content/azureblob.md
docs/content/b2.md
docs/content/box.md
docs/content/fichier.md
docs/content/ftp.md
docs/content/googlecloudstorage.md
docs/content/http.md
docs/content/opendrive.md
docs/content/qingstor.md
docs/content/s3.md
docs/content/sharefile.md
docs/content/storj.md
docs/content/sugarsync.md

docs: Small improvements

---

docs/content/install.md
docs/content/install.sh

Remove use of "Smart quotes" (extended ASCII)
(Didn't seem to be consistent use so I changed it to be like "the rest of it.")
No.
- [ N ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ N ] I have added tests for all changes in this PR if appropriate.
- [ N/A ] I have added documentation for the changes if appropriate.
- [ ? ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ Y ] I'm done, this Pull Request is ready for review :-)

Mct tinker doc formatting

---

vfs/vfscache/cache.go
vfs/vfscommon/path.go

Split out the two first two, "safe", commits from https://github.com/rclone/rclone/pull/5916

vfs: minor improvements

---

backend/s3/s3.go

Adding a new location in Warsaw (Poland) to endpoints for Scaleway.
More Information:
https://blog.scaleway.com/scaleway-is-now-in-warsaw/
https://www.scaleway.com/en/docs/storage/object/how-to/create-a-bucket/
I don't think so.

s3: Add Warsaw location for Scaleway

---

backend/webdav/odrvcookie/fetch.go

Support `SharePoint in other specific regions` in webdav
No.

webdav: add SharePoint in other specific regions support

---

docs/content/overview.md

Added entries missing from "Optional features" section, based on current list in "Features" section. Found that Akamai Netstorage, Koofr and Sia was missing. Added them, and looked up their optional features to fill in as best I could.
No

Complete list of optional features (Akamai Netstorage, Koofr and Sia)

---

backend/pcloud/pcloud.go

Continuing my slight quest to look at stale issues another tiny fix.  This fixes #5052.

pcloud: fix about with no free space left

---

docs/content/mega.md

added extra subsection under ### Failure to log-in 
related to issue https://forum.rclone.org/t/30935
- [*] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [-] I have added tests for all changes in this PR if appropriate.
- [*] I have added documentation for the changes if appropriate.
- [*] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [*] I'm done, this Pull Request is ready for review :-)

mega login diagnostics with MEGAcmd

---

docs/content/onedrive.md

Doc about creating client ID for OneDrive Business. The current methods (for OneDrive Personal) might not work.
No, I'm creating a post for discussion.

Added doc about client ID for OneDrive Business

---

backend/opendrive/opendrive.go

Resolves two issues with opendrive:
1) fetches metadata directly from `/file/info.json` in readMetaData when possible (if the object id is already known)
Previously all calls in readMetaData relied on the `/folder/itembyname.json` api which is buggy: items written to a directory take an arbitrary amount of time to appear via this endpoint, and the file info returned does not include the file hash.
2) resolves a bug caused by an undocumented feature of the `move_copy` endpoint which silently truncates new filenames to 255 char. rclone (correctly) throws an error when attempting to create a file or directory that surpasses the max length for opendrive, but there is no check performed in the move_copy command. Without such a check files written to the remote may have their names modified …

opendrive: resolve lag and truncate bugs fixes #5936

---

fs/cache/cache.go

A fix, `cache.Unpin` should most likely call `c.Unpin`.
No.

cache: fix cache unpin

---

backend/jottacloud/jottacloud.go

Existing version did save username in config, but only when entering the non-standard device/mountpoint sequence during config. Regardless of that, it did always request the username from the api at startup (NewFS). So the first one is a bug, but then the second superfluous api request masks the bug. (Alternatively one could say the api request is correct, but the first bug is just that the username should never be stored in config).
This commit improves these things:
- The username will now always be stored in config.
-> Consistency.
- When using standard authentication the username is picked from the login token, instead of requesting it separately from the remote api during the config process.
-> Saves 1 api request during config.
- The fs constructor picks the username from config …

Jottacloud: Always store username in config and use it to avoid initial api request

---

backend/azureblob/azureblob.go
backend/drive/drive.go
backend/googlecloudstorage/googlecloudstorage.go
backend/onedrive/onedrive.go
backend/s3/s3.go
backend/union/union.go
backend/union/upstream/upstream.go
backend/uptobox/uptobox.go
backend/yandex/yandex.go
cmd/help.go
cmd/selfupdate/verify.go
cmd/serve/docker/docker.go
cmd/serve/docker/systemd_unsupported.go
cmd/serve/ftp/ftp.go
fs/config_test.go
fs/filter/filter_test.go
fs/fshttp/http.go
fs/operations/operations_test.go
fs/operations/reopen.go
fs/rc/jobs/job_test.go
fstest/fstests/fstests.go
go.mod
go.sum
lib/cache/cache.go
lib/structs/structs_test.go
vfs/vfs.go

Fix more "problems" reported by the staticcheck lint tool (v0.3.2).
Continuing from https://github.com/rclone/rclone/pull/6228
See also https://github.com/rclone/rclone/issues/6273

Fix staticcheck linting problems

---

backend/azureblob/azureblob.go
docs/content/azureblob.md

Allow usage of remote azurite emulator.
Just add Endpoint parameter in advanced settings when defining/editing remote with something like:
http://10.254.2.5:10000/devstoreaccount1

Implements #6290 enhancement (azureblob)

---

vfs/help.go
vfs/vfs.go
vfs/vfscommon/options.go
vfs/vfsflags/vfsflags.go

Add a flag option for VFS to manually set the total disk space.
#3270

vfs: add flag option to manually set the total disk space

---

docs/content/install.md

docs: fix links to mount command from install docs

---

backend/sftp/sftp.go

Fix regression from https://github.com/rclone/rclone/pull/5763.
In the code to make root path absolute, it seems the introduced call to RealPath function fails with "Folder not found: directory/file.csv (SSH_FX_FAILURE)" on WS_FTP. Resorting to the previous strategy of fetching current working directory with Getwd and doing a simple path.join. Hopefully this works - even though Getwd is implemented as `RealPath(".")` (which is why I in the linked PR assumed I could simply do a RealPath on the input path).
https://forum.rclone.org/t/regression-in-ws-ftp-support/31976

sftp: fix issue with WS_FTP by working around failing RealPath

---

cmd/serve/sftp/connection.go

Too much? I think this code section is eccentric enough to warrant a comment, indicating it could be removed entirely in future. (Near future - even immediately?)
See #6351

Document legacy code for checksum detection in serve sftp

---

docs/content/filtering.md

fix typo in filtering.md

---

docs/content/onedrive.md

So sorry for the small pull request but this one typo was bothering me.

Update onedrive.md to fix a minor typo

---

backend/crypt/cipher.go

Replaces `strign` with `string`
No.

Fix comment typo in cipher.go

---

docs/content/ftp.md

Improve documentation of Anonymous FTP

---

docs/content/jottacloud.md

In light of recent discussions, I've tried to explain a bit more regarding the Jottacloud standard authentication and the use of tokens.
#6372

Jottcloud: Improve documentation of standard authentication

---

backend/box/box.go
backend/filefabric/filefabric.go
backend/googlephotos/googlephotos.go
backend/onedrive/api/types.go
backend/onedrive/onedrive.go
backend/seafile/seafile.go
backend/sugarsync/sugarsync.go
backend/webdav/webdav.go
backend/zoho/zoho.go

Cleanup the brand name in the comments and logs.
N/A

cleanup: brand name

---

cmd/serve/sftp/sftp.go

Document that serve sftp uses chunk size 32 KiB

---

docs/content/onedrive.md

fix a typo: aftering -> after

---

docs/content/install.md

This also adds repology badges where appropriate to show versions in external repositories.
Can you take a look @albertony and see what you think?

docs: update install docs to make more consistent

---

.github/workflows/build.yml
.github/workflows/build_publish_docker_image.yml
.github/workflows/build_publish_release_docker_image.yml

Keep up with recent versions of GitHub Actions.
No.

workflows: update GitHub Actions

---

cmd/mountlib/rc.go

Fixes https://github.com/rclone/rclone/issues/6469

Validate Daemon Option is not set when mounting Volume via RC

---

backend/oracleobjectstorage/oracleobjectstorage.go
docs/content/overview.md

Minor doc updates were suggested in https://github.com/rclone/rclone/pull/6504
This PR adresses them
Yes it was discussed in this PR: https://github.com/rclone/rclone/pull/6504
- [ X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).

oracle-object-storage doc fix

---

docs/content/downloads.md

docs: add direct download link for windows arm64

---

backend/sftp/sftp.go

Adding advanced configuration options for SFTP, to set Ciphers, Key Exchange and MACs algorithms.
https://github.com/rclone/rclone/issues/6503

Custom ssh encryption config

---

backend/s3/s3.go

Update list of Wasabi locations to ensure all locations are available

Add additional Wasabi locations

---

backend/sftp/sftp.go

Fish is different from POSIX-based Unix shells such as bash, and a bracketed variable references like we use for the auto-detection echo command is not supported. The command will return with zero exit code but produce no output on stdout. There is a message on stderr, but we don't log it due to the zero exit code:
> fish: Variables cannot be bracketed. In fish, please use {$ShellId}.
Fixes #6552

SFTP: Auto-detect shell type for fish

---

cmd/ncdu/ncdu.go

Based the commit on #6562.
Use tcell directly instead of the termbox wrapper
Following up on 36add0af, which switched from `termbox`
to `tcell`'s wrapper.
Here are some differences from the previous code.
The original `termbox` library only supports using one rune (code-point) for a cell. But many Unicode characters are made up of multiple runes (code-points), called grapheme clusters.
With the `tcell` library, you can also set additional runes, which seems to work for graphemes. This code iterates through graphemes through the `uniseg` library, which seems to be an indirect dependency already.
Previous: #6258
Issue:  #6272

ncdu: move to native tcell

---

cmd/serve/restic/restic.go

one word typo in the docs - 'remove' should be 'remote'

---

backend/storj/fs.go
docs/content/overview.md

Implement a server-side copy in the Storj backend.
https://github.com/rclone/rclone/issues/5961#issuecomment-1128765437

storj: implement server side Copy

---

backend/s3/s3.go

Storj switched to a single global s3 endpoint backed by a BGP routing. We want to stop advertizing the former regional endpoints and have the global one as the only option.
No.

s3/storj: update endpoints

---

backend/storj/fs.go
docs/content/overview.md
fstest/fstests/fstests.go

Implement the generation of a public link for the Storj backend.
No.

storj: implement public link

---

docs/content/googlephotos.md

fix grammar

---

docs/content/docs.md
fs/config.go
fs/config/configflags/configflags.go
fs/fshttp/http.go

fs:Added multiple ca certificate support.

---

cmd/cmount/mount.go
cmd/cmount/mountpoint_other.go
cmd/cmount/mountpoint_windows.go
cmd/mount/mount.go
cmd/mount2/mount.go
cmd/mountlib/mount.go
cmd/mountlib/utils.go

Mount: Avoid incorrect or premature overlap check on windows

---

backend/smb/connpool.go

smb backend: Check if the connection is closed

---

.github/workflows/build.yml

Currently, when pushing a branch to upstream rclone/rclone and making a pull request from that (instead of from a branch pushed to my own fork, which has the advantage of publishing beta binaries) the same github workflow runs twice - once for the branch push and once for the pull request.
Using the trick from here:
https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/
The condition is getting a bit long, unfortunately, but to break down the change: The existing condition
```
github.repository == 'rclone/rclone'
```
is extended
```
github.repository == 'rclone/rclone' && 
```
with a condition that it is not a pull request (i.e. it is branch push):
```
(github.event_name != 'pull_request'
```
or, if it is a pull request, then it is not from a branch on …

Avoid running workflow twice for pull requests with branch on main repo

---

backend/s3/s3.go

Fixes #6734
No, but in the above issue.

s3: the tier features for StorJ and IDrive sometimes wasn't disabled

---

docs/content/onedrive.md

Adding troubleshooting tips for Live Photos in OneDrive
https://forum.rclone.org/t/keep-only-those-different-files/35862

docs: added troubleshooting tips for Live Photos in OneDrive

---

.github/workflows/build.yml

Bump to go1.20 from go1.20-rc3
N/A

build: update to go1.20

---

backend/storj/fs.go
docs/content/flags.md
docs/content/storj.md

The docs and setup wizard still contained deprecated URLs and labels of Storj satellites. This change updates them.
No.

storj: update satellite urls and labels

---

fs/accounting/stats.go

Show human readable elapsed time when longer than a day

---

cmd/mountlib/help.go

Improve explanation of windows filesystem permissions

---

docs/content/oracleobjectstorage.md

Add more documentation around oci authentication ways to help customer chose the authentication provider. 
- [X ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ X] I have added tests for all changes in this PR if appropriate.
- [X ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).

oracle-object-storage: Add more documentation around oci authentication ways

---

backend/seafile/renew_test.go

Fix for flaky test in the Seafile backend:
An unexpected third renewal was presumably happening between `Wait` and `Shutdown`.
The test is now time based, which reflect the reality better.
Fixes #6799

seafile: fix for flaky tests #6799

---

docs/content/install.md

[`rclone`](https://scoop.sh/#/apps?q=rclone&s=0&d=1&o=true&id=ccc713250d346ba7920eb69c8c8fbd02e60d9e57) is available via Scoop.

docs: add scoop installation method

---

docs/content/commands/rclone_mount.md

Adds some notes on mounting on macOS with macFUSE and FUSE-T
https://forum.rclone.org/t/fr-fuse-t-support-for-mounting-volumes-on-mac/33110/20?u=jwink3101

rclone mount on macOS documentation

---

Dockerfile

Add missing `fuse3` dependency to Dockerfile to fix #6844

docker: add missing fuse3 dependency - fixes #6844

---

backend/ftp/ftp.go

It extracts `textproto.Error` from the errors returned by `github.com/jlaffaye/ftp`, so that necessary checks are done properly
The bug seems to be existed for 6 years!
https://forum.rclone.org/t/vsftpd-vs-rclone-part-2/36774/17

ftp: properly extract `textproto.Error` from the errors returned by `github.com/jlaffaye/ftp`

---

backend/s3/s3.go
docs/content/s3.md

Add GCS as a provider to workaround a specific issue with that storage.
https://github.com/rclone/rclone/issues/6670

s3: add GCS to provider list

---

backend/uptobox/uptobox.go

* Fixes another warning found by codeql. From #6555 and follow up to #6782

uptobox: fix improper regex

---

backend/googlecloudstorage/googlecloudstorage.go

Added requester pays functionality for Google Cloud Storage
Not that I'm aware

googlecloudstorage: added gcs requester pays

---

backend/jottacloud/jottacloud.go

When using option `no_versions` with the Jottacloud backend, uploading a file will first delete any existing - using the permanent ("hard") delete option. In contrast to regular delete, the permanent delete api request will fail with 404 if path is not found. If, for whatever reason, this should occurr, it would lead to upload error:
> Failed to copy: failed to remove old object: error 404: no.jotta.backup.errors.NoSuchFileException: File /xxxxxx/Jotta/Archive/test.txt does not exist (Not Found)
I think this will solve https://github.com/rclone/rclone/issues/6857. I didn't reproduce a real case myself, but provoked it in debugger by deleting file while paused on break point etc. I'm pretty sure the same can happen in real life though, and I think it is similar to the mentioned isseu.

Jottacloud: Avoid returning error when option no_versions and remove fail

---

librclone/README.md

librclone:Added example on using librclone with golang.

---

cmd/ncdu/ncdu.go

Fixes #6271
This PR implements two different approaches to fixing the issue, mentioned in the issue.
Issue #6271

cmd/ncdu: fix screen corruption

---

bin/cross-compile.go

build: set Rclone as file description since it is shown as process name in task manager

---

fs/operations/rc.go

The document need to be clarified. I have been struggling for this and find an answer from [this thread](https://forum.rclone.org/t/rclone-rc-operations-copyfile-copy-local-file-to-remote-fail/15608/3). This pull request is to help others avoid the same problem.
It is discussed in the forum 2 years ago <https://forum.rclone.org/t/rclone-rc-operations-copyfile-copy-local-file-to-remote-fail/15608/3>

Clarify the docs of remote control - operations/copyfile

---

docs/content/drive.md

Update instructions of setting up google drive service account.
No.

Update drive service account guide

---

backend/cache/cache.go
backend/combine/combine.go
backend/crypt/cipher.go
backend/crypt/crypt.go
backend/dropbox/dropbox.go
backend/fichier/api.go
backend/fichier/fichier.go
backend/hidrive/hidrive.go
backend/jottacloud/jottacloud.go
backend/s3/s3.go

backend: fix typos found by codespell

---

docs/content/docs.md

This was discussed in #3759, but not sure if this added documentation qualifies for closing the issue?

Document how the configuration file is written, and that an .old file will be deleted

---

docs/content/install.md

Interactive use from `docker` requires the `-it` flag. Otherwise the command files.
See: https://docs.docker.com/engine/reference/commandline/cli/#option-types
No

Doc update: Install with docker: interactive use

---

lib/buildinfo/arch.go
lib/dircache/dircache.go
lib/errors/errors.go
lib/terminal/terminal.go

lib: fix typos found by codespell

---

cmdtest/cmdtest_test.go

cmdtest: fix typos found by codespell

---

backend/hdfs/hdfs.go
backend/onedrive/onedrive.go
backend/oracleobjectstorage/options.go
backend/sftp/sftp.go

Fix repeat-word typos in docs.
No.

backend: fix repeated words typos

---

vfs/vfs.go
vfs/vfscache/cache.go
vfs/vfscache/item.go
vfs/vfscommon/options.go

vfs: fix typos found by codespell

---

fstest/testserver/init.d/TestSia

fstest: fix typo found by codespell

---

backend/azureblob/azureblob.go

Azurite [complains](https://github.com/Azure/Azurite/blob/main/src/blob/handlers/BlockBlobHandler.ts#L127) about an invalid `ms-access-tier` header when uploading a blob when no tier is [configured](https://rclone.org/azureblob/#azureblob-access-tier) (and [defaults to empty/nothing](https://github.com/rclone/rclone/blob/master/backend/azureblob/azureblob.go#L65)).
The purpose of this change is to be compatible with Azurite.
The API spec states [specifying the access tier is optional](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storage/data-plane/Microsoft.BlobStorage/preview/2021-08-06/blob.json#L4145). [As do the docs](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob?tabs=azure-ad#request-headers-all-blob-types). However I think Azurite is …

azureblob: send nil tier if empty string

---

backend/webdav/webdav.go

Fix webdav server side copy/move
[6964](https://github.com/rclone/rclone/issues/6964)

fix webdav server side copy/move not overwriting

---

cmd/mount2/mount.go
cmd/mount2/mount_test.go
cmd/mount2/node.go
go.mod
go.sum

Various fixes & updates for mount2
N/A

mount2: fixes & updates

---

README.md
backend/s3/s3.go
docs/content/_index.md
docs/content/s3.md

Add [Petabox.io](https://petabox.io) to S3 providers. I've ran rclone's integration tests successfully.
No.

s3: add petabox.io to s3 providers list

---

backend/s3/v2sign.go

The delete query string parameter must be included when you create the CanonicalizedResource for a multi-object Delete request.
Per https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html

add subresource delete to s3 v2sign

---

docs/content/chunker.md

Small typo in chunker.md doc
No
- [ NA] I have added tests for all changes in this PR if appropriate.
- [ NA] I have added documentation for the changes if appropriate.

docs: chunker.md doc typo

---

docs/content/s3.md

docs: S3 - old broken link updated

---

fs/filter/filter.go
fs/filter/filter_test.go

fs: fix deadlock error when all checkers exit

---

docs/content/faq.md

Add solution to an issue on Windows 10 / Windows 11
Add a solution to an issue I've noticed multiple times on various forums.
In my case it fixes the issues every time it had happened in my case.
n/a

Add additional FAQ item for port opening issues on Windows

---

backend/combine/combine.go
backend/crypt/crypt.go

backend: fix misspellings found by codespell

---

docs/content/dropbox.md

docs: dropbox get client id, clarify you need to click a button

---

backend/jottacloud/jottacloud.go
docs/content/jottacloud.md

Implement a Jottacloud-based backend for Onlime (https://onlime.dk), which recently moved to their own servers, after selling support and access to Jottacloud proper.
Not to my knowledge

20230701 onlime backend

---

backend/webdav/chunking.go
backend/webdav/webdav.go

Fix https://github.com/rclone/rclone/issues/7103
Before this change the RegExp validating the endpoint URL was a bit
too strict allowing only /dav/files/USER due to chunking limitations.
This patch adds back support for /dav/files/USER/dir/subdir etc.
Co-authored-by: Nick Craig-Wood <nick@craig-wood.com>

webdav: nextcloud: fix must use /dav/files/USER endpoint not /webdav error

---

docs/content/drive.md

Fix the step 4 in section "Making your own client_id" of drive.md
No

documentation: fix step 4 in "Making your own client_id"

---

README.md
docs/content/_index.md

doc: Add Object storage to Leviia on README.md

---

docs/content/s3.md

doc: Fix Leviia block

---

MAINTAINERS.md

Add @henrybear327 to the MAINTAINER file.
As instructed by @ncw

Add Chun-Hung Tseng to Maintainer

---

backend/protondrive/protondrive.go
go.mod
go.sum

**For Beta testers: Please remove all the files you have uploaded using rclone before trying this version! The bug in the digests parsing and uploading logic is a breaking change**
---
To address the [signature verification issue](https://github.com/rclone/rclone/issues/6072#issuecomment-1646749246) and the digests parsing bug discovered along the way.
Yes

protondrive: fix bug in digests parsing

---

docs/content/dropbox.md

<!--
Explain common Dropbox App Id mistake in docs.
No.

docs: dropbox: Explain that Teams needs "Full Dropbox"

---

backend/protondrive/protondrive.go
go.mod
go.sum

To address the [issue](https://github.com/rclone/rclone/issues/6072#issuecomment-1648721049) reported here, by using the approach mentioned [here](https://github.com/rclone/rclone/issues/6072#issuecomment-1648985817)

protondrive: fix a bug in parsing User metadata

---

backend/ftp/ftp.go
backend/sftp/sftp.go
backend/sftp/ssh_internal.go
lib/proxy/socks.go

Add support for socks 5 proxies to the SFTP/SSH backend
https://github.com/rclone/rclone/issues/3558

Add socks_proxy support for ftp/sftp/ssh backend

---

docs/content/overview.md

There was a typo that put a period where there should be a comma. It confused me a bit at first then I realized it's a typo.
No

add missing comma to overview webdav foodnote

---

docs/content/box.md

based on the forum discussion:
https://forum.rclone.org/t/box-getting-403-errors-when-using-chunker-working-fine-without-it/40388/22

docs: box client_id creation

---

backend/drive/drive.go

Fix typo in Google Drive docs

---

docs/content/local.md

such ash into such as
fix a typo in the local documentation
No

local: fix typo in documentation

---

docs/content/docs.md

Upstreaming knowledge from [this answer](https://forum.rclone.org/t/period-in-remotes-name-is-breaking-config-via-environment-variable/40655/2) to the docs.

Documenting environment-variable-based config supported characters

---

backend/protondrive/protondrive.go

Inform VFS users of a potential issue with the caching mechanism that is currently in place.

protondrive: update the information regarding the advance setting enable_caching

---

MAINTAINERS.md
docs/content/install.md
lib/buildinfo/snap.go

Add snap installation doc
Yes. [Here](https://github.com/rclone/rclone/issues/7221)
- [ x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).

add snap installation

---

backend/box/box.go
backend/filefabric/filefabric.go
backend/local/local.go
backend/local/xattr.go
backend/seafile/renew_test.go
backend/sftp/sftp.go
backend/smb/connpool.go
backend/smb/smb.go
backend/union/upstream/upstream.go
cmd/cmount/fs.go
cmd/cmount/mount.go
fs/operations/check.go
fs/operations/operations.go
fs/rc/jobs/job.go
fs/rc/jobs/job_test.go
fs/sync/pipe_test.go
lib/atexit/atexit.go
lib/file/preallocate_unix.go
lib/oauthutil/renew.go
vfs/file.go
vfs/read.go
vfs/test_vfs/test_vfs.go
vfs/vfs.go
vfs/vfscache/writeback/writeback.go

Use sync/atomic types

---

cmd/ncdu/ncdu.go

cmd/ncdu: add keybinding to rescan filesystem
Fixes #7255

    cmd/ncdu: add keybinding to rescan filesystem

---

cmd/ncdu/ncdu.go

It turns out I forgot something in the previous PR.
#7256

fixup! cmd/ncdu: add keybinding to rescan filesystem

---

backend/sftp/sftp.go

Elaborate exactly how server_command should be used in the configuration file
Help people understand the exact format of server_command in the configuration file
https://forum.rclone.org/t/sftp-server-command-help/41412

Add note regarding format of server_command

---

cmd/rcd/rcd.go
cmd/serve/dlna/dlna.go
cmd/serve/http/http.go
cmd/serve/restic/restic.go
cmd/serve/sftp/sftp.go
cmd/serve/webdav/webdav.go
lib/systemd/doc.go
lib/systemd/notify.go

cmd: refactor and use sysdnotify in more commands
Fixes #5117

cmd: refactor and use sysdnotify in more commands

---

cmd/bisync/help.go
cmd/bisync/rc.go
docs/content/rc.md

Added `rc` support for the flags recently added in #6971. 
Also fixed an older (and rather important) issue causing `dryRun` to be ignored!
No.

bisync: fix rc parameters

---

MAINTAINERS.md

Add @nielash as bisync maintainer
Discussed with ncw via email.

Add @nielash as bisync maintainer

---

backend/protondrive/protondrive.go
go.mod
go.sum

To address the signature verification issue mentioned [here](https://github.com/rclone/rclone/issues/6072)
The changes are discussed / logged at https://github.com/henrybear327/Proton-API-Bridge/issues/3

protondrive: fix signature verification issue

---

docs/content/install.md

https://ports.macports.org/port/rclone/
Add details on how to install rclone on macOS using MacPorts
No

docs: add MacPorts install info

---

backend/box/box.go

Add more logging to the polling code (originally PR #7248), in an attempt to better understand the occasional integration test failures. It's likely that either there are some events being incorrectly filtered in the code, or the Box Event API is slow and doesn't send all events before the test ends. Either way, this additional logging should help us to understand the issue.
Also expand the scope of the EventID filter so that IDs up to 1 minute old will be remembered. This reduces the number of duplicate notifications, since the Box Event API seems to repeat the same events up to 10s later.
No

box: polling tweaks - add more logging and remember more EventIDs

---

backend/azureblob/azureblob.go
backend/box/box.go
backend/mega/mega.go
backend/pikpak/pikpak.go
backend/s3/s3.go
backend/sftp/sftp.go
cmd/cmd.go
cmd/mount2/mount.go
docs/content/box.md
docs/content/changelog.md
docs/content/crypt.md
docs/content/install.md
docs/content/oracleobjectstorage/tutorial_mount.md
fs/object/object_test.go
fs/operations/rc_test.go
vfs/vfscache/downloaders/downloaders.go

Fix a few misspellings.
No.
I haven't prefixed the commit message, perhaps the most suitable would be `docs:` but I have changed files outside `docs`.

Fix typos newly found by codespell

---

docs/content/docs.md

The existing documentation for `--fast-list` has no mention of `ListR` feature. Also its a bit confusing that rclone will use the `ListR` feature by default when doing list commands, while the `--fast-list` is to enable it for other commands. This is if I have understood it correctly - because I'm a bit confused myself...!?

Update documentation for --fast-list adding info about ListR

---

bin/.ignore-emails
docs/content/authors.md

Adjust the files to correct the author SimJoSt in the docs.
I hope I made it in a way that makes sense and is true to the intention.
no

docs: change authors email for SimJoSt

---

backend/azureblob/azureblob.go
backend/azureblob/azureblob_test.go
docs/content/azureblob.md
go.mod
go.sum

Add support azure blob storage for cold tier
No

azureblob: add support cold tier

---

docs/content/union.md

union: fix documentation

---

cmd/hashsum/hashsum.go

Show hashsum arguments as optional in usage string

---

backend/quatrix/api/types.go
backend/quatrix/quatrix.go

quatrix: add resolve mode on conflict during move and partial upload

---

fs/log_test.go

Fix a typo introduced by 3553cc4.

fs: fix a typo in a comment

---

docs/content/overview.md

Document that SMB remote supports modtime.
https://forum.rclone.org/t/how-to-access-smb-samba-with-rclone/42754

Update Docs to show SMB remote supports modtime.md

---

cmd/mountlib/mount.go
cmd/serve/docker/driver.go
cmd/serve/docker/systemd.go
fs/log/log.go
fs/log/systemd.go
fs/log/systemd_unix.go
go.mod
go.sum
lib/systemd/notify.go
vfs/vfscache/cache.go

systemd: Fix detection and switch to the coreos package everywhere rather than having 2 separate libraries
https://forum.rclone.org/t/what-does-the-6-before-info-mean-and-will-it-always-be-6/43108/17

systemd: Fix detection and switch to the coreos package everywhere

---

bin/.ignore-emails
docs/content/authors.md

updating contributor email
discussed via email

chore: update contributor email

---

backend/oracleobjectstorage/client.go

Use the option for endpoint override
No

Override object storage endpoint for custom endpoints

---

docs/content/commands/rclone_serve_webdav.md

Fix broken link in docu at rclone_serve_webdav.md
No

Fix broken link in docu at rclone_serve_webdav.md

---

backend/googlephotos/googlephotos.go
cmd/listremotes/listremotes.go
docs/content/authors.md
fs/config/ui_test.go
fs/registry.go

The task was to add description fields for remotes.
Fixes the issue: https://github.com/rclone/rclone/issues/4391

Description field for remotes

---

README.md
docs/content/_index.md
docs/content/overview.md
docs/layouts/chrome/navbar.html

This PR adds [ImageKit](https://imagekit.io) to the discoverable sections of the web and documentation which was missed earlier at the time of integrating it as a backend.
Previous PR: https://github.com/rclone/rclone/pull/7071
N/A

imagekit: Updated docs and web content

---

docs/content/overview.md

@ncw The [previous PR](https://github.com/rclone/rclone/pull/7570) that I had raised yesterday was not marked as ready, but unfortunately it got merged 😢 There was an internal review still going on for the correctness of the documentation around features that we shipped on the backend.
Hence, this PR updates a section that needed minor changes.
N/A

imagekit: updated overview - supported operations

---

docs/content/filtering.md

adding missing backtick in code formatting

docs: add missing backtick

---

backend/oracleobjectstorage/client.go
backend/oracleobjectstorage/options.go
docs/content/oracleobjectstorage.md

Add support for Workload Identity to the Rclone Oracle provider.
n/a

Oracle backend supports workload identity

---

backend/opendrive/opendrive.go
backend/opendrive/types.go
fstest/test_all/config.yaml

Three fixes for integration tests, discussed on [#7591](https://github.com/rclone/rclone/issues/7591#issuecomment-1950296496).
- #7591

opendrive: fix moving file/folder within the same parent dir, add mailru/linkbox overrides

---

backend/onedrive/api/types.go
fs/accounting/accounting.go
fs/config/config.go

chore: remove repetitive words

---

docs/content/drive.md

and added some links to the reference

corrected relative path to absolute into  google drive.md

---

backend/onedrive/onedrive.go

As the commit title suggests, make server-side copy to work between `OneDrive Business` and `SharePoint` or between `SharePoint` and another `SharePoint` when using the same user's token. The origin is that I needed to copy from OneDrive Business to SharePoint, and after searching the internet, I found the forum link mentioned later. I was frustrated that it ultimately didn't result in a PR, so I initiated a PR to implement it.
https://forum.rclone.org/t/should-rclone-be-able-to-server-side-on-onedrive-business/32395/15
- [ X ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ X ] I have added tests for all changes in this PR if appropriate.
- [ X ] I have added documentation for the changes if …

onedrive: make server-side copy to work in more scenarios

---

bin/.ignore-emails
docs/content/authors.md

Just remove my email from authors public page because I get a lot of spam.
Nope, not relevant

Remove email from authors

---

backend/ulozto/api/types.go
backend/ulozto/ulozto.go
docs/content/overview.md
docs/content/ulozto.md

As the commit title suggests, this PR implements the Mover and DirMover interfaces. 
https://github.com/rclone/rclone/pull/7552 is the original integration.

ulozto: implement Mover and DirMover interfaces

---

fs/registry.go

Make it in line with rest of the docs.

Add ending period on description option help text

---

backend/onedrive/onedrive.go

Minor Typo, Find/Replace 'OneDriver Personal' with 'OneDrive Personal'
n/a

Minor Typo, Find/Replace 'OneDriver Personal' with 'OneDrive Personal'

---

cmd/bisync/bisync_test.go

A few more fixes for bisync integration tests:
- fix parsing of connection string remotes (comma in name)
- skip remotes that can't upload empty files
- `Mkdir` the test case subdir before `cache.Get`-ing it (only `storj` seems to need this... bug?)
- #7665

bisync: more fixes for integration tests

---

backend/s3/s3.go

adds il-central-1 Tel Aviv region

s3: add new AWS region

---

backend/koofr/koofr.go

backend koofr: remove trailing bracket - fixes #7600

---

backend/pikpak/helper.go

Fix a small typo in comment. This is the last remaining fix/typo from PR #6970, which can then be closed I guess.
No

pikpak: fix a typo in a comment

---

cmd/cmd.go

fix: close cpu profile

---

cmd/serve/s3/serve_s3.md

Suggestion to add more information to the documentation about serve s3.
See also: #7748

doc: add example how to run serve s3

---

backend/onedrive/metadata.go

Before this change when setting permissions from the metadata rclone would stop on the first error.
This change causes rclone to attempt to set all the permissions and return an error summary at the end.
No.

`onedrive`: set all metadata permissions and return error summary

---

backend/b2/b2.go
backend/cache/handle.go
backend/drive/drive.go
backend/dropbox/dropbox.go

chore: fix function names in comment

---

cmd/serve/s3/backend.go

Modified the `timeFomat` of `Last-Modified` header when respond to get object command.
https://github.com/rclone/rclone/issues/7762

serve s3: fix Last-Modified header format

---

cmd/lsjson/lsjson.go

To clarify a couple options that suffered from too many negatives.
No

lsjson: small docs change to clarify options

---

backend/googlephotos/pattern.go
fs/fserrors/error.go

chore: fix struct names

---

docs/content/downloads.md

https://github.com/rclone/rclone/issues/7798#issuecomment-2076504523

Document that newer Linux kernel version is required for ARMv5

---

lib/http/server.go

docs: minor formatting improvement

---

backend/drive/drive.go
backend/zoho/api/types.go
cmd/bisync/checkfn.go
cmd/bisync/resolve.go

chore: fix some comments

---

cmd/serve/dlna/cds.go

https://github.com/rclone/rclone/issues/7883

Make BrowseMetadata response of serve dlna more compliant - fixes #7883

---

backend/s3/s3.go

Changed Cephs defaults quirks for bucket creation
#7871

Ceph quirks

---

backend/sftp/sftp.go

I've noticed that my rclone instance opens hundreds of connections to my sftp server, sometimes hitting limits, despite default values of `--transfers` and `--checkers`. This PR ports a similar feature from the `ftp` remote to limit number of concurrent connections.
No.
Please verify whether this change makes sense, I'll add necessary documentation then. Also not sure if there is an easy way to add a test here, I don't see the `ftp` remote testing this feature.

sftp: --sftp-connections to limit maximum number of connections

---

docs/content/docs.md

Add docs for --progress about terminal width formatting.
#7794

docs: added info about --progress terminal width

---

backend/jottacloud/jottacloud.go

Jottacloud has writable metadata `mtime` and `btime`. On server-side copy and move the source metadata are preserved, but if custom values are set using the --metadata-set key=value these are not considered.
Example:
```
rclone lsjson jfs:Temp/r1 --metadata
[{"Path":"rclone.exe","Name":"rclone.exe","Size":122671560,"MimeType":"application/octet-stream","ModTime":"2024-05-01T08:19:09Z","IsDir":false,"Metadata":{"btime":"2024-05-01T08:19:09Z","content-type":"application/octet-stream","mtime":"2024-05-01T08:19:09Z","utime":"2024-05-01T08:34:40Z"}}]
rclone copy jfs:Temp/r1 jfs:Temp/r2 --metadata --metadata-set mtime=2003-02-03T04:05:06.499999999Z
rclone lsjson jfs:Temp/r2 --metadata
[{"Path":"rclone.exe","Name":"rclone.exe","Size":122671560,"MimeType":"application/octet-stream","ModTime":"2024 …
```

jottacloud: set metadata on server side copy and move - fixes #7900

---

docs/content/s3.md

Partially fix #7889 by adding docs.
Yes.

docs(s3): recommend `no_check_bucket = true` for Alibaba

---

backend/sftp/sftp.go

Correct comments on connections not to refer to concurrency

---

go.mod
go.sum

To enhance AWS Signature V4 authentication support
https://github.com/rclone/gofakes3/pull/6

serve s3: enhance AWS Signature V4 authentication support

---

go.mod
go.sum

Implement authentication expiration check for S3 requests
https://github.com/rclone/gofakes3/pull/7

serve s3: Implement authentication expiration check for S3 requests

---

docs/content/dropbox.md
docs/content/googlephotos.md
lib/batcher/options.go

docs: Small typo in dropbox.md

---

docs/content/install.md

docs: add comment how to reduce rclone binary size

---

cmd/gendocs/gendocs.go

This continues from PR https://github.com/rclone/rclone/pull/7606, which was fixing issue https://github.com/rclone/rclone/issues/7605. 
As discussed in the issue comments, that previous PR attempt missed the fact that the gendocs command must generate the alias front matter field. This is implemented here. With this in place, Hugo will automatically generate redirect pages, which immediately redirects to the primary page using the `http-equiv="refresh" html trick`, as explained in [How Hugo Aliases Work](https://bwaycer.github.io/hugo_tutorial.hugo/extras/aliases/).
The implementation got a bit dirty, to handle aliasing at any level of subcommand paths. Currently the `completion` command has alias `genautocomplete`, intended for `/commands/rclone_genautocomplete/` to be redirected to …

Add automatic alias redirects for command pages

---

docs/layouts/chrome/navbar.html

Fix alignment of some of the icons in the storage system dropdown

---

docs/content/remote_setup.md

Update remote setup documentation

---

backend/dropbox/dropbox.go
backend/local/metadata.go
backend/s3/s3.go
cmd/serve/docker/options.go
fs/config/obscure/obscure.go
lib/encoder/encoder.go

This fixes a few CodeQL issues, reported in the project's Security page on GitHub. It would be good to at least get rid of the ones reported as `Critical` here, to avoid scaring away any potential users..
This should fix 2 of 3 `Critical` issues:
- https://github.com/rclone/rclone/security/code-scanning/129
- https://github.com/rclone/rclone/security/code-scanning/130
It should also fix 5 issues of type "Incorrect conversion between integer types" (severity `High`), all of that type except one, as well as one of 4 issues of type "Size computation for allocation may overflow" (severity `High`).

Codeql fixes

---

backend/local/metadata.go

One more fix for a new issue that popped up after merging https://github.com/rclone/rclone/pull/8010.

local: fix incorrect conversion between integer types

---

backend/pcloud/api/types.go
backend/pcloud/pcloud.go
backend/pcloud/writer_at.go

This is the second approach on #7896 by implementing OpenWriterAt instead of OpenChunkWriter (#7895), proposed [here](https://github.com/rclone/rclone/issues/7896#issuecomment-2227097288) 
- Issue #7896

pcloud: implement SetModTime and OpenWriterAt

---

backend/s3/s3.go

Allow `backend restore` command to work with AWS S3 objects with Intelligent-Tiering storage class.
https://forum.rclone.org/t/adding-support-for-restoring-from-s3-intelligent-tiering-archive-access-tier/47408

s3: allow restoring from intelligent-tiering storage class

---

docs/content/docs.md

To make it very easy to properly protect backends credentials
https://github.com/rclone/rclone/pull/8051#discussion_r1744141418

documentation: add cheatsheet for configuration encryption

---

cmd/lsjson/lsjson.go

https://github.com/rclone/rclone/pull/7747#discussion_r1558092028

docs: group the different options affecting lsjson output

---

backend/jottacloud/jottacloud.go

:weary:
PS: This fixes a bug in the implementation from #7906, to hopefully finally fix issue #7900.

Fix setting of metadata on server side move in Jottacloud

---

docs/content/s3.md

Add 'Increasing performance' section in s3 docs, with tips for significantly increasing checkers and transfers values.
https://forum.rclone.org/t/rclone-performance-vs-s3s3mirror/47598

docs: add section for improving performance for s3

---

backend/protondrive/protondrive.go

The change improves performance of the Proton Drive backend by removing some redundant calls to the Proton Drive API. It may help with the performance issues reported in #7322 and #7413.
I'm particularly interested in using Proton Drive with `bisync`. For my particular use case (~500 files in ~50 directories weighing in at 600 MB), the change reduces `bisync` runtime from ~45 to ~7 minutes with `--resync`, and from ~30 mins to ~2 minutes without `--resync`.
The change is just based on the observation that links to files obtained via the Proton Drive API are sometimes retrieved twice. The function `List()` does a directory listing and gets a link to each child file, then constructs a path from each link, then `getObjectLink()` is called to get a link again from each path. The change …

Performance improvements for Proton Drive backend

---

backend/local/clone_darwin.go
backend/local/local_internal_test.go

Before this change, `--copy-links` erroneously behaved like `--links` when using cloning on macOS, and cloning was not supported at all when using `--links`.
After this change, `--copy-links` does what it's supposed to, and takes advantage of cloning when possible, by copying the file being linked to instead of the link itself.
Cloning is now also supported in `--links` mode for regular files (which benefit most from cloning). symlinks in `--links` mode continue to be tossed back to be handled by rclone's special translation logic.
- https://forum.rclone.org/t/macos-local-to-local-copy-with-copy-links-causes-error/47671/5?u=nielash

`local`: fix `--copy-links` on macOS when cloning

---

backend/box/box.go
cmd/bisync/bisync_test.go
fs/sync/sync_test.go
fstest/test_all/config.yaml

Several fixes for bisync integration tests, most of which were discussed [here](https://github.com/rclone/rclone/pull/7795#issuecomment-2163295857).
- https://github.com/rclone/rclone/issues/3511
- https://forum.rclone.org/t/rclone-bisync-box-failed-to-create-file-system-is-a-directory-not-a-file/47908/19?u=nielash

box: fix server-side copying a file over existing dst (and other bisync test fixes)

---

README.md
backend/s3/s3.go
docs/content/_index.md
docs/content/s3.md

This PR add [Outscale](https://fr.outscale.com/solutions-stockage-cloud/oos/) S3 provider, so we can use rclone with Outscale OOS API directly. 
Note that it's my first time contributing to this project, and I think that everything is correct in the checklist, but I might have miss some tasks. If so I'll try to fixe them asap.

Add Outscale S3 Provider

---

docs/content/s3.md

docs: fix Scaleway Glacier website URL

---

docs/content/drive.md

Making your own client_id
#8129

fix issue 8129 by using correct forward refs in sec 9 of using

---

cmdtest/environment_test.go

chore: fix function name in comment

---

cmd/bisync/bilib/output.go

Fix #8158 
no
- [x ] I have added tests for all changes in this PR if appropriate.

Fix Bug in bisync #8158

---

docs/content/docker.md

This proposal expande the current docker volume plugin troubleshooting possible steps to inclue a state cleanup command and a reminder that a un/reinstall don't clean up those cache files.
This proposal expande the current docker volume plugin troubleshooting possible steps to inclue a state cleanup command and a reminder that a un/reinstall don't clean up those cache files.
Change triggered by an issue : https://forum.rclone.org/t/docker-plugin-fail-to-start-reinstall/29871/7

Expanded docker volume plugin documentation

---

cmd/serve/sftp/server.go

Existing:
In serve sftp function `loadAuthorizedKeys`, after reading the authorized keys file, `ssh.ParseAuthorizedKey` from `golang.org/x/crypto` is called with the file content as input to parse a single authorized key. It silently skips invalid lines and comment lines until it is able to parse a key, and returns it together with remaining text. If it is unable to find a key, it returns an error. We repeat the call `ssh.ParseAuthorizedKey` with any remaining file content, in a loop, while collecting all parsed keys. However, this means that when reaching a point in the file content where there is remaining text but from which no valid keys can be parsed, such as comment lines at the end of the authorized keys file, we will end up getting an error return. The error is returned by …

Fix loading of authorized keys file with comment on last line

---

docs/content/pcloud.md

update pcloud doc to avoid puzzling token error when use remote rclone authorize
No. Just I met this when use the doc and want to save other ppl's time

update pcloud doc

---

docs/content/filtering.md

There's an error which looks like copypaste mistake.
- [~] I have added tests for all changes in this PR if appropriate.
- [~] I have added documentation for the changes if appropriate.

docs: filtering: fix --include-from copypaste error

---

docs/content/filtering.md

Filtering now mentions feeding --files-from from standard input
- [~] I have added tests for all changes in this PR if appropriate.
- [~] I have added documentation for the changes if appropriate.

docs: filtering: mention feeding --files-from from standard input

---

docs/content/smb.md

The documentation is outdated. The code uses another library, a newer maintained fork: https://github.com/rclone/rclone/blob/b85a1b684bba2c82684971e91ea49a0b8949ad89/go.mod#L27C1-L27C65

Link to CloudSoda/go-smb2 fork

---

go.mod
go.sum

Improve compatibility with Microsoft FTP server
https://github.com/jlaffaye/ftp/pull/354

ftp: update jlaffaye/ftp

---

backend/smb/connpool.go
backend/smb/kerberos.go
backend/smb/smb.go
backend/smb/smb_test.go
fstest/test_all/config.yaml
fstest/testserver/init.d/PORTS.md
fstest/testserver/init.d/TestSMBKerberos

Add support for kerberos authentication to the `smb` backend.
Fixes #7800.

smb: add support for kerberos authentication

---

backend/azurefiles/azurefiles.go
backend/iclouddrive/iclouddrive.go
backend/imagekit/client/media.go
backend/pcloud/pcloud.go
backend/s3/s3.go
bin/not-in-stable.go
cmd/bisync/compare.go
cmd/bisync/listing.go
cmd/bisync/testdata/test_resync/golden/test.log
cmd/bisync/testdata/test_resync/scenario.txt
cmd/config/config.go
cmd/copyurl/copyurl.go
cmd/serve/nfs/filesystem.go
cmd/serve/nfs/nfs.go
cmd/serve/s3/backend.go
cmd/serve/s3/list.go
docs/content/bisync.md
docs/content/crypt.md
docs/content/docs.md
docs/content/googlephotos.md
docs/content/rc.md
docs/content/s3.md
fs/fshttp/http_test.go
fs/log.go
fs/object/object.go
fs/object/object_test.go
fstest/fstests/fstests.go
vfs/rc.go
vfs/vfs.go
vfs/vfscache/item_test.go

docs: fix typos found by codespell in docs and code comments

---

vfs/vfs.go

vfs shutdown shoud close poll chan

feat: vfs shutdown should close poll chan

---

backend/b2/b2.go
backend/b2/b2_internal_test.go

Add `operations.SkipDestructive()` calls to the b2 backend operations so that `--dry-run` and `--interactive` are handled correctly.
Yes: issue #8194.

b2: add SkipDestructive handling to backend commands - fixes #8194

---

backend/s3/s3.go

s3: Added new storage class to magalu provider

---

backend/s3/s3.go

Add additional DigitalOcean Spaces S3 regions SFO2, LON1, TOR1, BLR1
n/a

s3: add DigitalOcean regions SFO2, LON1, TOR1, BLR1

---

.github/workflows/build_publish_docker_image.yml
Dockerfile

* Disable docker CI builds for PRs
* Added missing dockerfile changes for caching
N/A

build: disable docker builds on PRs & add missing dockerfile changes

---

fs/accounting/stats_groups_test.go

accounting: fix percentDiff calculation where end is greater than start
https://github.com/rclone/rclone/issues/8345

accounting: fix percentDiff calculation -- fixes #8345

---

docs/content/sftp.md

Added a link to `--sftp-path-override` for a better solution with working hash calculation.

Update sftp.md - improved Limitations

---

.github/workflows/build_publish_docker_plugin.yml

Remove docker image build dependency from docker plugin
#8394

build: remove dependency for docker plugin

---

cmd/gitannex/gitannex_test.go

This PR fixes two ways that the gitannex tests can hang:
1. Attempting to read a line with `testState.readLine()` that's never written will block indefinitely. The first commit prevents  `readLine()` from blocking for more than 30 seconds.
2. Our test harness never called `wg.Done()` when `require`-based assertions failed because they halt test execution. D'oh! Also, we were using `require` on the wrong goroutine. The second commit fixes both of these issues.
(More details on each of these in the commit messages.)
Yes: https://github.com/rclone/rclone/pull/8423#issuecomment-2701601290

cmd/gitannex: Fix two ways that tests can hang

---

backend/googlephotos/googlephotos.go

googlephotos: fix typos

---

docs/content/box.md

- [n/a] I have added documentation for the changes if appropriate.
- _It's not - if this is an issue LMK and I'll edit/make a new PR._

minor typo on box.md

---

docs/content/changelog.md

Fix some typos in the documentation via codespell.
No.

docs: fix typos via codespell

---

docs/content/s3.md

Typo fix in documentation.
No.

docs: fix `metadata` typo in s3/storj docs

---

backend/iclouddrive/api/drive.go

* Fixing SIGSEGV https://github.com/rclone/rclone/issues/8211
* Removed files potentially downloaded twice
[](https://github.com/rclone/rclone/issues/8211)

Update iclouddrive drive.go

---

docs/content/docs.md

Inspired by https://github.com/rclone/rclone/pull/8542

Add hint in main docs about config touch and config file not found

---

go.mod
go.sum

Update github.com/ebitengine/purego to v0.8.3 to fix mac_amd64 build

---

docs/content/docs.md
docs/content/overview.md

- Reorder providers alphabetically: moved FileLu above Files.com in /docs/content/overview.md
- Added FileLu to docs/content/docs.md

Reorder providers alphabetically: moved FileLu above Files.com

---

docs/content/docs.md

Explain the json log format in more detail

---

docs/content/rc.md

Fix incorrect json syntax in sample output in rc command docs

---

cmd/mount/dir.go

feat: support symlink detection when reading directories

---

backend/combine/combine.go

This fixes the problem that combine doesn't tell whether its upstreams are SlowHash or not, causing hasher to be confused.
This change aligns the 'combine' backend with the behavior of the 'union' backend, which already correctly propagates the 'SlowHash' feature.
https://github.com/rclone/rclone/pull/6484

combine: propagate SlowHash feature

---

fs/operations/rc.go

Reworking an stale PR:
- https://github.com/rclone/rclone/pull/6873
https://github.com/rclone/rclone/issues/6693

docs: remove broken links from rc to commands

---

docs/content/drive.md

update instructions with the most recent changes to google cloud console

Drive: Docs update making your own client ID instructions

---

backend/azureblob/azureblob.go
backend/combine/combine.go
backend/drive/metadata.go
backend/onedrive/metadata.go
backend/union/policy/epff.go
cmd/gitannex/e2e_test.go
cmd/serve/nfs/cache_test.go
fs/config/rc.go
fs/list/sorter.go
fs/operations/rc.go
fs/sync/rc.go

The new version of Go has been optimized, and variables do not need to be reassigned.

refactor: omit unnecessary reassignment

---

docs/content/smb.md

very small SMB doc typo

---

backend/s3/s3.go

Rearrange s3 backend code to be alphabetical, how it was intended to be.

s3: reorder providers to be in alphabetical order

---

lib/http/auth.go

docs: fix flag in rclone_serve_restic documentation
