fs/accounting.go
Print more of the file name, and make the output aligned, so it is nicer on frequent updates.
Also shows the end of the file instead of the start. I may have accidentally removed that.
=> Show more of the filename and align output.

local/local.go
=> Allow '&' and disallow ':'  in Windows filenames.

docs/content/docs.md, fs/config.go
The option name mirrors the 'wget' option name (also `--no-check-certificate`). The cURL equivalent is called `--insecure`, which is a bit unclear.
Put in the "developers" section in documentation with proper warnings.
Fixes #168
=> Add option to disable server certificate verification.

.travis.yml, fs/config.go
CI tests now tests `go vet`, `go fmt` (via goimports) and `golint`.
Adds Travis experimental OSX support.
Add "tip" tests. Can give an early indication about issues in upcoming Go versions.
This makes contributing easier, since users will get automatic "style errors".
=> Extend CI tests to include formatting + OSX.

amazonclouddrive/amazonclouddrive.go, b2/b2.go, docs/content/docs.md, docs/content/filtering.md, drive/drive.go, dropbox/dropbox.go, fs/fs.go, fs/hash.go, fs/hash_test.go, fs/limited.go, fs/operations.go, fs/operations_test.go, fstest/fstest.go, fstest/fstests/fstests.go, googlecloudstorage/googlecloudstorage.go, hubic/hubic.go, local/local.go, onedrive/onedrive.go, rclone.go, s3/s3.go, swift/swift.go, yandex/yandex.go
Add support for multiple hash types with negotiation of common hash types for comparison.
Manually rebased version of #277 (see discussion there)
=> Add support for multiple hash types (rebased)

b2/b2.go
Backblaze changed API endpoints on August 16, 2016. The old endpoints are still valid, but will be removed Feb 2nd 2017.
See https://help.backblaze.com/hc/en-us/articles/224959187-B2-Domain-Migration-Plan
=> New B2 API endpoint (API domain)

cmd/mount/file.go
This fixes the "total" count from `ls` and other size calculating tools like `du -s` or `ncdu`:
Without:
```
$ \ls -ls 
total 0
0 -rw-r--r-- 1 stefan stefan  583076191 Sep 18 15:56 random.bin
0 -rw-r--r-- 1 stefan stefan 1139375223 Sep 18 15:54 random2.bin
```
With:
```
$ \ls -ls 
total 18434355
569411 -rw-r--r-- 1 stefan stefan  583076191 Sep 18 15:56 random.bin
1112672 -rw-r--r-- 1 stefan stefan 1139375223 Sep 18 15:54 random2.bin
```
=> report number of blocks in fuse

docs/content/onedrive.md
I was uploading a 12GB file to Onedrive and got this error: `Failed to copy: invalidRequest: maxFileSizeExceeded: Declared file size too large. The largest allowed file size is 10737418240 bytes`. Didn't see it anywhere in the docs, so I thought I'd add it.
=> Update Onedrive doc to reflect file size limit

fs/accounting.go
- Only start the token ticker when the timetable entry has more than one
entry.
- This fixes the "Scheduled bandwidth change" log message when no
bwlimit is specified.
- Fixes #987
=> Only start bandwidth ticker when necessary.

fs/operations.go
The code to ignore checksum accidentally checks for the IgnoreSize flag rather than IgnoreChecksum. 
Original commit:
https://github.com/ncw/rclone/commit/9d331ce04b000ea1d284ee5b251fbc142ad8f623
=> fix --ignore-checksum

docs/content/amazonclouddrive.md
Noticed on the Amazon Drive page. Grepped and the only other occurrences are in the generated docs.
=> Fix spelling of Unfortunately in Amazon Cloud Drive docs

cmd/mount/dir.go, cmd/mount/dir_test.go, cmd/mount/file.go, cmd/mount/file_test.go, cmd/mount/mount.go
This patch allows the timestamp to be set for remotes that support it. It stays a no-op for remotes that don't – otherwise it breaks `touch somefile` if the file already exists, which would be a breaking change and is probably unwanted. The alternative would be to fail and ask people to set `--no-modtime`, I guess.
I implemented it for directories, too, even though the timestamp will not be persisted. 
Cheers
Stefan
=> implement ModTime via FUSE for remotes that support it (fixes #1197)

cmd/mount/file.go, cmd/mount/file_test.go
This is "proposal 3" from my [previous comment](https://github.com/ncw/rclone/issues/1197#issuecomment-289964080). I decided not to hand down error until there's an actual bug reported that warrants complicating the error handling in `WriteFileHandle.close`. 
It fixes not only the `cp -a` issue, but also the stale cache issue that would result in the dir listing showing a wrong timestamp for some time directly after copying. 
Cheers
Stefan
=> allow modTime to be changed even before all writers are closed (fixes #1197 -- again)

fs/config.go, fs/config_read_password.go
This makes rclone with encrypted config better suited for use in
pipelines. E.g.:
$ rclone lsl mydrive:Some/Dir | sort -k 4
If the password prompt ("Enter configuration password") is printed to
stdout, it will be swallowed by sort. By printing it to stderr, you
still see the prompt, without sacrificing compatibility with the unix
pipeline.
This patch only focuses on password prompts, which may seem a bit haphazard and inconsistent. However, I didn't want to embark on a full code reorg just to change this in your project :P feel free to adapt, of course.
=> Print password prompts to stderr

drive/drive.go
Fixes the bug found by users in #1346 
Found out that the reason was that people were hitting the maxResults limit (default: 1000). Could pin point it myself by overriding maxResults to 1
=> drive: nextPageToken field was missing

cmd/mount/mount.go, cmd/mount/read.go, cmd/mount/read_test.go, cmd/mount/write.go
I'm not sure how to write decent tests for the error cases, i.e. when comparing the hash sum fails. The only thing I can think of would be meddle with the internal state of some of the objects. When I edit the code so that hash comparison always fails, we get the desired behaviour: input/output errors both during reads and writes.
=> compare checksums on upload/download via FUSE

cmd/mount/dir.go, cmd/mount/dir_test.go, cmd/mount/fs.go, cmd/mount/fs_test.go, cmd/mount/mount.go
some comments on this PR:
* I will rebase/squash when this is ready. I expect your review will yield some more changes :)
* fixes #803, and allows fine grained eviction if needed
* I did not need to modify bazil/fuse after all: It already offers a callback through `NodeForgetter` when it discards something on its side. Together with the already implemented rename/remove, this should cover all cases.
* the extra code in `func (d *Dir) rename(…)` is to fix #1375. I experience it when I test manually with GDrive mounted, but I didn't manage to write a failing test case. I'll have to see in #1375 if this is just a bug in GDrive, just not present in the local backend used in test cases or maybe a timing related issue…
* I wonder if SIGHUP is a good signal choice. I would prefer something like …
=> allow to manually flush the mount cache (fixes #803)

sftp/sftp.go
Set `ssh.ClientConfig.HostKeyCallback` to `ssh.InsecureIgnoreHostKey()` since it's [required](https://github.com/golang/go/issues/19767) now.
=> sftp: specify HostKeyCallback in ClientConfig

.circleci/config.yml, Gopkg.lock, vendor/github.com/billziss-gh/cgofuse/.circleci/config.yml, vendor/github.com/billziss-gh/cgofuse/Dockerfile, vendor/github.com/billziss-gh/cgofuse/README.md, vendor/github.com/billziss-gh/cgofuse/fuse/fsop.go, vendor/github.com/billziss-gh/cgofuse/fuse/host.go
This PR adds cross-compilation for rclone using CircleCI. The PR updates cgofuse to v1.0.1 (necessary to properly cross-compile on Windows) and adds a simple CircleCI configuration file that cross-compiles rclone.
To cross-compile rclone I use the docker image [billziss/xgo-cgofuse](https://hub.docker.com/r/billziss/xgo-cgofuse/) which was produced by this [Dockerfile](https://github.com/billziss-gh/cgofuse/blob/master/Dockerfile). It is basically the xgo docker image with OSXFUSE, LIBFUSE and WinFsp-FUSE added so that cgofuse and rclone can be cross-compiled properly.
The cross-compilation can also be easily done from the command line:
```
$ docker pull billziss/xgo-cgofuse
$ go get -u github.com/karalabe/xgo
$ xgo --image=billziss/xgo-cgofuse …
```
=> Rclone cross compilation

oauthutil/oauthutil.go
Note that modified this code to work temporarily to obtain a refresh_token with GD but do not know the implications with any other supported integrations with rclone.
Initially when connecting with GCD with your own `client_id` and `client_secret` rclone does not request `access_type=offline` with Google which does not return a `refresh_token` that is needed to keep a fresh `access_token`. Therefore subsequent requests with rclone does not work due to the `access_token` being expired.
The change enables the `AuthCodeURL` function to request the offline token and therefore receiving a refresh token.
There's also a workaround to get this working without changing the code if you know oauth2 well. You can modify the AuthCodeURL and provide the query parameter manually and rclone will pick up …
=> Obtain a refresh token from Google oauth

amazonclouddrive/amazonclouddrive_test.go, b2/b2_test.go, cmd/cmount/fs.go, cmd/cmount/mount.go, cmd/mount/fs.go, cmd/mount/mount.go, cmd/mountlib/fs.go, crypt/crypt2_test.go, crypt/crypt3_test.go, crypt/crypt_test.go, drive/drive.go, drive/drive_test.go, dropbox/dropbox_test.go, fs/fs.go, fstest/fstests/fstests.go, ftp/ftp_test.go, googlecloudstorage/googlecloudstorage_test.go, hubic/hubic_test.go, local/local_test.go, onedrive/onedrive_test.go, s3/s3_test.go, sftp/sftp_test.go, swift/swift_test.go, yandex/yandex_test.go
With this patch I am the least sure about the actual selection of path to invalidate the cache for. Everything is given as `kind:File` (or type `*File`), even if it's a folder. In some scenarios it appeared as if it would cache invalidate `/`, even though I only had changes within `/subdir/`, but I did not manage to reproduce those. The integration test I added also passes for me.
I'll dogfood the patch in the following days, though, and can always contribute more patches I guess.
Cheers
Stefan
=> poll for Google Drive changes when mounted

fs/operations.go, fs/operations_test.go
#1261 is only about moving and copying from/to the same destination works for me on Google Drive even without the patch. I guess it might safe an operation in an edge case, though, so why not…
Cheers
Stefan
=> make moveto/copyto no-ops when source and destination are the same (fixes #1261)

fs/config.go
This should fix the issue described in #1287, or at least fail before destroying the existing config. I chose to delete the temporary backup file so that it is at least not kept around if a user decides to encrypt the config. The old file should probably erased securely when encryption is on, though.
=> fully write new config file before moving to target location (fixes #1287)

cmd/cmount/fs.go, cmd/mount/fs.go, cmd/mountlib/dir.go, cmd/mountlib/fs.go
I got confused for a moment when testing the google-drive-poll-changes patch why the dir cache was not honored. This is a very simple patch which might not needed depending on how many further changes are planned. In any case, it's a bandaid for people who use HEAD.
=> hand dirCacheTime through again

docs/content/s3.md
As it happens, after testing the `GetObject` permission is also required to do `HEAD` requests on a given object.
=> Updated S3 sync permissions

cmd/cryptcheck/cryptcheck.go, docs/content/docs.md
Hey,
I'm new to rsync, so naturally, I consult with the docs a lot. That's how I noticed the typo:
> By default rclone **doesn’t not** keep track of renamed files, […]
Submitting whole new PR to fix just this one seemed like overkill, so I went through whole `docs.md` file (with the help of Grammarly) and this is what I found.
In short this PR:
* adds commas to introductory phrases ('However', 'First', 'For example')
* makes provider names consistently capitalized
* fix some more typos ('bandwith', 'integriTIty', etc.)
Feel free to point out things I got wrong, I'll be happy to update the PR.
=> Fix typos and punctuation in the 'docs.md'

b2/b2.go, docs/content/b2.md
This PR addresses #1547 with a new option `--b2-soft-delete` that is on by default (i.e. no regression from the present version).  Setting it to `--b2-soft-delete=false` permanently deletes remote files during `sync` instead of hiding them.
=> Support for hard deletion of files during b2 sync

docs/content/local.md, local/local.go
Give users a way to explicitly acknowledge that symlinks are to be skipped without warnings.
I want an option like this because I sync a drive with tons of symlinks to Google Drive and don't want to be flooded with "Can't follow symlink without -L/--copy-links" messages every single time, which may even bury actually useful/actionable messages.
=> local: add --skip-links to suppress symlink warnings

docs/content/drive.md
This information has been gathered from #1339 and confirmed by myself.
This fixes #1552
=> Added documentation information about Drive server side copies limits

oauthutil/oauthutil.go, oauthutil/oauthutil_new.go, oauthutil/oauthutil_old.go
1. This makes AuthOptions a parameter for doConfig, Config and ConfigOffline to enable a Fs to add additional options (required for OneDrive for Business)
2. Fix to properly shutdown the webserver recieving the auth information (go1.8)
=> oauthutil: Added AuthOptions and shuts down the web server properly

docs/content/overview.md, docs/content/sftp.md, sftp/sftp.go, sftp/sftp_internal_test.go
This change adds support for checksums/hashes when using SFTP remotes. While SFTP doesn't directly support hashing, appropriate programs can be called using SSH, at least if shell access is available.
Since the function that determines which hash functions are available on the remote system is called frequently, it caches its result.
It's my first time writing Go code, so if there's anything I can or will need to improve, I'd be glad to be told. Thanks!
=> Add support for checksums/hashes with SFTP

fs/accounting.go, fs/accounting_unix.go
See issue #1607. The fix in a nutshell:
1. Remove assignment side effect from `newTokenBucket`
2. Set either `prevTokenBucket` or `tokenBucket` on bwlimit schedule changes, depending on whether bwlimit is toggled on or off
=> Fix bwlimit toggle in conjunction with schedules (Fixes #1607)

docs/content/local.md
Change flag `--no-local-unicode-normalization` to `--local-no-unicode-normalization` since that's the way the flag is called in the source code.
Fixes #1633
=> Local: Make documentation consistent with code

drive/drive.go
Fix for issue #1619 
Patch result was overwriting file info on request failure inside of the pacer.
=> Fix panic on gdrive dedupe

docs/content/s3.md, s3/s3.go
Hi,
I'm using rclone to back up stuff into an S3 bucket and was playing around with [lifecycle policies](http://docs.aws.amazon.com/AmazonS3/latest/user-guide/create-lifecycle.html) in an attempt to reduce storage costs. It is easy to make old files automatically move to lower cost glacier storage (though I've yet to verify if the increased cost per operation makes it worth it in my case).
When syncing to S3 everything works fine, but when syncing/copying back objects would need to be manually restored before rclone can download them. This PR only adds documentation and an error message to that effect.
I could look into adding actual restore support but I'm not sure how it should work. Since it takes minutes to hours after restore for the files to be available, it cannot really be done as …
=> S3 glacier documentation + RFC

fs/sync.go
This fixes a bug that rclone does not display an error message when the destination could not be listed. For example, if we had invalid S3 credentials, then copy to S3 was flagged as a success.
=> copy: error out if dst could not be listed

docs/content/s3.md, s3/s3.go
This is useful when using federated tokens in AWS
=> s3: set session token when using STS

b2/b2.go, b2/upload.go, fs/operations.go
Together with #1684 this would be the last patch needed to make #1614 complete – and thus #1672 mergable.
About the patch:
* the patch adds some complexity, because b2 requires at least two chunks for large uploads and everything is configurable. I also wanted to avoid in RAM copies of chunks.
* being able to read exactly one 1 chunk is not enough, we need at least one byte more. It's certainly an edge case and it appears no one tried to upload exactly chunk-sized files yet. The old code `size >= int64(uploadCutoff)` was off by one, too!
* I found that trying to handle both cases of upload/streaming in one function puts if/else all over the place and makes for a tougher read. Splitting them has a lot of code duplication, which I combated by pulling stuff into two extra functions. They …
=> b2: implement streaming upload of files with unknown length (see #1614)

docs/content/docs.md, fs/config.go, fs/fs.go, fs/operations.go, fs/sync.go, fs/sync_test.go
Implement `--immutable` option to treat source and destination files as immutable and disallow modification. Fail if existing files have been modified. 
This can be useful as an additional layer of protection for immutable or append-only data sets.
Changes with `--immutable` enabled:
- Add check in `equal()` to disable silent update of destination timestamp when size and hash match
- Return an error from `pairChecker()` if destination exists and does not match
=> Implement --immutable option

cmd/all/all.go, cmd/cryptdecode/cryptdecode.go, crypt/crypt.go
This PR implents `cryptdecode` command which takes a crypt remote and a list of encrypted file names as parameters and returns the unencrypted file names.
`rclone cryptdecode encryptedremote: encryptedfilename1 encryptedfilename2`
output
```
iptcju57oi1l1c1mhcym4ctbho 	 file02.txt
pbeg45x31rucld7iv4736ol429 	 Failed to decrypt
``` 
In the above example, `pbeg45x31rucld7iv4736ol429` is an invalid encrypted file name.
=> crypt: added cryptdecode command - #1129

docs/content/docs.md
resoves -> resolves
Per-remote environment variables start with `RCLONE_CONFIG_`.
=> Small fixes to docs.md

cmd/dedupe/dedupe.go
Does this trigger the regeneration of the `.md` files that contain that same typo?
=> Fix dedupe description typo

fs/config.go, fs/config_read_password.go, fs/config_test.go
Warn the user if password contains trailing+leading whitespaces.
=>  allow trailing+leading whitespace for passwords - #1717

swift/swift.go
Avoids blindly trying to create the segments container, which can fail if the
authentication credentials don't allow container creates or updates.
Fixes #1769
=> Check if swift segments container exists before create

crypt/cipher.go, crypt/cipher_test.go, crypt/crypt.go, docs/content/crypt.md
This PR adds an extra option that allows users to choose whether they want to encrypt directory names or leave them intact.
Example:
`1/12/123.txt` is encrypted to `1/12/qgm4avr35m5loi1th53ato71v0` when directory names are not encrypted.
Addresses #1240
=> crypt: Added option to encrypt directory names or leave them intact - #1240

fs/sync.go, fs/sync_test.go, fstest/fstest.go
This fixes a bug where `rclone move` does not delete the source directory after completion.
=> move: delete source directory after successful move - fixes #1642

cmd/cmd.go, cmd/cryptcheck/cryptcheck.go, cmd/ls2/ls2.go, cmd/lsjson/lsjson.go, cmd/serve/http/http.go, docs/content/docs.md, fs/accounting.go, fs/march.go, fs/operations.go, fs/sync.go, fs/sync_test.go, fs/walk.go
This PR implements exit codes as specified in [this comment](https://github.com/ncw/rclone/issues/1136#issuecomment-280131615) by @ncw. [#1136]
I've tried to make the changes as concise as possible, only affecting `cmd/cmd.go`.
I have a few issues with [L300](https://github.com/ncw/rclone/commit/f45dcd2a9db897b34a5d4c30237a5d01014cad38#diff-f8528230b76c77a45f085693ebe846d5R300): there's no error to examine but we know an error was caught somewhere up the chain. I've tagged those errors with the `Error not otherwise categorised` exit code.
=> rclone: implement exit codes - #1136

cmd/mountlib/mount.go
This PR fixes `mount` breaking on Window (#1827).
=> mount: Fix mount breaking on Windows - fixes #1827

vfs/vfs.go
Notify the user in case poll-interval is used on a unsupported remote
=>  mountlib: log when poll-interval is ineffective

Gopkg.lock, Gopkg.toml, cmd/cmount/mount.go, cmd/mount/mount.go, cmd/mountlib/mount.go, vendor/github.com/okzk/sdnotify/LICENSE, vendor/github.com/okzk/sdnotify/README.md, vendor/github.com/okzk/sdnotify/notify.go, vendor/github.com/okzk/sdnotify/notify_linux.go, vendor/github.com/okzk/sdnotify/sample/main.go, vendor/github.com/okzk/sdnotify/sample/sample.service, vendor/github.com/okzk/sdnotify/util.go
This change implements the systemd notify interface on linux for the mount and cmount commands.
Before this it was not possible to use systemd service dependencies to wait for the FUSE mount to be active. Services depending on a rclone mount would only see an empty folder.
Now it is possible to use `Type=notify` and the service will be considered started after the fuse mount is ready.
=> fuse: implement the systemd notify interface

fs/accounting.go
This PR enhances stats by adding the amount of data transferred vs the file size (in kb/mb/gb) and the current file transfer speed.
The transfer stats before:
```
4ea6039cadcc6860.mp4: 64% done, 2.049 MBytes/s, ETA: 17s
```
The improved transfer stats:
```
4ea6039cadcc6860.mp4: 64.438M/99.533M 64% done, 1.988 MBytes/s / 2.088 MBytes/s, ETA: 14s
```
**64.438M/99.533M** amount of data transferred in kb/mb/gb
**1.988 MBytes/s** current file transfer speed
I did not include the buffer stats (as requested https://github.com/ncw/rclone/issues/1167#issuecomment-281671324)
Fixes #1167
=> stats: show the amount of data transferred in kb/mb - fixes #1167

docs/content/s3.md, s3/s3.go
ECS container IAM metadata is in a different place than EC2 IAM metadata.
Use defaults' RemoteCredProvider function to query the standard locations
for the credentials.
Give the ECS role precedence over the role available from the underlying
EC2 instance.
=> s3: add support for ECS task IAM roles

fs/sync.go, fs/sync_test.go, fstest/fstest.go
This fixes the bug where root source directories get deleted after move (caused by ace9a3492438)
In this PR, deletion after a successful move is limited to directories involved in the move. The root directory does get deleted.
=> move: fixed root source directories getting deleted after move - fixes #1849

cmd/move/move.go, cmd/moveto/moveto.go, docs/content/commands/rclone_move.md, fs/sync.go, fs/sync_test.go
This PR adds a `--delete-empty-src-dirs` flag to the move command. 
If this flag is set then all empty directories in the source are deleted after move.
fixes #1854
=> move: add --delete-empty-src-dirs flag - fixes #1854

docs/content/filtering.md, fs/filter.go
Rclone now warns user about using --include and --exclude filters together.
=> filter: warn the user if he use --include and --exclude together fixes #1764

cache/cache.go, crypt/crypt.go, fs/fs.go
Hi @ncw 
I've added a new interface in FS to link a wrapped FS to its wrapper FS. Basically the same as `Unwrap` but in the other direction.
I need this ability in `cache` to be able to make some improvements on the performance side. In most cases I expect people will wrap cache under crypt and I will need to decrypt file names in some scenarios to be able to adapt the workers on demand.
This shouldn't break anything as it's an optional interface for increasing visibility. My doubts are on
- creating a circular link between wrapped and wrapper FS. I would have loved to be able to do it in some other way but I just couldn't see any other way
- Naming: `Wrap` is already a function in `Features` so I had to use `WrapFs`. If you have some better ideas for the names, let me know and I'll …
=> fs: add Wrap feature for FS to identify their parent FS

docs/content/swift.md, swift/swift.go
In our environment, we have a different identity provider (via tokens) to access swift. For this reason, even providing the correct passwords, projects, tenants, ... I wasn't able to connect to my swift installation.
However, the swift library allows for an alternate authentication: https://godoc.org/github.com/ncw/swift#Connection.ApplyEnvironment
where only two variables are needed:
```
OS_STORAGE_URL - storage URL from alternate authentication
OS_AUTH_TOKEN - Auth Token from alternate authentication
```
however currently rclone is always checking the username, password, ... and always trying to authenticate.
In this PR, I check if the two variables above are set from the environment (when `env_auth` is `true`) and in this case skip the authentication and just let the underlying library …
=> Allow using alternate auth for swift

fs/accounting.go
This PR reduces the transfer stats output to fit 80x25 terminals.
=> stats: condensed transfer output to fit 80x25 terminals

docs/content/sftp.md, sftp/sftp.go
This PR adds the option to use the insecure `aes128-cbc` cipher. This is disabled by default in the Go `crypto/ssh` library due to security concerns.
Unfortunately, there are still a number of devices and implementations that still mandate the use of this cipher.
=> sftp: add option to enable the use of aes128-cbc cipher

cache/cache_internal_test.go, cache/storage_persistent.go
Testing on CI pipelines before merge multiple times now. Had issues with a recent push and would like to avoid putting bad tests until these tests are more stable
=> cache: enable internal tests and fix race condition for them

s3/s3.go
The `X-Amz-Copy-Source` header should be a path. `url.QueryEscape` escapes spaces with a plus sign (`+`) while `rest.URLEscape` (which mimics the `url.PathEscape` available from go 1.8) uses `%20`
See: https://play.golang.org/p/xWAAVXu8DKK
This works around an issue when copying objects with spaces in their key on DigitalOcean Spaces.
=> s3: Use rest.URLEscape rather than url.QueryEscape.

docs/content/sftp.md, sftp/sftp.go
This PR adds the `disable_hashcheck` option to the SFTP backend. This _may_ be required if you’re connecting to a remote SFTP server which is not under your control. The default hash checking code will open an SSH connection and attempt to execute commands to determine if remote hashes are available. This can cause alerts to be generated in the remote server log if the user account/server is configured for SFTP-only access.
Some particularly security-conscious remote system admins view any attempt to execute commands as a hostile activity, and so this provides the friendly and accommodating rclone user a way to disable this functionality.
=> sftp: Add option to disable remote hash check command execution

docs/content/sftp.md, sftp/sftp.go
This PR lets the SFTP backend support `--no-update-modtime`, for some restricted SFTP servers that prohibit this operation (i.e. certain configurations of ProFTPd with mod_sftp)
=> sftp: add 'set_modtime' config option for picky SFTP servers

fs/accounting.go, fs/config.go
Added a config option to specify the printed file name length for stats.
I didn't update the various documentation .md files because I figured you would want to change the flag text and or description wording.
=> Fixes #1206 Supporting Arbitrary Stats Filename Lengths

docs/content/docs.md
Missed adding documentation in original PR https://github.com/ncw/rclone/pull/1951
Fixes comment on #1206 
Also noticed there was a missing - in the documentation for  --stats-log-level.
=> docs: Add documentation for --stats-file-name-length

cmd/cryptdecode/cryptdecode.go, crypt/crypt.go
This pull request adds a `--reverse` flag to the `cryptdecode` command. When this flag is supplied the command returns encrypted file names.
=> cryptdecode: added option to return encrypted file names. Fixes #1923

docs/content/faq.md
Added section to FAQ about environment variables, which allow to control
location of SSL root certificate as well as DNS resolver used.
see also comment in #683
=> FAQ: env vars for SSL root certs and DNS resolver

docs/content/docs.md
Greetings!
New rclone user here, I was going through the documentation and spotted a few typos.
This is my attempt to fix them.
=> docs: fix various typos in docs.md

backend/amazonclouddrive/amazonclouddrive.go
It is unnecessary to notify the node.Parents, because a cahnge event is
generated for all involved files and folders in a move from d1/f1 to
d2/f1. There will be a event for d1, d2 and f1.
Additionally a duplicate notification is resolved when them empty string
is in pathsToClear.
Related to #2006
=> amazonclouddrive: remove unnecessary notifies from DirChangeNotify

Makefile, bin/decrypt_names.py, bin/make_manual.py, bin/upload-github, cmd/info/all.sh
Change absolute binary paths in scripts to /usr/bin/env or make them relative.
This allows the scripts to be used on linux distributions like NixOS, where binaries are not located in /usr/ or /bin/.
=> scripts: make absolute paths consistent

backend/drive/drive.go
Allow using Drive Documents as FS root by doing a direcoty list during NewFS.
Fixes #1772
=> drive: fix single Drive Document as FS root

backend/drive/drive.go, backend/drive/drive_internal_test.go, backend/drive/upload.go
This is my current state of updating the drive API to v3 (#320)
It should be complete except for Google Docs exports with the vfs package.
The workaround using a HEAD request to determine the size of a exported file in the `Size()` method does not work anymore, because exports are now transferred using chunked-encoding. A solution could be to download the whole file to get the size, but this very expensive and there is no guarantee the content does not change between exports.
Exports using basic operations like copy will succeed nonetheless.
All other tests are passing fine.
=> WIP: Update drive use v3 API

backend/drive/upload.go
This fixes broken chunked uploads for Google Drive introduced by #2007
=> drive: fix chunked upload

backend/drive/drive.go, backend/drive/upload.go
Here is the next fix after changing to API v3 :sweat_smile:
This fixes uploads to existing files for Google Drive introduced by #2007.
Instead of updating the old file a new "Untitled" file would be created in the root folder.
=> drive: fix upload to existing file

cmd/lsjson/lsjson.go
Explain the Path value in the docs for lsjson.
#2019
=> lsjson: explain the Path value in the docs

backend/drive/drive.go, backend/drive/drive_internal_test.go
If the listing has no google docs in or the user uses
`--drive-skip-gdocs` then we don't fetch the export formats which
saves a transaction to drive.
What do you think of this as per our discussion in #320 ?
=> drive: request the export formats only when required #320

backend/local/local.go, backend/local/local_internal_test.go
This PR adds an extra check in the local backend that compares the local file size and modtime to the stored object's size and modtime to ensure that local files are not being modified during upload.
=> copy/move: detect file size change during copy/move - fixes #1250

docs/content/crypt.md
As discussed in #2040 a fix for the documentation
=> [crypt] Changed max filename length documentation to 143

vfs/write.go, vfs/write_test.go
I am aware that more or less the same change is needed for the `read_write.go`, but I wanted to get some feedback on this before copying over the work.
I tried rsync, touch, cp, and `echo bla > bla` and they all still work. `touch bla && rm bla` stops being racy for me. Tested dropbox and drive remotes only so far.
I wonder if we need to change the logic to not use `writeCalled`, for cases where the syscalls would be roughly: open → flush → flush → write → flush/release. Previously this likely worked, because we would ignore the flush twice, but now we actually issue a write and thus the 2nd flush closes. I don't know of any program that works like that, though.
=> vfs: write 0 bytes when flushing unwritten handles to avoid race conditions in FUSE - fixes #1181

backend/onedrive/onedrive.go
Because of a bug in the Onedrive API it will sometime report the wrong size. If the size is wrong other remotes that depend on the size might fail. To fix this we overwrite the objects size with the real size from ContentLength header.
=> onedrive: Overwrite object size value with real size when reading file.

vfs/file.go, vfs/read_write.go, vfs/read_write_test.go, vfs/write.go
I think this is finally a working fix for #2034.
It introduces synchronization between multiple `RWFileHandle.openPending()` and between multiple `RWFileHandle.close()` of the same file.
`RWFileHandle.openPending()` will try to reuse an existing cache file if one exists.
In `read_write_test.go` I had to perform a full vfs cleanup after each test to ensure there are no existing cache files. This also stops old `cache.cleaner()`'s from interfering the tests, in case the tests use more time than usual (like during debugging).
Should the test changes go into a separate commit?
=> vfs: fix race between multiple RWFileHandle #2034

docs/content/install.sh
Forced a re-check of the version prior to printing, else it would print the version of the previously installed (or null if not installed prior to running the install script).
Just prints out version on completion of the install script.
=> Add version output at end of the install.sh script

backend/amazonclouddrive/amazonclouddrive_test.go, backend/azureblob/azureblob_test.go, backend/b2/b2_test.go, backend/box/box_test.go, backend/cache/cache_test.go, backend/crypt/crypt2_test.go, backend/crypt/crypt3_test.go, backend/crypt/crypt_test.go, backend/drive/drive_test.go, backend/dropbox/dropbox_test.go, backend/ftp/ftp_test.go, backend/googlecloudstorage/googlecloudstorage_test.go, backend/hubic/hubic_test.go, backend/local/local_test.go, backend/onedrive/onedrive_test.go, backend/pcloud/pcloud_test.go, backend/qingstor/qingstor_test.go, backend/s3/s3_test.go, backend/sftp/sftp_test.go, backend/swift/swift_test.go, backend/webdav/webdav_test.go, backend/yandex/yandex_test.go, fstest/fstests/fstests.go
This adds a `TestInternal` function to `fstests.go` which allows to perform a custom test on the backend `Fs` using the optional `InternalTester` interface.
The interface will allow to create tests which operate on the test remote after the regular fstests, but before cleanup.
My use case is to create tests for the document handling in Google Drive, which can operate on the test remote.
A example implementation of the interface would look like this in `backend/drive/drive_internal_test.go`:
```go
func InternalTestDocumentUpload(t *testing.T) {
// ...
}
func InternalTestDocumentUpdate(t *testing.T) {
// ...
}
func (*Fs) InternalTest(t *testing.T) {
// go1.7+
t.Run("InternalTestDocumentUpload", InternalTestDocumentUpload)
t.Run("InternalTestDocumentUpdate", InternalTestDocumentUpdate)
// …
```
=> fstests: add TestInternal

backend/crypt/cipher.go, backend/crypt/crypt.go, cmd/cryptdecode/cryptdecode.go
This adds a `NewCipher` function to the crypt backend, which contains the `Cipher` specific code from `NewFs`.
The `NewCipher` function will be used by `cryptdecode` to encode and decode names without constructing the wrapped remote.
This fixes #2075
=> cryptdecode: use Cipher instead of NewFs

cmd/serve/restic/stdio_conn.go
This commit removes an unneeded log message I accidentally left in the code, I mentioned it here: https://github.com/restic/restic/issues/1561#issuecomment-372829003
=> serve/restic: Remove log message on Close

backend/onedrive/api/types.go, backend/onedrive/onedrive.go, docs/content/onedrive.md
Fixes the double versions on OneDrive except when copying files but still does it on copy
=> onedrive: Removed upload cutoff and always do session uploads

backend/sftp/sftp.go, docs/content/sftp.md
Adds a flag `--sftp-ask-password` to the sftp backend, such that rclone prompts the user for a password if none was configured and other methods didn't work for authenticating.
Fixes #2137, although there should probably be a flag for the FTP backend as well.
=> sftp: Add --sftp-ask-password flag to prompt for password when needed - #2137

backend/onedrive/onedrive.go
Apparently the endpoint I used for upload is from Microsoft Graph but it's actually used in the official documentation for the OneDrive REST API. Switching back to the previously used one fixed the upload. (Seems to be only an issue for OneDrive Personal and not Business).
Also fixed the weird CreateDate.
```2018/03/16 10:37:20 DEBUG : test.txt: Starting multipart upload
2018/03/16 10:37:20 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/03/16 10:37:20 DEBUG : HTTP REQUEST (req 0xc0422be400)
2018/03/16 10:37:20 DEBUG : POST /v1.0/drive/root:/test.txt:/upload.createSession HTTP/1.1
Host: api.onedrive.com
User-Agent: rclone/v1.39-DEV
Content-Length: 116
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip …
```
=> Fixes wrong upload endpoint and createDate

cmd/cmd.go, cmd/version/version.go, cmd/version/version_test.go, fs/config/config.go, fs/config/config_test.go
Let's see if the tests pass also on CI. 
The patch delays loading the config file until the config is accessed for the first time. This allows `rclone help` and `rclone --version` to succeed (note: `rclone --help` always worked, even without the patch. It seems that cobra skips the initialization/`preRun` handlers in this case).
Ideally each command would decide on its own if it needs the config or not, but I could not find a way to do that without putting `LoadConfig()` into almost every subcommand.
=> load config file only on first access (closes #1659, closes #2096)

backend/cache/cache.go
this PR adds cache statistics to the rc commands. "rclone cachestats" will not work while the cache remote is mounted (DB is locked)
=> rc: add cache remote statistics

docs/content/about.md, docs/content/s3.md
We noticed a few things with the website and the links. The website format was a little messy. Formatted test so that hugo can process correctly. Also noticed mangled URL on the main page that links to IBM COS. Made these changes in this branch.
=> Minor format and URL changes to IBM COS Documentation content.

cmd/serve/restic/restic.go
This PR adds an optional append-only mode to the restic serve cmd, similar to the one implemented in restic's [rest-server](https://github.com/restic/rest-server/blob/master/cmd/rest-server/main.go#L39). Specifically, deletes to any resources that are not locks are disallowed.  For reference, here are the spots in the rest-server handlers where this is used:
https://github.com/restic/rest-server/blob/master/handlers.go#L233
https://github.com/restic/rest-server/blob/master/handlers.go#L527
=> cmd/serve/restic: add append-only mode

Makefile
The 1.40 tarball looks wrong:
```
$ wget https://github.com/ncw/rclone/releases/download/v1.40/rclone-v1.40.tar.gz
(...downloading...)
$ tar tf rclone-v1.40.tar.gz | head
rclone-v1.40.appveyor.yml
rclone-v1.40.circleci/
rclone-v1.40.circleci/config.yml
rclone-v1.40.gitignore
rclone-v1.40.pkgr.yml
rclone-v1.40.travis.yml
rclone-v1.40CONTRIBUTING.md
rclone-v1.40COPYING
rclone-v1.40Gopkg.lock
rclone-v1.40Gopkg.toml
```
=> Fix `make tarball`

cmd/serve/restic/restic.go, cmd/serve/restic/restic_appendonly_test.go
This commits add tests for the HTTP handler for `rclone serve restic` in append-only mode. It is tested that files cannot be overwritten or deleted. See #2186 for some background.
Closes #2195
=> serve/restic: Disallow overwriting files in append-only mode

cmd/serve/http/http.go, cmd/serve/httplib/httplib.go, cmd/serve/restic/restic.go, cmd/serve/webdav/webdav.go, fs/rc/rc.go
This allows the user to know the address of the listener if specifying a 0-port (i.e. letting the OS choose an available port). I've amended the documentation at the top of the file as well.
The main crux of this change is to split out the creation of the listener with the call to Serve(). This affected where the blocking happens, so I had to add a channel for waiting. But it all worked out. :+1: I've done this kind of thing a time or two before. :wink:
=> serve restic: Print actual listener address

cmd/size/size.go
This makes the output of `rclone size` machine-readable with the `--json` flag:
```
$ ./rclone size --json .
{"count":10583,"bytes":418665191}
```
Closes #2234.
=> size: Add --json flag

backend/s3/s3.go
This change adds the `s3-disable-checksum` option to disable uploading MD5 sums.
Tested with two 10 MB `rclone copy`s, one without `--s3-disable-checksum` and one with.  Without the option, the resulting file has a `x-amz-meta-md5chksum` metadata property; with the option, the resulting file has no such property.
=> s3: Add an option to disable checksum uploading - fixes #2213

backend/drive/drive.go, backend/googlecloudstorage/googlecloudstorage.go, docs/content/drive.md, docs/content/googlecloudstorage.md
Adds the ability to configure a service account without needing a file on disk: `service_account_credentials` (the contents of the service account credentials file) can be put directly into an environment variable. This works for Google Cloud Storage and Google Drive!
As discussed here: https://forum.rclone.org/t/accessing-google-cloud-storage-without-service-account-file/5461/5?u=matt
Includes a mention in the docs.
Thanks again for the pointers. Let me know if there's anything else!
=> Add service_account_credentials for Google Cloud and Drive

fs/sync/sync.go, fs/sync/sync_test.go
This PR simply creates empty src directories on the destination. Addresses #1837
=> copy: mkdir empty source directories to destination - fixes #1837

backend/sftp/sftp.go, docs/content/sftp.md
The flag allows calculation of checksums on systems using different paths for SSH and SFTP, like synology NAS boxes.
Tested on synology NAS – checksums are finally calculated. Added a mention in the documentation.
=> sftp: Add --ssh-path-override flag #1474

cmd/mountlib/mount.go, fs/chunkedreader/chunkedreader.go, fs/chunkedreader/chunkedreader_test.go, fstest/mockobject/mockobject.go, vfs/read.go, vfs/vfs.go, vfs/vfsflags/vfsflags.go
This is PR  adds the option `--vfs-read-chunk-size`to the vfs package.
The intention behind this is to reduce the used download quota for some combinations of remotes and workloads.
In my case it's a Google Drive remote containing large files which are only read in small parts. It seems like Drive is counting every requested byte to the daily quota even when the file is not fully downloaded. Using `Range` requests the number of requested bytes can be reduced at the cost of an increased number of requests.
For the tests to keep working i needed to implement the `fs.RangeOption` for the local remote (i can split that into a separate commit if desired)
=> vfs: add option to read source files in chunks

backend/drive/drive.go, vfs/vfs.go
This fixes 2 bugs in the `ChangeNotify` handling of drive and vfs wich were reported in #2251.
The `ChangeNotify` implementation in `drive` excluded all directories not found in the `dirCache`, which meant new directories would never trigger any notification. 
The `vfs` package assumed that only files can invalidate their parent, but directories should also do this if they are renamed or new. It is currently not possible to get the cause of a directory event, so the parent of a directory needs to be invalidated also.
Sadly this meas that when using the `amazonclouddrive` backend there are now unnecessary invalidation's, as the parent will get its own notification, leading to another parent cache invalidation.
=> Fix ChangeNotify for folders

cmd/cmd.go, cmd/mount/mount.go, lib/atexit/atexit.go
When running `rclone mount`, there where 2 signal handlers for `os.Interrupt`.
Those handlers would run concurrently and in some cases cause either unmount or `atexit.Run()` being skipped.
In addition `atexit.Run()` will get called in `resolveExitCode` to ensure cleanup on errors.
=> mount: ensure atexit and unmount get run on interrupt

backend/cache/plex.go
When using a PMS that requires HTTPS I get the following in the logs, where `https://fooflix.com` is the configured Plex URL and it is only available via that address.
```
ERROR : plex: websocket.Dial ws://fooflix.com/:/websockets/notifications?X-Plex-Token={redacted_token}: bad status
```
Inspecting Plex Web all the sockets connect via `wss://`. In the rclone code `https://` was being replaced with `ws://`, not the secure version.
=> cache: use secure websockets for HTTPS Plex addresses

cmd/check/check.go, cmd/cryptcheck/cryptcheck.go, fs/operations/operations.go, fs/operations/operations_test.go
--one-way argument will check that all files on source matches the files on detination,
but not the other way. For example files present on destination but not on source will not
trigger an error.
Fixes: #1526
=> check: Add one-way argument

fs/sync/sync.go, fs/sync/sync_test.go
This PR copies empty source directories to the destination. Reworked an earlier PR to ensure there's no replication when copying directories (i.e attempting to copy directories that already exist)
=>  copy: create (pseudo copy) empty source directories to destination - fixes #1837

backend/onedrive/onedrive.go, lib/oauthutil/oauthutil.go
More details on the single commits can be found in their messages.
This addresses #1975 
I thought of a way to handle errors returned by the authentication providers in a generic way.
This is what I came up with, every backend can provide its own handler and gets the failed oauth request with all parameters. This handler then returns a struct with some data about the error. This struct can be formatted for the web and cli interface.
What do you think of the concept? I think the code can be improved, but I just wanted to share the "Proof-of-Concept" before I add anything else to it.
=> errorHandler function for failed oauth requests

backend/s3/s3.go, docs/content/s3.md
If you are uploading small amount of large file over high speed link and these uploads do not fully utilize your bandwidth, then setting `--s3-upload-concurrency 8` may help to speed up the transfers.
=> Allow adjusting S3 upload concurrency with --s3-upload-concurrency

backend/onedrive/api/types.go, backend/onedrive/onedrive.go
Do not merge as this is WIP for  #1200 it's totally broken and will cause data corruption.
I'm only adding it here to see if anyone can help with it and get some pointers.
It seem the way remote shared drives are working is that when you fetch the main folder instead of getting a regular item you get an item with remoteItem property and all the proper item details are nested under this item.
Another caveat is that to query  the remote item you need to fetch it from its original drive.
So when fetching a remote folder children you need to access "drives/REMOTE_ID/items/REMOTE_ID/children" doing it as "drive/items/LOCAL_ID/children" will return a weird empty response
And You'll also need to access all the children under the remote drive
I'm not sure if there is a good way to do it using the …
=> onedrive shared folder support WIP 

fs/sizesuffix.go, vfs/vfs.go, vfs/vfsflags/vfsflags.go
`--vfs-read-chunk-size` has been in beta for some time now and seems to work well for many users.
There are a few posts in the forum discussing the general usage of this feature and settings users have tried.
Here are a the ones I think are the most interesting:
https://forum.rclone.org/t/new-feature-vfs-read-chunk-size/5683
https://forum.rclone.org/t/slow-media-start-times-with-mount-cache/5895
https://forum.rclone.org/t/my-vfs-sweetspot-updated-21-jul-2018/6132
This is the outline of these discussions:
- Any value for `vfs-read-chunk-size` will reduce the chance of hitting download limits, since the current default will always request the whole file.
- `vfs-read-chunk-size-limit` can be set to `off` to allow the chunk size to grow infinitely. This only affects consecutive reads and …
=> enable vfs-read-chunk-size by default

docs/content/b2.md
Instead of using 'make' the word 'create' is much easier to find, when you want to create a new bucket ;) Took me some minutes, so I am suggesting this tiny fix.
=> B2 Docs: use 'create' instead of 'make' for easier access

docs/content/docs.md
this change was omitted in the fix for #2008
=> docs: remove references to copy and move for --track-renames

backend/azureblob/azureblob.go, backend/b2/api/types.go, backend/box/box.go, backend/crypt/cipher_test.go, backend/crypt/crypt.go, backend/onedrive/onedrive.go, backend/onedrive/quickxorhash/quickxorhash_test.go, backend/yandex/api/performdelete.go, backend/yandex/api/performdownload.go, backend/yandex/api/performmkdir.go, backend/yandex/api/performupload.go, cmd/mount/dir.go, cmd/mountlib/mounttest/dir.go, cmd/mountlib/mounttest/file.go, fs/config/config.go, fs/config/configmap/configmap_test.go, fs/fs.go, fs/fserrors/error.go, fs/fshttp/http_test.go, fs/operations/operations.go, fstest/test_all/test_all.go, vfs/read_write.go, vfs/read_write_test.go, vfs/write_test.go
Fix some warning that were found by [go-critic](https://github.com/go-critic/go-critic) like redundant dereference, shadowed builtins, not using named consts, redundant parentheses. 
Log:
```
check-package: github.com/ncw/rclone/fstest/test_all/test_all.go:175:46: underef: could simplify (*timeout).String to timeout.String
check-package: github.com/ncw/rclone/backend/yandex/api/performdelete.go:32:73: unslice: could simplify body[:] to body
check-package: github.com/ncw/rclone/backend/yandex/api/performdownload.go:37:80: unslice: could simplify body[:] to body
check-package: github.com/ncw/rclone/backend/yandex/api/performmkdir.go:31:34: unslice: could simplify body[:] to body
check-package: github.com/ncw/rclone/backend/yandex/api/performmkdir.go:31:114: unslice: could simplify body[:] …
```
=> all: fix go-critic linter suggestions

backend/swift/swift.go, docs/content/swift.md
Add support for swift storage policies.
Tested against OVH and I can use this to create PCA containers.
This implements the container creation mentioned in #1603.
Is there a way to add specific automated tests for this? I didn't immediately find a good place it.
=> Swift: Add storage_policy

backend/cache/object.go, cmd/lsjson/lsjson.go
This adds the `--original` flag to the lsjson command, which enables the output of the ID from the underlying remote object.
This is useful when wrapped backends like `crypt` or `cache` are used and you want find real ID of a file.
It currently only works for `fs.Object`, not for `fs.Directory`.
=> lsjson: add option to display the original object id

vfs/dir.go, vfs/rc.go
The `vfs/refresh` command will walk the directory tree (using `walk.NewDirTree`) for the given paths and freshen the directory cache for the full tree.
It will use the fast-list capability of the remote when enabled.
When a mount is setup like this
```
rclone mount --checkers=6 --dir-cache-time 240h --rc --fast-list remote: /mnt/remote
```
you can now precache a large directory tree with 
```
rclone rc vfs/refresh dir=hugedir
```
before running a script that would read each directory in the tree one by one to speed up the process.
The `vfs/refresh` command will always walk the full directory tree, regardless of its directory cache state.
=> vfs: add the vfs/refresh rc command

cmd/all/all.go, cmd/reveal/reveal.go, fs/config/obscure/obscure_test.go
This PR adds the `reveal` command, which is the opposite of the existing `obscure` command.
It will take as an argument an obscured password (that is, a password as stored in rclone.config) and will return the actual password value. 
I'm taking for granted this command doesn't exist just because it was not implemented, and not because we don't want it to be easily available. In the end, my understanding is that obscurity is just an extra step for avoiding visual eavesdropping.
Lot of global flags are available for this command and are useless, but since obscure command also has them I didn't go further in removing them.
=> Add reveal command

README.md, backend/all/all.go, backend/jottacloud/api/types.go, backend/jottacloud/jottacloud.go, backend/jottacloud/jottacloud_test.go, backend/jottacloud/replace.go, backend/jottacloud/replace_test.go, bin/make_manual.py, cmd/cmd.go, docs/content/about.md, docs/content/docs.md, docs/content/jottacloud.md, docs/content/overview.md, docs/layouts/chrome/navbar.html, fs/options.go, fstest/test_all/test_all.go
This is my work adding support for Jottacloud as requested in #307. The basic Interfaces are implemented and working but there are still some things to do.
Some open stuff.
* Jottacloud does not publish any documentation on there API but they do seem to allow API usage. Therefore I mostly used the implementations in [havardgulldahl/jottalib](https://github.com/havardgulldahl/jottalib) and [albertony/jafs](https://github.com/albertony/jafs) as reference. 
* I'm only using the https://www.jottacloud.com/jfs/ API (this one is somewhat documented in there forum) even tough there seems to be newer API on https://api.jottacloud.com/files/v1 but so far only their own jotta-cli tool uses it and it's not documented anywhere. 
* In fact there seems to be a third api …
=> Add support for Jottacloud

fs/config/config.go
This PR adds an extra message when creating a new crypt remote and choosing to auto-generate a password for encyption. It warns the user that the "plaintext" version of the password won't be stored so that he remembers to keep it safe somewhere.
@ncw Feel free to comment about the sentence, I am open to any change to make it as clear as possible or if you think the sentence needs to be introduced at some other stage. I have kept line length to 120, not sure what is the convention.
=> Add disclaimer about generated passwords being stored in an obscured format

backend/jottacloud/api/types.go, backend/jottacloud/api/types_test.go
I encountered a time parsing bug while testing the new Jottacloud backend. If a
mount point in Jottacloud has never been written to, the `modification` XML
element will be an empty string.
Example from my initial testing. My `jotta` remote was configured to use the
`/Sync` mount point, which I had never used before.
```
$ rclone ls jotta:
2018/08/11 22:48:36 ERROR : : error listing: couldn't list files: parsing time "" as "2006-01-02-T15:04:05Z0700": cannot parse "" as "2006"
2018/08/11 22:48:36 Failed to ls: couldn't list files: parsing time "" as "2006-01-02-T15:04:05Z0700": cannot parse "" as "2006"
```
=> jottacloud: Handle empty time values

fs/accounting/accounting.go, fs/asyncreader/asyncreader.go, fs/asyncreader/asyncreader_test.go, vfs/read.go
Try to fulfill `Seek` calls on read only files by discarding bytes in the current buffer data.
Previously all `Seek` calls would discard the whole buffer and open a new connection every time.
Now they will consume the buffer until the right position is reached and only open a new connection if the position is outside the buffer data.
It is also possible to `Seek` backwards, but only inside the current buffer block.
=> vfs: "Seek" in the --buffer-size data

docs/content/docs.md, fs/config/configflags/configflags.go, vfs/help.go
Since there seems be some confusion how much memory `--buffer-size` uses, I suggest we change the command line help, to make it clearer it's per `--transfer`.
The full documentation already makes this clear, but the CLI help is probably the first place people will read and should express the same.
I also added a paragraph for `mount` and `cmount` to the documentation that they behave somewhat differently.
Should the CLI help also include this difference?
Is it possible change the help text for `mount` and `cmount` only?
=> docs: clearify buffer-size is per transfer/filehandle

backend/onedrive/onedrive.go
It seems I've forgotten to uncomment this check.
=> (minor) onedrive: Add back the check for DirMover interface

fs/config/config_list.go, fs/config/config_list_test.go
To help #2467 and possibly replace list parsing methods in other remotes, this adds two `[]string` value types for config values, `CommaSepList` and `SpaceSepList`.
They use the `encoding/csv` package for parsing, which allows to use quoted entries inside the list.
=> config: add List value types

cmd/ncdu/ncdu.go
I don't think this `log.Fatal(err)` in ncdu is intentional, but better ask than revert later.
This makes a termbox error much more recognizable.
#2538 could be an error returned by termbox, which is simply a syscall error message.
=> ncdu: return error instead of log.Fatal in Show

.appveyor.yml, .travis.yml, CONTRIBUTING.md
This PR makes a few changes to the config files for Travis CI and AppVeyor CI so that they work for forks of the repo.
P.S. Circle CI already works for forks and needs no change.
=> Make CIs available for forks

backend/jottacloud/jottacloud.go, docs/content/jottacloud.md
When deleting, the item will be moved to trash by default, as before, but now you can specify option `--jottacloud-use-trash=false` to permanently delete it instead.
PS: I used the same naming of the option as in Drive (`--drive-use-trash=false`), but it is kind of annoying to have such boolean arguments where the default is true so you must always set the `=false` value instead of just the `--option` , if you know what I mean. Mega has such a negated option `--mega-hard-delete`, but then that name wasn't 100% fit..
=> Implement optional permanent deletion in Jottacloud (not using trash)

cmd/cmd.go, fs/accounting/stats.go
This is a proposal to properly handle `FatalError` and `NoRetryError` when they are not directly returned by the command, but just reported to stats.
See https://github.com/ncw/rclone/pull/2488#issuecomment-416675577 for the addressed use-case.
=> stats: handle FatalError and NoRetryError when reported to stats

docs/layouts/_default/single.html, docs/layouts/chrome/menu.html, docs/layouts/chrome/navbar.html, docs/layouts/index.html, docs/layouts/indexes/category.html, docs/layouts/indexes/post.html, docs/layouts/indexes/tag.html, docs/layouts/page/single.html, docs/layouts/post/single.html, docs/layouts/section/commands.html, docs/static/css/custom.css
- Reduced size of the social menu and increased the size of the content
- Added scrollable property to the index menus
- Fixed code wrapping issue
Fixes #2103 
Some screenshots with the changes:
Signed-off-by: Anagh Kumar Baranwal <anaghk.dos@gmail.com>
=> docs: display changes

backend/jottacloud/api/types.go, backend/jottacloud/jottacloud.go, cmd/link/link.go, docs/content/jottacloud.md, docs/content/overview.md
Title basically says it all..
Did not see any functionality in rclone for removing the public link again? That would be simple to implement for Jottacloud (just set mode "disableShare" instead of "enableShare")..
=> Implemented PublicLink support for Jottacloud

backend/cache/cache.go, backend/crypt/crypt.go, docs/content/cache.md
This fixes reports that arose lately, where using a plain `remote` setting like `cloud:` in `cache` or `crypt` would brake some backends.
The way the `remote` value and the root path from the command line where joined together introduced a additional `/` in the wrapped remote path. A `remote` value `cloud:` and the root path `dir` became `cloud:/dir` instead of the desired `cloud:dir`.
This difference could break remotes like `sftp` and `googlecloudstorage`.
I also added a section to the `cache`docs, that `sftp:dir` and `sftp:/dir` will share the same cache folder, which can have unintended side effects.
Fixes #2553
Fixes https://forum.rclone.org/t/rclone-is-not-working-outside-of-the-root-of-crypt-remote/6697
=> crypt/cache: preserve leading / in the wrapped remote path 

backend/azureblob/azureblob.go, docs/content/azureblob.md
The 5000 limit comes from
https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs
Fixes #2390
=> azure: add --azureblob-list-chunk parameter

docs/content/cache.md
A discussed in #2215, this adds a section to the cache docs to explain the usage of `.plex.direct` URL's.
=> docs: add section for .plex.direct urls to cache

fs/accounting/accounting.go
Fix for the https://github.com/ncw/rclone/issues/2490 issue
I wasn't sure how I should split the visible characters ( quoting the issue description `This ticket is to change the UI to <...> like ThisisATestFile...EndOfFilesName.xxx`) so I implemented the version where a visible prefix is equal or  one character longer than a visible suffix.
=> change too long names cutting mechanism - fixes #2490

backend/azureblob/azureblob.go, backend/azureblob/azureblob_internal_test.go, backend/azureblob/azureblob_test.go, fs/fs.go, fstest/fstests/fstests.go
azureblob and fstests - Exclude archive tier from SetTier integration tests, added ExcludedSettings to fstests.Opt, a key-value map to hold various settings, where key is setting name and value is list of settings
=> azureblob and fstests - Exclude archive tier from SetTier integration tests

backend/drive/drive.go
Use the right variable when constructing document file stems in `list`.
Fixes #2591
=> drive: fix escaped chars in documents during list

backend/drive/drive.go, vendor/google.golang.org/api/drive/v2/drive-api.json, vendor/google.golang.org/api/drive/v2/drive-gen.go, vendor/modules.txt
Add `--drive-v2-download-min-size` flag to allow downloading files via the drive v2 API. If files are greater than this flag, a download link is generated when needed.
The flag is disabled by default.
Workaround for #2573
=> drive: add workaround for slow downloads

fs/list/list.go
Addresses discussion started in #878.
I thought it might be better to drop "from sync (and deletion)" altogether since listing is not just restricted to the sync command (`rclone -vv --exclude a tree remote:dir` would output the "Excluded from sync (and deletion)" line for example).
With files setup as:
```
dir/a
dir/b
remote/dir/a
remote/dir/b
```
The output from a `rclone -vv --exclude a --delete-excluded sync dir remote:dir` seems clear enough:
```
2018/09/20 23:17:33 DEBUG : a: Excluded
2018/09/20 23:17:33 INFO : Google drive root 'dir': Waiting for checks to finish
2018/09/20 23:17:33 DEBUG : b: Size and modification time the same (differ by -852.223µs, within tolerance 1ms)
2018/09/20 23:17:33 DEBUG : b: Unchanged skipping
2018/09/20 23:17:33 INFO : Google drive root 'dir': Waiting …
```
=> list: change debug logs for excluded items

backend/amazonclouddrive/amazonclouddrive.go, backend/cache/cache.go, backend/crypt/crypt.go, backend/drive/drive.go, fs/fs.go, fstest/fstests/fstests.go, vfs/rc.go, vfs/vfs.go
This rc command allows to query and edit the `--poll-interval` value.
The polling function will be restarted if the new interval is greater than 0.
```
rclone rc vfs/poll-interval interval=2m
```
To disable polling `interval=0` can be used.
```
rclone rc vfs/poll-interval interval=0
```
Without any parameter set, only the current status will be returned:
```json
{
"enabled": true,
"interval": {
"raw": 60000000000,
"seconds": 60,
"string": "1m0s"
},
"supported": true
}
```
A use case for this command could be to disable change polling temporarily while is script is renaming entries in a large folder over multiple minutes. During this time, the directory cache would be reset many times and cause the folder (and subfolders) to be read again.
**Edit:**
After I pushed this PR I realized a …
=> vfs: add vfs/poll-interval rc command

backend/webdav/odrvcookie/renew.go, backend/webdav/webdav.go
This change will start a go function when the sharepoint vendor is initialized.
The function renews the authentication cookies every 12 hrs. It should prevent sharepoint from blocking requests as 403 FORBIDDEN.
#2562
=> webdav/sharepoint: renew cookies after 12hrs

backend/drive/drive.go
When moving a directory in drive, most of the time only a notification for the directory itself is created, not the old or new parents.
This tires to find the old path for the changed directoy in the `dirCache` and the new path with the `dirCache` of the new parent, which can result in two notifications for a moved directory.
It is somewhat related to #2006, but affects directories instead of files.
=> drive: improve directory notifications in ChangeNotify

backend/onedrive/api/types.go, backend/onedrive/onedrive.go, docs/content/onedrive.md
OneNote files are a kind of files that look like files, but behave like folders. Operations like `Open` and `Update` fail on them. This PR hides them from directory listing, and prevent invalid operations on them, returning more user-friendly error messages. 
Since hiding these files from listing may also prevent them from being deleted, the flag `--onedrive-expose-onenote-files` is also added, which allows OneNote files to show up in directory listing. Illegal operations on them are still rejected even if this flag is set.
This should fix #211.
=> onedrive: ignore OneNote files by default - fixes #211

backend/onedrive/api/types.go, backend/onedrive/onedrive.go, docs/content/overview.md
Implement Onedrive link sharing `PublicLink` based on [Create sharing link](https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online) API
* Advantage:
1. Support file and folder.
2. Link will not be expired unless sharing permission is removed.
* Disadvantage:
1. Need to add `?download=1` after generated link to directly download file. Otherwise browser is needed for download button. See [Get direct download link of a file in OneDrive](https://techcommunity.microsoft.com/t5/OneDrive-for-Business/Get-direct-download-link-of-a-file-in-OneDrive-for-Business/td-p/149766)
However, There's another way to implement `PublicLink` which is based on [DriveItem->Download](https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/api/driveitem_get_ …
=> onedrive: add link sharing support. #2178

backend/alias/alias.go, backend/cache/cache.go, backend/crypt/crypt.go, fs/fspath/path.go, fs/fspath/path_test.go
This change unifies the way the wrapping remotes join the configured root path with the path provided to `NewFs` and allows to use `\\server\` paths on Windows. 7b975bc1ff7c4f4ff900db0a2b1e2e254cdbd57a fixed this for the `alias` remote, but `crypt` and `cache` could not handle them until now.
The new function `fspath.JoinRootPath` that is used to join the paths is equivalent to `path.Join`, but if the first non empty element starts with `//` this is preserved. Since all path are already `/` separated (by `fspath.Parse`) there is no need to use `filepath.Join`.
No
=> backend: unify NewFs path handling for wrapping remotes

backend/azureblob/azureblob.go, backend/azureblob/azureblob_test.go, backend/b2/b2.go, backend/b2/b2_test.go, backend/drive/drive.go, backend/drive/drive_test.go, backend/dropbox/dropbox.go, backend/dropbox/dropbox_test.go, backend/jottacloud/jottacloud_internal_test.go, backend/onedrive/onedrive.go, backend/onedrive/onedrive_test.go, backend/s3/s3.go, backend/s3/s3_test.go, backend/swift/swift.go, backend/swift/swift_test.go, fs/sizesuffix.go, fstest/fstests/bits.go, fstest/fstests/bits_go1_9.go, fstest/fstests/fstests.go, lib/readers/pattern_reader.go, lib/readers/pattern_reader_test.go
This adds a test for chunked uploads to the integration tests.
Each remote now has a `ChunkedUploadConfig` field in the `fstests.Opt` struct, to specify the required settings for the test. In addition, each remote that supports chunked uploads has to implement the `fstest.SetUploadChunkSizer` interface, which allows to change the value at runtime. Remotes that do not implement the `fstest.SetUploadChunkSizer` interface will not be tested, since the test would be the same as `TestFsPut` with bigger files.
These are the currently minimum chunk sizes and the total number of bytes uploaded to the remote during the test:
remote | min chunk size | test upload size
------ | -------------- | ----------------
b2 | 5M | 190M
s3 | 5M | 190M
drive | 256K | 13M
onedrive | 320K | 25M
\* | 1 | 28M
These …
=> fstests: add TestFsPutChunked

CONTRIBUTING.md, MAINTAINERS.md, MANUAL.md, docs/content/about.md
This the way GitHub refer to themselves.
I tried not to include changes to generated files, per contribution instructions.
This spells "GitHub" the same way that that company does; with uppercase "G" and "H".
No.
=> docs: replace "Github" with "GitHub"

backend/jottacloud/jottacloud.go
Failing integration tests described in #2650 should be fixed now. Seems the problem was with the empty folders in the test case. It was caused by some incorrect logic in my previous integration test fix (#2558) - which I struggled a bit with, so hopefully all tests works now.
=> jottacloud: fix bug in --fast-list related to empty folders (#2650)

backend/sftp/sftp.go
The Hash() function still attempts to run a remote SSH command to check the SHA/MD5 checksum of a file, even if the `disable_hashcheck` option is set in the configuration file. This change fixes that behaviour and makes `disable_hashcheck` work as expected again.
=> sftp: Ensure file hash checking is really disabled

backend/webdav/api/types.go
Compatibility with webdav.komfortcloud.de
Add RFC3339 date format as proposed.
https://github.com/ncw/rclone/issues/2712
A  local build with this patch resolved the issue.
=> WebDav: Add RFC3339 date format - fixes #2712

fs/operations/dedupe.go, fs/operations/dedupe_test.go
Fixes dedupe with rename strategy choosing names of files that already exist on the remote as described in #2512. Wasn't sure about adding tests since the existing test case doesn't seem to cover this scenario. 
With files in a remote folder as:
```
file
file
file-1
file-2
```
the first two should be renamed to file-3 and file-4
=> dedupe: check for existing filename before renaming a dupe file

Makefile, docs/content/cache.md
Fixes the docs generation to use the generic `$HOME` & `$USER` variables instead of specific values for reference.
Fixes #2687 
---
Some observations:
* Doesn't work properly when built on Mac.
* User is still set statically in some places where the internal go function is called first.
=> Fixed the docs generation to use `$HOME` instead of specific user directory

backend/s3/s3.go
Wasabi has two location, US East and US West, with different endpoint URLs.
When configuring S3 to use Wasabi, provide the endpoint information for both
locations.
=> s3: add config info for Wasabi's US-West endpoint

docs/content/install.sh
- [x ] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ x] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
=> - install using 'busybox' if available, when no other unzip tools present

backend/azureblob/azureblob.go, backend/azureblob/azureblob_internal_test.go, backend/azureblob/azureblob_test.go, backend/azureblob/azureblob_unsupported.go
FreeBSD support was added in Azure/azure-storage-blob-go@0562badec5489e409f1b18596e3f77a309420a84
OpenBSD and NetBSD support was added in Azure/azure-storage-blob-go@1d6dd77d7442fea5e32722ac0e05ee0e22059222
No
=> Allow building azureblob backend on *BSD

backend/b2/b2.go, docs/content/b2.md
The `cleanup` command will delete unfinished large file uploads that
were started more than a day ago (to avoid deleting uploads that are
potentially still in progress).
Fixes #2617
=> b2: cleanup unfinished large files

docs/content/install.sh
7z check doesn't work due to misplaced comma, so installation fails on Synology.
As discussed here: https://forum.rclone.org/t/rclone-install-broken-for-synology-again/7863/5
=> Fix install for Synology

backend/crypt/cipher.go, backend/crypt/cipher_test.go
The EME Transform() method will panic if the input data is larger than 2048 bytes.
Fixes #2826
=> crypt: check for maximum length before decrypting filename

backend/qingstor/upload.go
qingcloud backend emit traces message with typos on _very_ common operations (at each file creation...)
=> qingcloud: fix typos in trace messages

fstest/fstests/fstests.go
This PR makes it possible to specify a subfolder to run the tests in.
Before this, the command `go test -v -remote remote:some/path` causes the `FsName` test to fail because `remote.Name() == "remote:"` is not equal to `remoteName == "remote:some/path"`
=> fstests: fix TestFsName fails when using remote:with/path

docs/content/b2.md
This trivial patch adds a note about the minimum version of rclone
needed in order to be able to use multiple application keys with the b2
backend.
For reference: https://github.com/ncw/rclone/issues/2513
As Debian stable (amongst other distros) is shipping an older version,
users running rclone < 1.43 and reading about this feature in the online
docs may struggle to realise why they are not able to sync to b2 when
configured to use an application key other than the master one.
No. It is a trivial patch meant to clarify minimum version of rclone needed to use b2 multi application keys.
=> note on minimum version with support for b2 multi application keys

backend/onedrive/api/types.go, backend/onedrive/onedrive.go
This PR should fix the compatibility issues for "shared with me" folders in OneDrive Personal.
With these changes, in some infrequent cases when using OneDrive Personal, an extra query will be made when reading the metadata of a path. Also, moving between a shared folder and a normal (local) folder will fall back to copying+deleting because the `Update` API does not allow moving between drives. Otherwise rclone should behave the same as before.
Some extra work may be needed in order to automate the testing for "shared with me" folders in the CI platforms:
1. The tests should be run in a shared folder in addition to a normal one, for example with `go test -v -remote onedrive:shared_folder/deeper/path` (See also https://github.com/ncw/rclone/pull/2875)
1. It would be the best if operations …
=> onedrive: fix broken support for "shared with me" folders - fixes #2536, #2778

backend/sftp/sftp.go, docs/content/sftp.md
This PR improves the usage of SSH private keys in the sftp backend.
It adds shell expansion for environment variables and the leading `~` syntax. It also provides two new options to the backend. 
The `key_file_pass` option can be used to configure a password for the provided key file. Due to library limitations the current OpenSSH key file format, identified by a `-----BEGIN OPENSSH PRIVATE KEY-----` header, can't be decrypted with this option.
The `key_use_agent` flag can be used to force `ssh-agent` based authentication. When this option is set, the backend also respects the `key_file` option and only uses the specified key when authenticating with the `ssh-agent`.
#2843
=> sftp: improve private key handling

backend/jottacloud/api/types.go, backend/jottacloud/jottacloud.go
Since we have to calculate the MD5 before uploading a file I added support for talking to the new API from Jottacloud to pre-allocate a file and get some information back before uploading.
The allocate method returns http status code 201 when the file is already uploaded and we can skip uploading it altogether (de-duplictation). A copy is still created at the desired location.
Additionally it also returns a "resume" position for the file if the upload was interrupted before. That way rclone can resume uploads to Jottacloud now with this PR.
@ncw I am having some trouble with the oauth for the api server from Jottacloud. They require the string for the `grant_type` to be uppercase. In the code https://github.com/ncw/rclone/blob/7194c358ad7b0287cdc44081a98879349d819288/vendor/golang.org/x/oa …
=> Jottacloud resume / de-duplication support

cmd/rcd/rcd.go
I was reading the docs and found a typo.
I didn't look for this problem in issues or the forum.
=> fix typo in rcd docs

README.md, docs/content/about.md, docs/content/s3.md
Scaleway is offering a S3 compatible product. The goal of this PR is to inform rclone users that they can use Scaleway object storage with rclone.
=> Add Scaleway to rclone documentation

fs/fs.go, fs/operations/operations.go, fs/rc/config.go, fstest/fstests/fstests.go
This PR implements the changes disscussed in https://github.com/ncw/rclone/issues/2832#issuecomment-451862366. It:
- Makes clear in docs that `Put` and `Update` won't be called from outside a backend with a size < 0
- Makes `operations.Copy` call `operations.Rcat` if the input size is -1 which will buffer it on disk if necessary or use PutStream if available
- Ensures in the tests that `Fs.Put()` and `Object.Update()` don't panic when `src.Size() == -1`.
=> Refine handling of unknown-sized uploads - #2832

backend/drive/drive.go
This change fixes the issue discovered in [#2946](https://github.com/ncw/rclone/issues/2946#issuecomment-461435150).
It has the drawback, that folders with multiple parents will be scanned multiple times (once per parent) during `ListR`.
This also improves `ChangeNotify` for items with multiple parents.
#2946
=> drive: improve handling of items with multiple parents

.golangci.yml
Since the switch to `golangci` some lints enabled before are now skipped.
I especially noticed the following two:
```
Error return value of `dirEntries.Close` is not checked (errcheck)
```
and
```
exported method Fs.List should have comment or be unexported (golint)
```
`golangci` has in integrated list of lints skipped by default for all linters.
This behavior is documented in the [command line help](https://github.com/golangci/golangci-lint#command-line-options) under `--exclude-use-default`.
If the lints are intended to be skipped, feel free to close this, but I think they are useful to rclone, especially the `errcheck` ones.
No
=> golangci: enable lints excluded by default

backend/amazonclouddrive/amazonclouddrive.go, backend/azureblob/azureblob.go, backend/b2/b2.go, backend/box/box.go, backend/drive/drive.go, backend/dropbox/dropbox.go, backend/googlecloudstorage/googlecloudstorage.go, backend/jottacloud/jottacloud.go, backend/mega/mega.go, backend/onedrive/onedrive.go, backend/opendrive/opendrive.go, backend/pcloud/pcloud.go, backend/s3/s3.go, backend/swift/swift.go, backend/webdav/webdav.go, backend/yandex/yandex.go, fs/fs.go, fs/fs_test.go, lib/errors/errors.go, lib/errors/errors_test.go, lib/pacer/pacer.go, lib/pacer/pacer_test.go, lib/pacer/pacers.go
A while ago I tried to use the `lib/pacer` package for a personal project and found it hard to use without rclone config system. So I decided to improve reusability by removing the dependency on the `fs` package.
This change splits the sleep time calculation from the large `pacer.Pacer` struct into smaller parts and moves the rclone specific behavior like logging to the `fs` package. The new `Calculator` types also accept only their specific configuration options to make it clearer which pacer uses which settings.
All the default numbers and pacing algorithms should be the same as before. The existing tests only got modified to match the new API. I also added a `TestCallParallel` to check the parallel connection limit and modified the `TestGoogleDrivePacer` to test the new burst behavior. …
=> pacer: modularize the package 

docs/content/drive.md
Adding notes to inform users of a possible conflict/misbehavior when uploading to team drives
https://forum.rclone.org/t/fast-list-overwriting-and-endless-sync-with-gsuite-drive/8718/19
=> Adding notes for another situation that may cause Rclone to attempt to re-upload files it shouldnt when using google team drives.

cmd/help.go
Rclone's Bash completion script is currently unable to tab-complete remotes that have underscores in their names (e.g. `Dropbox_Alternate1:`). This change is intended to fix that issue.
No.
=> cmd: Fix tab-completion for remotes with underscores in their names

backend/sftp/sftp.go
In some custom scenarios developers might need a preconfigured ssh connection to be reused. This change enables that
No
=> allow custom ssh client config

backend/drive/drive.go
Adding informational message to drive when creating remotes to suggest creation of their own client-id rather than using rclone's default one.
https://forum.rclone.org/t/rclone-keeps-getting-error-reading-destination-directory-couldnt-list-directory-googleapi-error-403-rate-limit-exceeded-ratelimitexceeded/8885/8
- [ X] I'm done, this Pull Request is ready for review :-)
=> drive: Recommendation for creating own client ID

backend/googlecloudstorage/googlecloudstorage.go, docs/content/googlecloudstorage.md
This change allows rclone to fall back to application default credentials if all other methods fail. This is particularly useful when running on google compute, as machines run with the identity of a service account, and no json file of credentials is available. 
In practice, this means that when running in google compute, there is now no need to configure creds of any sort.
No.
=> Fall back to default application credentials in google cloud storage

backend/drive/drive.go, fs/fs.go, fs/operations/operations.go
Add a fs.Feature to display that the remote can copy between configs and add a check for this
https://github.com/ncw/rclone/issues/2728
=>  Add ServerSideAcrossConfig Flag and check for it

cmd/copy/copy.go, cmd/copyto/copyto.go, cmd/move/move.go, cmd/moveto/moveto.go, cmd/sync/sync.go, fs/sync/rc.go, fs/sync/sync.go, fs/sync/sync_test.go
This PR adds the `--create-empty-src-dirs` flag to the copy, sync and move commands.
This was discussed in #2869
=> copy/sync/move: add --create-empty-src-dirs flag fixes #2869

cmd/serve/dlna/dlna.go, cmd/serve/dlna/dlna_test.go
The SCPD URL was being set after marshalling the XML, and thus coming
out blank.  Now works on my Samsung TV, and likely fixes some issues
reported by others in #2648.
Simple bug fix.
#2648 has some reports of dlna not working; this solved the problem for me.
=> dlna: fix root XML service descriptor

cmd/help.go
Complete remotes with underscores and dashes. Get rid of the regular expression to make the completion much faster.
No.
---
The previous behavior of the remotes completion was that only
alphanumeric characters were allowed in a remote name. This limitation
has been lifted somewhat by #2985, which also allowed an underscore.
With the new implementation introduced in this commit, the completion of
the remote name has been simplified: If there is no colon (":") in the
current word, then complete remote name. Otherwise, complete the path
inside the specified remote. This allows correct completion of all
remote names that are allowed by the config (including - and _).
Actually it matches much more than that, even remote names that are not
allowed by the config, but in such a case there already …
=> cmd: fix completion of remotes

cmd/help.go
Fix autocompletion of remote paths with spaces like:
$ rclone lsd remote:/test/path\ with\ spaces
https://github.com/ncw/rclone/issues/3047
=> Fix autocompletion of remote paths with spaces

backend/s3/s3.go, docs/content/s3.md
Add new AWS S3 storage class `DEEP_ARCHIVE`.
Issue #3088
=> s3: add support for "Glacier Deep Archive" storage class - fixes #3088

cmd/lsf/lsf.go, cmd/lsjson/lsjson.go, fs/operations/lsjson.go
=> added files-only and dirs-only to lsjson

backend/sftp/sftp.go, backend/sftp/sftp_internal_test.go, docs/content/overview.md
Fixes #3107
This adds support for using about with SFTP remotes.
Currently, this does not check to ensure that it is possible to invoke `df`. Should this be added, and if so, when should the check occur?
The `-k` flag in `df -k` should ensure even non-GNU `df` returns with 1k-blocks.
I've tested this on my Ubuntu Linux server. It still needs to be tested on other platforms.
Also, for some reason, [my Travis build](https://travis-ci.com/gary-kim/rclone/builds/108866098) is passing but the one here is not?
Add support for the `about` command for SFTP remotes
#3107
=> SFTP: add about support

lib/rest/rest.go
In the Documentation it states:
// If (opts.MultipartParams or opts.MultipartContentName) and
// opts.Body are set then CallJSON will do a multipart upload with a
// file attached.
=> Fix Multipart upload check

cmd/serve/ftp/ftp.go, cmd/serve/ftp/ftpflags/ftpflags.go, cmd/serve/ftp/ftpopt/ftp_options.go
- [x ] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x ] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
=> Adds a public IP flag for ftp.  Closes #3158

fs/config/configflags/configflags.go
Fixing a typo in the --dump-headers command line flag description.
No
=> Fix typo: Dump HTTP bodies -> Dump HTTP headers

fs/fshttp/http.go, fs/operations/operations.go, fs/operations/operations_test.go
rclone will currently always fail when copying a file via `rclone copyurl <url> <remote>`. `--no-check-certificate` exists, but is only used for http fs as far as I can tell. This patch extends the usage to `copyurl` as well, so that `rclone copyurl --no-check-certificate <url> <remote>` will allow to copy from broken servers. 
Not that I am aware.
=> support --no-check-certificate on copyurl command

docs/content/install.sh
Skip man docs during install if linux mandb is not installed
https://github.com/ncw/rclone/issues/3175
=> install: linux skip man pages if no mandb - fixes #3175

docs/content/cache.md
Fixes a typo in the cache docs page that causes Hugo not to find the title and description.
No
=> Docs: Fix Cache Docs Typo

backend/jottacloud/jottacloud.go, docs/content/jottacloud.md
I finally found the time to implement support for selecting custom devices and mountpoints. This is done with an additional step during config. Old config files stay compatible and will automatically use the default Jotta/Archive which was the only option in the past. This should help everyone who has used the official client in the past. I'd ask everyone who has waited for this feature to test it because I only did some quick rough testing.
Should be mostly ready and working. I'll cleanup the code some more and update the docs this weekend.
=> jottacloud: Add support for selecting device and mounpoint fixes #3069

docs/content/docs.md, fs/config.go, fs/config/configflags/configflags.go, fs/march/march.go, fs/sync/sync_test.go
This change adds the ability to prevent the clone/sync of duplicate files for which only the casings differs, regardless if the source/target file-systems have case-sensitive filesystems (e.g. most/all linux systems)
e.g. files "Application A.doc" and "application a.doc" are now treated as the same file if the flag is set.
Issue link: https://github.com/ncw/rclone/issues/2773
Forum link: https://forum.rclone.org/t/copy-sync-how-to-ignore-casing-when-checking-for-duplicates/7715
- [X ] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [X ] All commit messages are in [house …
=> fs: add --ignore-case-sync for forced case insensitivity - fixes #2773

backend/onedrive/onedrive.go, fstest/fstests/fstests.go
This PR fixes #3164, and also adds a unit test to prevent similar failures in the future.
The changes have been discussed and explained in https://github.com/ncw/rclone/issues/3164.
=> Fix #3164 Onedrive skips files; add FsRootCollapse test

fs/direntries.go, fs/direntries_test.go, fs/march/march.go, fs/march/march_test.go
This change adds sorting by object type to DirEntries sorting. Additionally it distinguishes between objects and directories in matchListings function. By adding this directories with the same name as object name are  distinguished from objects, and can be synchronized. This allows to synchronize files between cloud storages that are key/value stores. For example when the source has the following structure (taken with rclone ls -R --files-only)
```
index
index/test
index/test2
```
previously it couldn't synchronize the `index` file because it had the same name as directory `index/`. After this change the `index` file and `index` directory are distinguished and are not reported as duplicates. This could be a problem when you are synchronizing the files from Key/Value storage to local …
=> Distinguish between objects and directories when synchronizing filesystems

docs/content/docs.md, fs/config/config.go
To run rclone in "portable" mode, as in "portable app", by putting rclone.exe together with rclone.conf in a folder on a memory stick. Rclone will pick up the local config file without having to always remember to specify the --config command line argument, and not having to resort to launcher script like described in [forum](https://forum.rclone.org/t/how-to-change-the-path-to-the-config-file-rclone-cong-permanently/10324/5).
The idea came from [this](https://forum.rclone.org/t/how-to-change-the-path-to-the-config-file-rclone-cong-permanently/10324/5) forum post, although it does not describe the solution itself.
=> Use rclone.conf from rclone executable directory if already existing

docs/content/rc.md, fs/config.go, fs/config/configflags/configflags.go, fs/rc/job.go, fs/rc/job_test.go
After Jobs finish execution they are checked  for expiry at regular intervals. These values are hard coded.
This change makes them configurable by exposing `JobExpireDuration` and `JobExpireInterval` configuration options and `job-expire-duration` and `job-expire-interval` command line flags.
Default values are preserved and are set to 60s and 10s respectively.
=> Make Job expiry timeouts configurable

backend/box/upload.go, fs/config/config.go
Enable creating new encrypted config, via external script invocation.
https://github.com/ncw/rclone/issues/3127
=> enable creating encrypted config through external script invocation

fs/operations/operations.go, fs/operations/operations_test.go
Fixes #3104
Fix a bug where moveto would delete a file when trying to change the case of a name on a remote that is case insensitive.
#3104
=> moveto: fix case-insensitive same remote move

fs/config/config.go, fs/config/config_test.go
Fixes #3268
Allowing a configfile to be re-read from disk when you expect there might have been changes that were written from an other please.
Yes in #3268
=> fs/config: Add method to reload configfile from disk

backend/sftp/sftp.go
Adjusted the logic in the SetModTime function to completely disable all checks associated with the update if sftp-set-modtime is disabled.
This handles really odd edge cases where an SFTP server will remove the file immediately upon upload (for example, as part of a batch processing workflow). If the file is removed, the SetModTime function still attempts to stat() the file, which does not at that point in time exist.
The code should be pretty obvious in what it's doing 😄
=> sftp: Completely ignore all modtime checks if SetModTime=false

cmd/sync/sync.go, docs/content/docs.md, fs/config/configflags/configflags.go, fs/operations/operations.go, fs/sync/sync.go, fs/sync/sync_test.go
1. Refactor the BackupDir checks so they apply to Move and Copy command not only Sync
2. allow --suffix by itself to add suffix and backup files in current directory
BackupDir change was discussed in #3219
suffix change was discussed in #2801
=> Backup dir

fs/operations/multithread.go, fs/operations/operations.go
Fixes #3307
`errgroup` wraps context with new one that is canceled once the first Go routine from the group returns. We should use separate context for operations related to this part.
I haven't tested this as I can't run integration tests.
=> context: fix errgroup interaction with context

fs/accounting/stats.go, fs/accounting/stats_test.go, fs/parseduration.go, fs/parseduration_test.go
The ETA can now display higher units: days, weeks, and years, in addition to the previous units
https://github.com/ncw/rclone/issues/3221
**Note**: I have looked for other details regarding the ETA String representation, and found nothing specific.
=> fs: Higher units for ETA - Issue #3221

fs/march/march.go, fs/operations/operations.go, fs/operations/operations_test.go, fs/sync/sync.go, fs/sync/sync_test.go
Partially fixes #3172
As described in linked issue errors in file system access are not returned when copying/moving. This change corrects that by catching any listing errors.
=> march: return errors when listing dirs

backend/s3/s3.go, docs/content/s3.md
Support for AWS S3 storage classes that currently aren't supported.
#3088 mentions Glacier Deep Archive. Intelligent-Tiering hasn't been discussed as far as I can tell, but it seems like a no-brainer to support all possible storage classes.
=> s3: Add support for Glacier Deep Archive and Intelligent-Tiering

docs/content/s3.md
This permission is required for `rclone lsd`.
PR that added the policy docs: https://github.com/ncw/rclone/issues/1455
=> Update docs on S3 policy to include ListAllMyBuckets permission

docs/content/docs.md
It's likely a mistake to use `--use-server-modtime` if you're not also using `--update`. It might even make sense to emit a warning in the code when doing this, but for now, I made it more clear in the docs.
I also clarified how `--use-server-modtime` can be useful in the `--update` section.
PR where `--use-server-modtime` was added: https://github.com/ncw/rclone/pull/2214
=> Clarify `--update` and `--use-server-mod-time` docs

backend/sftp/sftp.go, docs/content/sftp.md
rclone doesn't support 2 SSH key exchange algorithms `diffie-hellman-group-exchange-sha256` and `diffie-hellman-group-exchange-sha1` due to the upstream package `crypto` didn't support it.
The upstream lib `crypto` has recently added support for those algorithms in this [commit](https://github.com/golang/crypto/commit/57b3e21c3d5606066a87e63cfe07ec6b9f0db000)
However, since `diffie-hellman-group-exchange-sha256` and `diffie-hellman-group-exchange-sha1` are not recommended, see this [proposal](https://tools.ietf.org/id/draft-baushke-ssh-dh-group-sha2-05.xml). They need to be opt-in explicitly by the client, in this case, rclone.
This PR attemps to opt-in `diffie-hellman-group-exchange-sha256` and `diffie-hellman-group-exchange-sha1` when the flag `--sftp-use-insecure-cipher` is set to …
=> Attempt to fix #1810

backend/fichier/api.go, backend/fichier/fichier.go, backend/fichier/structs.go
API now provides folder_id and pass as number which go doens't want to unmarshal into string so make them int instead. Requires a little more converting between string and int because of dir cache but not a big deal.
=> fichier: make FolderID int and adjust related code - fixes #3359

backend/koofr/koofr.go, go.mod, go.sum, vendor/github.com/koofr/go-koofrclient/api_scheme.go, vendor/github.com/koofr/go-koofrclient/client_files.go, vendor/modules.txt
Support for setting modification times on Koofr backend.
No.
=> Koofr backend: support for setting modification times

fs/rc/rcflags/rcflags.go
Changes the GitHub releases URL for rclone-WebUI-react to the new one on the rclone organization.
=> Changing rclone-webui-react url with the new one on rclone organization

backend/local/fadvise_other.go, backend/local/fadvise_unix.go, backend/local/local.go
This patch makes rclone keep linux page cache usage under control when
uploading local files to remote backends. When opening a file it issues
FADV_SEQUENTIAL to configure read ahead strategy. While reading
the file it issues FADV_DONTNEED every 128kB to free page cache from
already consumed pages.
The read pattern is the following, the 32768 buffer size comes from io.Copy function.
```
fadvise64(5, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
read(5, "\324\375\251\376\213\361\240\224>\t5E\301\331X\274^\203oA\353\303.2'\206z\177N\27fB"..., 32768) = 32768
read(5, "\361\311\vW!\354_\317hf\276t\307\30L\351\272T\342C\243\370\240\213\355\210\v\221\201\177[\333"..., 32768) = 32768
read(5, ":\371\337Gn\355C\322\334 \253f\373\277\301;\215\n\240\347\305\6N\257\313\4\365\276ANq!"..., 32768) = 32768
read(5, …
```
=> backend/local: Avoid polluting page cache when uploading local files to remote backends

lib/oauthutil/oauthutil.go
This is `WIP` and based on feedback from people here I'll update the message and fulfill other requirements once things have been finalized.
The purpose is to give a helpful message to users in caseof different rclone versions on remote and local which makes the `config` file unusable.
Yes, this has been discussed on `issues` before and that's how I've been able to solve it.
=> [WIP] Adds info regarding rclone version on remote and local

backend/jottacloud/api/types.go, backend/jottacloud/jottacloud.go
Looks like jottacloud is slowly transitioning to their new API and disabled the usage of the email address as username for JFS API. Don't merge this immediately Jottacloud's config function is getting dangerously close to spaghetti code and I consider using this PR to clean that up a bit.
=> jottacloud: use new api for retrieving internal username - fixes #3434

fs/march/march.go, fs/march/march_test.go, fstest/fstest.go
Creating a test-case that would actually catch the no-traverse problem turned out to be a lot more work than I thought. In the end I decided to create to create 2 new test cases that actually invoke march in the same way syncCopyMove does. This requires a bit more helper code than I'm comfortable with but I don't really see a simpler way to catch these types of bugs. Also frustratingly the test framework didn't have a good way of comparing a DirEntries to a slice Items generated by working with the fake test remotes so I added one.  Closes #3336
=> Significantly rework testing for march and fix checking subdirs when using --no-traverse

backend/drive/drive.go
Purge should not be used with --drive-trashed-only flag as it leads to
unexpected behavior. After this commit if TrashedOnly option is set to
true, error message is returned.
See also: https://forum.rclone.org/t/drive-trashed-only-weird-occurrence/11066/14
=> drive: add error for purge with --drive-trashed-only #3407

cmd/mount/mount.go
The two `if` should check against `mountlib.ExtraOptions` and `mountlib.ExtraFlags` respectively, instead of checking `mountlib.ExtraOptions` twice.
=> mount: Fix typo in argument checking

fs/rc/jobs/job.go
The goal is to initialise `jobID` in `fs/rc/jobs/`. The intended use case is to always start with a new `jobID` to avoid conflicts upon restarts of rclone.  
No, I consider it low risk and the patch is really small.
=> Job id setting

cmd/rcd/rcd.go, cmd/serve/httplib/httpflags/httpflags.go, fs/rc/rcserver/rcserver.go
Auto-login makes use of login_token to directly enable rclone-webui-react to login the user without entering any credentials in the browser.
Prefix patch for rcd enables user to use --rc-prefix command with web-gui
=> Autologin for web-gui and prefix patch for rcd

fs/rc/jobs/job.go, fs/rc/jobs/job_test.go
Without this patch the resulting error is first converted to string and then recreated.
This makes it impossible to use the defined error types to figure out the cause of the error,
and may result in invalid HTTP status codes.
This patch adds a test TestExecuteJobErrorPropagation to validate that the errors are
properly propagated.
No
=> fs/rc/jobs: ExecuteJob propagate the error returned by function

cmd/rcd/rcd.go
Added nil for the object type while logging to fs.Infof
=> rcd: Added missing parameter for web-gui info logs.

fstest/test_all/config.go, fstest/test_all/config.yaml, fstest/test_all/run.go
this allows to run the testing framework with the `-short` option which disables the chunk tests, this is very useful when constantly running the tests with slow internet
no
=> allow usage of -short in the testing framework

docs/content/install.sh
Fix the problematic "template" argument for `mktemp` in `install.sh`.
Yes. This PR fixes #3479.
=> docs: fix template argument for mktemp in install.sh

cmd/copyurl/copyurl.go, docs/content/commands/rclone_copyurl.md, fs/operations/operations.go, fs/operations/operations_test.go, fs/operations/rc.go, fs/operations/rc_test.go
Add flag for `copyurl` command to allow users don't specify file name in destination path.
#3420
=> copyurl: add --auto-filename flag for using file name from url in destination path

cmd/help.go
As reported in #3489.
Fixes 'compopt: command not found' on autocomplete on macOS.
https://github.com/rclone/rclone/issues/3489#issuecomment-526231994
=> Fix 'compopt: command not found' on autocomplete on macOS

cmd/help.go
A workaround for #3489. Code in `__rclone_custom_func` relies on process substitutions `<(...)` to preserve changes of variables within `while` bodies, which is not supported in the posix mode.
It partially disables autocomplete if the posix mode is on to avoid confusing errors.
https://github.com/rclone/rclone/issues/3489
=> Disable __rclone_custom_func if posix mode is on

.appveyor.yml, azure-pipelines.yml, docs/content/commands/rclone_mount.md, vfs/dir.go, vfs/vfs.go, vfs/vfs_case_test.go, vfs/vfs_test.go, vfs/vfsflags/vfsflags.go
This change solves a particular problem with rclone mount.
I use rclone on windows to mount a cloud file archive and need an automated scriptable way to verify file consistency. Windows provides `fciv` for that, a functional equivalent of `sha1sum` / `md5sum` Linux utilties but with a different format of directory checksums. Linux utilities use hex-encoded one-file-per-line format and `fciv` uses base64 encoded xml based format. `fciv ` is used daily by many windows devops to verify large archives for consistency. I use automated powershell scripts to run it against the archive.
However, there is a gotcha: fciv brings file names to lower case for compatibility with previous windows versions. This is not a problem if I mount archive using such programs as WebDrive or NetDrive but breaks …
=> vfs: add flag --vfs-case-insensitive for windows mounts

vfs/vfs_case_test.go
TestCaseSensitivity fails at the preparation stage for a Box.com backend when it tries to create two files with names different by case only. This is not a bug of Box but a rather tough variant of a case-insensitive file system. This PR skips this test early (even before preparation stage) for Box and all officially (according to features) case-insensitive backends.
See https://github.com/rclone/rclone/pull/3504#issuecomment-528364299 and https://github.com/rclone/rclone/pull/3504#issuecomment-528556158
=> vfs: completely skip TestCaseSensitivity on Box.com

docs/content/bugs.md, docs/layouts/chrome/menu.html
Just addressing a pet peeve of mine: "GitHub" is spelled with a capital H.
My text editor also stripped trailing whitespace from all the files it modified. If this is a problem, I can separate that out into a separate commit, separate pull request, or modify my editor to not strip trailing whitespace.
=> GitHub has a capital H

lib/rest/rest.go
This PR fixes a dropped error in the `rest` package.
=> rest: fix dropped error

contrib/docker/docker-compose.dlna-server.yml, contrib/docker/docker-compose.webdav-server.yml
As discussed in #3460.
Docker Compose sample manifests.
See inline comments for details.
Usage should be fairly straightforward for Docker users, just doing `docker-compose -f file.yml up [-d]`.
=> Contrib: add Docker Compose sample manifests for DLNA and WebDAV servers

backend/mailru/mailru.go
When a file to upload is 40 bytes or more, it can be put directly in the hash field of Mailru metadata. Currently backend performs unneeded actions for small files: requests or calculates checksum and tries put by hash.
This patch optimizes that out. It also fixes a very rare nil point dereference panic.
It does not require new documentation or tests, just run the integration suite.
No
=> mailru: skip extra http request if data fits in hash

Dockerfile, docs/content/authors.md, docs/content/install.md
Specifically:
- enable Docker container userspace operation
- enable Docker userspace mount exposed to the host
- add more Docker image usage documentation
The changes affect only the Docker image. I haven't noticed any CI/CD pipeline checking the Docker image. (Perhaps that should be a task in itself.)
Yes: https://forum.rclone.org/t/run-docker-container-in-userspace/11734/7
=> Docker container fixes

cmd/serve/dlna/cds.go, cmd/serve/dlna/dlna_test.go
Further fixes for #3253.  The ContentDirectory spec actually says the childCount attribute is optional, so maybe we could just leave it out, but I can't test this one myself & it looks like other implementations (minidlna & emby) choose to fill in.
=> dlna: count the number of children in the response to BrowseMetadata

cmd/serve/dlna/dlna.go, cmd/serve/dlna/dlna_test.go, cmd/serve/dlna/dlna_util.go, cmd/serve/dlna/mrrs.go
Using the same responses as minidlna.
Fixes #3502.
=> dlna: Fake out implementation of X_MS_MediaReceiverRegistrar.

backend/s3/s3.go
When used with `v2_auth = true`, `PresignRequest` doesn't return
signed headers, so remote dest authentication would be fail.
This commit copying back `HTTPRequest.Header` to `headers`.
Tested with RiakCS v2.1.0.
Signed-off-by: Anthony Rusdi <33247310+antrusd@users.noreply.github.com>
=> s3: fix signature v2_auth headers

backend/chunker/chunker.go, backend/chunker/chunker_test.go, docs/content/chunker.md, fs/sync/sync_test.go, fstest/test_all/config.yaml
- remove GetTier and SetTier
- remove wdmrcompat metaformat
- remove fastopen strategy
- make hash_type option non-advanced
- adverise hash support when possible
- add metadata field "ver", run strict checks
- describe internal behavior in comments
- improve documentation
note:
wdmrcompat used to write file name in the metadata, so maximum metadata size was 1K
removing this format allows to cap size by 200 bytes now.
see https://github.com/rclone/rclone/pull/3503#issuecomment-534300870
=> finish chunker meta-format before release

cmd/serve/dlna/cds.go, cmd/serve/dlna/dlna_util.go
Allows for filename.srt, filename.en.srt, etc., to be automatically associated with video.mp4 when playing over dlna.
This is the "modern" method, which I've verified to work on VLC and in LG webOS 2.  There is a vendor specific mechanism for Samsung that I havn't been able to get working on my F series.
Serve metadata for external subtitles.
#3588
=> dlna: support for external srt subtitles

fs/operations/dedupe.go
When performing rclone dedupe, if it encounters an insufficientFilePermisson error and is not able to delete duplicates, it still shows message 'All duplicates removed'. This message should not be printed.
#3550 
- [*] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [*] I have added tests for all changes in this PR if appropriate.
- [*] I have added documentation for the changes if appropriate.
- [*] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [*] I'm done, this Pull Request is ready for review :-)
=> operations: display 'All duplicates removed' only if dedupe successful -fixes#3550

cmd/mountlib/mounttest/fs.go, cmd/mountlib/mounttest/write.go, cmd/mountlib/mounttest/write_non_unix.go, cmd/mountlib/mounttest/write_unix.go, vfs/read_write.go, vfs/read_write_test.go, vfs/vfs.go
vfs: move writeback of dirty data out of close() method into its own method (FlushWrites) and remove close() call from Flush()
If a file handle is duplicated with dup() and the duplicate handle is flushed, rclone will go ahead and close the file, making the original file handle stale. This change removes the close() call from Flush() and replaces it with FlushWrites() so that the file only gets closed when Release() is called. The new FlushWrites method takes care of actually writing the file back to the underlying storage.
Fixes #3381
https://github.com/rclone/rclone/issues/3381
https://forum.rclone.org/t/rclone-mount-vfs-cache-doesnt-appear-to-handle-dup-calls-gracefully/11030
=> Replace close() call in Flush() with writeback of dirty data to backing storage (Fix for #3381)

fs/operations/operations.go
`Couldn't find file - Need to Transfer` changed to `Need to transfer -
File Not Found at Destination` because while reading the debug logs, it
confuses with failure in operation.
When copying a file from `src` to `dst`, the Debug message `Couldn't find file - need to transfer`  gives a impression of a failure thought it's a message from a mechanism that checks for file in `dst`.
Changing it to `Need to transfer - File not found at Destination`, gives an impression that certain is to be executed because of the result `File not found`.
I want to do this because everytime I stumble across this message, it causes panic by reading `Couldn't find file`
No, it hasn't been.
=> Change the Debug message in NeedTranser

backend/ftp/ftp.go
Some misconfigured FTP servers advertise support for EPSV mode (the modern-day
equivalent of PASV), whereas in reality this doesn't always work (due to a
buggy firewall/gateway between the FTP server and the client, or a buggy server
implementation).
This option will tell the underlying FTP module to never use EPSV mode even if
the server claims to support it.
Not that I've seen, it's probably quite a rare occurrence.
=> ftp: allow disabling EPSV mode

fs/filter/filter.go, fs/filter/filter_test.go
I would like to address the issue #3599 where one should forbid mixing --files-from opt with other one
Here's the link to the discussion: https://forum.rclone.org/t/why-do-we-ignore-other-filtering-rules-when-using-the-files-from-flag/12065/5
- [ x ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ x ] I have added tests for all changes in this PR if appropriate.
- [ x ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ x ] I'm done, this Pull Request is ready for review :-)
=> filter: prevent mix opts when filesfrom is present - fixes #3599

backend/onedrive/onedrive.go, docs/content/onedrive.md, docs/content/webdav.md
This PR adds the workarounds for these long-standing, frequently-asked-about issues:
- [SharePoint: Replacing existing Office files returns itemNotFound: The resource could not be found. · Issue #3212](https://github.com/rclone/rclone/issues/3212)
- [onedrive (SharePoint): file integrity check fails because SharePoint modifies specific files · Issue #2599](https://github.com/rclone/rclone/issues/2599)
...and a hint on the unit of chunk size corresponding to #3512.
The Sharepoint section in `docs/content/webdav.md` is also updated for accuracy.
Lastly, this PR applies some minor format adjustments to the docs for clarity.
=> docs: update onedrive/sharepoint docs on some known issues

backend/sftp/sftp.go
Include more cyphers when using option `use_insecure_cipher`: `aes192-cbc`, `aes256-cbc`, and `3des-cbc`.
This option was introduced in #1810, and here I'm adding a couple more ciphers to the list, which are also still out there being used.
=> sftp: include more ciphers with use_insecure_cipher

cmd/cmount/fs.go, cmd/mount/handle.go, cmd/mountlib/mounttest/file.go, cmd/mountlib/mounttest/fs.go, cmd/mountlib/mounttest/write.go, vfs/file.go
os.File.WriteAt returns an error if a file was opened with O_APPEND. Replacing it with os.File.Seek and os.File.Write for cache modes >= writes will ensure that writes will always work if a file is opened with O_APPEND.
Writing to a file opened with O_APPEND on a mounted remote (with caching >= writes) returns an error because os.File.WriteAt does not allow writing to files opened with O_APPEND.
No
=> mount: replace use of WriteAt with Write for files opened with O_APPEND

backend/onedrive/onedrive.go
This should fix #3664.
Onedrive API is not happy with the trailing slash when reading metadata given item ID. So let's remove it.
#3664
=> onedrive: no trailing slash reading metadata

fs/accounting/accounting.go, fs/accounting/stats.go, fs/accounting/stats_groups.go, fs/accounting/transfer.go
The group parameter gives a id to uniquely identify a job and allow operations to be performed on it.
This will allow the job to be stopped using the rclone web ui.
=> Adding group parameter in status return

cmd/authorize/authorize.go, docs/content/commands/rclone_authorize.md, fs/config/config.go, lib/oauthutil/oauthutil.go
On google fs (drive, google photos, and google cloud storage), if
headless is selected, do not open browser.
This also supplies a new option "auth-no-open-browser" for authorize
if the user does not want it.
This should fix #3323.
No browser popup if headless and using drive
#3323
=> config: do not open browser on headless on google

backend/s3/s3.go
`ExpiryWindow` accepts time.Duration but it was set to value 3.
This changes it to 3 * time.Minute since default is 5 min.
I haven't seen some drastic bug from this but the value seems odd enough to change it.
=> backend/s3: fix ExpiryWindow value

fs/config/config.go
While working on the jotta fix i noticed these erros:
```
2019/11/08 22:39:58 ERROR : Failed saving config "client_id" = "o7cd6o7fa1v34jha6ir9tq67ev" in section "jtest" of the config file: section 'jtest' not found
2019/11/08 22:39:58 ERROR : Failed saving config "client_secret" = "MOukZqTJb-Y_N_VTc7QoUQsgkgOmyaBbdDyUi3YFy4tmHd5FqoM84Fv_" in section "jtest" of the config file: section 'jtest' not found
```
This is caused by the config reload in SetValueAndSafe. While I'm not entirely sure while there is even a need to reload the config in SetValueAndSafe I'm pretty sure this error should be ignored and the comment suggests so too.
=> config: SetValueAndSave ignore error if config section does not exist

docs/content/s3.md
Hello, documentation for Scaleway was already there, but the TOC was missing it.
=> docs: add Scaleway to the S3 table of contents

docs/content/rc.md, fs/accounting/stats.go, fs/accounting/stats_groups.go, fs/accounting/stats_test.go
Two changes in single PR since they depend on each other.
1.
rclone library users might be intrested in changing default value to other, or even disabling it. With current version it's impossible which leads to races when number of uploaded objects exceeds default limit.
Fixes #3732
2.
In order to reduce memory usage `stats-reset` also clears finished transfers.
Fixes #3734 
No
=> accounting: allow MaxCompletedTransfers to be configurable

docs/content/install.md
Explain how to workaround the problems due to macOS Gatekeeper requiring an executable to be notarized.
With reference to @ncw requests in #3689:
> I think what we should do now put a note into the install doc to the effect that macOS Catalina can't run rclone binaries by default and specify the xattr workaround provided it works OK.
Done. I also mentioned the `xattr` workaround, although I am not even sure it makes sense to mention, since it is needed only when downloading the package with a web browser. Please have a look at the details in the PR.
> Maybe another section on brew install rclone. I don't know who packages rclone for brew so I'm a bit nervous recommending it there, but it seems bang up to date.
I added a new section, and actually put it as the first macOS section given the …
=> docs/install: explain how to workaround macOS Gatekeeper requiring notarization

backend/jottacloud/api/types.go, backend/jottacloud/jottacloud.go, docs/content/jottacloud.md
This kinda needs some user testing. It doesn't break any of my stuff but you can never be sure with Jottacloud. Authentication now works by using a one time token you can generate in the Security Tab of the Jottacloud webui  ([Link](https://www.jottacloud.com/web/secure)). Will update docs once I confirm this doesn't break anything.
Fixes #3645
=> jottacloud: use new auth method used by official client

docs/content/commands/rclone_mount.md
Provided instructions for mounting remotes as network shares/network drives in a Windows environment
This PR adds the proper documentation to explain Windows users how to mount rclone remotes as network shares, as discussed [in the forums](https://forum.rclone.org/t/mount-as-network-drive-in-windows/7341)
=> Add instructions in how to mount remotes as network shares in Windows

cmd/help.go
Closes #3767.
It adds `--ask-password=false` to each invocation of `rclone` from a complete function to suppress password prompt in case the config is encrypted. It also redirects stderr to suppress an error message like `rclone sync --dry-run 2019/11/28 20:35:17 Failed to load config file "/home/user/.config/rclone/rclone.conf": unable to decrypt configuration and not allowed to ask for password - set RCLONE_CONFIG_PASS to your configuration password`.
https://github.com/rclone/rclone/issues/3767
=> Fix completion with an encrypted config

backend/s3/s3.go
Rclone will calculate checksums on read for all objects in local
backend. This is a problem in performance critical environments or for
large files.
We are introducing `disable_checksum option for the local backend to
disable hashing for file reads.
- [] I have added documentation for the changes if appropriate.
=> backend/local: add disable_checksum option

backend/chunker/chunker.go, backend/chunker/chunker_internal_test.go, docs/content/chunker.md
This patch reduces string length of temporary transaction identifiers from 10 to 6 characters while keeping them sufficiently random. This helps to reduce file name overhead from 34 to 24 characters (with default settings).
Discussed in the issue https://github.com/rclone/rclone/issues/3705 and in https://forum.rclone.org/t/filename-too-long/12753/34
=> chunker: reduce length of temporary suffix

docs/static/css/custom.css
Fix the problem where clicking on in-page anchor results in heading hidden behind the fixed navigation bar.
**Before**
**After**
No
- _N/A_ I have added tests for all changes in this PR if appropriate.
- _N/A_ I have added documentation for the changes if appropriate.
=> docs: fix in-page anchor navigation positioning

backend/s3/s3.go, docs/content/s3.md
This change adds the new region "Asia Patific (Hong Kong)", or `ap-east-1`, to s3 options as well as docs.
Extra tests are not needed IMO.
No.
=> s3: Add new region Asia Patific (Hong Kong)

fs/accounting/stats.go, fs/accounting/stats_groups.go, fs/accounting/stats_groups_test.go, fs/accounting/stats_test.go
This change is adding an option to delete stats on demand to avoid piling them up. Reset is not enough when you want to avoid hitting the max configured value.
Also did some cleanup to the touched files and added test.
=> fs/accounting: add a call to delete status groups

.github/workflows/build.yml, CONTRIBUTING.md
Before the fixes in this PR, GitHub Actions builds will fail in forks of rclone because of:
- Import path problems ([Example](https://github.com/Cnly/rclone/runs/372322900#step:9:1)), and
- impossible attempts to upload built binaries ([Example](https://github.com/Cnly/rclone/runs/372323002#step:6:1))
This PR fixes the problems by specifying a fixed path when cloning the source code and ensuring the build is not in a fork before trying to upload artifacts. A better solution for the import path problem may be to set `GO111MODULE=on`, but we still have go 1.10 in our build matrix, which doesn't support Go modules, hence the current solution.
GitHub Actions builds after these fixes can be seen in [my fork](https://github.com/Cnly/rclone/commit/10a04d11f1115154ef9d4e4e92c1128086cc2cb6/checks?c …
=> build: fix import path and upload failures for forks

fs/operations/operations.go
Statistics of ransfers which were interrupted are not cleared before
retry iteration. These transfers completed with over 100 percentage.
This change clears transfer accounting before next retry iteration is
done in order to keep numbers in track.
Fixes #3861
No
=> fs/operations: Clear accounting before low level retry

fs/operations/operations.go
Adds a simple debug message that helps to track down cases where the hashes could not be checked.
=> operations: write debug message when hashes could not be checked

go.mod, go.sum, vendor/github.com/mattn/go-runewidth/runewidth.go, vendor/github.com/nsf/termbox-go/api.go, vendor/modules.txt
see https://github.com/nsf/termbox-go/commit/58d4fcbce2a7e6a3a48afbc6b7ec2a916ac33ee0
"rclone ncdu" doesn't work on FreeBSD and the bug is inside termbox-go. Updating go.mod can fix it.
=> vendor: update termbox-go to fix ncdu command on FreeBSD

backend/crypt/crypt.go
Most of the defaults are the first option yet not this one. I find it confusing and propose that the default be brought to the top.
Create clarity as the user goes through the encryption selection options.
unable to locate
- [ ✓] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [✓] I have added tests for all changes in this PR if appropriate.
- [✓] I have added documentation for the changes if appropriate.
- [✓] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [✓] I'm done, this Pull Request is ready for review :-)
=> Reordered the filename encryption options

cmd/serve/ftp/ftp.go, cmd/serve/proxy/proxy.go, cmd/serve/proxy/proxy_test.go, cmd/serve/sftp/server.go, cmd/serve/sftp/sftp_test.go, cmd/serve/webdav/webdav.go, docs/content/commands/rclone_serve_sftp.md
Add support for #3572 (public key auth with auth proxy)
#3572
This is a slight modification of the discussion on the ticket, I made it match the behavior of user/pass when the proxy is involved. Instead of spitting back public keys that are acceptable, the proxy returns a backend config and a zero if the public key is acceptable. I did it this way for two reasons #1 consistency of behavior and #2 I want to be able to log specifics of an auth request and while I definitely don't send user passwords on to logging, I see real value in having the successful or failed public key to help a user debug a connectivity issue.
Let me know if you have any concerns or if I've goofed this up somehow, Thanks!
=> serve sftp: Add support for public key with auth proxy - fixes #3572

docs/content/about.md
SFTP Wikipedia link was pointing to the general page for the meaning of "sftp".
I changed it to the specific page for sftp.
No, I scrolled trought the list of services on rclone.org and noticed it.
=> Use correct link for sftp wikipedia article

backend/onedrive/onedrive.go
Add Sites.Read.All permission to onedrives Azure AD auth scope.
This allows to search for MS teams site in rclone config.
Fixes #1770 
#1770
=> add Sites.Read.All permission for onedrive

cmd/hashsum/hashsum.go, fs/operations/operations.go, fs/operations/operations_test.go
#3663 
this flag used to output QuickXorHash in the same format with MS Graph
Api
=> Add flag --base64 to command hashsum

backend/crypt/crypt.go
Currently running something like `rclone copy test/. crypt:test/.` causes the crypt remote to interpret the trailing `.` as a directory as directory name. This is incorrect and causes all kinds of problems. Add a simple check to remove trailing dots from paths on the crypt remote.
=> crypt: correctly handle trailing dot

docs/content/install.sh
This allows people with their config already made to copy their config to the new server(s), without having to create the directories.
It's irritating to get the error 50th time or so that the directory doesn't exist.
No.
=> install.sh: create ~/.config/rclone directory

docs/content/docs.md, fs/config.go, fs/config/config.go, fs/config/config_test.go, fs/config/configflags/configflags.go
=> allow specification of config password dynamically - fixes #3694

backend/webdav/webdav.go, docs/content/docs.md, fs/config.go, fs/config/configflags/configflags.go, fs/sync/sync.go, fs/sync/sync_test.go
It allows users to specify the maximum duration of a transfer session sort of as requested in #985, making it easier to script rclone to e.g. backup during the night. The setting I've added introduces a duration flag. After rclone has been running for that amount of time, no new transfers will be initiated, but those already started will be able allowed to complete. It may be useful to implement a further flag for a hard limit that will terminate in-progress transfers once the session limit is reached, but in another PR.
Note - Since `--max-transfer` doesn't appear to have tests, neither does this feature. I have tested the non-server copy manually though - I've never used server mode so would need some pointers to test that.
Sort of in #985
=> Add a max session time limit

docs/content/docs.md
Fix spacing error under `-P --progress` in `docs.md`
No
=> docs: fix spacing error under `-P` in `docs.md`

README.md
Just noticed that the CI shields in the README are no longer used.
No.
=> Update README.md shields for changed CI

fs/rc/webgui.go
This picks up a dropped error variable in `fs/rc`.
=> fs/rc: fix dropped error

cmd/serve/ftp/ftp.go
`os.SEEK_SET` is deprecated, and replaced with `io.SeekStart`.
=> cmd/serve/ftp: replace deprecated os.SEEK_SET with io.SeekStart

lib/oauthutil/oauthutil.go
`oauth2.NoContext` is deprecated, this replaces it with `context.Background()`.
While we're in here, would it make sense to put a timeout on this context?
=> lib/oauthutil: replace deprecated oauth2.NoContext

fs/operations/operations.go, fs/sync/sync.go
The purpose of this change is to improve the log output for when no changes are made. This is accomplished by the following changes:
- changing a few log messages to debug level
- adding an info log message for when 0 bytes were transferred
Here is an example output:
```shell
~/go/src/rclone $ ./rclone -vv sync ~/src_folder/ ~/dst_folder/
2020/02/09 13:38:02 DEBUG : rclone: Version "v1.51.0-DEV" starting with parameters ["./rclone" "-vv" "sync" "/Users/tim/src_f
older/" "/Users/tim/dst_folder/"]                                                                                           
2020/02/09 13:38:02 NOTICE: Config file "/Users/tim/.config/rclone/rclone.conf" not found - using defaults
2020/02/09 13:38:02 DEBUG : Local file system at /Users/tim/dst_folder/: Waiting for checks to …
```
=> fs: improve log output when no changes are made - fixes #3454

backend/premiumizeme/premiumizeme.go
This removes the unused functions `Object.metaHash()`, `Object.srvPath()`, and `Fs.rootSlash()` from the `backend/premiumizeme` package.
=> backend/premiumizeme: prune unused functions

docs/content/onedrive.md
It seems that `Any Azure AD directory - Multitenant` does not exist any more. At the time of writing there are 3 options:
1. Accounts in this organizational directory only (Default Directory only - Single tenant)
0. Accounts in any organizational directory (Any Azure AD directory - Multitenant)
0. Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)
I tried the second one and got `You can't sign in here with a personal account. Use your work or school account instead.` during setup (not sure whether it would work for OneDrive Buinsess though). The third one worked without any issue.
No.
=> docs: update account type during OneDrive app registration

vfs/cache_test.go, vfs/dir_test.go, vfs/file_test.go, vfs/vfs_test.go
Linted with `staticcheck`.
This explicitly assigns unused variables to `_` in the `vfs` package.
=> vfs: Unused Variables

backend/cache/cache_internal_test.go, backend/cache/directory.go, backend/cache/storage_persistent.go
Linted with `staticcheck`.
This removes the unused functions `run.writeRemoteRandomBytes()` `run.writeObjectRandomBytes()` `run.listPath()` `Directory.parentRemote()` and `Persistent.dumpRoot()`.
=> backend/cache: Remove Unused Functions

backend/s3/s3.go
When a part upload request fails error is returned and gCtx is cancelled.
This does not prevent from other parts being tried.
They immediately fail due to a canceled context, but are retried by rclone anyway...
Example AWS debug output
```
-----------------------------------------------------
2020/02/11 14:12:17 DEBUG: Retrying Request s3/UploadPart, attempt 4
2020/02/11 14:12:17 DEBUG: Request s3/UploadPart Details:
---[ REQUEST POST-SIGN ]-----------------------------
PUT /backuptest-rclone/huge/file.db?partNumber=11&uploadId=190939b4-3c43-4b98-ac11-92303e3f11b0 HTTP/1.1
Host: 192.168.100.99:9000
User-Agent: aws-sdk-go/1.23.8 (go1.13.1; linux; amd64)
Content-Length: 5242880
Authorization: AWS4-HMAC-SHA256 Credential=miniouser/20200211/us-east-1/s3/aws4_request, …
```
=> backend/s3: Fail fast multipart upload

backend/s3/s3.go
The error code 500 Internal Error indicates that Amazon S3 is unable to handle the request at that time. The error code 503 Slow Down typically indicates that the requests to the S3 bucket are very high, exceeding the request rates described in Request Rate and Performance Guidelines.
Because Amazon S3 is a distributed service, a very small percentage of 5xx errors are expected during normal use of the service. All requests that return 5xx errors from Amazon S3 can and should be retried, so we recommend that applications making requests to Amazon S3 have a fault-tolerance mechanism to recover from these errors.
https://aws.amazon.com/premiumsupport/knowledge-center/http-5xx-errors-s3/
Register 500 as retryErrorCode in s3 backend.
=> backend/s3: Added 500 as retryErrorCode

fs/accounting/stats_groups.go
To restore a log line that was commented and merged.
=> fs/accounting: Restore "Max number of stats groups reached" log line

lib/oauthutil/oauthutil.go
It append "--" on the `rclone authorize` command line before `client_id`, in case that the `client_id` or `client_secret` has a prefix of "-" (OneDrive's does), and affects the argument parsing of `getopt` (see man page `getopt(1)`).
Nope.
=> oauthutil: give robust CLI command line

backend/qingstor/qingstor.go, backend/qingstor/upload.go
I linted this with `staticcheck`.
This prunes the unused `list()` function and satisfies the linter by removing a noop `fmt.Sprintf()`.
=> Prune qingstor

backend/azureblob/azureblob.go
Linted with `staticcheck`.
This removes the unused `Object.parseTimeString()` from `backend/azureblob`, as well as an unneeded `fmt.Sprintf()`.
=> Prune azureblob

backend/s3/s3.go
Amazon S3 is built to handle different kinds of workloads.
In rare cases where S3 is not able to scale, for whatever reason, users will face status 500 errors.
Main mechanism for handling these errors are retries.
Amount of retries needed is different for each use case.
This change is making max_retries option for s3 backend configurable.
=> backend/s3: add max_retries to options

cmd/serve/dlna/cds.go, cmd/serve/dlna/dlna_test.go, cmd/serve/dlna/upnpav/upnpav.go
Basically, solving #3541 with a different approach - bringing in
the upstream upnpav module, and changing ChildCount from int to a
*int to avoid childCount="0" in the XML output when that value is
simply unknown.
Current approach is leading to some recursion issues and according
to the DLNA spec it shouldn't be necessary, anyway.
Discussed in #3588 , @jorams reported an issue where the entire remote is being scanned in order to get the childCount metadata.
Alternative approach: could also just add a flag to ensure there's no recursion, but the CDS stuff is already quite messy, so this seems like a better idea and better handles the "top level directory with subdirectories for each media item" use case anyway.
It's possible some clients may have an adverse reaction to the change, but I …
=> dlna: cds: don't specify childCount at all when unknown

backend/s3/s3.go
S3 couldn't abort multi-part upload when context is canceled
because canceled context prevents abort request from being sent.
=> backend/s3: fix multipart abort context

cmd/serve/dlna/cds.go, cmd/serve/dlna/dlna_test.go
Fill in some missing timestamp metadata now that upnpav is in the local tree.  Depends on #3976.
=> Dlna cds add modtime

vfs/vfs.go
I wish, that running Linux `df` on a mount is as accurate as possible, considering the data reported by the remote.
Yes: https://github.com/rclone/rclone/issues/3997#issuecomment-591664003
=> vfs: make `df` output more consistent on a rclone mount.

bin/make_manual.py, docs/content/changelog.md
Generated documentation has invalid links.
To see such errors, you can use the command `grep -E -o -e '\(/[^)]+\)' rclone.1 | sort | uniq`:
```
(/amazonclouddrive/#status)
(/bugs/#limitations)
(/chunker)
(/commands/rclone_mount/#attribute-caching)
(/commands/rclone_mount/#file-buffering)
(/docs/#backup-dir-dir)
(/docs/#configure)
(/docs/#fast-list)
(/docs/#max-backlog-n)
(/docs/#no-traverse)
(/googlephotos)
(/local/#filenames)
(/mailru)
(/memory)
(/overview/#encoding)
(/overview/#features)
(/overview/#invalid-utf8)
(/overview/#optional-features)
(/overview/#restricted-characters)
(/overview/#restricted-filenames)
(/rc)
(/s3/#digitalocean-spaces)
(/sharefile)
(/sugarsync)
```
These links are not converted from relative style into absolute.
And this problem affects not only …
=> doc: fix links in generated documentation

fs/sync/sync.go
Sync/copy now only creates empty directories when they don't exist on the remote (--create-empty-src-dirs flag) - fixes #2800
sync/copy now only create empty source directories on dst when they do not exist.
Yes, this is issue #2800
=> copy/sync: fix bug on copying empty dirs

backend/s3/s3.go
There is a deprecation warning on `github.com/aws/aws-sdk-go/aws/session.New()`
>  Deprecated: Use NewSession functions to create sessions instead. NewSession has the same functionality as New except an error can be returned when the func is called instead of waiting to receive an error until a request is made.
This PR removes the deprecated `New()` function and replaces it with `NewSession()`.
=> backend/s3: Replace Deprecated session.New()

cmd/mountlib/mount.go
Shrink a volume name to 32 symbols on Windows so mount won't fail.
#4026
=> mount: fix fail because of a too long volume name - fixes #4026

backend/webdav/webdav.go
When running `rclone about webdav-remote:`, a typical answer would look like:
```
Total:   10G
Used:    90.119M
```
In such a situation, we have the data to compute the Free value too, so it should be done.
Besides, the current code does not allow either Free or Used to be equal to 0 (meaning “full” or “empty”): in this situation, it may happen that no value is reported. This is also fixed.
Yes: https://github.com/rclone/rclone/issues/3997
=> webdav: report full and consistent usage with `about`

backend/s3/s3.go
Fix the memory pool allocator in the s3 backend to use the provided size argument. Otherwise, when the requested pool is larger than the configured size, a panic occurs when attempting to use the buffer.
see #4047
=> fix #4047: use the provided size parameter to allocate new memory pool

backend/onedrive/onedrive.go
If chunk size is more than 250M (262,144,000 bytes) then API throws the following error: 
`Microsoft.SharePoint.Client.InvalidClientQueryException: The request message is too big. The server does not allow messages larger than 262144000 bytes.`
=> OneDrive maximum chunk size limit warning

backend/b2/upload.go
This prunes an unused function from `backend/b2`.
=> backend/b2: remove unused largeUpload.clearUploadURL()

backend/cache/storage_persistent.go, backend/cache/utils_test.go
Some methods in backend/cache had an all-caps warning that they should only be used in tests. This PR moves those methods to a file that is only compiled in test mode, so the warning is unnecessary.
I don't believe so.
=> cache: move methods used for testing into test file

docs/content/docs.md, docs/content/flags.md, fs/config.go, fs/config/configflags/configflags.go, fs/sync/sync.go, fs/sync/sync_test.go
This commit adds the --track-using-modtime flag which makes
rclone match renames using the file modification time instead
of file hashes. This enables support for tracking renames in
encrypted remotes. For two files to match, their modification
times must be within 1 millisecond of each other to account
for remote modification time inaccuracies.
Fixes #3696
Fixes #2721
This commit adds the `--track-using-modtime` flag which makes
rclone match renames using file modification time. It makes
`--track-renames` work with encrypted destinations.
It was discussed [here](https://forum.rclone.org/t/can-not-use-track-renames-when-syncing-to-and-from-crypt-remotes/11063).
=> fs: Add configurable matching criteria for --track-renames

lib/oauthutil/oauthutil.go
When using onedrive and configuring a remote with --no-check-certificate, the token is not fetchable with error `x509: certificate signed by unknown authority`
This is because the token fetch in oauthutil does not use the provided http client.
This PR allows the oauth2 token fetch phase to honor the --no-check-certificate flag.
No
=> Use custom http client so that --no-check-certificate is honored by oauth2 token fetch

backend/drive/drive.go, backend/dropbox/dropbox.go, backend/onedrive/onedrive.go
Stop sync when OneDrive has no storage left. OneDrive returns HTTP response code `507` and error code `quotaLimitReached` when that happens.
Yes. Fixes #4089
```
harry@ubuntu16:/mnt/c/Users/HARRY/rclone$ ./rclone copy "/mnt/c/Users/HARRY/1GbTestFile.bin" onedrive1:
2020/03/25 18:19:19 ERROR : 1GbTestFile.bin: Failed to copy: quotaLimitReached: Quota limit reached
2020/03/25 18:19:19 ERROR : Fatal error received - not attempting retries
2020/03/25 18:19:19 Failed to copy: quotaLimitReached: Quota limit reached
```
Stop sync when Team Drive has reached its maximum files limit and flag `--drive-stop-on-upload-limit` set to **true**.
Yes. Fixes #3979
Stop sync when Dropbox has no storage/space left.
No.
=> make error quotaLimitReached (onedrive) and teamDriveFileLimitExceeded (google drive) to be fatal

docs/content/crypt.md
Without explaining exactly how this is generated, it can be confusing
and worrying to not know how the password that encrypts your data is
stored.
This also brings peace of mind to the user that even though
the same password is obscured differently each time, all the data to
get back to the original password remains. Explaining how it works
is much better than the reader of the documentation having to trust
a blackboxy/magical mechanism.
No
=> docs: unmystify how crypt stores encryption password in config

backend/s3/s3.go
This change adds SSE-C support to AWS, Ceph, and MinIO backends. This allows for customer provided encryption keys.
https://github.com/rclone/rclone/issues/2827
=> Add SSE-C support for AWS, Ceph, and MinIO

cmd/lsf/lsf.go, docs/content/docs.md, docs/content/filtering.md, fs/filter/filter.go, fs/filter/filter_test.go, fs/filter/filterflags/filterflags.go
--files-from parses input files by ignoring comments starting with # and ;
and stripping whitespace from start and end of strings. We want to add some solution to this so that expected behavior of `rclone lsf` being good input to `--files-from` is restored.
A --process-raw flag was added so that --files-from reads every line from the file ignoring
comment characters and not stripping whitespace while maintaining backwards
compatibility.
https://forum.rclone.org/t/rclone-skips-files-ending-in-unicode-whitespace-when-using-files-from/15285
=> filterflags: Added --process-raw flag

cmd/serve/sftp/sftp.go
The option --key would set the sftp host key. It could be mistaken for some default-user-key. Instead, explicitly call it 'host key' to avoid confusion.
No related issue, spontaneous suggestion after personal confusion.
=> doc: Clarify 'key' option for host key on serve sftp

backend/jottacloud/api/types.go, backend/jottacloud/jottacloud.go, docs/content/jottacloud.md
As discussed in the forum I added a --jottacloud-trash-only flag that shows Trashed files in their original location. Normal operations should actually work on trashed files as long as the flag is included in the command.
I've also quickly added the cleanup command.
=> Implement option to view the Jottacloud trash

backend/s3/s3.go
Resizing is not needed as it is handled by Pool implementation.
No
=> s3: do not resize buf on put to memBuf

fs/accounting/stats.go, fs/log.go
Output actual json representation when using json logs.
https://github.com/rclone/rclone/pull/3373#issuecomment-523395333
https://github.com/rclone/rclone/pull/3903#issuecomment-578971245
=> fs: expand stats output for json log

cmd/cmd.go, docs/content/docs.md, fs/config.go, fs/config/configflags/configflags.go
This allows rclone to exit with a non-zero return code if no files are
transferred. This is useful when calling rclone as part of a workflow/script
pipeline as it allows the end user to stop processing if no files have been
transferred.
NB: Enabling this option will return in rclone exiting non-zero if there are no
transfers. Depending on how you're currently using rclone in your scripts,
this may break existing setups!
```
rclone --error-on-no-transfer copy remote:/myfiles s3:my-s3-bucket/files/from/me
RC=$?
if [ $RC -eq 0 ]; then
echo "I'm going to process some files now"
elif [ $RC -eq 9 ]; then
echo "There's nothing to do, goodbye"
exit 0
else
echo "Something went wrong in the transfer"
exit 1
fi
```
No, but it probably should be... I've sort of stolen the `--stats-*` namespace for …
=> cmd: add --error-on-no-transfer option

cmd/copy/copy.go
Just a drive-by typo fix. I presume the [md](https://github.com/rclone/rclone/blob/master/docs/content/commands/rclone_copy.md) is autogenerated from this file?
=> copy: fix typo

Dockerfile
GOOS and GOARCH being set like this makes it impossible to compile on
other archs.
For me GOARCH prevents compilation on my ARM machine.
For others GOOS will prevent windows.
xref https://github.com/rclone/rclone/issues/4086
=> Dockerfile: remove GOOS and GOARCH

backend/googlephotos/googlephotos.go, backend/googlephotos/pattern.go, backend/googlephotos/pattern_test.go
Make the start year configurable instead of hard coding it to `2000`
Discussion: https://github.com/rclone/rclone/issues/3630
=> backend/googlephotos: Add start_year for google photos options

backend/b2/b2.go, backend/box/box.go, backend/box/upload.go, backend/fichier/api.go, backend/fichier/fichier.go, backend/googlephotos/googlephotos.go, backend/jottacloud/jottacloud.go, backend/onedrive/onedrive.go, backend/opendrive/opendrive.go, backend/pcloud/pcloud.go, backend/premiumizeme/premiumizeme.go, backend/s3/s3.go, backend/sharefile/sharefile.go, backend/sugarsync/sugarsync.go, backend/webdav/webdav.go, backend/yandex/yandex.go, docs/content/docs.md, docs/content/flags.md, fs/config.go, fs/config/configflags/configflags.go, fs/operations/multithread.go, fs/operations/operations.go, fs/operations/reopen.go, fs/operations/reopen_test.go
The goal is to add two repeatable flags as follows
--header-upload "Header: String"
--header-download "Header: String"
Headers added with the --header-upload flag will get added to all Put/Update calls.
Headers added with the --header-download flag will get added to all Open calls.
In this PR I would like to lay the groundwork for these flags and complete an implementation for at least one of the backends. My immediate need is for s3/minio so I am focusing on that.
I have been following the implementation steps laid out [here](https://github.com/rclone/rclone/issues/59#issuecomment-504379064).
https://github.com/rclone/rclone/issues/59
=> fs: add header-download and header-upload flags

backend/box/box.go, lib/jwtutil/jwtutil.go
When using box jwt auth from a server that has an incorrect timestamp. It can result in the following error:
`Current date/time MUST be after or equal to the not-before date\/time listed in the 'nbf' or 'iat' claim`
The `iat` claim doesn't actually have to be set on the request for box to accept it, and so it makes sense to remove it.
When I first hit this issue I wasn't receiving any error messages from rclone, so I've fixed that up too.
Nope
=> Remove "iat" from box jwt claims and fix error handling

backend/fichier/api.go, backend/fichier/fichier.go
1fichier recently changed there rate-limiting to a level that makes it almost unusable. Additionally they changed the HTTP error when rate limited from 429 to 403. Together this causes rclone's in integration tests to fail and makes any sync with 1fichier basicly impossible. The api documentation doesn't reflect the changes yet so this is a best-guess effort to work around it.
It looks like you can make barely 2 requests per second with the actual rate possibly being different for different operations. For this reason, I added a custom pacer for 1fichier though neither usage nor settings a final yet. Sadly the changes make 1fichier almost unusable for more than a handful of files and folders. The integrations tests alone take almost 1 hour to complete now.
=> Try to deal with new 1fichier rate limiting

backend/googlephotos/googlephotos.go
For a certain class of broken or missing image Google Photos puts an
image in the error message.
Before this fix we blindly chucked it into the error message.
After this fix we replace it with some sensible text.
=> googlephotos: don't put an image in error message - fixes #4144

cmd/delete/delete.go
If you supply `--rmdirs` flag with delete command, it will remove all empty directories along with it leaving the root intact.
Implementing remove folders with rclone delete #4055
https://github.com/rclone/rclone/issues/4055
=> cmd: added --rmdirs flag to delete command - fixes #4055

docs/content/docs.md
add Windows Powershell example wiki link to  --password-command doc
In the --password-command documentation, add a link to the Windows Powershell Wiki article 
Nick suggested I do this in a reply 
https://forum.rclone.org/t/how-to-use-rclone-password-command-with-windows-powershell-for-config-password/15950
Note: It appears from the diff that a trailing blank was added to line 925 ("`size` - order by the size of the files "). I have no idea how that happened (I'm using the GitHub web interface to make this change). 
Worse, I don't know how to remove the trailing blank with the GitHub web interface - sorry..
- [x ] I have added documentation for the …
=> --password-command doc Powershell Wiki link

fs/config/config.go
Bind rclone standard input to password command's standard input. This
allows to provide password from a pipe and collect it using `cat`.
The typical use case is when rclone is on a remote server with an
encrypted configuration. This solved the environment variable
issue (#3368), the password storage on remote host and a potential
issue with command logging on remote host when password command
is `echo secret`.
Now the following chain is allowed:
echo 'secret' | ssh host.example.com \
sudo -u rclone \
rclone --config /path/to/rclone.conf \
--password-command 'cat' ls remote:
Allow password-command to read password from rclone standard input and use `cat`.
A typical usage can be:
echo 'secret' | ssh host.example.com \
sudo -u rclone \
rclone --config /path/to/rclone.conf \ …
=> fs config: bind Stdin to password command

cmd/serve/sftp/server.go, cmd/serve/sftp/sftp.go
It is often useful to provide different host key algorithms for client compatibility reasons.
For example, `Ed25519` is still not supported everywhere, incompatible clients should be able to fall back on `ECDSA` or `RSA`.
No
=> serve sftp: add support for multiple host keys

fs/accounting/accounting.go
During a copy/sync command, if an operation fails due to a network
issue and is retried, the underlying io.Reader is re-initialised,
but the stats for bytes already read are not reset, leading to incorrect
stats. THis was fixed by resetting the bytes read when an Account is
re-initialized.
During a copy/sync command, if an operation fails due to a network issue and is retried, the underlying io.Reader is re-initialised, but the stats for bytes already read are not reset, leading to incorrect stats. This was fixed by resetting the bytes read when an Account is
re-initialized.
https://github.com/rclone/rclone/issues/4178
=> accounting: reset bytes read during copy retry - fixes #4178

cmd/cmount/mount.go, cmd/mount/mount.go, cmd/mount2/mount.go, cmd/mountlib/mount.go, cmd/mountlib/rc.go, cmd/mountlib/rc_test.go
Adding mount support for remote control.
I need suggestions about the directory structure, and the change is being implemented correctly.
This is just an initial implementation. 
I see that every independent module like `fs` has a separate `rc.go` file. But the files in `cmd` don't have it. Instead inside their init function, they have an `AddCommand()` call. How should the `mount` endpoint addition for `rc` look like?
No
=> rc: adding mount command

docs/content/docs.md, fs/config.go, fs/config/configflags/configflags.go, fs/march/march.go, fs/march/march_test.go, fs/sync/sync.go
To add the flag discussed in issue #4228 which was born out of a conversation about a suspected bug on the forum.
https://forum.rclone.org/t/unique-unicode-characters-lead-to-duplicate-object-found/16314
=> march: added flag to allow Unicode filenames to remain unique

backend/googlephotos/pattern.go, backend/googlephotos/pattern_test.go, docs/content/googlephotos.md
Enable access “Favorite” images on Google Photos backend.
This adds a “feature/favorites” folder in the Google Photos backend
and uses the Feature Filter API
https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search#Filters
https://github.com/rclone/rclone/issues/4189
=> googlephotos: create feature/favorites directory

docs/content/drive.md
The option of 'other' seems to be gone from the https://console.developers.google.com/apis/credentials/oauthclient
page.
It only lists these now:
Web application
Android
Chrome app
iOS
TVs and Limited Input devices
Desktop app
Universal Windows Platform (UWP)
I just changed those couple words
=> Google console doesn't list 'other' anymore

backend/sftp/sftp.go, docs/content/sftp.md
This was closed by mistake:
https://github.com/rclone/rclone/pull/4238
I'd like to be able to store the key in the config (or environment variable) with the rest of the parameters rather than carrying it around in an external file to deploy along with the rclone config.
So i'd allow for a config parameter to store the actual key rather than only read a file system file. This would also enable tools that abstract the filesystem from the app running rclone to work correctly here (RCX for android for example).
command:
--sftp-key-pem (actual key)
config:
key_pem = (actual key)
I was thinking since the config file doesn't allow multi-line that I would force a sane delimiter (\r\n and \n).
=> Sftp: Ssh add key pem to config 2

backend/cache/cache.go, cmd/backend/backend.go
This change adds support for server side copying to the cache backend (when wrapping a backend that supports it) when the `tmp_upload_path` option is specified. Previously, this configuration would result in the following behaviour from e.g. `mv`:
```text
user@HOSTNAME:/data/data# mv a.txt b.txt
mv: cannot move 'a.txt' to 'b.txt': Input/output error
```
rclone itself would emit a message similar to the following:
```text
ERROR : data/a.txt: Dir.Rename error: Fs "Encrypted drive 'data:'" can't rename files (no server side Move or Copy)
```
This was caused by the `cache` backend "masking out" Copy support from the wrapped backend due to the `local` backend not supporting it.
https://github.com/rclone/rclone/issues/3206
=> Cache - Add Support for Server Side Copy When Using Temp Upload

cmd/mountlib/mount.go
The link is for WinFsp, so link from "WinFsp" rather than "open
source".
=> docs: move link to correct location

docs/content/dropbox.md
Proposed by the original repo owner in this comment: https://github.com/rclone/rclone/issues/2301#issuecomment-388291079
Give rclone users more info about an error that occurs while you are trying to sync Dropbox files protected by copiright.
Yep, the original repo owner suggested it [here](https://github.com/rclone/rclone/issues/2301#issuecomment-388291079)
=> dropbox: Add copyright detector info in limitations section

.github/workflows/build_publish_docker_image.yml, .github/workflows/build_publish_release_docker_image.yml, Dockerfile, go.mod, vendor/modules.txt
With this PR I would like to move the CI for docker images from dockercloud to GitHub Actions.
Also, I would like to add support for multi-arch images in order to support not only amd64 but also arm, x86... architectures
I don't know
=> Moving from dockercloud to GitHub action + multi-arch support

docs/content/_index.md
Minor punctuation, brevity and emphasis changes. Comment on strapline:
I took a guess this was source for web front page. Enclosed are some minor tense, punctuation, brevity and positivity change proposals.
I did think a bit about the main strapline description. It just doesn't bounce out at me. After looking at a few dreadful alternatives - looked like I had swallowed a thesaurus and wanted to win a worst mixed metaphors competition - I wondered about:-
Rclone :: Cloud Storage's Rosetta Stone
or:-
Rclone :: Cloud Storage's Rosetta
IT people may not be historians but they have heard of the Rosetta stone and understand it's significance. It is classy, classical and is a good fit for rclone's functionality, philosophy and mission.
There are umpteen other projects in computing using the …
=> Minor punctuation, brevity and emphasis changes. Comment on strapline

backend/s3/s3.go
This allows to configure a maximum amount of chunks used to upload file.
- Support Scaleway which has a limit of 1k chunks currently
- Reduce a cost on S3 when each request costs some money at the expense of memory used
Nope
=> s3: add `max_upload_parts` support

backend/tardigrade/fs.go
This provides two things:
* It gives Storj insight into which uplink clients are using the
network.
* It facilitate rclone participating in the Tardigrade Open Source
Partner Program https://tardigrade.io/partner/
=> backend/tardigrade: Set UserAgent to rclone

vfs/file.go
Previously files before they get uploaded will inherit the directory modtime.  This changes that to use the current time instead.
https://forum.rclone.org/t/times-on-files-initially-set-incorrect-on-mount/16923/3
=> vfs: Change modtime of file before upload to current

backend/sftp/sftp.go
This PR fixes a bug in the SFTP Backend.
For SSH authentication, `key_pem` should both override `key_file`
and not require other SSH authentication methods to be set.
Prior to this fix, rclone would attempt to use an ssh-agent
when `key_pem` was the only authentication method set.
This fix has not been discussed.
[Original feature PR](https://github.com/rclone/rclone/pull/4240)
[Original feature discussion](https://forum.rclone.org/t/add-ssh-key-to-config-file-rather-than-filesystem-pointer/16404)
=> sftp: Fix SSH key PEM loading

backend/s3/s3.go, docs/content/s3.md
This PR adds Scaleway to the list of know S3 compatible providers, allowing quick selection of region/endpoint and enforcing required settings for ForcePathStyle and MaxUploadParts.
Suggested in #4159 and formalized in #4338
=> s3: add Scaleway provider - fixes #4338

fs/accounting/prometheus.go
Fixes #4341
Signed-off-by: Gary Kim <gary@garykim.dev>
Fix a bug with metrics being incorrect.
Fixes #4341
=> rcd: fix incorrect metrics

fs/fspath/path.go, fs/fspath/path_test.go
I have briefly looked at go (and familiarized myself with it) before, this is the first actually useful piece of code I have written with go. In total, it took 3 hours for this tiny piece of code. A bit of remind go, a casual (hackathon mode: <5m) 30-40m in this tiny piece, more time than I'd like in getting the environment ready (mainly [cloning to the wrong location the wrong way](https://github.com/rclone/rclone/issues/4261#issuecomment-644315664)), 10m to install go (the recommended way is to get a tar and never update, what I don't agree to, returned to my package manager and also added it to my script of run-this-after-reinstall), ~45 in general adding to documentation.  :tada: 
Disallow naming or renaming remotes beginning with a dash ( - ), as while operating normally, you can't …
=> config: reject remote names starting with a dash. (#4261)

fs/fspath/path.go
```
q) Quit config
e/n/d/r/c/s/q> n
name> !)"=)¤
Can't use "!)\"=)¤" as config name contains invalid characters - may only contain 0-9, A-Z ,a-z ,_ , - and space .
```
Notice: `and space .`?
Change it to `and space.`.
There isn't anything using this error, what places something else than a dot at the end (if there was, you'd end up with 'and spacesomething other.').
No.
=> Error: errInvalidCharacters: 'and space .' -> 'and space.' Remove a space between the word, space, and period.

cmd/mountlib/rc.go
Currently, the mount is saved even if an error, occurs, which should not happen. This PR fixes that by returning the error and not saving the mount.
=> rc: Add mount to list only if mount point was successfully created

Dockerfile
Added the tzdata package to the dockerfile to fix custom timezone
https://forum.rclone.org/t/rclone-in-docker-uses-tz-as-utc-not-as-provided/17173
=> Fix custom timezone in rclone docker image

fs/operations/rc.go, fs/operations/rc_test.go, fs/rc/params.go, fs/rc/rcserver/rcserver.go, fs/rc/registry.go
Add functionality to upload a file to a remote using the rc. 
This will allow a file to be uploaded directly through the web GUI.
May close #3412
No
=> rc: Add operations/uploadfile to upload a file through rc using multipart/form-data

docs/layouts/chrome/navbar.html
Navbar will remain visible on the top of the screen, even when
the user has scrolled down.
This makes it easier to navigate the site quickly.
The purpose is to make the navbar on the webpage visible at all times. Even when the user has scrolled.
Nope. I browsed rclone.org and found it annoying to scroll back up.
This change can be discussed here in the PR.
=> docs: make the website navbar stick to top

docs/content/onedrive.md
OneDrive now supports up to 100 GB for both OneDrive Personal and OneDrive for Business.
No
=> [Docs] Updated OneDrive max file size

cmd/serve/dlna/dlnaflags/dlnaflags.go
Mark the flags for `serve dlna` as code in the documentation. Otherwise, we get en dashes in the man page, making args more difficult to copy/paste to a command line. Previously, the man page would show flags like `–addr`; now it shows `--addr`.
No.
=> dlna: Mark flags in docs as code

backend/s3/s3.go
Use the regional s3 endpoint for us-east-1
No. Came across this yesterday. When having an s3 endpoint set up with the following config:
```
[s3]
type = s3
provider = AWS
env_auth = true
region = us-east-1
acl = bucket-owner-full-control
```
Running `rclone -vv lsjson s3://{bucket_in_another_region}/whatever` gives the following:
```
ERROR : : error listing: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
status code: 400, request id: {ID}, host id: {ID}
```
This isn't caught by the [retry](https://github.com/rclone/rclone/blob/master/backend/s3/s3.go#L1089) because it's a 400, not a 301
The reason why it's a 400 is because rclone is going to `s3.amazonaws.com` rather than `s3.us-east-1.amazonaws.com`. 
When …
=> s3: Use regional s3 us-east-1 endpoint

backend/googlecloudstorage/googlecloudstorage.go, docs/content/googlecloudstorage.md
Currently credentials are required to download a public bucket file
which is not really necessary and makes automated usage more complex.
Add a new option "anonymous" which when enabled configures the
gcs backend to use an anonymous HTTP client. This of course only works
for read access and trying to write will lead to errors like that:
"googleapi: Error 401: Anonymous caller does not not have
storage.objects.create access to the Google Cloud Storage object.",
as expected. By default the anonymous access option is disabled so that
the GCS Application Default Credentials are still used by default as
before and an error is given if they can't be found.
no
I didn't add tests - does this apply? I tested it manually but it could be tested with some hardcoded public bucket.
=> gcs: add support for anonymous access

bin/get-github-release.go
This patch removes a `defer` statement inside of a loop.
No.
=> GitHub Release Tool Patch

bin/make_manual.py
The documentation contains an embedded datetime which do not read
SOURCE_DATE_EPOCH. This makes the documentation unreproducible when
distribution tries to recreate previous build of the package.
This patch ensures we attempt to read the environment variable before
default to the current build time.
Signed-off-by: Morten Linderud <morten@linderud.pw>
No.
=> make_manual: Support SOURCE_DATE_EPOCH

docs/content/drive.md, docs/content/privacy.md
When I was trying to create and verify a Google Drive API key as according to the present instruction, it did not work for me. I found a workaround that is based on [Python Quickstart](https://developers.google.com/drive/api/v3/quickstart/python) and added the corresponding bit of documentation.
Later, after submitting the app for review, I received a message from Google Cloud Trust & Safety Team that asked for the clear description of how Google user data are used, which is governed by the [Google API Services User Data Policy](https://developers.google.com/terms/api-services-user-data-policy). I added a section to the Privacy Policy and hope that it helps one in passing this screening.
No.
=> Workaround and Policy for Google Drive API

cmd/obscure/obscure.go
`rclone obscure` currently only accepts a command line argument of `password` to generate
an obfuscated password. This is an issue since generating obfuscated passwords programatically
requires sending the plain text password as a shell argument, which can cause problems if the
password contains shell characters, or if the password is from an untrusted source.
This patch opens up STDIN which will allow developers to open the STDIN source and print a password
directly to `rclone obscure`, which can increase safety and convenince.
Unknown. A cursory glance did not turn up any forums posts.
=> cmd/obscure: Allow obscure command to accept password on STDIN

backend/amazonclouddrive/amazonclouddrive.go, backend/box/box.go, backend/drive/drive.go, backend/dropbox/dropbox.go, backend/googlecloudstorage/googlecloudstorage.go, backend/googlephotos/googlephotos.go, backend/hubic/hubic.go, backend/onedrive/onedrive.go, backend/pcloud/pcloud.go, backend/yandex/yandex.go, lib/oauthutil/oauthutil.go
This PR does the following:
1. Adds SharedOptions data structure to oauthutil.
2. Adds config.ConfigToken option to oauthutil.SharedOptions.
3. Updates the backends that have OAuth functionality.
The main purpose is to expose the `token` configuration options as backend flags on the CLI. The various OAuth backend options have also been factored into a single place to be used across the OAuth enabled backends.
Here are some examples of this in use:
```
$ ./rclone --drive-token '{"access_token":"$TOKEN","token_type":"Bearer","refresh_token":"$REFRESH","expiry":"2020-07-31T20:04:09.923068-07:00"}' --drive-root-folder-id $ROOT_ID lsl :drive:
```
```
$ ./rclone --dropbox-token '{"access_token":"$TOKEN","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}' lsl :dropbox:
```
Discussed in #2849
=> oauthutil: adds SharedOptions for OAuth backends

fs/operations/rc.go, fs/operations/rc_test.go
This bug ignored the remote parameter while uploading a file, thus the file will appear only in the root of the fs. This PR fixes that and adds test for it
No
=> Fix uploadfile only works for root of the fs

go.mod, go.sum
Uplink v1.2.0 comes with two improvements related to rclone:
* Fix for resource leak in uploads.
* The socket dialer comes with better congestion control in some
environments. On Linux environments, if a congestion controller named
'ledbat' is installed, it will be used. Consider installing
https://github.com/silviov/TCP-LEDBAT
N/A
=> backend/tardigrade: Upgrade to uplink v1.2.0

fs/rc/internal.go, fs/rc/internal_test.go, fs/rc/params.go, fs/rc/rcserver/rcserver.go, fs/rc/registry.go
This will allow rclone to run the commands which are not available directly through rc, over rc.
This api will spawn a temporary instance of rclone to execute the command. Then it will return the raw command output.
This will also help in the development of a web-based rclone terminal. (
=> core/command: Allow rc to execute rclone terminal commands.

fs/fserrors/enospc_error.go, fs/fserrors/enospc_error_notsupported.go, go.mod, go.sum, vfs/read_write.go, vfs/vfscache/cache.go, vfs/vfscache/cache_test.go, vfs/vfscache/downloaders/downloaders.go, vfs/vfscache/item.go
This patch detects out-of-space errors of the full cache mode and resets clean cache files (not changed) to make space.
https://forum.rclone.org/t/removing-recreating-cache-file-upon-enospc/17791
=> Vfs reset cache

backend/s3/s3.go
This PR updates IBM COS endpoints as per https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints. The list can be found in https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-endpoints.
Specifically, the change updates existing ones to use the new domain and adds missing endpoints. Only public and private endpoints are included, though I'm wondering if `direct` endpoints should be included as well. Personally, I have not used them.
Yes, there is issue #4522 opened with IBM Cloud notification regarding domain change.
=> Updated IBM COS endpoints

backend/jottacloud/jottacloud.go
Another fix from the [lgtm static analysis](https://lgtm.com/projects/g/rclone/rclone/) (It's a minor style fix really). Just rename an unused response to `_` to ensure that the you don't actually want to use it.
Briefly in #4539 as its one other static fixes mentioned
- [] I have added tests for all changes in this PR if appropriate.
- [] I have added documentation for the changes if appropriate.
This is the last fix from the lgtm static analysis that is an easy fix. 
Most of the remaining ones are either style recommendations in JS/Python or security fixes that complain because you can access the file system through user provided get values in potentially unsafe ways. The latter obviously needs a redesign to fix properly or adding // noqa comments to stop the static analysis from …
=> jottacloud: rename unused variable to _ in jottacloud.go

vfs/vfscache/cache.go
Quiet the logging from the VFS cache purger to drop messages about not removing files to the debug level
https://github.com/rclone/rclone/commit/c665201b85483da1e6eceff18844d9d1741943e2#commitcomment-41941933
=> vfs: Quiet removeNotInUse logging to debug when not removing

backend/drive/drive.go, docs/content/drive.md
`--drive-alternate-export` is not necessary anymore, `exportLinks` file field provides links which can handle export of big files.
No
=> Remove --drive-alternate-export in favor of exportLinks

docs/content/jottacloud.md
Clarify that users does not have to worry about disk caching and tweaking of the --jottacloud-md5-memory-limit flag as long as they upload from local disk, not even with crypted remote when using rclone version 1.52 and newer.
[X ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
~[X] I have added tests for all changes in this PR if appropriate.~
[X] I have added documentation for the changes if appropriate.
[X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
[X] I'm done, this Pull Request is ready for review :-)
=> docs/jottacloud: mention that uploads from local disk will not need to cache files to disk for md5 calculation

backend/drive/drive.go
Fixes #4555 
In https://github.com/rclone/rclone/commit/30eb094f286c28fdbd7ddd0a6fe39fd5bbe8e833 the Google Drive Client ID help text was changed due to the OAuth options being centralized. However the original text was useful so it should be added back in. This commit updates the help text while still using the shared oauth options.
Here's how it looks.
**drive**: uses the custom help text
```
Storage> drive
** See help for drive backend at: https://rclone.org/drive/ **
Google Application Client Id
Setting your own is recommended.
See https://rclone.org/drive/#making-your-own-client-id for how to create your own.
If you leave this blank, it will use an internal key which is low performance.
Enter a string value. Press Enter for the default ("").
client_id> 
```
**dropbox**: uses the …
=> drive: adds special oauth help text - fixes #4555

cmd/mountlib/mount.go
After being confused as to why the mount command disappeared from my rclone after updating, I discovered it was due to https://github.com/rclone/rclone/commit/17b4058ee944ab660b30593a858ff9d591b62a3b, so decided to add a note to the docs about it.
=> docs: Updated mount command to reflect that it requires Go 1.13 or newer

backend/opendrive/opendrive.go
This type of error is unlikely to be an error that can be resolved by a retry, and is triggered in #2296 by files with a timestamp before the unix epoch.  This does not address the underlying timestamp issue that #2296 describes, only avoids that issue triggering useless retries.
OpenDrive previously retried 400 errors, but that should probably not be the case, and at least in the case of #2296 it is quite detrimental.
#2296
=> opendrive: Do not retry 400 errors

backend/dropbox/dropbox.go, docs/content/dropbox.md
Whoops that turned out to be bigger a change than I had remembered. It also works somewhat differently than `--drive-shared-with-me`. This actually adds 2 flags:
* ``--dropbox-shared-files``: instructs rclone to act on individual shared files (those that show up directly under shared). In this mode rclone's features are extremely limited - only listing shared files and downloading them is supported every other operation will be disabled.
* ``--dropbox-shared-folders``: instructs rclone to operate on shared folders. When this flag is used with an empty root only the List operation is supported and all shared folders will be listed. If you use ``--dropbox-shared-folders`` with a non empty root the first part of the path will be interpreted as the name of shared folder. rclone will then try …
=> dropbox: add support for viewing shared files and folders

backend/seafile/api/types.go, backend/seafile/seafile.go
seafile: fix broken when using seafile as backend on 32bit cpu (etc raspberry) - fixes #4588
Changing the type of seafile Library Size to int64.
#4588
=> seafile: fix broken on raspberry - fixes #4588

backend/chunker/chunker.go, fstest/test_all/config.yaml
Chunker wraps a stream to upload with a splitting reader and calls the underlying (base) put() in a loop.
When a chunk is read completely, the wrapper returns EOF to base put and refills chunk limit
(see https://github.com/rclone/rclone/blob/v1.53.1/backend/chunker/chunker.go#L1168).
The crypt backend appears to be special. After receiving EOF it calls Read() again.
Since limit is already refilled, chunker feeds it the next chunk resulting in a wrong underlying upload.
This PR postpones refilling of the chunk limit to the next call of base Put() so that wrapper "insists" on EOF for the chunk.
The crypt overlay behavior is out of scope for this PR and not considered a bug.
Also this PR adds the chunker->crypt overlay chain to the integration suite. It's quick and low on resources.
Fixes …
=> chunker: fix upload over crypt (fixes #4570)

backend/mailru/api/m1.go, backend/mailru/mailru.go
An rclone user encountered an old corrupted file that resulted in an invalid modifcation timestamp
returned by mail.ru server as a large unsigned integer bitwise representing int64 "-1".
Currently mail.ru backend keeps server timestamps as signed int64 and the above number results
in panic during json unmarshaling.
This issue is rare and cannot be easily reproduced in a test.
This fix makes mail.ru backend catch invalid timestamps and replace them by Unix epoch "1970-01-01-...".
The reporter confirmed that this change fixes issue for them
(see https://github.com/rclone/rclone/issues/4229#issuecomment-630050995).
Yes, in the bug report https://github.com/rclone/rclone/issues/4229
=> mailru: fix invalid timestamp on corrupted files (fixes #4229)

backend/chunker/chunker.go
Chunker needs to detect groups of files that form a compund object in the underlying directory.
Currently it uses a dead simple approach: it sorts directory listing by name and finds consecutive groups of file names with a common prefix that satisfies mask.
This approach requires that variable name part must be on the end of file name, for sorting to work.
This pre-condition is backed by the strict check at https://github.com/rclone/rclone/blob/v1.52-stable/backend/chunker/chunker.go#L413.
However, the other requirement has no check: the directory listing must be fed in a single piece.
But, if underlying remote (eg. `drive`) supports the `ListR` interface, the listing for a single directory could come in pieces
sorted one-by-one (see …
=> chunker: disable ListR to fix missing files on Drive

backend/sftp/sftp.go, docs/content/sftp.md
Enable certificate based authentication, by allowing the user to optionally specify the public key to use.
We take the normal "signer" that was used for key auth, and if the user has specified the pubkey then we wrap that with a new signer that also holds the public key.
https://forum.rclone.org/t/ssh-certificate-based-authentication-does-not-work/
- [*] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [*] I have added documentation for the changes if appropriate.
- [*] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [*] I'm done, this Pull Request is ready for review :-)
=> sftp: allow user to optionally specify pubkey file to enable cert-based auth

cmd/cmd.go, cmd/mountlib/mount.go, fs/config.go, fs/config/configflags/configflags.go, fs/log.go, fs/log/log.go, go.mod, go.sum, vfs/vfscache/cache.go
Following #4596
I hope the changes are in the right spots, don't hesitate to request additional changes even just to better match the rclone architecture. I have separated each step in a different commit for easier reviewing but in the end I think this PR should have its commits squashed.
preview:
```
✔ 18:16 ~/Golang/Workspaces/perso/src/github.com/rclone/rclone [ sysdjournald L | ✚ 1 ] $ ./rclone --log-level DEBUG version
2020/09/18 18:16:51 DEBUG : rclone: Version "v1.54.0-DEV" starting with parameters ["./rclone" "--log-level" "DEBUG" "version"]
rclone v1.54.0-DEV
- os/arch: linux/amd64
- go version: go1.14.6
2020/09/18 18:16:51 DEBUG : rclone: Version "v1.54.0-DEV" finishing with parameters ["./rclone" "--log-level" "DEBUG" "version"]
✔ 18:16 …
```
=> Improve systemd integration (logging & status)

cmd/cmd.go, docs/content/docs.md, fs/accounting/stats.go, fs/config.go, fs/config/configflags/configflags.go, lib/terminal/terminal.go, lib/terminal/terminal_normal.go, lib/terminal/terminal_unsupported.go
Fixes #4187
Adds the flag `--print-progress-title` which, when used with `-P/--progress`, will print the string "ETA: ..." to the terminal title.
This was discussed on #4187.
- [`x`] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [`x`] I have added documentation for the changes if appropriate.
- [`x`] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [`x`] I'm done, this Pull Request is ready for review :-)
=> lib/terminal: add WriteTerminalTitle - fixes #4187

vfs/vfscache/cache.go, vfs/vfscache/downloaders/downloaders.go, vfs/vfscache/item.go
=> Fix cache reset.1.53.1

docs/content/box.md
Documentation for Box: Add the full name of the backslash-lookalike unicode character to make it easier for users to understand what's going on.
No.
=> docs: Box: explain about the backslash-like unicode character

backend/jottacloud/jottacloud.go
In #4645 we noticed jottacloud token refresh for v2 authentication failing due to oauth clientID and clientSecret being set in the config. Jottacloud v2 authentication uses the static value `jottacli` as clientID and no clientSecret at all and we set them as such but if different values are set config file oauthutil will override them. This happens when a user switched from v1 to v2 authentication because these values are left in the config file.
Given that there is probably good reason for oauthutil to have this behavior I've extended extended the configmap with Delete method so we can explicitly delete these from the config file. There would be other ways to fix this but I don't thing having a delete method for configmap hurts.
=> jottacloud: remove clientID/clientSecret from config when using v2 auth

backend/crypt/cipher.go
This is just a very minor simplification of some code in the `crypt` backend. There's no change to functionality or security, it just removes a few lines of unneeded code.
Basically, it looks like we're copying the nonce into a buffer and then immediately overwriting it. So we don't need to do that. Note, I'm not a Go programmer, so let me know if I'm missing something here.
No, I was just looking through the code and noticed it. The change is so small I didn't think it needed discussion.
Thanks for a great tool!
=> crypt: small simplification, no functionality change

backend/mailru/mailru.go
Mailru backend suffers from problem similar to `chunker` PR https://github.com/rclone/rclone/pull/4614
When a localfs file is uploaded to mailru, the backend requests hashsum from file source.
Local files provide any kind of hashsum but hashing can take long for large files and postpone actual transfer.
Unlike chunker, mailru can use hashsum in advance to completely skip upload (transparent deduplication on server).
However, in case of encrypted or unique files (eg. `restic` dumps) the hashsum check is irrelevant and ineffective.
The mailru backend has config options that control eligibility of this optimization:
`speedup_enable` (can completely disable hashsumming), `speedup_file_patterns` (enable based on file extension), `speedup_max_disk` (disable based on file size), etc.
Due to a …
=> mailru: avoid prehashing of large local files

backend/chunker/chunker.go
Chunker by nature is dedicated to handling very large files and supports MD5/SHA1 hashes for composite objects.
When it uploads a new object on target, it requests hashsum from the source. Most remote backends support
a limited set of hashsums keeping them in a metadata field attached to object. The "local" backend is special.
When chunker requests **any** type of hashsum via `src.Hash(<type>)` API, rclone performs live checksumming
right on the local file. If the file is large, this incurs a visible pre-transfer delay, which can explain issues reported
in https://github.com/rclone/rclone/issues/4021.
In fact, chunker does not need the whole checksum to guarantee correctness of the transfer and depends on the
checks performed by underlying remote on the separate chunks. Moreover, chunker …
=> chunker: avoid prehashing of large local files, hash in-transit (fixes #4021)

backend/ftp/ftp.go
Minor wording change to help for explicit and implicit FTPS flags. More consistent between flags. Add 's' to request because only one 'client' mentioned. Line 62 simplify.
I had been intending to go through the ftp backend docs page but am leaving that until after accepted pr is published at point release.
consistency and clarity
No
- [ x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
=> Update ftp.go - ftps flag docs

fs/operations/operations.go
If the object is moved rclone prints name of the destination object into the info log in verbose mode .
fixes: #4658
=> operations: move verbosly log name of the destination object

fstest/testserver/init.d/TestSeafile
We must run Seafile server in docker environment before Seafile integration tests can be run. We don't have to sleep for 60 seconds to have everything ready. We can assume everything is ready when Seafile webserver returns status code 200. Seafile Dockerfile (https://github.com/haiwen/seafile-docker/blob/master/image/seafile/Dockerfile) runs scripts/start.py where is defined that before init_seafile_server() we always wait for mysql wait_for_mysql() (https://github.com/haiwen/seafile-docker/blob/master/scripts/start.py) so We know database has been created and integration tests are ready to run.
No
=> testserver: speed up initialize of TestSeafile for Seafile integration tests

fs/operations/operations.go
Fix the copy and move operations that broke in 127f0fc when copying directly to a remote without a specific destination.
#4747
=> fs: Fix copy & move operations directly to remote

cmd/mountlib/mount.go
I find the documentation of the mount command a bit confusing, especially regarding windows specific things. So I tried to make it a bit clearer, and also some minor cleanup here and there.
For example the usage of term "network shares" in the section [Mount as a network drive](https://rclone.org/commands/rclone_mount/#mount-as-a-network-drive), I think is used both as a generic term for remote filesystems and for the "shared folder" functionality in windows. For examle it states: "many people prefer network shares to be mounted as normal system drives, this might cause some issues" and then "if you experience any of those, consider mounting rclone remotes as network shares".
*The terms "fixed drive" and "remote (network) drive", as used in …
=> mount: docs: make note about mounting as network drive in windows less confusing

docs/content/commands/rclone_mount.md
I updated the links to VFS File caching section that were not working. Changed "#file-caching" to "#vfs-file-caching".
I didn't find any issues about that.
=> Fixed links to VFS FIle Caching section

docs/content/ftp.md, docs/content/overview.md
Limitation consistent with `rclone about remote:` and mentioned in the rclone forum
Reflect issue from forum in rclone documentation
https://forum.rclone.org/t/rclone-union-mfs-most-free-space-not-working-for-ftp/20346
- [ x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
=> mfs limitation ftp remote

fs/parseduration_test.go
Update parseduration tests to use UTC time for comparison since the strings to be parsed do not have any timezone information
No
=> parseduration: fixed tests to use UTC time

fs/accounting/stats.go
startedTransfers is accessed by multiple threads, and it wasn't
protected by the mutex call in Transferred() func.
Fixes #4799
No
=> accounting: remove data race in Transferred() (#4799)

cmd/cmount/mount_brew.go, cmd/cmount/mount_unsupported.go, cmd/mount/mount_unsupported.go
cmount: Add optional `brew` tag to throw an error when using mount in the binaries installed via Homebrew - Fixes #4775
Add optional `brew` tag to throw an error when using mount in the binaries installed via Homebrew
#4775
=> cmount: Add optional `brew` tag

backend/s3/s3.go
s3: Added error code 429, indicating too many requests, as a retriable error
s3: Added error code 429, indicating too many requests, as a retriable error
N/A
=> s3: Added error code 429 as a retriable error

MAINTAINERS.md, README.md, backend/compress/compress.go, bin/make_manual.py, docs/content/docs.md, docs/layouts/chrome/navbar.html
Hopefully fixes #4797.
I didn't add anything to `docs/overview.md` as the other overlay remotes aren't listed there either. I also decided to add myself as the maintainer for the compress backend.
=> compress: doc and test fixups

backend/azureblob/azureblob.go, backend/azureblob/azureblob_test.go, go.mod, go.sum
Hi! 👋  first-timer here.
This PR uses `adal` and creates its own token refresher instead of using `oauthutil`, because I could not figure out how to integrate Azure Storage's pipeline with a custom oauth client. It was relatively straightforward, however, to use `newPipeline` with a new service principal credential type.
Ref:
- https://github.com/rclone/rclone/issues/3230
- https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app?tabs=dotnet#well-known-values-for-authentication-with-azure-ad
- https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization#available-authentication-types-and-methods
- https://gist.github.com/ItalyPaleAle/ec6498bfa81a96f9ca27a2da6f60a770
azure: add support for service principals
Before: users can only connect to Azure blob …
=> azure: add support for service principals - fixes #3230

backend/googlecloudstorage/googlecloudstorage.go, docs/content/googlecloudstorage.md
Allow storage class to be set individually on objects, overriding the default storage class setting at the bucket level.
There is a valid reason to want this kind of feature; it allows for cost optimization. See also [this comment on stackoverflow](https://stackoverflow.com/a/62105146). With the proposed changes to the code, it would now be possible to set a default storage class that is cost-effective in operations cost, but still have individual objects stored using the cheaper COLDLINE or ARCHIVE storage classes.
See issue #3043
=> gcs: Storage class object header support - fixes #3043

fs/fshttp/http.go
Multi-line HTTP header debug messages can overlap in output/logs, making them difficult to parse. This fix wraps multi-line HTTP debug messages in a mutex to prevent the overlap.
Not to my knowledge.
- [X ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [N/A ] I have added tests for all changes in this PR if appropriate.
- [N/A ] I have added documentation for the changes if appropriate.
- [X ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
=> fshttp: prevent overlap of HTTP headers in logs

cmd/dbhashsum/dbhashsum.go, cmd/hashsum/hashsum.go, cmd/md5sum/md5sum.go, cmd/progress.go, cmd/sha1sum/sha1sum.go, docs/content/commands/rclone_hashsum.md, docs/content/commands/rclone_md5sum.md, docs/content/commands/rclone_sha1sum.md, fs/operations/operations.go, fs/operations/operations_test.go
Add a download flag to hashsum and related commands to force rclone to download and hash files locally
This commit modifies the operations.hashSum function by adding an alternate code path.  This code path is triggered by passing downloadFlag = True.  When activated, rclone will download files from the remote and hash them locally.  downloadFlag = False preserves the existing behavior of using the remote to retrieve the hash.
This commit modifies HashLister to support the new hashSum method as well as consolidating the roles of HashLister, HashListerBase64, Md5sum, and Sha1sum.
The unit test operations_test.TestHashSums is modified to support this change and test the download functionality.
The command functions hashsum, md5sum, sha1sum, and dbhashsum are modified to support this change. …
=> operations: Add a download flag to hashsum and related commands to force rclone to download and hash files locally

docs/content/crypt.md
Fix invalid option name in the example code block of `crypt config` in crypt.md.
no
=> docs: fix invalid option name in example of crypt config

backend/swift/swift.go
Add code to delete object what in openstack swift backend. In case object is static large object, the code missing delete segments.
=> swift: fix deletion of static large object

backend/azureblob/azureblob.go, backend/azureblob/imds.go, backend/azureblob/imds_test.go, lib/pacer/pacer_test.go, lib/pacer/pacers.go
Adds a configuration option (`azureblob_use_msi`) to use a managed service identity when authenticating to Azure from an Azure virtual machine, which eliminates the need to manage explicit credentials. This method acquires a bearer token (valid for 24 hours) from the [Azure Instance Metadata Service](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http), and if a temporary error is returned will retry using the exponential backoff method specified in the linked documentation.
The token is not presently persisted to disk; if users are expected to invoke the `rclone` binary a large number of times in a short period that functionality would be desirable. The present implementation also does not check token …
=> azureblob: add managed identity support

cmd/cmount/mount.go, cmd/cmount/mountpoint_other.go, cmd/cmount/mountpoint_windows.go, cmd/mount/mount.go, cmd/mountlib/mount.go, lib/file/driveletter_other.go, lib/file/driveletter_windows.go, vfs/help.go, vfs/vfsflags/vfsflags_unix.go, vfs/vfstest/fs.go
On Windows one can mount in one of two modes: fixed disk drive or network drive. Currently the default is disk drive, and to mount as network drive you must pass argument --VolumePrefix into libfuse/WinFsp via the --fuse-flag option in rclone mount:
```
rclone mount remote: X: --fuse-flag --VolumePrefix=\server\share
```
This syntax is a bit convoluted, especially if the network mode is more or less the preferred method (too little user experience myself, but sounds it from what I read it). My intention is to make it a bit more elegant and user-friendly - make the choice between fixed vs network drive mounting more "native" to rclone, and possibly also making the network mode the default.
See also discussion in #4714.
**Part 1: Network mode option**
The existing `--volname` option, …
=> mount: more user friendly mounting as network drive on windows

cmd/ncdu/ncdu.go
Implemented empty folder flag for ncdu browser interface. If there is empty folder in the list the flag e is prepended before size. If there is no empty folder this flag is ommited. It has the same behaviour as original ncdu browser. (https://dev.yorhel.nl/ncdu/man)
Fixes issue: #3369.
=> ncdu: add empty folder flag into ncdu browser

fs/log/log.go, fs/log/systemd.go, fs/log/systemd_unix.go
The thing was to not make auto systemd detection if `--log-file` was set.
So this proposal only auto detect systemd integration if `--log-file` is not set.
And if both `--log-file` and `--log-systemd` are set then systemd integration is disabled since logs will not go into stdout/err.
I also moved `--log-systemd` from config flags to log flags to keep log flags together.
There is also the case when `--syslog` and `--log-systemd` are both set. In this PR since the `startSysLog` function is called after `enableSystemdLog` function and they both override the fs.LogPrint variable, the systemd integration will always be disabled.
https://github.com/rclone/rclone/pull/4609
=> systemd log integration

backend/b2/b2.go
The current authentication scheme works without creating a public download endpoint for a private bucket as in the B2 official blog. On the contrary, if the existing authorization header gets duplicated in the Cloudflare Workers script, one might receive 401 Unauthorized errors. This commit add some info about this behavior to the doc to help smooth the setup process.
As discussed in the [forum](https://forum.rclone.org/t/backblaze-b2-with-cloudflare-worker-conflicts-on-the-authorization/21353).
I'm not sure where I should squash the commit. I'll make changes if required.
=> b2: docs for download_url with private buckets

backend/onedrive/api/types.go, backend/onedrive/onedrive.go
This PR fixes https://github.com/rclone/rclone/issues/4342 by:
* Disabling server-side copy if either drive isn't OneDrive Personal
* Falling back to normal copy if server-side copy fails
=> onedrive: fall back to normal copy if server-side copy unavailable

backend/onedrive/onedrive.go
This is a partial fix for #4590. It works for OneDrive for Business only and allows existing files to be replaced by server-side copy operations.
=> onedrive: (business only) workaround to replace existing file on server-side copy

backend/onedrive/onedrive.go, docs/content/onedrive.md
This fixes #4700, fixes #4184, fixes #2920.
=> onedrive: remove % and # from the set of encoded characters

backend/onedrive/onedrive.go
Allow for addressing site by SPO URL, e.g. `https://contoso.sharepoint.com/sites/mysite` or `mysite`
1. By URL is more friendly than finding the site-id
2. For too many SPO sites, like more than 200, using URL is the only way
This method is using [server-relative URL](https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http#access-a-site-by-server-relative-url), thus also adding a "low-level" support for it.
ref: https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http#access-a-site-by-server-relative-url
ref2: https://docs.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0#sharepoint-api-root-resources
=> onedrive: Support addressing site by server-relative URL

backend/chunker/chunker.go
Before this patch chunker required that there is at least one
data chunk to start checking for a composite object.
Now if chunker finds at least one potential temporary or control
chunk, it marks found files as a suspected composite object.
When later rclone tries a concrete operation on the object,
it performs postponed metadata read and decides: is this a native
composite object, incompatible metadata or just garbage.
This change is factored from #4902
It was discussed in #4902, https://github.com/rclone/rclone/pull/4675#issuecomment-739639666 and https://github.com/rclone/rclone/pull/4675#issuecomment-740206801
=> chunker: improve detection of incompatible metadata

backend/jottacloud/jottacloud.go, docs/content/jottacloud.md
This PR adds support for Telia Cloud in the jottacloud backend. It adds another authentication option during setup, so where users previously chose between standard and legacy authentication, a third option to use Telia Cloud authentication has been added. The rest is handled via a standard oauth2 flow.
#4924
=> jottacloud: Add support for Telia Cloud

docs/content/onedrive.md
Onedrive max file size limit has been updated to 250GB since 13 Jan 2021
No.
=> docs: Update Onedrive max file size limit

docs/content/filtering.md
This is an attempt at rewriting the rclone filter documentation page as much by way of an RFC as PR.
I have drawn largely from what appears to be the strong original structure of the page; existing text, and forum comment.
The term flag is used throughout rather than differentiating `--` options with more complex arguments. That diverges from some standard practice but is consistent with messages in the rclone binary and `go` documentation.
The term directory not folder is used throughout.
I tried referring to objects more broadly rather than files and it just did not seem to work. Apart from a note at the top the explanations refer entirely to paths, directories and files. My justification is that bucket store users understand the concept of files. Not all users of directory aware …
=> Changes to rclone filtering documentation (recovered) #4767

backend/b2/b2.go
Fix a crash when a b2 remote is accessed.
Did not find any discussions about this specific crash.
Here is a copy of the crash that should be fixed (at least I get a list of the files instead of a crash).
```
$ rclone ls -vv b2:bucket/dir
2021/01/25 18:08:43 DEBUG : rclone: Version "v1.53.4" starting with parameters ["rclone" "ls" "-vv" …
```
=> b2: fixed possible crash when accessing Backblaze b2 remote

docs/content/commands/rclone_serve_ftp.md, docs/content/commands/rclone_serve_sftp.md
Fix a broken link (missing /bin in path).
No
=> docs: fix broken link in serve sftp/ftp

fs/parseduration.go, fs/parseduration_test.go
To fix a broken unit test.
TestParseDuration relied on an elapsed time calculation which
would vary based on the system local time. Fix the test by not relying
on the system time location. Also make the test more deterministic
by injecting time in tests rather than using system time.
#4529
=> Fix test failure in different local time zones

fs/rc/webgui/plugins.go
=> plugins: Move plugins cache path initialization to initPluginsOrError.

backend/drive/drive.go
Add default system office icons to .desktop Google Drive URL link files.
List of icons from [Icon Spec](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#mimetypes) since the .desktop spec is also from FreeDesktop the icons should always exist.
I couldn't find it.
=> drive: add system office icons to .desktop google drive links

.github/workflows/build.yml
The rclone ci/cd is currently using go `1.16-beta1`
which was phased out from github today
and replaced by go `1.16-rc1` resulting in build errors like
```
Run actions/setup-go@v2
Setup go  version spec 1.16.0-beta1
Attempting to download 1.16.0-beta1...
matching 1.16.0-beta1...
Not found in manifest.  Falling back to download directly from Go
Error: Unable to find Go version '1.16.0-beta1' for platform linux and architecture x64.
```
This PR fixes that.
No
=> build: replace go 1.16-beta1 by 1.16-rc1

fstest/testserver/init.d/rclone-serve.bash
I am working on a PR with a test which runs `rclone serve webdav` in docker.
I noticed that every run of `test_all` leaves empty files named `1` in the source directory.
Guilty is the line  `kill -0 &>1 > /dev/null` in [rclone-serve.bash](https://github.com/rclone/rclone/commit/45e8bea8d099db946faa2af7342f8152c5c12f96#diff-55f3aaae89c3c87d29ada578033b27f1b731e5390cf5577cc6571fb9e1a983bfR20) introduced by commit https://github.com/rclone/rclone/commit/45e8bea8d099db946faa2af7342f8152c5c12f96
While it was enough to replace `&>1 >/dev/null` by `2>&1 >/dev/null` or by `&>/dev/null`, I went further.
I applied _shellcheck_ on `rclone-serve.bash` and fixed all warnings, mostly by quoting bare shell variables. Integration test continue to work for me. The result is here.
No
=> fstest: apply shellcheck on rclone-serve.bash

docs/content/azureblob.md
Improve documentation. Azure Blob access tier values are case-sensitive, though this is not indicated anywhere in the documentation. Adding examples with proper casing.
Not that I can see.
=> Add examples for Azure Blob Access Tier to documentation

go.mod, go.sum
#4970 was caused by an issue in my sgzip library. A mistake in the compression code caused seeking to break after the first block. I've fixed this now and improved the tests so this can't happen again. Sadly this does not fix seeking in files compressed with the previous version, the metadata is just plain wrong for them. So these will need to be reuploaded for multistream downloads to work.
=> Update sgzip - fixes #4970

cmd/cmount/mountpoint_windows.go, cmd/mountlib/mount.go
Fixed bug in mount on Windows introduced in 1.54.0, where mounting on root directory is no longer possible.
Edit: Added a second commit that also fixes a less critical issue regarding relative paths when mounting to directory. More details below. Let me know if you want me to move this to a separate MR or something..
- Removed incorrect error return for mountpath that represents a directry at root level on existing drive.
- Also removed the distinction between `X:` and `X:\`: The latter will be converted to `X:` and used for drive letter mount, previously it would be reported as error "parent of mountpoint directory does not exist". Any other paths logically representing the same, such as `X:\some\folder\..\..` will still be reported as error: "parent of mountpoint directory does not …
=> mount: allow mounting to root directory on windows

backend/local/local.go, docs/content/local.md
Some virtual filesystems (such as Google Drive File Stream) may
incorrectly set the actual file size equal to the preallocated space,
causing checksum and file size checks to fail.
This flag can be used to disable preallocation for local backends of
this type.
Adds a flag that allows disabling preallocation, which allows a Google Drive File Stream virtual filesystem to be used as a local backend target.  Without this change, any files copied by rclone to a GDFS filesystem result in checksum and file size errors.
It was mentioned in https://github.com/rclone/rclone/issues/3207 , but there are other GDFS issues intermingled there as well.  This change only addresses the preallocate issue.
=> local: Add flag --no-preallocate - #3207

Dockerfile
partially addreses rclone/rclone#4831
creates a rclone user, but does not set rclone user as default
=> feat: add rclone user

go.mod, go.sum, lib/encoder/filename/decode.go, lib/encoder/filename/decode_test.go, lib/encoder/filename/encode.go, lib/encoder/filename/fuzz.go, lib/encoder/filename/gentable.go, lib/encoder/filename/init.go, lib/encoder/filename/scsu.go, lib/encoder/filename/scsu_go113.go
Instead of only adding SCSU to #4866, add it as an existing table.
Allow direct SCSU and add a reasonable table as well.
Add byte interfaces that doesn't base64 encode the URL as well with `EncodeBytes` and `DecodeBytes`.
Fuzz tested and decode tests added.
Only in issue #4866
File used for generating the table: [sample.txt.gz](https://github.com/rclone/rclone/files/5765636/sample.txt.gz) using `go run gentable.go -index=sample.txt -scsu -all`
=> Add SCSU as tables

fs/cache/cache.go, fs/config.go, fs/config/configflags/configflags.go, fs/operations/operations.go, fs/operations/operations_test.go, fs/sync/sync.go, fs/sync/sync_test.go
**EDIT**
I use rclone for creating regular backup, for example:
- create assets-2020-06-01 for the first time (full backup);
- then create assets-2020-08-01 as second backup (with --compare-dest I can do increment backup).
I want to create assets-2020-09-01 increment backup, but found that I can't specify multiple --compare-dest path in rclone.
This PR fixes that.
**EDIT** No
=> feat: add multiple paths support to `--compare-dest` and `--copy-dest`

.github/workflows/build.yml
The rclone ci/cd is currently using go `1.16-rc1`
which was phased out from github today
and replaced by go `1.16.x` resulting in build errors like
```
Error: Unable to find Go version '1.16.0-rc1' for platform linux and architecture x64.
```
This PR fixes that.
No
Refer to golang downloads at https://golang.org/dl/
=> build: replace go 1.16-rc1 by 1.16.x

fstest/testserver/init.d/docker.bash, fstest/testserver/testserver.go
Currently if container under test has multiple IP addresses,
the `docker_ip` function from `docker.sh` will return a gibberish.
This patch makes it return the first address found.
Additionally, I apply shellcheck on `docker.sh`.
No
=> docker.bash: work correctly with multi-ip containers

backend/crypt/crypt.go, backend/crypt/crypt_test.go
As discussed in #1077, I'm adding an option to leave the data unencrypted. This permits a user to have only the filenames encrypted if they so choose.
#1077
https://forum.rclone.org/t/is-it-possible-to-encrpyt-filenames-only/902
=> crypt: add option to not encrypt data #1077

backend/s3/s3.go
Fix shared_credentials_file s3 auth option
https://forum.rclone.org/t/shared-credentials-file-config-option-not-works/22318/6
=> Fix shared_credentials_file s3 auth

vfs/help.go, vfs/vfs.go, vfs/vfscommon/options.go, vfs/vfsflags/vfsflags.go
I needed a report on Used space for S3 remotes, whereas none is given as it is now.
Implementation relies on pre-existing code for `rclone size`, i.e. the `Count` operation, which ultimately relies on the `walk.ListR(…)` function.
I chose to follow the trail down to `ListR` instead of using `Count`, because:
* Although the software architecture of rclone is not very clear to me at this stage, for some reason I did not feel comfortable having `vfs.go` rely on `operations.go`;
* `Count` also counts the number of objects, which is useless to me;
* `Count` does not have any guarantee regarding parallelism for its function, and thus uses costly atomic integers, whereas `ListR` explicitly guarantees, that “fn will not be called concurrently whereas the directory listing will proceed …
=> vfs: --vfs-used-is-size uses `rclone size` to give used space (full recursive listing)

docs/content/filtering.md
An attempt to make directory filter rules marginally less confusing inspired by reading 
https://github.com/rclone/rclone/blob/master/docs/content/commands/rclone_hashsum.md
I think the filter documentation is in step with that commit. The prior position when, with `ListR`, --exclude /foo/ did not have an equivalent effect to to --exclude /foo/** was not properly explained in the rewrite I did.
The three bullet points identifying when directory recursion optimisation is applied to the listing trouble me. The two prior attempts at putting the code logic into words were as bad. Maybe something closer go code logic should be incorporated?
No.
=> Docs: directory filter rules

backend/zoho/zoho.go
Fix setting custom client id's for zoho as discussed in #5029
=> zoho: fix custom client id's

docs/content/docs.md
M**B**ytes and M**b**ytes are used interchangeably at docs.md.
Lowercase is preferably used  for bits(`Mbits`).
* Use uppercase consistently across all docs.md. Intances of `Mbytes` replaced to `MBytes`
=> docs: uppercase for MBytes

backend/dropbox/dropbox.go, go.mod, go.sum
This implements polling support for the Dropbox backend. The Dropbox SDK dependency had to be updated due to an auth issue, which was fixed on Jan 12 2021. A secondary internal Dropbox service was created to handle unauthorized SDK requests, as is necessary when using the ListFolderLongpoll function/endpoint. The config variable was renamed to cfg to avoid potential conflicts with the imported config package.
https://github.com/rclone/rclone/issues/2949
=> dropbox: add polling support - fixes #2949

backend/fichier/api.go, backend/fichier/fichier.go, backend/fichier/object.go, backend/fichier/structs.go, docs/content/overview.md
1fichier has supported copy and move for a while now and I finally had a few minutes to implement it in rclone. Makes the 1fichier backend so much more usable :)
=> fichier: implement copy & move

CONTRIBUTING.md
`-u` in particular because following `git push` in the doc do not specify which remote to push to.
=> CONTRIBUTING.md: recommend to push feature branch with -u + minor tuneups

backend/cache/cache_internal_test.go, backend/chunker/chunker_internal_test.go
Today the `golangci-lint` tool began reporting errors in two places of rclone test code.
Apparently its `ineffectual assignment` check has become more stringent.
This quick fix addresses it and restores commits health on the master branch.
It's recommended to back-port it on the stable branch as it affects health of all future commits.
No. It's an early bird.
=> address stringent ineffectual assignment check in golangci-lint

go.mod, go.sum
Recently jlaffaye/ftp accepted patches that fix two outstanding issues:
- https://github.com/jlaffaye/ftp/pull/219 (trim trailing whitespace from the list commands)
- https://github.com/jlaffaye/ftp/pull/221 (Fix STOR of zero length files to ProFTPd with TLS)
This PR makes rclone's `go.mod` pull the patched library
#1850 (FTP: 500 'LIST ': command not understood)
https://forum.rclone.org/t/rclone-ftps-explicit-rclone-touch-empty-files-proftpd-unable-to-build-data-connection-operation-not-permitted/22522/15
=> ftp: update dependency jlaffaye/ftp

backend/fichier/fichier.go, docs/content/overview.md
Files always have a public link on 1fichier. Let's make them accessible via rclone.
=> fichier: implement public link

docs/content/docs.md, docs/content/local.md
Document that path syntax `\\?\Volume{b75e2c83-0000-0000-0000-602f00000000}\some\path` is not supported.
https://github.com/rclone/rclone/issues/3864
=> mount: docs: add note about volume path syntax on windows

cmd/rcd/rcd.go
rcd: Added systemd notification during the 'rclone rcd' command call. This also fixes #5073 
Signed-off-by: Naveen Honest Raj <naveendurai19@gmail.com>
When running `rclone rcd` command, there is no systemd notification sent. There are cases where the end user depends on such systemd notification and this enhancement I worked on in this PR will come in handy.
Yes, it is discussed here. (https://github.com/rclone/rclone/issues/5073#issuecomment-788024498)
=> rcd: Added systemd notification during the 'rclone rcd' command call.

.gitignore, cmd/all/all.go, cmd/cmd.go, cmd/selfupdate/help.go, cmd/selfupdate/selfupdate.go, cmd/selfupdate/selfupdate_test.go, cmd/selfupdate/verify.go, cmd/selfupdate/writable_unix.go, cmd/selfupdate/writable_unsupported.go, cmd/selfupdate/writable_windows.go, cmd/version/version.go
Implements `rclone self-update` command (ticket #548)
Flags and features:
- verifies sha256 hash of release archive
- verifies access to replaced file and directory, optionally asks user to run with elevated privileges (in Scotland - elavated)
- mimics permission bits of original file, if any
- `--output` - downloads new executable to a custom location
- `--beta` - self-explanatory
- `--check` - just an alias of `rclone version --check`
Yet unimplemented, left for future patches:
- `--stable` (`--backports`)
- `--version`
**UPDATE 2021-03-08**:
Will be implemented:
- `--stable` (mutually exclusive with `--beta`)
- `--version VER` (micro-release autocompletion if stable)
- `--package deb` (linux only)
- `--package rpm` (linux only)
- PGP signature validation (pending public key)
Yes:
- …
=> cmd: rclone selfupdate

backend/hdfs/object.go
The permissions for when a directory is created in HDFS was incorrect. It was an invalid decimal to octal conversion that was converting `755` to `1363` or `d-wxrw--wt`. This means that the user creating the directory couldn't read it on a second pass, therefore breaking `rclone copy` when creating directories.
This varied from how `rclone mkdir` functioned for HDFS, which was `0755`, the proper octal.
=> HDFS: Fix permissions for when directory is created

cmd/dedupe/dedupe.go, cmd/sync/sync.go
Update the docs regarding sync and dedupe commands with info regarding handling duplicate objects.  See ticket #4429.
=> docs: Updated sync and dedupe command docs #4429

backend/local/local.go
Avoid the following irrelevant question when configuring local remote on linux:
```
Disable UNC (long path names) conversion on Windows
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
1 / Disables long file names
\ "true"
nounc> 
```
Simple quick-fix: Just hiding it under the advanced config section when not on windows. Could have removed it from the list instead, but was thinking about generated docs etc..
No
=> local: make nounc advanced option except on windows

backend/azureblob/azureblob.go
Add option to set public access level of a container with a new flag `azureblob-public-access`. Mostly useful when to create container using command `mkdir` however it should be useful for `sync` or `copy` command. Flag must require value and should be either `blob` or `container` or `''`(empty).
Flag is useful when the container is being created as part of the command. 
Discussed the actual option required for this change along with other important points.
https://forum.rclone.org/t/azure-container-and-set-public-access-to-read-only/22363
https://github.com/rclone/rclone/issues/5045
=> azureblob: Add container public access level support. Fixes #5045

docs/content/docs.md
Document how to bypass loading of config file, relevant when keeping encrypted configuration file but executing commands not relying on configuration (such as genautocomplete) - because one may want to avoid the password prompt.
Fixes #5125
Depending on https://github.com/rclone/rclone/commit/bb0b6432ae5d74a741815a8cc1f0cf2d46e3dddb
=> docs: describe how to bypass loading of config file

docs/content/filtering.md
Document that pattern list format are not able to imply directory filter if the pattern list contains `/` or `**`. This was detected with copy operation and `--create-empty-src-dirs`, because then empty directories that did not match the filter were created. See the linked issue for details.
I suppose the case with `--create-empty-src-dirs` will be the same for any cases where "directory recursion optimisation" (as described in filtering docs) is not active, such as with `--fast-list` (have not been able to test it, yet). Therefore decided to make this as a paragraph separate from the description of the pattern list limitation.
Difficult, as always, to formulate the text, so appreciate *any* feedback (@edwardxml?)
Fixes #5112
=> docs: add note about limitation with pattern-list to filtering docs

fs/accounting/accounting.go
Ensure there is no divide by zero in speed reported by rc core/stats command.
Issue #5132 reports getting +Inf values, have not been able to test that case - just did an attempt at a "blindfolded quick fix" (is that a thing?)...
#5132
=> rc: avoid +Inf value for speed in core/stats

cmd/copyurl/copyurl.go, fs/operations/operations.go
Added new option:
> -p, --print-filename   Print the resulting name from --auto-filename
Example usage (PowerShell):
```
$x = .\rclone.exe copyurl https://www.youtube.com/watch?v=SzuZnh91U8E C:\Temp -a -p
PS > Write-Host "Downloaded file: ${x}"
Downloaded file: watch
```
https://github.com/rclone/rclone/issues/5094
=> copyurl: add option to print resulting auto-filename

cmd/selfupdate/help.go, cmd/selfupdate/selfupdate.go
This PR polishes the selfupdate command a little to aid users with reverting updates:
- the success message will mention a previous version number
- the help synopsis will include instructions on reverting the update and help to identify betas or development builds
- the help will tell more about beta updates and include a fallback for old rclone version
These details are useful for those who submit new github requests or posts on forum
but will be gathered in the single place.
Additionally: removed a dead piece of code, probably a refactoring leftover.
Yes, in #5096
I cannot include this fix right there because #5096 is a backlog PR and has a special lifecycle.
=> selfupdate: add instructions on reverting the update

cmd/cmd.go, cmd/cmount/arch.go, cmd/cmount/mount.go, cmd/selfupdate/help.go, cmd/selfupdate/selfupdate.go, cmd/version/version.go, fs/rc/internal.go, lib/buildinfo/cgo.go, lib/buildinfo/cmount.go, lib/buildinfo/tags.go
Use build tags in the `version` and `selfupdate` commands
Knowing build tags would be useful.
For example, only `cmount` builds support passing custom libfuse flags.
(See #3545 for an example why it matters).
As stated in https://github.com/golang/go/issues/7007#issuecomment-66089610, golang does not and will not provide any runtime API for finding build tags on the fly:
> Build tags are for building. I do not want them to be exposed in the runtime.
> if you need to know ... you can write different files with different build tags and different initialized ... variables
This PR uses this very technique to initialize an internal array of build tags.
The technique has a limitation that every detectable tag must be known in advance.
Currently only the `cmount` and `cgo` tags are supported. …
=> Use build tags in the `version` and `selfupdate` commands

docs/content/install.sh
Before this change if the download script was run on MacOS ARM, it attempted
to request the "current-osx-arm.zip" archive and unzip it, resulting in
error `cannot find zipfile directory` because we don't provide such a build.
**EDIT: for v1.55 we will support osx/arm**
This patch makes `install.sh`:
- ~~request amd64 build on MacOS arm~~
- always run curl with flag `-f` (aka `--fail`) so it fails explicitly on any `40x`/`50x` http status
Additionally it fixes few cosmetic _shellcheck_ warnings:
- replaces obsolete backticks with `$(...)`
- quotes bare variables
Fixes #5145
=> install.sh: fail on download errors

backend/crypt/crypt.go
When copying files into non-crypt remotes:
DEBUG : zip/kdbx.20210314.185330.7z: MD5 = 814e77ae9ae377c3201193c858da46d7 OK
INFO  : zip/kdbx.20210314.185330.7z: Copied (new)
But when copying file into crypt remote, there is no info about integrity check even if it is performed (unless it fails and it will be reported as part of "corrupted on transfer" error):
INFO : 01.kdbx: Copied (new)
This change adds the same debug log for crypt remotes.
https://forum.rclone.org/t/local-copy-operation-fails-with-handle-is-invalid/22880/12
=> crypt: log hash ok on upload

backend/swift/swift.go, backend/swift/swift_test.go, go.mod
The max size object in swift is 5G, if we copy object what greater than 5G (large object) the operation will fail.
I run test local.
=> swift: support copying large objects

.github/workflows/build.yml
Replace xgo (unmaintained) with a standalone NDK-based compiler toolchain for Android builds. Everything works, but I obviously couldn't test the upload step. Binaries for all 4 architectures are written to a `build` folder.
Request: https://github.com/x0b/rcx/issues/123
Related (xgo iOS): https://github.com/rclone/rclone/issues/5124
=> build: replace xgo with NDK for Android builds

docs/content/docs.md
Add some documentation of the configuration file format, without going too much into details.
Seems rclone currently uses https://github.com/unknwon/goconfig library for handling the configuration file, but not mentioning this in the doc, as I guess it may change over time - and that one is actually documented as being sort of deprecated ("under bug fix only mode, which means no more features will be added").
I am linking to https://rclone.org/overview/ for list of backend "types", but it does not show the internal "codename" for the backends that must be put as value of the `type` key in config file. Command `rclone help backends` seems to show these type values. Perhaps the overview page should have listed them as well?
Added an example, used mega because I found that supported plain …
=> docs: add short description of configuration file format

.github/ISSUE_TEMPLATE/Bug.md, .github/ISSUE_TEMPLATE/Feature.md
This PR partially implements #5074 
It adds useful recommendations from the forum ticket templates to the github issue templates
and recommends users to run `rclone selfupdate`.
It blocks on #5080 but should be merged separately
#5080 can be merged after successful review but will be released with rclone 1.55
This PR will affect rclone github templates immediately after merge on master.
Let's review this now but merge together with 1.55 release
#5074
https://forum.rclone.org/t/previously-working-rclone-backup-now-giving-error-unknown-command-rcat-for-rclone/22507/14
=> backlog: ticket templates should recommend to update rclone

cmd/cmount/mount.go, cmd/selfupdate/help.go, cmd/selfupdate/selfupdate.go, lib/buildinfo/cmount.go, lib/buildinfo/tags.go
Before this patch selfupdate detected ANY build with `cmount` tag as a build
having libFUSE capabilities. However, only dynamic builds really have it.
The official Linux builds are static and have the `cmount `tag as of the time
of this writing. This results in inability to update official Linux binaries.
This patch fixes that.
The build can be fixed independently by #5199
- https://forum.rclone.org/t/rclone-1-55-release/23217/11
- #5190
- #5199
=> selfupdate: dont detect FUSE if build is static

backend/onedrive/onedrive.go, docs/content/flags.md, docs/content/onedrive.md
Add `--onedrive-list-chunk` option similar to existing options for azureblob, drive, and s3.
Suggested as a workaround for a OneDrive pagination bug, see https://forum.rclone.org/t/unexpected-duplicates-on-onedrive-with-0s-in-filename/23164/8
=> onedrive: add list_chunk option

cmd/cmd.go, cmd/selfupdate/help.go, cmd/selfupdate/noselfupdate.go, cmd/selfupdate/selfupdate.go, cmd/selfupdate/selfupdate_test.go, cmd/selfupdate/verify.go, cmd/selfupdate/writable_unix.go, cmd/selfupdate/writable_unsupported.go, cmd/selfupdate/writable_windows.go, cmd/selfupdate_disabled.go, cmd/selfupdate_enabled.go, lib/buildinfo/tags.go
Allow downstream packagind to build rclone without selfupdate command
Fixes #5187
@ncw Please review
=> build: add build tag noselfupdate

cmd/cmd.go, cmd/version/version.go, go.mod, go.sum, lib/buildinfo/osversion.go, lib/buildinfo/osversion_openbsd.go, lib/buildinfo/osversion_windows.go
Make `rclone version`  print runtime OS version, kernel and architecture bitness.
The implementation is based on https://github.com/shirou/gopsutil (namely [gopsutil/host](https://github.com/shirou/gopsutil/tree/master/host))
The detection on OpenBSD is limited to OS name because base package fails to build on it.
Related to https://github.com/rclone/rclone/issues/5121#issuecomment-803612181
References:
- https://unix.stackexchange.com/questions/92199/how-can-i-reliably-get-the-operating-systems-name
- https://www.reddit.com/r/golang/comments/f6wrtv/how_to_determine_32_or_64_bit_on_host_machine/
- https://stackoverflow.com/questions/7011071/detect-32-bit-or-64-bit-of-windows
- https://github.com/golang/go/issues/24843
- https://github.com/zcalusic/sysinfo#sample-output
- …
=> cmd/version: print os/version, kernel and bitness

fs/sync/sync.go
Suppress spurious error message when performing `rclone sync` with `--files-from` and `--no-traverse` flags.
The `rclone sync` command logs an error if the `--no-traverse` flag is specified, as traversing destination directories is necessary to compare them with the source for syncing.
However, when the `--files-from` flag is present, the `--no-traverse` flag modifies the file listing behavior to query each specified path individually rather than traversing the directory listing (see the [docs](https://rclone.org/filtering/#files-from-read-list-of-source-file-names)).  This functionality works as expected with the sync operation, so this PR adds a check to suppress the error message in this case.
No
=> sync: don't warn about --no-traverse when --files-from is set

docs/content/install.sh
Having a progress seems to break some automated scripts and there isn't a way to pass some flags to these curl requests to disable them. I don't know if showing the progress is any helpful to be honest.
=> Silence the progress output with curl requests

backend/b2/api/types.go, backend/b2/api/types_test.go, backend/crypt/cipher.go, backend/crypt/cipher_test.go, docs/content/b2.md, lib/version/version.go, lib/version/version_test.go
Continues #4024.
Fixes #1627 
I refactored the versioning code into its own package `lib/version`, including the filename versioning tests in `backend/b2`.
While `rclone --b2-versions ls TestCryptB2:` would now correctly list all file versions in plaintext, `rclone --b2-versions copy TestCryptB2:testfile-v(...).txt tmp/` wouldn't work. That turned out to be due to `encryptFileName` not dealing with the versioned filenames, yet `decryptFileName` _does_, so I've also fixed that.
I'd also like to add some integration tests to check the interaction between `crypt` and `b2` - particularly for the `copy` issue I ran across - but I'm not sure how to go about it.
Yes, in the previous PR.
* As noted above, an integration test between `crypt` and `b2` with `--b2-versions` is probably something we …
=> crypt: support timestamped filenames from --b2-versions (attempt 2)

cmd/version/version_test.go, docs/content/docs.md, fs/config/config.go, fs/config/config_test.go, fs/config/configfile/configfile.go, fs/config/configfile/configfile_test.go, fs/config/configflags/configflags.go, fs/config/crypt_test.go, fs/config/ui.go, fs/config/ui_test.go, fs/fs.go, fstest/fstest.go, lib/file/file_other.go, lib/file/file_test.go, lib/file/file_windows.go
Solving issues and making it more user friendly with memory-only config.
Ref the following cases described in the issue:
Case 1. --config /dev/null on Linux
Case 2. --config NUL on Windows
Case 3. --config ""
Case 4. --config /notfound
All should be handled by this PR, ~~but I have only tested on Windows~~ tested on Windows 10 and arch linux in WSL.
Fixes #5222
=> config: fix issues with memory-only config file paths

cmd/rcat/rcat.go
This allows preallocating space at remote end with `RcatSize`.
To allow streaming uploads even when remote backend doesn't support them.
`RcatSize` should fall back to regular `Rcat` if `--size` flag is missing.
See #4403
=> Add --size flag for rclone rcat - closes #4403

cmd/config/config.go, docs/content/docs.md, fs/config/config.go
Use %AppData% as primary default for configuration file on Windows, which is more in line with Windows standards, while existing default of using home directory is more Unix standards - though that made rclone more consistent accross different OS.
Main changes from existing (something for release notes?)
- Any existing configuration file should be picked up in exactly the same way as before, so no changes for **existing** configs.
- Well.. with one possible exception: If there happens to be a file `%APPDATA%/rclone/rclone.conf`, it would not have been picked up automatically before, but could be used by explicitely referring to it with `$RCLONE_CONFIG` or `--config`, but will now be picked up automatically. That *could* lead to surprises on upgrade, but not very likely.
- Windows:
- …
=> Change default location of config file to %AppData% on Windows

backend/drive/drive.go
Fixes #5104
rClone opens Browser when Service Account Credential is given which is Not Required. The same doesn't happens when Service Account File is given. This PR is supposed to fix this.
https://github.com/rclone/rclone/issues/5104
=> Don't Open Browser when Google Drive Service Account Credentials Specified

docs/content/docs.md, fs/config/config.go
Two things:
1. Run tests with memory-only configuration on all platforms (dependent on the next).
2. Continuation of  https://github.com/rclone/rclone/pull/5223:
Case 1. --config /dev/null on Linux
Case 2. --config NUL on Windows
Case 3. --config ""
Case 4. --config notfound
Extending case 4 to any path where `notfound` is the file/base name.
Previously used RCLONE_CONFIG="/notfound", assuming it was path to a non-existant file. Then at some point in time (quite recently) we started detecting this, as well as empty string and os null device, as an indicator of memory-only config. On most platforms the tests therefore automatically started to run with memory-only config. But on Windows the tests are run from Git (MSYS2) bash, which convertes the "/" into its internal filesystem root being …
=> Platform independent memory-only config option to be used in build

go.mod, go.sum
Release notes: https://github.com/storj/uplink/releases/tag/v1.4.6
Follow up PRs will take advantage of the new bucket error and negative
offset support to remove roundtrips.
Upgrade backend/tardigrade to use the latest uplink library release.
No
=> backend/tardigrade: Upgrade to uplink v1.4.6

backend/onedrive/onedrive.go
OneDrive randomly returns the error message: "InvalidAuthenticationToken: Unable to initialize RPS". These unexpected errors typically caused the entire rclone command to fail.
This work around recognizes these errors and marks them for a low level retry, that mostly succeeds. This will make rclone commands complete without being noticeable affected.
Fixes: #5270
This change contains the simple work around proposed in this post:
https://forum.rclone.org/t/invalidauthenticationtoken-unable-to-initalize-rps/23595/35
This is the approval and comments from @ncw:
https://forum.rclone.org/t/invalidauthenticationtoken-unable-to-initalize-rps/23595/37
I decided to go with Nicks recommendation to reduce testing and potential negative side effects.
During test I discovered that the rclone pacer …
=> onedrive: Work around for random "Unable to initialize RPS" errors

docs/content/sftp.md
- added clarification to default remote path if no path is specified 
- added examples for mounting a remote path (other than the default home directory) to a local folder.
Provide clarification to the SFTP default remote path with examples. 
https://forum.rclone.org/t/change-sftp-remote-source-from-the-default-home-dir/23796/3
- [NA] I have added tests for all changes in this PR if appropriate.
=> SFTP remote: Documentation updates/additions

backend/b2/b2.go
Including the bucket name as part of the `fileNamePrefix` passed to
`b2_get_download_authorization` results in a link valid for objects that
have the bucket name as part of the object path; e.g.,
rclone link :b2:some-bucket/some-file
would result in a public link valid for the object
`some-bucket/some-file` in the `some-bucket` bucket (in rclone-remote
parlance, `:b2:some-bucket/some-bucket/some-file`). This will almost
certainly result in a broken link.
The B2 docs don't explicitly specify this behavior, but the example
given for `fileNamePrefix` provides some clarification.
See https://www.backblaze.com/b2/docs/b2_get_download_authorization.html.
- - -
I'm not sure if it's worth it to try to add tests for this? B2 will happily mint a token for files/directories that don't exist. The …
=> b2: don't include the bucket name in public link file prefixes

go.sum, vfs/vfscache/cache.go
The vfs-cache-max-size parameter is probably confusing to many users.
The cache cleaner checks cache size periodically at the --vfs-cache-poll-interval
(default 60 seconds) interval and remove cache items in the following order.
(1) cache items that are not in use and with age > vfs-cache-max-age
(2) if the cache space used at this time still is larger than
vfs-cache-max-size, the cleaner continues to remove cache items that are
not in use.
The cache cleaning process does not remove cache items that are currently in use.
If the total space consumed by in-use cache items exceeds vfs-cache-max-size, the
periodical cache cleaner thread does not do anything further and leaves the in-use
cache items alone with a total space larger than vfs-cache-max-size.
A cache reset feature was introduced …
=> vfs: Add cache reset for --vfs-cache-max-size handling at cache poll interval

.github/ISSUE_TEMPLATE/Bug.md, .github/ISSUE_TEMPLATE/Feature.md
https://forum.rclone.org/t/issue-templates-sthap-1-me-tooing/23667  
@jtagcat:
Nextcloud has this at the top of issue templates:
_code snippet, see git diff_
Thoughts on adding something similar to the rclone repo? I'd add a link to the forum, maybe even https://forum.rclone.org/t/how-to-ask-for-assistance/8379.
While going through issues, there's just so many 'looks long and seems to have something important', but is yet an another '+1 me too'. (example: [#1778: iCloud](https://github.com/rclone/rclone/issues/1778))
There might be possible pushback, discouraging contributions? Thoughts?
@ncw:
That is an interesting idea. I wish GitHub could let us put a bit of boiler plate on each issue, but this seems like a good idea.
Please open a new issue on Github and we can discuss this further. …
=> GitHub issue templates: Add GH Etiquette.
