rclone/rclone

- backend/alias/alias_internal_test.go
- backend/http/http_internal_test.go
- cmd/cmd.go
- cmd/mountlib/rc_test.go
- cmd/serve/dlna/dlna_test.go
- cmd/serve/http/http_test.go
- cmd/serve/restic/restic_appendonly_test.go
- docs/content/docs.md
- fs/config/config.go
- fs/config/config_test.go
- fs/config/configfile/configfile.go
- fs/config/crypt_test.go
- fs/config/default_storage.go
- fs/config/rc.go
- fs/config/rc_test.go
- fs/config/ui.go
- fs/config/ui_test.go
- fs/rc/rcserver/rcserver_test.go
- fstest/fstest.go
- fstest/test_all/test_all.go
Restructuring of config code in v1.55 resulted in config file being loaded early at process startup. If configuration file is encrypted this means user will need to supply the password, even when running commands that does not use config. This also lead to an issue where mount with --deamon failed to decrypt the config file when it had to prompt user for passord.
This PR removes the forced config file loading at startup, and instead waits until first actual config access.
Fixes #5236
Fixes #5228
> Delay load config file

- backend/tardigrade/object.go
v1.4.6 of uplink allows us to do a negative offset from the end of the
file. This removes a round trip when requesting the last N bytes of a
file.
Previous to v1.4.6 of uplink it wasn't possible to do a negative offset
on download. This meant that to fulfill the semantics of http range
headers it was necessary to first fetch the size of the object via a
stat call and compute absolute offset and length.
No, but it was mentioned in a previous PR
> backend/tardigrade: use negative offset

- backend/s3/s3.go
Could you add --s3-no-head-object to reduce HTTP Head?
The results are as follows:
################################
Before add --s3-no-head-object
################################
$ ./go/bin/rclone --checksum --dump headers --log-level DEBUG --no-traverse copy --files-from in.txt aws:noaa-goes17 dst
2021/03/18 14:38:31 DEBUG : Using config file from "/home/xxxx/.config/rclone/rclone.conf"
2021/03/18 14:38:31 DEBUG : rclone: Version "v1.55.0-beta.5314.e59acd16c" starting with parameters ["./go/bin/rclone" "--checksum" "--dump" "headers" "--log-level" "DEBUG" "--no-traverse" "copy" "--files-from" "in.txt" "aws:noaa-goes17" "dst"]
2021/03/18 14:38:31 DEBUG : Creating backend with remote "aws:noaa-goes17"
2021/03/18 14:38:31 DEBUG : You have specified to dump information. Please be noted that …
> add --s3-no-head-object

- .github/workflows/build.yml
Add `gomobile bind` to build.yml to know when it breaks. I added it directly to the existing android build process since an independent failure is deemed unlikely.
https://github.com/x0b/rcx/issues/123#issuecomment-828410059
> build: add gomobile android build

- lib/http/http.go
Adds a default handler to the base router for the default server to serve a generic 404 message is no route is found
This should have been included in https://github.com/rclone/rclone/pull/3842
> lib/http: add default 404 handler

- cmd/serve/http/http.go
- cmd/serve/http/http_test.go
This better uses available middleware to set headers, and removes an extraneous parameter from the Bind method
This should have been included in https://github.com/rclone/rclone/pull/3842
> http: clean up Bind to better use middleware

- fs/fs.go
Avoid sometimes creating additional subdirectory in cache folder. It may happen as a result of "detected overridden config - adding ... suffix to name", where the suffix is base64 encoded MD5, when the encoded suffix happens to include the `/` character - which is in the base64 "alphabet".
Edit: Is backwards compatibility an issue here? That there may be an existing cache directory `cache`\\`path`\\`{Db`\\`Y9}` with content, and after this change rclone will not find the existing cache and begin with a new cache directory `cache`\\`path`\\`{Db_Y9}`? And then, any changes still in the old cache that has not been written back to remote will be lost? 🤔 
Fixes #5316
> vfs: avoid unnecessary subdir in cache path

- cmd/selfupdate/selfupdate.go
selfupdate by mistake replaced `darwin` by `osx` in GOARCH instead of GOOS.
https://forum.rclone.org/t/rclone-1-55-1-release/23802/11
> selfupdate: fix archive name on macos

- docs/content/dropbox.md
Instructions in https://rclone.org/dropbox/#get-your-own-dropbox-app-id are a little incomplete. I had to guess a few extra details to make things work. This patch adds missing parts.
Fixes #5242
> dropbox: improve the "own App IP" instructions

- docs/content/flags.md
- fs/config/configflags/configflags.go
A few days ago (on forum), I explain how difficult it was to the --disable syntax : https://forum.rclone.org/t/looking-for-advice-for-remote-crypt-chunker/23924
So, today I'm submitting a small change.
I hope that next time I will be looking for that syntax, it will be easier to me (an maybe others)
Is it acceptable to replace ? : Disable a comma separated list of features.  Use help to see a list.
by : Disable a comma separated list of features.  Use --disable help to see a list.
no
> some improvement about documentation related to --disable

- docs/content/docs.md
- docs/content/local.md
1. Mention that network/unc paths are supported in local filesystem on windows
2. Mention that additional leading path separators are ignored
- This is the case from the linked forum thread.
- Are we sure that this is how it is working? From my testing and code inspection it seems to be true.
- Are we confident this is how we want it to be, so that it is correct to document it - which avoids uncertainty as in the forum question? Or is it more of a coincidence that should be left undocumented?
3. Fixes a wrong link
https://forum.rclone.org/t/leading-slash-in-source-dest-paths/24005
> Docs: Add notes about leading path separators and unc paths

- docs/content/docs.md
- fs/fshttp/dialer.go
These patches fix #5293 and add more graceful error handling since failing to set socket options shouldn't cause the process to exit. 
I've tested:
* macOS IPv4: ✅ working
* macOS IPv6: ✅ working
* openSUSE Tumbleweed IPv4: ✅ working
* openSUSE Tumbleweed IPv6: ✅ working
* Windows 10 20H2 IPv4:  ⚠️ fails due to https://github.com/golang/go/issues/42728; handled by custom error handler (prints `WARNING: dialer: setting DSCP on Windows/IPv4 fails silently; see https://github.com/golang/go/issues/42728` and continues)
* Windows 10 20H2 IPv6:  ⚠️ fails due to lack of support in net/ipv6; handled by standard error handler (prints `WARNING: dialer: failed to set DSCP socket options: not implemented on windows/amd64` and continues)
If Go adds proper support for Windows, DSCP will work properly …
> dialer: fix DSCP support and improve error handling

- backend/googlecloudstorage/googlecloudstorage.go
- docs/content/googlecloudstorage.md
- GCS: Write `goog-reserved-file-mtime` in addition to `mtime`.
- GCS: Fallback to `goog-reserved-file-mtime` if `mtime` doesn't exist.
- Docs: Mention the new modification time behavior and the modify window issue.
- Docs: Unify markdown format.
Fixes #5331.
> 🕰️ GCS: Compatible with gsutil's mtime metadata

- docs/content/filtering.md
Fix backtick formatting in filtering docs.
Fixes #5387
> docs: fix code section formatting in filtering docs

- docs/content/yandex.md
https://forum.rclone.org/t/yandex-documentation/24445/2
Potential incorrect documentation for Yandex token
https://forum.rclone.org/t/yandex-documentation/24445/2
> docs: incorrect token type in Yandex docs

- cmd/config/config.go
There is an extra swift in example commands.
```
rclone config update myremote swift env_auth true
```
The correct command should be:
```
rclone config update myremote env_auth true
```
https://forum.rclone.org/t/example-command-error-in-help-info-and-manpage/24729
> docs: fix incorrect syntax in config update example

- README.md
- backend/cache/cache.go
- docs/content/_index.md
- docs/content/cache.md
- docs/content/docs.md
- docs/layouts/chrome/navbar.html
Deprecate cache backend
https://forum.rclone.org/t/mounting-crypt-remotes-with-vfs-cache/24443/7
> deprecate cache backend

- backend/onedrive/onedrive.go
Make `rclone link onedrive` return direct download link.
Share link of file will be converted to direct link, but folder won't, since Onedrive manages folder download in a different and intransparent way.
https://github.com/rclone/rclone/issues/5381
> onedrive: Make link return direct download link

- backend/azureblob/azureblob.go
- docs/content/azureblob.md
Fix the documentation for Azure AD for RBAC command
The correct command is `az ad sp create-for-rbac` according to
https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az_ad_sp_create_for_rbac
The command from documentation doesn't work
I've updated update the link in the doc to point to az command documentation, in addition to original link that lead to generic role based access description.
not that I'm aware of
> Fix typo in Azure AD instructions

- CONTRIBUTING.md
To make it easier to contribute without prior knowledge of Git, GitHub and Go.
The change includes improved/added steps to:
* Install Git with basic setup
* Use both SSH and HTTPS for the git origin
* Install Go and verify the GOPATH
* Update the forked master
* Find a popular editor for Go
The addition of an HTTPS link for the git origin was discussed and approved in this forum thread:
https://forum.rclone.org/t/contributing-guide-git-github-com-https-github-com/23855
The rest is based on my own experiences while preparing [my first contribution](https://github.com/rclone/rclone/pull/5273) on a Windows computer. 
I have done my best to research the changes and make the guide applicable for all platforms, protocols and preferences.
I am however still a beginner, so a careful review by …
> Docs: Contributing eased for beginners in Go, Git and GitHub

- fs/accounting/stats.go
- fs/accounting/stats_groups.go
- go.sum
Maintain and display a rolling average speed.
Use two rings to store the last few measurements of `duration` and `bytes`. Use the difference between the most recent and the oldest measurement to calculate transfer speed. The speed then needs to be updated before displayed.
#3909 (sort of)
> accounting: use rolling average for speed display - fixes #3909

- fs/operations/operations.go
- fs/sync/sync_test.go
The [`--compare-dest`](https://rclone.org/docs/#compare-dest-dir) flag specifies a remote directory to compare files to when syncing.
Currently, if a file in the compare-dest is identical to a source file (same size and checksum), but its timestamp differs, the timestamp of the compare-dest file will be updated.
The documentation does not mention this behavior and it is likely an unintended side effect of how the checking is implemented.  I believe the compare-dest should be treated as an immutable reference point and should not be modified by the operation.
No, as far as I know
> fs/operations: Don't update timestamps of files in --compare-dest

- backend/local/local.go
- fs/sync/sync.go
- fs/sync/sync_test.go
**UPDATED on 2021-06-12**
This change fixes the bug described below:
if a file is removed while the local backend List() runs, the call will flag an accounting error.
The bug manifests itself if local backend is the Sync target due to intrinsic concurrency.
The odds to hit this bug depend on --checkers and --transfers.
Chunker over local backend is affected even more because updating a composite object
with a smaller size content translates into removing chunks on the underlying file system
and involves a number of List() calls.
This patch will make `List` **skip the file**.
Unit test:
```
go test ./fs/sync -remote TestChunkerChunk3bLocal: -run TestSyncConcurrent
```
or run the full rclone integration test with `-backends local,chunker`.
No
> local: skip files removed concurrently with `List`

- cmd/cmd.go
- lib/atexit/atexit.go
- lib/atexit/atexit_other.go
- lib/atexit/atexit_test.go
- lib/atexit/atexit_unix.go
- lib/exitcode/exitcode.go
With this change fatal signals handled by the `atexit` package causea non-zero exit code. On Unix systems it's `128 + int(signum)` while
on other systems, such as Windows, it's always 2 ("error not otherwise
categorised").
Resolves #5437.
> Terminate with non-zero status after receiving signal

- backend/jottacloud/jottacloud.go
- docs/content/jottacloud.md
This is another one of those annoying workaround. Currently, Jottacloud doesn't provide a way to delete old versions of files via the API and no such option exists in the web ui either. This means the only way to remove old versions from the file is to completely delete. Since old versions obviously count against your quota, they can get rather annoying. This pr adds an option to avoid any server side versioning by deleting old files before uploading a new version.
> jottacloud: add no versions option

- fs/operations/operations.go
Correct the logging level in `rmdirs` so that `-v` shows what happens
Yes https://forum.rclone.org/t/rmdirs-v-doesnt-show-anything-vv-works-as-expected/25422/3
---
This is my first time working in Golang and certainly doing anything on rclone! Thanks for the support and making it so easy to learn
> fs/operations: add rmdirs -v output - fixes #5464

- backend/onedrive/onedrive.go
- docs/content/onedrive.md
> onedrive: handle HTTP 400 better in PublicLink()

- cmd/mountlib/mount.go
- cmd/serve/docker/volume.go
After mountlib refactoring by #5415 `mount --daemon` waits for mount thread instead of returning immediately.
This patch fixes it.
~~Additionally it moves remaining helper functions from `mount.go` to `utils.go` (I forgot to move them in #5415 !).~~
**UPDATE 2021-07-26** I removed refactoring from this PR leaving only the fix.
Fixes #5472
> mountlib: restore daemon mode after #5415

- backend/s3/s3.go
- docs/content/s3.md
* Wasabi starts to provide AP Northeast (Tokyo) endpoint for all customers, so add it to the list
- ref: https://wasabi.com/press-releases/wasabi-expands-global-presence-announces-apac-headquarters-in-japan/
no.
> s3: add Wasabi's AP-Northeast endpoint info

- docs/content/docs.md
- fs/operations/operations.go
- fs/operations/operations_test.go
- fs/sync/sync.go
- fs/sync/sync_test.go
Proposed solution for issue #5463 
Yes. See issue referenced.
> fs: move with --ignore-existing will not delete skipped files - #5463

- cmd/selfupdate/selfupdate.go
migrate `fmt.Print` to log methods in fs pkg.
Fixes #5505
> selfupdate: fix --quiet option, not quite quiet

- cmd/serve/docker/docker_test.go
- cmd/serve/docker/driver.go
CI/CD unit test for serve/docker sporadically fails with ~5% probability on macOS/amd64.
Looking through rclone CI/CD logs I could not find occurrences of the failure on other OS flavors under test.
Couple examples:
- https://github.com/rclone/rclone/runs/3214015105?check_suite_focus=true#step:11:176
- https://github.com/rclone/rclone/runs/3294451359?check_suite_focus=true#step:11:183
Failure always happens during writing a small json state file with `ioutil.WriteFile` at [cmd/serve/docker/driver.go](https://github.com/rclone/rclone/blob/v1.56.0/cmd/serve/docker/driver.go#L326) right after [unmounting a volume](https://github.com/rclone/rclone/blob/v1.56.0/cmd/serve/docker/driver.go#L285),  in the test it unmounts a local directory located right below the state file.
**DISCLAIMER:** _I …
> serve/docker: fix racy tests on macOS/windows

- cmd/mountlib/mount.go
Our support personnel regularly remind our users that `--fast-list does nothing on a mount`.
This patch automates the job.
- https://forum.rclone.org/t/infinite-loop-with-plex-media-server-and-data-on-rclone/25683/10
- https://forum.rclone.org/t/dropped-my-cache-remote-and-now-seeing-visual-artifacts/25922/2
- https://forum.rclone.org/t/vfs-cache-issues-with-union-chunker-google-drive/25848/2
- https://forum.rclone.org/t/does-multi-thread-streams-work-for-dropbox-business/25795/4
- many more...
@animosity22 @ncw 
Please review
> cmd/mount: remind that --fast-list does nothing on a mount

- fs/accounting/stats_groups.go
- fs/accounting/stats_groups_test.go
The `speed` in core/stats does not change the speed which is returned by the global stats using sum.
No.
> rc: fix speed does not update in core/stats

- backend/pcloud/pcloud.go
- docs/content/commands/rclone_hashsum.md
- docs/content/pcloud.md
- fs/hash/hash.go
- fs/hash/hash_test.go
Add SHA-256 hashing support for pcloud backend. Fixes #5496
Yes
> pcloud: add sha256 support - fixes #5496

- cmd/copy/copy.go
- cmd/copyto/copyto.go
- cmd/moveto/moveto.go
- cmd/sync/sync.go
Switched from talking about "unchanged" files to "identical" files.
I found out the hard way that the rclone copy will overwrite newer files.
Looking at posts in the rclone forum, this is a common experience.
The docs for copy have referred to "unchanged" files.
This is ambiguous because it intuitively introduces a sense
of chronology, but chronology is irrelevant.
Rclone only "cares" about difference, not change.
> Removed ambiguity from copy command docs

- backend/googlephotos/googlephotos.go
This fixes the problem of album names containing \n which caused problems as local directories could not be created during sync.
Yes: https://forum.rclone.org/t/google-photos-sync-failed-for-multi-lined-album-names/25589
Please note the diff is intentionally redacted - it show cases the two primary differences in album names due to this change.
```
$ rclone_new lsf -Fp --csv gphotos:shared-album &> rclone_new_2021-08-15_shared-album_lsf.txt
$ rclone lsf -Fp --csv gphotos:shared-album &> rclone_2021-08-15_shared-album_lsf.txt
$ diff rclone_2021-08-15_shared-album_lsf.txt rclone_new_2021-08-15_shared-album_lsf.txt
88c88
< "2018 US Trip - San Francisco, Seattle/"
---
> "2018 US Trip - San Francisco, Seattle／Kirkland, New York/"
164,166c164
< "California Citrus State Historic Park
< 
<  29 …
```
> googlephotos: Use encoder for album names

- cmd/mountlib/help.go
- vfs/help.go
Merging duplicate documentation of VFS chunked reading. It was previously described as part of the common VFS documentation, in the VFS Performance chapter, and in addition there was a separate chapter "chunked reading" in the mount specific documentation. Tried to merge them into a separate chapter in the common VFS documentation: VFS Chunked Reading.
Not sure about the meaning behind the following sentence previously in VFS Performance, if there is a detail relevant to keep:
> This is advantageous because some cloud providers account for reads being all the data requested, not all the data delivered.
I left that out, in favor of the following sentence from the chunked reading doc:
>  This can reduce the used download quota for some remotes by requesting only chunks from the remote that …
> docs/vfs: Merge duplicate chunked reading documentation from mount docs.

- cmd/config/config.go
Minor improvement in docs for rclone config subcommands, removing backticks that are intended for markdown code elements in strings that are inserted into larger code blocks.
Result is, instead of:
```
rclone config delete `name` [flags]
```
Then this:
```
rclone config delete name [flags]
```
Also removed `name` code element in short string of rclone config delete, as it makes it stick out in the docs at https://rclone.org/commands/, none of the other have this.
> docs/config: remove use of backticks around words within a larger code block

- backend/azureblob/azureblob.go
- backend/s3/s3.go
Could you add --azureblob-no-head-object to reduce HTTP Head?
The results are as follows:
################################
Before add --azureblob-no-head-object
################################
2021/07/26 14:23:29 DEBUG : rclone: Version "v1.56.0-beta.5589.da36ce08e" starting with parameters ["rclone" "--no-traverse" "--checksum" "--dump" "headers" "--log-level" "DEBUG" "copy" "azure:noyoritest/a.txt" "c.txt"]
2021/07/26 14:23:29 DEBUG : Creating backend with remote "azure:noyoritest/a.txt"
2021/07/26 14:23:29 DEBUG : Using config file from "/home/noyori/.config/rclone/rclone.conf"
2021/07/26 14:23:29 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go …
> add --azureblob-no-head-object

- cmd/mount2/mount_test.go
This PR contains a single commit spun off #5550 
Really skip `mount2` ~~and cmount~~ test on single-CPU runners to prevent sporadic lockups.
Discussed in https://github.com/rclone/rclone/pull/5550#issuecomment-903684789 and [commit 6a9ef27b comments](https://github.com/rclone/rclone/commit/6a9ef27b0919fed17c3865a395afec97a6ed53d3#commitcomment-55235890)
cc @ncw
> test: skip mount2 test on CI runners

- docs/content/drive.md
If the status of the added APP in Google APIs & Services is "testing", then "Authorization Error" will occur when `rclone config` try to get access to it. So the step I added may be necessary to get a gdrive client ID.
Solutions for "Authorization Error" can be found in [this issue in googleapis](https://github.com/googleapis/google-api-php-client/issues/2001)
> docs: add a step for drive.md

- backend/seafile/seafile.go
- backend/seafile/seafile_internal_test.go
rclone 1.56 introduced a defect where you cannot create a new seafile remote with 2FA activated:
- this PR should fix the defect
- added unit tests for the seafile 2fa state machine
https://forum.rclone.org/t/config-seafile-with-2fa-password-cant-be-blank/26541
> seafile: fix 2fa state machine

- go.mod
- go.sum
Updates the `golang.org/x/sys` module to prevent a panic on startup when built with Go 1.17
Fixes: #5611
Yes: https://github.com/rclone/rclone/issues/5611
> build: update golang.org/x/sys for go1.17 build

- docs/content/authors.md
- docs/content/docs.md
- docs/content/downloads.md
- docs/content/faq.md
- docs/content/install.md
- docs/content/licence.md
Some cleanup in the usage, install and download docs. Mainly related to headers.
Ensure each page starts with a level 1 header (`# header`), and then only use level 2 or higher for sections below. E.g. existing install doc uses header level 1 for "Autostart", above [Autostart on Windows](https://rclone.org/install/#autostart-on-windows), but then this does not get a anchor on hover-over and also is not listed in the contents box to the right. And existing downloads doc have several level 1 headers but only one level 2 header, and then only the level 2 header "Script download and install" is shown in the contents box to the right.
The [usage](https://rclone.org/docs/) docs started with level 2 header called "Configure". So for consistency I introduced a level 1 header with the page name, …
> docs: cleanup header levels

- backend/ftp/ftp.go
Our users complained many times that rclone FTP client manifests random problems with completing a file upload.
As my investigations have shown, the bug triggers because [jlaffaye/ftp does not properly nudge](https://github.com/jlaffaye/ftp/blob/5d41901190670f202a4aafb39c81d72e2e42bd8d/ftp.go#L721) the [fshttp anti-hanging timer](https://github.com/rclone/rclone/blob/v1.56.0/fs/fshttp/dialer.go#L85) on command channel after a file upload. I have a [working fix](https://github.com/ivandeex/rclone/releases) for [jlaffaye/ftp](https://github.com/ivandeex/ftp/commit/08390f8cbaa60e98bb1687989752e31feaf8b416) and [backend/ftp](https://github.com/ivandeex/rclone/commit/f70e98d1595feadf6d52ade6e9565aec3ed77aa3) which I will submit **later**.
This pull request solves a second-stage bug triggered …
> ftp: fix deadlock after failed update when concurrency=1

- cmdtest/environment_test.go
- docs/content/docs.md
- fs/config.go
Note:
- Beta build here: https://beta.rclone.org/branch/remote-name-env/
Valid remote names according to (existing) [docs](https://rclone.org/docs/#valid-remote-names):
> Remote names may only contain 0-9, A-Z ,a-z ,_ , - and space.
> Remote names may not start with -.
I will add the following:
- May not start with space (any leading/trailing spaces will be trimmed off automatically).
- Case sensitive.
That is the general case. But creating remotes using environment variables (RCLONE_CONFIG_..._TYPE) currently has additional, undocumented, limitations:
1) May not contain -.
2) Case insensitive.
This PR aims at removing the additional limitation 1) imposed on remote names from environment variables: Make rclone properly support hypen in remote names when creating remote using environment …
> config: support hyphen in remote name from environment variable

- backend/local/local.go
- cmd/copy/copy.go
- cmd/gendocs/gendocs.go
- cmd/selfupdate/selfupdate_test.go
- cmd/serve/docker/docker_test.go
- cmd/serve/docker/driver.go
- cmd/serve/docker/serve.go
- cmd/serve/docker/unix.go
- cmd/serve/docker/volume.go
- cmd/serve/sftp/server.go
- cmd/test/makefiles/makefiles.go
- fs/config/config.go
- fs/config/configfile/configfile.go
- fs/rc/webgui/webgui.go
- fstest/run.go
- fstest/test_all/report.go
- lib/file/mkdir_other.go
- lib/file/mkdir_windows.go
- lib/file/mkdir_windows_test.go
- vfs/test_vfs/test_vfs.go
- vfs/vfscache/cache.go
Improve os.MkdirAll on Windows, to avoid it trying to create `\\?` as a directory for a path where the drive letter does not exist. E.g. `\\?\A:\Temp`. Calling os.MkdirAll on such a path results in error message `mkdir \\?: The filename, directory name, or volume label syntax is incorrect.` The improved version will instead report it as ~`mkdir \\?\A:\Temp: The system cannot find the path specified.`~ `mkdir \\?\A:\: The system cannot find the path specified.`
~Edit:~
~Added additional commit with refactoring: Renaming package file (lib/file) to osutil (lib/osutil). Reasons for doing this:~
~- It already did not only contain *file* related functionality, but e.g. functions for driveletter and uncpath handling were also stuffed in there. And now the new MkdirAll does not necessarily have …
> Improve MkdirAll on Windows

- cmd/mountlib/help.go
- docs/content/commands/rclone_mount.md
- fs/config.go
- fs/mount_helper.go
- fs/mount_helper_test.go
- lib/daemonize/daemon_unix.go
This PR will make rclonefs wrappers moot!
The PRedecessor #5593 solve(d) most problems that prevented rclone from running the mount in background i.e. working _like a generic unix mount_ program (`sshfs`, `mount.glusterfs` and others can do it out of the box), namely:
- have the main process prepare for mounting,
- spawn a background process to handle the mount,
- wait a little until the mount success or timeout (kill the background process if mount failed)
- don't block, exit with status code
The last incompatibility left is the way mount arguments are passed.
The core `/bin/mount` program will (in the basic scenario) get the `-t FSTYPE` argument then run the `/sbin/mount.FSTYPE` helper program passing it mount options. Automountd and systemd generally follow the same logic...
But rclone …
> Run rclone as a mount helper program

- docs/content/ftp.md
- fstest/test_all/config.yaml
PR #5589 established recommended encodings to use with major FTP servers: ProFtpd, PureFtpd, VsFtpd.
This PR updates integration tests correspondingly.
I also mention interactive encoding selector in the FTP backend documentation (forgot it earlier).
@ncw 
Please update `encoding` of the FTP test remotes on the integration box as recommended by https://github.com/rclone/rclone/pull/5589#issuecomment-916364725:
```
[TestFTPProftpd]
type = ftp
host = localhost
port = CI_FTP_PORT_PROFTPD
user = rclone
pass = CI_FTP_PASS_OBSCURED
encoding = Asterisk,Ctl,Dot,Slash
[TestFTPPureftpd]
type = ftp
host = localhost
port = CI_FTP_PORT_PUREFTPD
user = rclone
pass = CI_FTP_PASS_OBSCURED
encoding = BackSlash,Ctl,Del,Dot,RightSpace,Slash,SquareBracket
[TestFTPVsftpd]
type = ftp
host = localhost
port = …
```
> ftp: set correct encoding in integration tests with ProFtpd,PureFtpd,VsFtpd

- docs/content/commands/rclone_copy.md
- docs/content/commands/rclone_move.md
Warn that if user tries to copy/move into a file path it will not give the expected results.
https://forum.rclone.org/t/premiumize-cant-move-files/27169/17
> docs: note that destination is always a directory

- librclone/librclone.go
Document that strings are utf8 encoded.
> docs/librclone: document that strings are utf8 encoded

- docs/content/faq.md
- docs/content/local.md
- docs/content/overview.md
Title says it all.
https://forum.rclone.org/t/cannot-correctly-handle-filenames-with-u-ff1a-full-width-colon/26698
> docs: add faq section explaining why rclone changes fullwidth characters in file names

- docs/content/_index.md
- docs/content/swift.md
Oracle cloud storage now rebranded as OCI bucket with new url
No
> url: oracle cloud storage link fix

- docs/content/docs.md
Document the newly introduced --human-readable in more detail, with a section in the `docs.md`.  Too detailed?
Currently (previously) the option is only listed in `flags.md`.
https://github.com/rclone/rclone/pull/5237
> docs: describe the --human-readable option in more detail

- README.md
- docs/content/docs.md
- docs/content/jottacloud.md
Fix mentions of obsolete whitelabel services in docs:
- `Com Hem Cloud` is now `Tele2 Cloud` (the company Com Hem was discontinued as a brand as of April 2021, after being merged into Tele2 in 2018–2019).
- `Get Sky` is now `Telia Sky` (my previous Get Sky account was rebranded to Telia Sky mid 2020, Telia company bought the Get company some time before that so if not all accounts are rebranded I guess they will be soon).
Added list of known whitelabel services to Jottacloud docs:
- Not 100% decided if we should do this, maintain such an unpublished list in rclone docs.
- The reason to include it is that many (most?) users of such services may not know that it is a Jottacloud based service, and that they can use rclone with Jottacloud backend to access it.
- So, I guess my suggestion is …
> docs/jottacloud: update description of whitelabel services

- docs/content/sftp.md
There seem to be some confusion with regards to `pubkey_file` option in sftp. Attempting to set the regular `id_rsa.pub` (or similar) here results in error `public key file is not a certificate file`. Normally the public key should not be configured, as it will be extracted from the private key `id_rsa` (or similar). The `pubkey_file` is only to be used when you have a certificate-signed public key.
Not the easiest topic to write about and get the wording right so please put your 👓 on before reviewing 😆 
https://forum.rclone.org/t/how-to-use-ed25519-key/26919
https://forum.rclone.org/t/ssh-certificate-based-authentication-does-not-work/19222
https://forum.rclone.org/t/sftp-ssh-error-public-key-file-is-not-a-certificate-file/22795
> docs/sftp: more detailed explanation of pubkey file and certificate

- docs/content/drive.md
The application type "other" is not an option anymore.
remove application type "other" from drive.md
no
> docs: remove application type "other" from drive.md

- docs/content/docs.md
- fs/fspath/path.go
- fs/fspath/path_test.go
Add `.` as legal character in remote names. :bomb:
Beta build here:
- https://beta.rclone.org/branch/remote-name-dot/
Note to self:
<sub><sup>- PR from branch on fork</sup></sub>
<sub><sup>  (https://github.com/albertony/rclone/tree/remote_name_dot)</sup></sub>
<sub><sup>- Pushed the branch also to upstream to get beta build, renamed from remote_name_dot to remote-name-dot to be valid in semver</sup></sub>
<sub><sup>  (https://github.com/rclone/rclone/tree/remote-name-dot)</sup></sub>
https://forum.rclone.org/t/problem-with-parsing-of-environment-variables/26528/10
> config: allow dot in remote names

- fs/sync/sync_test.go
The test `ConcurrentTruncate` is not applicable to uptobox which can't upload empty files.
The test was not skipped as intended because the direct error was compared.
This fix will compare error Cause because Sync wraps the error.
- #5734
- #5745 
- https://github.com/rclone/rclone/commit/70297c3aed39c1073a95aa20c67d5a5366af05ef
> sync/test: skip test ConcurrentTruncate on uptobox (take 2)

- backend/ftp/ftp_internal_test.go
On slow machines (e.g. Github CI), especially if GOARCH=386,
the test for cmd/serve/ftp could fail if this value is too small.
Fixes #5783
> backend/ftp: increase testUploadTimeout.maxTime to 10 seconds

- fs/accounting/stats.go
- fs/accounting/stats_groups.go
- fs/accounting/stats_groups_test.go
This fixes the value of `transferQueueSize`, that was not summed up when calculating the sum of the statistics group, resulting in the bug described in #5749 .
Since I don't have familiarity with the code base, I don't know if this change may introduce any side effect.
#5749
> stats: fix missing computation of transferQueueSize

- backend/union/policy/eplus.go
Union generated a `panic` when it had to select the least-used-space backend, because the `lusEntries` function returned `nil`.
To solve it: I initialized the `minUsedSpace` variable with `math.MaxInt64` so that the first backend would trigger the condition `if space < minUsedSpace`, thus `entry` would never be `nil` after the loop.
Not that I could find.
> backend: Fix union eplus policy returned nil

- backend/local/local_internal_test.go
- cmd/touch/touch_test.go
- fs/operations/check_test.go
- fs/operations/dedupe_test.go
- fs/operations/listdirsorted_test.go
- fs/operations/lsjson_test.go
- fs/operations/multithread_test.go
- fs/operations/operations_test.go
- fs/operations/rc_test.go
- fs/sync/rc_test.go
- fs/sync/sync_test.go
- fstest/fstest.go
- fstest/run.go
- vfs/dir_handle_test.go
- vfs/dir_test.go
- vfs/file_test.go
- vfs/read_test.go
- vfs/read_write_test.go
- vfs/vfs_case_test.go
- vfs/vfs_test.go
Previously only the fs being checked on gets passed to `GetModifyWindow()`. However, in most tests, the test files are generated in the local fs and transferred to the remote fs. So the local fs time precision has to be taken into account. On Windows, the local fs has a time precision of 100ns. Checking remote items uploaded from local fs on Windows also requires a modify window of 100ns.
With the changes in this PR applied, integration tests against Google Cloud Storage remotes can now pass on Windows.
As discussed in #5347.
> 🧪 `fstest.Run`: add convenience methods to check local and remote fs with precision

- fs/accounting/transfer.go
Whenever transfer.Account() is called, a new goroutine acc.averageLoop()
is started. This goroutine exits only when the channel acc.exit is closed.
acc.exit is closed when acc.Done() is called, which happens during tr.Done().
However, if tr.Reset is called during a copy low level retry, it replaces
the tr.acc, without calling acc.Done(), which results in the goroutine
mentioned above never exiting.
This commit calls acc.Done() during a tr.Reset()
Also cleaned the authors list to remove multiple emails for this author.
No
> operations: fix goroutine leak in case of copy retry

- fs/rc/rcserver/rcserver.go
I have zero knowledge of Go and of the code structure of rclone so please review carefully, I might have done something wrong.
Makes the error about retrieving latest web GUI version non-fatal; If there is no network rclone will fail regardless.
The API can return 403 if for some reason the rate limit is exceeded and this will make rclone fail, but there is no reason it should.
#5385
> rc: error on web GUI update won't be fatal - fixes #5385

- backend/ftp/ftp.go
- docs/content/ftp.md
This adds a flag `ask_password` to `ftp` backend that prompts the user for password whenever a password is not set.
This closes #5160 and I implemented it to work similar to how `--sftp-ask-password` functions
> ftp: add --ftp-ask-password to prompt for password when needed

- backend/jottacloud/jottacloud.go
- docs/content/jottacloud.md
This PR adds support for Tele2 Cloud former ComHem Cloud in the jottacloud backend. It adds another authentication option during setup, so where users previously chose between standard, legacy authentication and Telia Cloud, a fourth option for Tele2 Cloud authentication has been added. The rest is handled via a standard oauth2 flow.
No.
> jottacloud: Add support for Tele2 Cloud

- backend/hasher/kv.go
- backend/sftp/sftp.go
- cmd/hashsum/hashsum.go
- cmd/md5sum/md5sum.go
- cmd/sha1sum/sha1sum.go
- fs/hash/hash.go
- fs/operations/operations.go
- fs/operations/operations_test.go
Add support for hashing from stdin from rclone hashum/md5sum/sha1sum commands, like standard linux tools:
> With no FILE, or when FILE is -, read standard input.
Output format:
```
2f8f3230bbc42e379a1554ca3419d46d  -
```
Then it can be used as a drop-in replacement for md5sum in existing sftp backend code.
> Hashsum stdin

- backend/hdfs/fs.go
- docs/content/overview.md
The purpose of this change is to add `Move` support to the HDFS back end, so that e.g. `backup-dir` can be used with HDFS remotes.
No.
> Add Move support to the HDFS backend

- backend/sftp/sftp.go
Fix typo in sftp.md (`--ssh-path-override` -> `--sftp-path-override`)
No
> sftp: fix typo

- cmd/serve/sftp/sftp.go
Update documentation for `serve sftp --stdio`
https://forum.rclone.org/t/serve-sftp-upload-fails-illegal-seek-ssh-fx-failure/27238/16
> serve sftp: update docs on --stdio

- backend/crypt/cipher.go
- backend/crypt/cipher_test.go
- backend/crypt/crypt.go
- backend/crypt/crypt_test.go
- docs/content/crypt.md
- go.mod
- go.sum
This PR add support for base64 and base32768 file name encoding for crypt. This resolves https://github.com/rclone/rclone/issues/5801 and relieve the problem of file name length being too long when encrypted.
It is based on the commit 78cab2ba2071dd4c58a34afa22486ad1dec306fc by @Max-Sum . For other changes in https://github.com/Max-Sum/rclone/commits/compress_crypted_filename, I' m worried that some of them might break backward compatibility or involving security issue, and I' m not very familiar in cryptography.
https://forum.rclone.org/t/whats-going-on-with-the-proposal-about-base32768-file-name-encoding/27341
https://forum.rclone.org/t/base32768-to-compress-filename-length/13202
> Support base64 and base32768 file name encoding for crypt.

- fs/fshttp/http.go
- fs/fshttp/prometheus.go
- fs/rc/rcserver/rcserver.go
This patch adds rclone_http_status_code counter vector labeled by
* host,
* method,
* code.
It allows to see HTTP errors, backoffs etc.
The Metrics struct is designed for extensibility.
Adding new metrics is a matter of adding them to Metrics struct and including them in the response handling.
This feature has been discussed in the forum [1].
[1] https://forum.rclone.org/t/prometheus-metrics/14484
It adds HTTP level metrics for debugging purpuses.
https://forum.rclone.org/t/prometheus-metrics/14484
> fshttp: add prometheus metrics for HTTP status code

- backend/yandex/yandex.go
- docs/content/yandex.md
This PR add support for optional permament deletion for Yandex backend
This change will be useful for sync that involves a lot of deletions where without this option you need to delete file twice, first by moving it to trash and then emptying it.
What it does:
Adds option --yandex-hard-delete that will delete files permanently instead of moving them to trash
I don't know.
> yandex: add permanent deletion support

- backend/s3/s3.go
- docs/content/s3.md
Wasabi started to provide **AP Northeast 2 (Osaka)** endpoint as `s3.ap-northeast-2.wasabisys.com`, so add it to the list.
ref:
- [Wasabi Technologies Accelerates APAC Operations and Growth with New Storage Region in Osaka](https://wasabi.com/press-releases/wasabi-technologies-accelerates-apac-operations-and-growth-with-new-storage-region-in-osaka/)
- [What are the service URLs for Wasabi's different storage regions? – Wasabi Knowledge Base](https://wasabi-support.zendesk.com/hc/en-us/articles/360015106031-What-are-the-service-URLs-for-Wasabi-s-different-storage-regions-)
no.
> s3: Add Wasabi AP Northeast 2 endpoint info

- backend/s3/s3.go
The `ContentLength` can be taken directly from the response thus we can avoid extra type conversion steps.
No
> s3: simplify content length processing when download url is set

- lib/rest/rest.go
The MEGA SDK - and, by extension, MEGAcmd - [escapes many HTML entities](https://github.com/meganz/sdk/blob/f1f05bc7d7ec67cb6d03d9e327ec3ee64e82562d/src/utils.cpp#L2125-L2398) in the XML it serves as the WebDAV server. This is not conformant XML, and I have already [submitted a PR](https://github.com/meganz/sdk/pull/2600) to fix this. That having been said, I am submitting a fix for rclone too for a couple of reasons:
- MEGAcmd development seems to be rather slow, and it could be some time until it's updated with the latest SDK - that is, _if_ a fix is merged into the SDK. Moreover, the `mega` backend currently has an issue (#4695) that makes it difficult to use, making this WebDAV functionality useful.
- The MEGA SDK might not be the only WebDAV application exhibiting this behavior. In …
> lib/rest: process HTML entities within XML

- cmd/tree/tree.go
Cleanup. PR #5237 where --human-readable was introduced actually did remove the --human flag from tree command, but then later PR #5538 reintroduced it probably due to an incorrect merge.
Fixes #5868
> tree: remove obsolete --human replaced by global --human-readable

- backend/onedrive/onedrive.go
- docs/content/onedrive.md
In fix of #1770 , a new permission request was added in the OneDrive backend support: `Sites.Read.All`. This is intended to solve the error when using a custom SharePoint site. However, such changes are undocumented. 
On a domain with an excessively strict authorization policy (e.g. my university), the domain disallows users to consent permissions on their own and the `Sites.Read.All` permission is undocumented thus not configured, the extra `Sites.Read.All` scope when requesting an access token will trigger "Application needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it." message.
Therefore, this PR involves a new advanced config entry `disable_site_permission` (default to …
> onedrive: about the Sites.Read.All permission request

- vfs/vfscache/cache.go
When `vfs-cache` is enabled, rclone fails to upload every file with a name that contains special characters (those which are called "runes" in the rclone's codebase). But, if the runes are only in the directory names, it succeeds.
From what I have inspected, it is because rclone copies original files to cache with a fully escaped path (with a quote character in front of each rune), but when it flushes the cache to the actual remote, it looks for the cached file in a partially escaped path (with a quote character only in front of each rune in the directory part of the path).
The correct operation would be fully escaping the cache paths every time they are referred to.
So, I submit the patch in this pull request.
No
> vfs: Fix bug caused by vfs cache special character ("rune") escape ("quoting") inconsistency

- cmd/help.go
This link appears to be broken, so here is another reference to (I think) the same file that provides a good example of coba. We could also do the current commit https://github.com/moby/moby/blob/8312004f41e9500824fa16ae991eeee0083f4771/cli/cobra.go although it might be better to maintain an up to date example.
The link to the example for how to format usage strings appears to be broken  (404).
Nope.
> cmd: fix broken example link in help.go

- librclone/librclone/librclone.go
Currently rpc methods must always specify a valid json string as "input", even for methods which does not take any "arguments" - such as listremotes. This means one must send the string "{}". Trying to send empty string, or null, results in status code 400 and error message: "failed to read input JSON: EOF".
With this change I suggest treating empty string and null same as "{}".
> librclone: allow empty string or null input instead of empty json object

- docs/static/css/custom.css
The "Links" menu looks a little bit "messy", due to icons having different sizes. This adds a custom css to align the icons and the following text labels. Image below shows original first, then the new version:
Similar to #5701, which aligned the "Storage systems" drop down. I chose to use width 18px here for the menu, instead of 20px as with dropdown. Concluded that it looked a tiny bit better with the smaller font size, but anything from 16px and up looks fine to me, and since texts are short saving of horizontal space is not something that needs to be considered, so exact value is not important (to me).
> docs: align menu items when icons have different sizes

- librclone/README.md
Clearify that existing C examples work on Linux/macOS but not on Windows.
Document the challanges faced when building on Windows, with Visual C++.
*PS: I'm working on a private project where I create a "modern" C++ wrapper, using RAII technique to automatically handle loading the library (in run-time) and automatically deallocating the strings returned from the API. With a CMake build system. Cross platform. When (more) done, if there is interest, I could either link to this project from the librclone readme as an external resource or contribute the main source code as a C++ binding/example/whatever... 🤓*
> docs/librclone: document use from C/C++ on Windows

- librclone/README.md
Suggest using build option `-ldflags -s` to create optimized build (omit symbol table and debug information).
With my test, building c-shared on Windows there is a huge different - half the size:
- No optimization: 79 012 KiB
- Optimized (-ldflags -s): 36 917 KiB (53% reduction)
Edit:
- Tested same on Linux, Arch in WSL: Reduction from 74084 KiB to 56319 KiB (24% reduction)
- Adding -w as well, `-ldflags -s -w`, changes nothing.
https://github.com/rclone/rclone/pull/5729#issuecomment-950344364
> docs/librclone: add -ldflags -s to suggested build command

- docs/content/jottacloud.md
Some minor documentation improvements:
- Add note that if configuring any other devices than the default, and Jottacloud built-in, "Jotta" device then upload is not supported - it will throw error `Failed to copy: upload not supported for devices other than Jotta`
- Link to newly created [--temp-dir](https://rclone.org/docs/#temp-dir-dir) documentation, which correctly describes defaults for all operating systems and also mentions the new `rclone config paths` command. Previously only mentioned `TMPDIR`, which is not correct on Windows.
> docs/jottacloud: add note about upload only being supported on jotta device

- fs/config/ui.go
Fixes issue introduced in #5551.
Instead of:
```
Option config_mountpoint.
Please select the mountpoint to use. Normally this will be Archive.
Choose a number from below, or type in an existing string value.
Press Enter for the default (Archive).
1 /
\ (Archive)
2 /
\ (Shared)
3 /
\ (Sync)
```
Then:
```
Option config_mountpoint.
Please select the mountpoint to use. Normally this will be Archive.
Choose a number from below, or type in an existing string value.
Press Enter for the default (Archive).
1 > Archive
2 > Shared
3 > Sync
```
> config: fix display of config choices with empty help text

- lib/buildinfo/osversion_windows.go
Fix output of `rclone version` on Windows 11 (as well as the later versions of Windows 10).
Note: On rclone version 1.57 it reports "Windows 10" even on Windows 11, but this is fixed via updated dependency in latest master.
Sample output before:
```
rclone v1.58.0-beta.5948.c504d9701
- os/version: Microsoft Windows 11 Pro 2009 (64 bit)
- os/kernel: 10.0.22000.434 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.6
- go/linking: dynamic
- go/tags: cmount
```
This PR changes the following line:
```
- os/version: Microsoft Windows 11 Pro 21H2 (64 bit)
```
Implementation details:
Until Windows 10 version 2004 (May 2020) the friendly-name (codename) can be found from registry entry ReleaseID, but after that we must use entry DisplayVersion (ReleaseId is stuck at 2009). I simply …
> version: report correct friendly-name for windows 10/11 versions after 2004

- fs/rc/rcserver/rcserver.go
As per https://github.com/rclone/rclone-webui-react/issues/139, if the user has secured their server using some alternate mechanism, we should allow them to bypass the authentication in rclone by using an existing flag `--rc-no-auth`.
No
https://github.com/rclone/rclone-webui-react/issues/139
> rc: Allow user to disable authentication for web gui

- cmd/serve/http/data/data.go
See:
https://rclone.org/commands/rclone_serve_http/#ssl-tls
The help text for lib/http, ending with a SSL/TLS section, is joined with the help text for data - which does not begin with a header and is therefore included in the unrelated SSL/TLS section.
> docs/serve: move help for template option into separate section

- cmd/help.go
See this section: https://rclone.org/http/#http-no-head
The help description for this flag ends with a list, and when the generic help template appends default list items (Config, Env Var, Type etc) after this help text it will be automatically joined into the same list, which is not the intention. I've rewritten that particular text in another pr, but in general I think it is better to extend the generic help template to include a small "intro" before the list items, to make sure it is separated from the rest of the help text.
~I could not come up with a better name than "Specification"... Can you??~
EDIT:
- Added header "Properties:" as per  [comment](#issuecomment-1021375128").
- Added Provider as an additional entry, if set. 
- s3 docs have a lot of variants of same options with …
> docs: add label before options spec list

- docs/content/drive.md
Making a client-id for Google Drive requires you to add two more fields
besides the already documented "Application name" field. This commit
documents what should be written for those two fields.
Fixes #5967
Yes
> docs/content: describe mandatory fields for drive

- backend/drive/drive_internal_test.go
- backend/union/union_internal_test.go
- backend/union/union_test.go
- cmd/mountlib/rc_test.go
- cmd/serve/restic/restic_appendonly_test.go
- cmd/serve/restic/restic_privaterepos_test.go
- cmdtest/cmdtest_test.go
- fs/rc/webgui/rc_test.go
- lib/file/file_test.go
- lib/file/mkdir_windows_test.go
We can write less code by using the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
No
> test: use `T.TempDir` to create temporary test directory

- librclone/README.md
- librclone/librclone.go
Add support for "mount/*" commands in librclone.
See https://github.com/rclone/rclone/pull/5729 for a previous attempt, and see the comments there for some relevant discussions.
TODO:
- Needs to refactor mount commands as linking to them will pull in cobra and all of its dependencies which should be kept out of librclone.
Fixes #5661
> librclone: add support for mount commands

- docs/layouts/chrome/navbar.html
*This is suggestion, up for discussion (see below).*
This makes it easier for new users to know what commands are available. There have been cases where users did not know about a command because they only looked at the dropdown showing the few most common ones. They would have to go into the "Overview" site to find the rest.
I kept the existing entries as is, added a divider, and then appended all the missing ones. Did not include subcommands (like "config create") that are linked to from parent ("config") docs.
A possible confusion is that the top ones (the existing ones) are ordered according to relevance, and then the ones below the divider are in alphabetic order. This means "copyto" and "copyurl" are next to each other in the lower section, but "rclone copy" is in a different …
> docs: include all commands in online help top menu drop-down

- docs/content/jottacloud.md
Added note in docs related to change in https://github.com/rclone/rclone/pull/5823.
Did not add a mark/note in the table at https://rclone.org/overview/#features, where Jottacloud is "rated R" in the MIME types column, but can add it if you think it deserves it...?
> docs/jottacloud: add note that mime types are not available with --fast-list

- backend/drive/drive.go
- docs/content/drive.md
Added --drive-copy-shortcut-content flag, that enables the user to copy the content of shortcuts when performing server side transfer.
#4604
> drive: added --drive-copy-shortcut-content, fixes #4604

- backend/s3/s3.go
- docs/content/s3.md
- docs/content/tardigrade.md
Make it easier (and documented) to use Storj distributed cloud storage via the s3 interface.
1. Both on the Tardigrade and S3 backend it's clarified what are the pros and cons of using them.
2. Storj added as a special s3 provider (with the predefined URL) 
The discussion started here: https://forum.rclone.org/t/backward-compatibility-rules/26569/12
And later moved to #5616
> s3: add specific provider for Storj Shared gateways

- backend/onedrive/onedrive.go
> onedrive: Do not retry on 400 pathIsTooLong

- fs/config/config_read_password.go
- fs/config/config_read_password_unsupported.go
- go.mod
- lib/terminal/terminal_normal.go
golang.org/x/crypto/ssh/terminal is deprecated in favor of
golang.org/x/term, see https://pkg.go.dev/golang.org/x/crypto/ssh/terminal
The latter also supports ReadPassword on solaris, so enable the
respective functionality in fs/config for solaris as well.
> fs/config, lib/terminal: use golang.org/x/term

- go.mod
- go.sum
Updates golang.org/x/crypto to v0.0.0-20220331220935-ae2d96664a29.
Fixes the issues with connecting to OpenSSH 8.8+ remotes in case the
client uses RSA key pair due to OpenSSH dropping support for SHA1 based
ssh-rsa signature.
https://github.com/rclone/rclone/issues/6076
> sftp: Fix OpenSSH 8.8+ RSA keys incompatibility (#6076)

- backend/jottacloud/jottacloud.go
OpenId standard states: "Multiple scope values MAY be used by creating a space-delimited, case-sensitive list of ASCII scope values." (https://openid.net/specs/openid-connect-basic-1_0.html#Scopes). Scope "openid" is required, and "offline_access" is required if we want a refresh token.
Jottacloud's OpenID configuration endpoint returns "scopes_supported" as list: openid address email full jotta-default offline_access phone profile roles web-origins.
When encoding token request body space will be replaced with "+".
Existing code in rclone set value "offline_access+openid", when encoded in body it will become "offline_access%2Bopenid". I think this is wrong. Probably an artifact of "double urlencoding" mixup - either in rclone or in the jottacloud cli tool version it was sniffed from? It …
> jottacloud: fix scope in token request

- cmd/size/size.go
- cmd/test/memory/memory.go
- docs/content/rc.md
- fs/operations/dedupe_test.go
- fs/operations/operations.go
- fs/operations/operations_test.go
- fs/operations/rc.go
- fs/operations/rc_test.go
Some backends do not provide object size and simply return -1, e.g. Google Docs documents in Google Drive backend. The reported size will ignore these, i.e. assume size 0. This PR adds information when this is the case.
This PR adds reporting of a notice log message:
```
2022/04/06 14:09:32 NOTICE: Google drive root '': Size may be underestimated due to 2 objects with unknown size
Total objects: 13 (13)
Total size: 27.125 MiB (28442166 Byte)
```
An alternative could be to include it in the output string:
```
Total objects: 13 (13)
Total size: 27.125 MiB (28442166 Byte) [Size may be underestimated due to 2 objects with unknown size]
```
I've also included the relevant information in the json and rc output, that is: The number of objects with unknown size. Don't know if this is something we …
> size: warn about inaccurate results when objects with unknown size

- cmd/ncdu/ncdu.go
- cmd/ncdu/scan/scan.go
Some backends do not provide object size and simply return -1, e.g. Google Docs documents in Google Drive backend.
Current version of ncdu does not consider this and end up summing directory sizes including such negative numbers.
- Files are still reported with size -1 as before, when that is what the backend reports.
- Directory sizes skip negative file sizes (assumes size 0) in the sum, and a new flag `~` is added at start of line and description indicating the size may be underestimated at end of line for directories which contain any such files (recursively).
- The value for average size in directory does *not* consider such files, i.e. the average is an average over files with known sizes. This means it may be *over*estimated rather than *under*estimated which is always the case with …
> ncdu: fix issue where dir size is summed when file sizes are -1

- backend/jottacloud/api/types.go
Minor code cleanup.
The UploadResponse type included several properties that are no longer returned by Jottacloud, and the backend implementation did not use them anyway.
> Jottacloud: Minor cleanup of upload response

- backend/jottacloud/api/types.go
- backend/jottacloud/jottacloud.go
Jottacloud have several different apis and endpoints using a mix of different
timestamp formats. In existing code the list operation (after the recent liststream
implementation) uses format from golang's time.RFC3339 constant. Uploads (using the
allocate api) uses format from a hard coded constant with value identical to golang's
time.RFC3339. And then we have the classic JFS time format, which is similar to RFC3339
but not identical, using a different constant. Also the naming is a bit confusing,
since the term api is used both as a generic term and also as a reference to the
newer format used in the api subdomain where the allocate endpoint is located.
This commit refactors these things a bit.
> Jottacloud: Refactor timestamp handling

- backend/b2/b2.go
- docs/content/b2.md
- fs/parseduration.go
- fs/parsetime.go
- fs/parsetime_test.go
The goal is to be able to browse the b2 bucket state as it was at a specified point in time, using b2's file versions. This is especially useful in combination with other backup tools, such as restic, which may use rclone as a backend.
I have not added any tests, since I did not find any for `--b2-versions` which is similar functionality but I might be looking in the wrong place.
For example, this allows the following:
```
rclone mount --b2-version-at=2022-03-13T00:00:00Z b2:bucket /mnt/rclone
```
Or when using a backup tool such as restic:
```
restic -o 'rclone.args=serve restic --stdio --b2-version-at=2022-03-13T00:00:00Z' --no-lock mount /mnt/restic
```
To access pruned backup files whose data is still kept by b2 lifecycle rules.
Yes, but not by me: …
> b2: Add b2-version-at flag to show file versions at time

- backend/internetarchive/internetarchive.go
This fixes a bug that it takes very long time on upload, caused by my misunderstanding of how `Hash()` work.
The new method now uses a 32-char identifier which is temporarily used for watching changes.
Hope @gippeumgwa report us back in 12 hours.
https://forum.rclone.org/t/upload-copy-stalls-for-internetarchive-remote/30580
Closes https://github.com/rclone/rclone/issues/6150
> backend/internetarchive: fix uploads can take very long time

- fs/mount_helper.go
- fs/mount_helper_test.go
Do not trigger an error when parsing mount options starting with an underscore.
This make possible the example given in #5594.
> Accept nedev arg

- backend/s3/s3.go
Rclone incorrectly requests to restore listed objects which are not in Glacier storage class.
This change checks the storage class before attempting to restore the object. This saves a unnecessary chargeable request.
No.
> S3 backend restore command to skip non-GLACIER objects

- backend/storj/fs.go
The "relative" argument was missing when Put'ing a file. This
sets an incorrect object entry in the cache, leading to the file being
unreadable when using mount functionality.
Fixes https://github.com/rclone/rclone/issues/6151 and doesn't seem to break any other functionality.
> storj: fix put

- backend/azureblob/azureblob.go
- backend/b2/upload.go
- backend/s3/s3.go
- fs/chunksize/chunksize.go
- fs/chunksize/chunksize_test.go
Add support for dynamic modification of `--b2-chunk-size` when necessary as discussed in #4643.
Created a new package, `chunksize` that implements a chunk size calculator, which is then called by B2 to dynamically adjust the chunk size when needed.  This package was created with the intent to eventually leverage this calculator in all backends that need to do dynamic chunk size adjustments (S3 at a minimum).
Yes.  #4643
> B2: Dynamically adjust --b2-chunk-size when necessary

- cmd/cmd.go
Setting the following exit code when error is NoLowLevelRetryError, same as for NoRetryError:
> 6 - Less serious errors (like 461 errors from dropbox) (NoRetry errors)
Only case where this error is returned, is currently in local backend, when size or timestamp are changing during sync.
Fixes #5785
> Set proper exit code for errors that are not low-level retried (e.g. size/timestamp changing)

- backend/cache/cache.go
- backend/chunker/chunker.go
- backend/compress/compress.go
- backend/crypt/crypt.go
- backend/dropbox/dropbox.go
- backend/hasher/hasher.go
- backend/onedrive/onedrive.go
- backend/pcloud/pcloud.go
- backend/premiumizeme/premiumizeme.go
- backend/putio/fs.go
- backend/sftp/sftp.go
- backend/webdav/webdav.go
- cmd/about/about.go
Avoid overly self-aware error messages like this:
> 2022/01/14 21:43:36 Failed to about: About call failed: about failed: file does not exist
The command processing starts with the "Failed to <commandname>".
The about and rc outer layers wrap any errors with "about call failed: "
- The first letter was actually uppercase in the about command, I changed it to lowercase as is the convention.
Now, in the backend's About functions, there is no need to shout out even more that this is about ... about...
> about: improved error message

- docs/content/rc.md
Global flags documentation page listed flags that were not listed in the remote control documentation page, so I added them.
> Documentation: added global flags missing from remote control page

- Makefile
- fs/version.go
- fs/versionsuffix.go
- fs/versiontag.go
Introduces a way to quickly set a custom pre-release label / version suffix on my own builds of rclone. 
As of now master version is "v1.58.0-DEV". I can override this easily with something like `-ldflags "-X github.com/rclone/rclone/fs.Version=v9.9.9-CUSTOM"`, but then I loose the version number it was based on. It would be better if I could keep the *number*, and only set my own suffix. That could be achived, of course, with a little `sed` magic or similar. But with this PR I can simply just set fs.VersionSuffix instead. This makes the build command very easy on any platform, and easy configurable in IDEs like VSCode etc.
Nice to have? Definitely not a must have. And perhaps there are better ways to do this already? Perhaps this file needs to be single variable-only to not break some …
> Configurable version suffix independent of version number

- docs/content/install.md
Main purpose is to updated according to Go version 1.17: Use `go install` instead of `go get`.
Included additional information regarding cmount buildtag, required winfsp installation on windows, and "optimized builds" with `-ldflags -s`.
Maybe the text should be split into subsections now? E.g. the "git + go build" method vs the "go install/go get" method? (Not sure what to name the headers then)
Fixes #5809
> docs: improve guide for installing from source

- docs/content/remote_setup.md
Add another option (utilizing SSH Tunnel) for Linux/macOs users to complete the auth on headless box.
> remote setup: Add one more option for Linux/MacOS users to complete the auth on headless box

- backend/azureblob/azureblob.go
- backend/azureblob/azureblob_test.go
Resolves #5943 by support case insensitive access tiers for azureblob.
I appreciate @fstuff already made this change in a PR, but looks like that went idle. I'm happy to close this if @fstuff wants to revisit their PR? I wanted to pick up some easy issues and this was the first in the list for good first issues.
https://github.com/rclone/rclone/issues/5943
> azureblob: case insensitive access tier

- docs/content/bisync.md
I tested Yandex Disk backend through bisync tests. Now we can add one more tested backend to bisync doc page.
[test.log](https://github.com/rclone/rclone/files/8791797/test.log)
No
> content: add Yandex Disk as tested bisync backend

- backend/dropbox/batcher.go
Change obsolete UploadSessionFinishBatch method usage to UploadSessionFinishBatchV2. Change in sdk was made in https://github.com/dropbox/dropbox-sdk-go-unofficial/pull/106
Current bisync tests for dropbox are failing due following error:
```
2022/05/28 21:48:39 ----------------------------------------------------------
2022/05/28 21:48:39 | MISCOMPARE  -Golden vs +Results for  test.log
2022/05/28 21:48:39 | @@ -25,0 +26,2 @@
2022/05/28 21:48:39 | +WARNING: API `UploadSessionFinishBatch` is deprecated
2022/05/28 21:48:39 | +Use API `UploadSessionFinishBatchV2` instead
2022/05/28 21:48:39 ----------------------------------------------------------
```
Golden test.log files are free of warnings. These messages are generated in github.com/dropbox/dropbox-sdk-go-unofficial/v6
I moved from …
> dropbox: migrate from deprecated api

- fs/operations/operations.go
- fs/operations/operations_test.go
- fs/sync/sync.go
- fs/sync/sync_test.go
Previously, the overlap check was based on simple prefix checks of the source and destination paths. Now it actually checks whether the destination is excluded via any filter rule or a "--exclude-if-present"-file.
[Forum Post](https://forum.rclone.org/t/excluding-overlapping-destination/29591)
> sync: overlap check is now filter-sensitive

- docs/content/docs.md
RCLONE_VERBOSE does not use a true/false setting, instead using a 0,1,2 setting. This updates the documents to reflect this information.
Update documentation for environment variable RCLONE_VERBOSE
[6207](https://github.com/rclone/rclone/issues/6207)
> Verbosity environment variable information

- docs/content/filtering.md
A documentation improvement to clarify that the use of regular expression filters prevents rclone from using directory optimisation, as it must instead check every path against the supplied regex.
Yes, [in this forum post](https://forum.rclone.org/t/rclone-regex-in-filter-causes-spurious-directory-catch-all-filter/30985)
Signed-off-by: Matthew Vernon <mvernon@wikimedia.org>
> docs: note use of regexp filtering prevents directory optimisation

- docs/content/overview.md
It is confusing for users to know what "ModTime" support in a backend really means.
This change documents backends that support storing and reading modtimes (`ModTime`), at least some kind of usable timestamp, but does not support changing the modtime-only (`SetModTime`). Marking these with `Partial` in the `ModTime` column features table. 
Existing version seemed to have a mix of `Yes` and `No` for backends supporting `ModTime` but not `SetModTime` (I guess it is confusing for developers too - and I'm including me here).
The following are set to Partial, because `ModTime` is implemented, but `SetModTime` returns `ErrorCantSetModTime` or `ErrorCantSetModTimeWithoutDelete`:
```
1Fichier: No -> Partial
Amazon Drive: No -> Partial
Dropbox: Yes -> Partial
FTP: No -> Partial
Google Photos: No …
```
> docs: clearify backend support for setting modtime only

- backend/jottacloud/jottacloud.go
- backend/onedrive/onedrive.go
- docs/content/jottacloud.md
- fs/backend_config.go
Default device/mountpoint setup is, as before, Jotta/Archive.
Previously one could configure custom device/mountpoint, but then only existing ones. Also uploading was only supported when using the built-in Jotta device (trying to do it on other devices would log an error).
This PR mainly adds two things:
1. Support for upload on any device/mountpoint.
2. Support for creating new device/mountpoints.
The upload implementation is (as before) using the so called "allocate api", where we send a post request to endpoint `files/v1/allocate` and supply the file path as parameter. The existing code used paths of form `<mountpoint>/<folders...>/<file>`, which means the device is implied. I found that an alternative form is `/jfs/<device>/<mountpoint>/<folders...>/<file>`, which means we can use it …
> Jottacloud: Add full support for custom device/mountpoints

- fs/config/ui.go
Improve readability in the config ui.
Primary intention was to add spacing (i.e. empty lines) between individual sections, such as individual options, or questions. But; improving one thing, makes another thing stand out, so I added some more changes to improve consistency and overall readability.
The changes are:
- Empty line between sections, i.e. before each individual option is presented, and before individual questions like "Edit advanced config?"
- Not a very generic or elegant solution, that would require too much refactoring I think. But to make it obvious where newlines are inserted as part of this I created a separate helper function `newSection`. This should make it easy to read, avoid accidental removal of "duplicate" newlines, and make a good starting point for any future …
> Config UI readability

- backend/uptobox/uptobox.go
Quick fix for root paths "/" and ".".
> uptobox: fix root path handling - fixes #5903

- cmd/ncdu/ncdu.go
If the remote on the command line is "remote:subdir", when
deleting "filename", the confirmation message shows the path
"remote:subdirfilename". Using path.Join() fixes this.
A superfluous '/' will be added after the ':' even if the
remote is just "remote:", but that's still a valid syntax.
> cmd/ncdu: display correct path in delete confirmation dialog

- backend/mailru/mailru.go
This started out as an issue reported by the staticcheck linting tool: "Poorly chosen name for variable of type time.Duration" (ST1011). It refers to the `serverPool.expirySec` variable. I fixed this by renaming it from `expirySec` to just `expiry`. But this revealed another problem: It is initialized with value of constant `serverExpirySec`, integer 180, but despite the name of this constant its value in this assignment will be treated as nanoseconds! I fixed this by multiplying with `time.Second`, which makes the code/naming consistent, and I assume this is according to the intention ❓ But it changes the actual logic since the initial value is now 180 seconds while before was 180 nanoseconds ❗
> Use variable type int instead of time.Duration for keeping number of seconds

- cmd/mount/dir.go
- cmd/mount/file.go
- cmd/mount/mount.go
The bazil.org/fuse library did support macOS, but this was removed as described in #4393.
This PR removes some remnants in code, as detected by the staticcheck lint tool:
fuse.VolumeName is deprecated: Ignored, OS X remnant.  (SA1019)
c.MountError is deprecated: Not used, OS X remnant.  (SA1019)
c.Ready is deprecated: Not used, OS X remnant.  (SA1019)
a.Crtime is deprecated: Not used, OS X remnant.  (SA1019)
a.Crtime is deprecated: Not used, OS X remnant.  (SA1019)
> Remove legacy OS X remnants from mount code

- cmd/ncdu/ncdu.go
Add the ability to select multiple items in the ncdu interface to delete them.
Either press `v` to select the current item, or `V` to highlight items as you move over them (slightly awkward behaviour that I'll tidy up here if you swap direction, the final item isn't toggled back). Then I've added a `D` command that will delete all the currently selected items.
Rebase and slight cleanup of this feature. One small additional change I might suggest is using the same eybind for delete and delete selection and just changing it's behavior depending on if items are selected.
> Add selection to ncdu command

- backend/s3/s3.go
Add a note in the S3 docs that increasing the chunk size property decreases the accuracy of the progress statistics.
Yes: https://forum.rclone.org/t/multipart-upload-stops-for-few-minutes-after-4th-chunk/29122/7
> s3: add note about chunk size decreasing progress accuracy

- docs/content/drive.md
Updated instructions in `Making your own client_id` section to record process for selecting "Internal" OAuth consent screen.
> Update drive.md - Internal OAuth consent screen

- backend/fichier/api.go
As discussed #6165 we should be parsing the 1fichier error code and not retrying some errors. Sadly they don't seem to have a public list of them. I've sent them a message asking if they could provide me with a complete list. In the meantime I've the 3 error codes I know.
> fichier: parse api error codes and them accordingly

- docs/content/commands/rclone_sync.md
Just a small addition to the rclone sync docs to make it easier to read and understand.
n/a
> rclone sync grammatical clarification

- cmd/copyurl/copyurl.go
- fs/operations/operations.go
- fs/operations/operations_test.go
- fs/operations/rc.go
Adding `--auto-filename-header`
To set preferred download filenames for HTTP requests, RFC 6226
specifies a 'filename' directive, available within 'Content-Disposition'
header, and suggests both token and quoted string syntaxes should be allowable
for the filename directive. i.e.: either `filename=name.txt` or
`filename="name.txt"` should be acceptable.
See below for details:
https://httpwg.org/specs/rfc6266.html#disposition.parameter.filename
https://httpwg.org/specs/rfc6266.html#advice.generating
`--auto-filename-header` is designed to work in conjunction with `--auto-filename`, honoring the filename directive when retrieving files from a server.
Directives contained within the `Content-Disposition` header are semicolon delimited, and can vary in length and order. Consideration had to …
> copyurl: Update copyurl to honor HTTP filename directive

- backend/drive/drive.go
- docs/content/drive.md
During the configuration of a new Google Drive, the root_folder_id is only displayed when Advanced Settings are selected. Made a PR again as the previous one was not adhering to rules
#3463
> drive: moved rclone_folder_id to advanced section fixes #3463

- lib/http/auth/basic.go
I was running the staticcheck linter and investigated the following reported issues:
> this value of r is never used (SA4006)
> WithContext is a pure function but its return value is ignored (SA4017)
On the following line:
https://github.com/rclone/rclone/blob/fdd2f8e6d21d1cf95b33fd2bb09f9c1caef0069d/lib/http/auth/basic.go#L114
I'm not sure I understand this line and the `CustomAuth` function it is in, but my impression is that staticcheck is in fact correct here, and that this line does nothing as the implementation currently is.
```
// WithContext returns a shallow copy of r with its context changed
// to ctx. The provided ctx must be non-nil.
//
// For outgoing client request, the context controls the entire
// lifetime of a request and its response: obtaining a connection,
// sending …
```
> Fix missing response when using custom auth handler in http serve

- MANUAL.html
- MANUAL.md
- MANUAL.txt
- README.md
- docs/content/licence.md
- rclone.1
Global fix of typo with "terms of MIT the license"
> Fix typo in license webpage

- README.md
- backend/all/all.go
- backend/hidrive/api/queries.go
- backend/hidrive/api/types.go
- backend/hidrive/helpers.go
- backend/hidrive/hidrive.go
- backend/hidrive/hidrive_test.go
- backend/hidrive/hidrivehash/hidrivehash.go
- backend/hidrive/hidrivehash/hidrivehash_test.go
- backend/hidrive/hidrivehash/internal/internal.go
- bin/make_manual.py
- docs/content/_index.md
- docs/content/docs.md
- docs/content/hidrive.md
- docs/content/overview.md
- docs/layouts/chrome/navbar.html
- fstest/test_all/config.yaml
- lib/oauthutil/oauthutil.go
- lib/oauthutil/renew.go
- lib/pacer/pacers.go
This adds support for the cloud storage technology HiDrive as a new backend called `hidrive`.
It directly uses the [HiDrive REST API](https://developer.hidrive.com/http-api-reference/), offering access to more features and better usability, as opposed to connecting rclone to HiDrive via webdav, etc.
As the API is the same for [HiDrive by STRATO](https://www.strato.de/cloud-speicher/) and [HiDrive by IONOS](https://www.ionos.de/office-loesungen/hidrive-cloud-speicher), this new backend will work for both.
**The code is written by myself with support from my team here at [STRATO AG](https://www.strato.de/).**
Yes, see #1069.
-------
We are mostly ready to start the review process for this change,
but there are some last quirks we would like to discuss with you before.
I will also add a few …
>  new backend: STRATO HiDrive - fixes #1069

- backend/internetarchive/internetarchive.go
- docs/content/internetarchive.md
- docs/content/overview.md
This PR adds support for viewing metadata in IA from rclone.
~~I can't figure out how to implement writer part, so I've only implemented metadata read part (fs.Metadataer).~~
None.
> backend/internetarchive: add support for Metadata

- backend/union/upstream/upstream.go
On Void Linux i686 glibc, with go1.18.3 and rclone 1.59.0, this test failure happens:
```
$ RCLONE_CONFIG="/notfound" go test ./backend/union
--- FAIL: TestStandard (0.00s)
fstests.go:451: Using remote "TestUnion:"
panic: unaligned 64-bit atomic operation [recovered]
panic: unaligned 64-bit atomic operation
goroutine 70 [running]:
testing.tRunner.func1.2({0x56d97520, 0x56e25540})
/usr/lib/go/src/testing/testing.go:1389 +0x2c5
testing.tRunner.func1()
/usr/lib/go/src/testing/testing.go:1392 +0x4a5
panic({0x56d97520, 0x56e25540})
/usr/lib/go/src/runtime/panic.go:844 +0x265
runtime/internal/atomic.panicUnaligned()
/usr/lib/go/src/runtime/internal/atomic/unaligned.go:8 +0x38
runtime/internal/atomic.Load64(0x5859d4cc)
/usr/lib/go/src/runtime/internal/atomic/atomic_386.s:225 +0x10 …
```
> backend/union/upstream/upstream.go: fix alignment of struct field

- cmd/sync/sync.go
- docs/content/docs.md
- fs/fs.go
- fs/operations/operations.go
- fs/operations/operations_test.go
I noticed while reading the changelog for v1.59.0 that changes have been listed that weren't actually implemented. I guess I must've missed the usage of the Overlapping function in the --backup-dir option. This PR replaces the old Overlapping function with the new filter-sensitive one and also adds documentation notes and hints in error messages.
Sorry for this oversight.
No.
> Backup dir fix

- fs/rc/jobs/job.go
- fs/rc/jobs/job_test.go
Adds new rc call to stop all running jobs in a group. Fixes #5561
Adds new rc call `job/stopgroup` to stop jobs by _group
#5561
> jobs: add ability to stop group

- backend/internetarchive/internetarchive.go
- docs/content/internetarchive.md
Skips checksum for some files using a different method for hashing.
https://forum.rclone.org/t/internet-archive-md5-tag-in-id-files-xml-interpreted-incorrectly/31922/2
Closes #6321
> internetarchive: ignore checksums for files using the different hashing method

- backend/drive/drive.go
- backend/drive/drive_internal_test.go
Extend the shouldRetry function by also checking for the quotaExceeded
reason, and since this function appeared to be untested, add a test case
for the existing errors and this new one.
I am very much a Go novice, and the tests don't quite pass, so I'd welcome
feedback on how to best improve it.
Discussed in #615 , as was the solution I implemented
> drive: Raise fatal error when quota exceeded

- backend/internetarchive/internetarchive.go
This fixes the handling of URLs involving hash symbol.
Closes #6326
> internetarchive: handle hash symbol in the middle of filename

- backend/jottacloud/jottacloud.go
Reverts the commit that changed config to always store username in config, also for standard auth. It broke legacy auth.
Also avoids storing the username in config at all unless using legacy auth. Previously (before the mentioned reverted commit) it was only stored to pass the information between config steps, but not really a relevant configuration parameter. This was something I introduced myself when implementing support for custom device/mountpoint sequence in #5926. Although this now adds even more customer info requests, which is something I have tried to reduce, it is only during the config phase, and I think it makes it more consistent and avoids unnecessary information in config.
See commit messages for more details.
Fixes #6309
> Jottacloud: Fix legacy authentication

- cmd/serve/dlna/dlna.go
- cmd/serve/dlna/dlna_test.go
- cmd/serve/dlna/dlna_util.go
[Changes](https://github.com/anacrolix/dms/commit/3d402bc95f0bde7d353e23cf4f3c5e4fdc37c9ec#diff-835dd4c4999146276b07a369231a91c13111bdf55266e5cd245e5d2e33a3b24aL13-R36) in [anacrolix/dms](https://github.com/anacrolix/dms) changed `upnp.ServiceURN` to include a namespace identifier. This identifier was previously hardcoded, but is now parsed out of the URN. The old SOAP action header parsing logic was duplicated in rclone and did not handle this field. Resulting responses included a URN with an empty namespace identifier, breaking clients.
See #6354
> dlna: fix SOAP action header parsing - fixes #6354

- docs/content/downloads.md
Script installation instructions in `downloads.md` differ from those in
`install.md` and fail on MacOS.
> docs: fix script installation command on downloads page

- cmd/serve/dlna/dlna.go
- cmd/serve/dlna/dlna_test.go
- cmd/serve/dlna/dlna_util.go
- cmd/serve/dlna/dlnaflags/dlnaflags.go
Enabling a user to specify the interfaces used for DLNA (SSDP). This is especially useful when serving DLNA on a machine with many virtual network interfaces (for example when also running Kubernetes) for which you don't wish to advertise DLNA.
No.
> dlna: specify SSDP interface names from command line

- backend/sftp/sftp.go
- cmd/serve/sftp/sftp.go
Document that chunk_size should be left at default 32 KiB when using serve sftp.
Related to #6408
> Document that chunk_size should be left at default 32 KiB when using serve sftp

- backend/ftp/ftp.go
- docs/content/flags.md
- docs/content/ftp.md
- go.mod
- go.sum
Forces the use of `LIST -a` command
when listing a directory which should
list all hidden folders and files.
To introduce an option to workaround systems that do not include hidden files/folders by default when using the FTP MLST command.
https://forum.rclone.org/t/how-to-list-hidden-folders-with-ftp/32812
> ftp: Add force_list_hidden option

- .golangci.yml
Fix wrong name for `max-issues-per-linter` variable, which also .golangci.example.yml  had at some point:
https://github.com/golangci/golangci-lint/commit/2f5f082da15cd434ccc8237089efcba264a2f72a
> build: fix lint option max-issues-per-linter

- docs/layouts/chrome/menu.html
- docs/layouts/chrome/navbar.html
- docs/static/css/custom.css
Better alignment of icons of different sizes
This reverts the changes from PR https://github.com/rclone/rclone/pull/5889 and https://github.com/rclone/rclone/pull/5701 and implements an alternative fix which is more "native" Font Awesome solution:
> Font Awesome icons are designed on grid and share a consistent height. But they vary in
width depending on how wide or narrow each symbol is. If you prefer to work with icons
that have a consistent width, adding fa-fw will render each icon using the same width.
(https://fontawesome.com/docs/web/style/fixed-width)
The original solution had wrong css, as a result of misunderstanding the precedence of `element,element` and `element element` selectors, leading to an issue with icons in backend doc headers.
Before:
After:
As a bonus, it also gives …
> Docs: Better alignment of icons

- backend/sftp/sftp.go
This checks directory existence if mkdir operation fails.
Race condition happens very often when an union remote points to the same (physical) directory, and directory creation is needed.
As servers find the directory that others are created, you get "Failure" errors and unfortunate files will be skipped.
Although it looks it's patched for the FTP backend, but SFTP is not.
> sftp: check for directory existence if mkdir fails

- README.md
- backend/s3/s3.go
- docs/content/_index.md
- docs/content/s3.md
Add IONOS S3 Object Storage to the rclone.
No, but I've checked a few pull requests related to the same topic. 
The compiled tool works fine, but I ran integration tests, and some of them failed, for example -
--- FAIL: TestIntegration/FsMkdir/FsPutFiles/FsListRDirFile2 (0.29s)
--- FAIL: TestIntegration/FsMkdir/FsPutFiles/FsListR (0.06s)
--- FAIL: TestIntegration/FsMkdir/FsPutFiles/FsListLevel2 (0.23s)
--- FAIL: TestIntegration/FsMkdir/FsPutFiles/FsListRLevel2 (0.06s)
--- FAIL: TestIntegration/FsMkdir/FsPutFiles/FsListFile1 (7.29s)
--- FAIL: TestIntegration/FsMkdir/FsPutFiles/FsListFile1and2 (7.30s)
--- FAIL: TestIntegration/FsMkdir/FsPutFiles/FsPurge (14.98s)
--- FAIL: TestIntegration/FsMkdir/FsPutFiles/FsCopy (7.58s)
- [✓] I have read the [contribution …
> s3: add support for IONOS Cloud Storage

- docs/content/commands/rclone_mount.md
According to [systemd.automount](https://www.freedesktop.org/software/systemd/man/systemd.automount.html) manual
> Note that automount units are separate from the mount itself, so you should 
> not set After= or Requires= for mount dependencies here. 
> For example, you should not set After=network-online.target or 
> similar on network filesystems. Doing so may result in an ordering cycle.
Small change in mount documentation
> Remove "After" in automount example

- docs/content/install.md
The purpose is to avoid confusing myself and misinforming forum members again... with regards to make command and windows version info resources.. 😫 
https://forum.rclone.org/t/icon-and-version-info-is-not-displayed-in-exe-after-successful-build/33244
> docs: improve description of make command in install docs

- docs/content/_index.md
It is now called Glacier and documentation is at https://www.scaleway.com/en/glacier-cold-storage/
On the other hand, it is unclear to me the role of "name": should it stay "C14" or should it become "Glacier" or "Scaleway Glacier" ?
> docs/content: fix Scaleway C14 broken link

- backend/union/union.go
This fixes the problem that union doesn't tell whether its upstreams are SlowHash or not, causing hasher to be confused.
https://forum.rclone.org/t/local-and-hasher-dont-work-nicely-each-other/33179/5
> union: propagate SlowHash feature

- README.md
- backend/all/all.go
- backend/oracleobjectstorage/client.go
- backend/oracleobjectstorage/command.go
- backend/oracleobjectstorage/copy.go
- backend/oracleobjectstorage/object.go
- backend/oracleobjectstorage/options.go
- backend/oracleobjectstorage/oracleobjectstorage.go
- backend/oracleobjectstorage/oracleobjectstorage_test.go
- backend/oracleobjectstorage/oracleobjectstorage_unsupported.go
- backend/oracleobjectstorage/waiter.go
- docs/content/oracleobjectstorage.md
- fstest/test_all/config.yaml
- go.mod
- go.sum
Add support for new native backend: Oracle Object Storage
Existing access via s3 compat way works but it works with only access-key, secret-key which forces users to pass credentials around
Native way works with OCI config file, Instance Principal, Resource Principal way and hits the native end points. 
Instance Principal way is great for automation, in the sense that customer's do not have to mess with secrets on oci compute instance for bucket access 
https://github.com/rclone/rclone/issues/6299
> oracle-object-storage: Add a new native backend -fixes #6299

- cmd/serve/httplib/httpflags/httpflags.go
- cmd/serve/httplib/httplib.go
- docs/content/flags.md
- docs/content/rc.md
- lib/http/http.go
- lib/http/http_test.go
To allow users to select their minimum TLS version. For example, to disable TLS 1.0 and 1.1.
No
> Allow users to disable TLS 1.0 and 1.1

- docs/content/install.sh
To download the correct executable om armv7 (E.g. RPi 2 Model B)
The observation:
https://forum.rclone.org/t/out-of-memory-after-moving-to-rpi-8gb-and-ssd/33521/8
This initially proposed solution:
https://forum.rclone.org/t/out-of-memory-after-moving-to-rpi-8gb-and-ssd/33521/19
The decision to match everything starting with armv7
https://forum.rclone.org/t/out-of-memory-after-moving-to-rpi-8gb-and-ssd/33521/27
The modification was tested on Ubuntu with different hardcoded settings of OS_type.
> install.sh: fix arm-v7 download

- docs/content/alias.md
To make users aware of the possibility of using connection strings in the alias backend.
https://forum.rclone.org/t/crypt-alias-with-different-password-password2/33506/14
> docs: Describe connection strings in alias backend

- cmd/mountlib/rc.go
`mount/listmounts` currently only returns the remote name in `Fs`:
```bash
rclone rc mount/mount fs=remote0:photos mountPoint=/home/username/mounts/remote0
```
```json
{
"Fs": "remote0",
"MountPoint": "/home/username/mounts/remote0",
"MountedOn": "2022-10-16T00:46:33.351736924"
}
```
expected behaviour 
```json
{
"Fs": "remote0:photos",
"MountPoint": "/home/username/mounts/remote0",
"MountedOn": "2022-10-16T00:46:33.351736924"
}
```
https://github.com/rclone/rclone/pull/6499
> rc: Fix mount/listmounts not returning the full Fs entered in mount/mount

- .github/workflows/build.yml
Removes the following warning from build logs:
```
Warning: Unexpected input(s) 'stable', valid inputs are ['go-version', 'go-version-file', 'check-latest', 'token', 'cache', 'cache-dependency-path', 'architecture']
```
> Setup go v3 fix

- backend/local/local.go
In existing version, relative paths are made absolute with `filepath.Abs`, which implicitely performs a `filepath.Clean` which eliminates path elements such as `..`. But paths that are already absolute are not cleaned, which means a path element `..` will be kept and encoded according to backend encoding.
This PR adds a call to `filepath.Clean` for absolute paths, making it more consistent.
Windows paths with prefix `\\` are excluded from this, they were already excluded from `filepath.Abs` in existing version, as UNC paths cannot be relative (this is documented) nor contain "relative" path elements (undocumented, but at least the `dir` command such as `dir \\?\C:\Some\Path\..\OtherPath` errors with "The filename, directory name, or volume label syntax is incorrect", and also, in any …
> Clean absolute paths in local backend

- docs/content/install.md
The links look like they are currently wrong as the windows ones link to linux binaries. I have corrected these to be the windows equivalents.
Documentation correction
n/a
> Corrected windows download links from linux versions

- docs/content/commands/rclone_serve_restic.md
> docs: fix typo `remove` in rclone_serve_restic command

- docs/content/local.md
Before, the documentation for this option looked like this:
The bullet point was not intended.
This fixes it.
Preview on github:
No
> [doc] Fix character that was incorrectly interpreted as markdown

- cmd/ncdu/ncdu.go
- cmd/ncdu/scan/scan.go
Some smaller improvements to ncdu. The biggest being added support for showing modification times.
Modification times can now be togled with `m` and sorted with `M`, like the [original ncdu](https://dev.yorhel.nl/ncdu) tool. Time format is the same as when testing ncdu 1.17 (on Fedora and Alpine): "2006-01-02 15:04:05 -0700". One downside of this format is that it contains spaces, while other fields like count and size in the output are separated by space.
Example output, with everything (size, count, average and modified time) shown:
```
153        1       153 2021-04-15 18:11:40 +0200 [          ] /i18n
21.252Ki       23       946 2021-04-15 18:11:40 +0200 [          ] /layouts
3.019Mi       28 110.402Ki 2021-04-15 18:11:40 +0200 [##########] /static
757                    2021-08-31 …
```
> Ncdu improvements

- fs/rc/js/wasm_exec.js
Fixes the following error while running [rclone as wasm](https://github.com/rclone/rclone/tree/master/fs/rc/js): ```LinkError: import object field 'runtime.walltime' is not a Function```.
[`walltime1` function was renamed to `walltime`](https://go-review.googlesource.com/c/go/+/314770/4), therefore code on wasm_exec.js was updated accordingly.
No.
> wasm: fix walltime link error

- backend/azureblob/azureblob.go
- docs/content/azureblob.md
In #3285 support for `azureblob` was added. In #6290 the option was added to override the endpoint. This adds the option to override the account name and key also.
Note: this could be regarded backwards incompatible. E.g. for people who keep their production credentials in the config but only switch `use_emulator` on and off. In which case an attempt would be made to authorize with the emulator with wrong credentials.
I couldn't find any mentions of it.
> azureblob: allow emulator account/key override

- backend/s3/s3.go
* Fix a bug caught by static analysis where a nil value might accidentally be accessed.
An unchecked error value could cause resp to be nil which would cause issues when it is accessed on the next line. This adds a check around which doesn't reference the resp variable unless the err value is nil
> s3: Fix unchecked err in S3 Listv2

- fs/rc/internal.go
- lib/debug/common.go
- lib/debug/go1.19.go
- lib/debug/go1.19_compat.go
Added rc commands to set the GC Percent & Memory Limit (1.19+)
N/A
> rc: Add commands to set GC Percent & Memory Limit (1.19+)

- backend/smb/smb.go
Given existing code line in the ensureDirectory function:
```
cn.smbShare.MkdirAll(f.toSambaPath(path.Dir(_path)), 0o755)
```
When uploading a file to the root of the share, _path here is empty string, then path.Dir will return "." (from its implicit call to path.Clean), toSambaPath will encode it to the Unicode wide equivalent, and the result is as described in the forum thread: A directory `．` is being created, in addition to the uploaded file.
I fixed this by checking for the "." and return from ensureDirectory before ever calling MkdirAll - assuming it is not necessary to call with empty string "".
(I've been thinking about the use of path.Clean/Join/Dir etc on remote paths in the backend implementations in general; if it is strictly speaking not the correct thing to do, i.e. the …
> SMB: Fix issue where spurious dot directory is created

- backend/azureblob/azureblob.go
- backend/azureblob/azureblob_test.go
Add support for inferring the Azure Service Principal identity and secret from environment variables as per [EnvironmentCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet).   I find myself using `rclone` in a context where `EnvironmentCredential`s are already available for other reasons and it seems silly to go write a JSON file just to use the values therein.
Are there additional tests you'd like to see for this feature?
No, sorry.
I believe the ticked boxes are correct, but please be gentle if I've missed something.
> azureblob: support service principals using the EnvironmentCredential scheme

- cmd/ncdu/ncdu.go
The previous version used values after the maximum Unicode code-point
to encode a key. This could lead to an overflow since a key is a int16,
a rune is int32 and the maximum Unicode code-point is larger than int16.
A better solution is to simply use negative runes for keys.
PR #6564
> cmd/ncdu: use negative values for key runes

- backend/ftp/ftp.go
user message should read FTPS since it refers to the implicit "FTP over TLS" aka FTPS
Improve user output, just a small typo maybe.
No
> Minor change in user facing output at ftp.go

- backend/ftp/ftp.go
Use a more efficient way to lookup a single FTP item when supported by the remote server.
Here: https://forum.rclone.org/t/ftp-does-not-play-well-with-files-from/31158
And https://github.com/rclone/rclone/issues/6225
> ftp: Improve performance of findItem

- cmd/tree/tree.go
- docs/content/commands/rclone_tree.md
- docs/content/docs.md
- docs/content/flags.md
- fs/config.go
- fs/config/configflags/configflags.go
- fs/terminalcolormode.go
- fs/terminalcolormode_test.go
- lib/terminal/terminal.go
This PR adds a new global flag `--terminal-color-mode` which allows you to change the way ANSI codes are handled in output. This is similar to the `-color` flag for many UNIX commands (grep, ls...).
Currently, rclone only adds ANSI codes to output if target file descriptor is an actual terminal. With this new flag, the behavior can be changed by using one of the following modes:
- `AUTO` (default) = current behaviour => only add ANSI codes when the output medium is an actual terminal
- `ALWAYS` => always add ANSI codes, even to normal files
- `NEVER` => never add ANSI codes
I am still not sure if this is the best name for the flag. Maybe just `--terminal-color` or `--color` is better?
This has been discussed by someone else on the forum 2 years ago: …
> Add global flag '--color'

- fs/rc/js/LICENSE.wasmexec
- fs/rc/js/wasm_exec.js
The BSD-style license that Go uses requires the license to be included with the source distribution; so add it as LICENSE.wasmexec (to avoid confusion with the other licenses in rclone) and note the location of the license in wasm_exec.js itself.
Make rclone comply with the license terms of wasm_exec.js which is included in rclone; specifically that "Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer."
I found this while reviewing rclone 1.60.1 for uploading to Debian.
No.
> WASM: comply with wasm_exec.js licence terms

- cmd/config/config.go
- docs/content/amazonclouddrive.md
- docs/content/box.md
- docs/content/drive.md
- docs/content/dropbox.md
- docs/content/googlecloudstorage.md
- docs/content/googlephotos.md
- docs/content/hidrive.md
- docs/content/onedrive.md
- docs/content/pcloud.md
- docs/content/premiumizeme.md
- docs/content/putio.md
- docs/content/remote_setup.md
- docs/content/sharefile.md
- docs/content/yandex.md
- docs/content/zoho.md
- lib/oauthutil/oauthutil.go
The config question "Use auto config?" confused many users and lead to recurring forum posts from users that were unaware that they were using a remote or headless machine.
This commit makes the question and possible options more descriptive and precise.
This commit also adds references to the guide on remote setup in the documentation of backends using oauth as primary authentication.
https://forum.rclone.org/t/idea-to-improve-wording-of-auto-config-during-configuration/33951
> lib/oauthutil: Improved usability of config flows needing web browser

- backend/drive/drive.go
- docs/content/docs.md
- fs/fspath/path.go
- fs/fspath/path_test.go
This started as a documentation task; to add a statement that remote names may not *end* with space. This triggered more investigations, to verify that this is really always the case, and then one thing lead to another... First fixed/simplified the remote/config name regex by removing superfluous elements, unnecessary capture groups etc. Then extended it to explicitly match only when no leading/trailing space, so that an error is reported in the same way as when illegal characters are used.
Normally the remote names from config are trimmed (`strings.TrimSpace`) early on, and will never contain leading/trailing space when matched against the changed regex. This is the case when using interactive command line (config ui) and when the remote names are read/parsed from the config file. I.e. …
> Stricter check for remote names with leading/trailing space

- docs/content/box.md
Add note about Box API rate limits with reference to Box description of the limits,
Yes, here:
https://forum.rclone.org/t/rclone-smb-to-box/34818/9
> docs: Added note on Box API rate limits

- docs/content/bisync.md
- docs/content/chunker.md
- docs/content/combine.md
- docs/content/compress.md
- docs/content/docker.md
- docs/content/fichier.md
- docs/content/filefabric.md
- docs/content/googlephotos.md
- docs/content/gui.md
- docs/content/hasher.md
- docs/content/hdfs.md
- docs/content/hidrive.md
- docs/content/internetarchive.md
- docs/content/koofr.md
- docs/content/mailru.md
- docs/content/memory.md
- docs/content/netstorage.md
- docs/content/oracleobjectstorage.md
- docs/content/premiumizeme.md
- docs/content/putio.md
- docs/content/seafile.md
- docs/content/sharefile.md
- docs/content/sia.md
- docs/content/smb.md
- docs/content/storj.md
- docs/content/sugarsync.md
- docs/content/tardigrade.md
- docs/content/uptobox.md
- docs/content/zoho.md
With current version of official docs, after the 1.61 release, there is a bit of a mix in the version number formats used in the newly introduced version badges. E.g. the Box backend has "v1.38" (two parts) while 1Fichier has "v1.49.0" (three parts). This PR makes them consistent by removing the trailing ".0" parts. My thinking is that it looks a bit better this way, that the looks of the full "v1.49.0" label is a tiny bit more on the technical side, if you see what I mean...? But if you have a strong opinion the other way, that's fine too, my primary goal is consistency here. (Sorry for not noticing before the release, really should have seen this in tip.rclone.org).
> docs: show only significant parts of version number in version introduced label

- cmd/rc/rc.go
rc: set url to the first value of rc-addr since it has been converted to an array of strings now 
rc: set url to the first value of rc-addr since it has been converted to an array of strings now
#6641
> rc: set url to the first value of rc-addr -- fixes #6641

- backend/local/local.go
In my logs I've seen various error messages like
```
failed to read directory "<PATH>": %!w(<nil>)
```
No
- [n/a] I have added documentation for the changes if appropriate.
> backend/local: fix %!w(<nil>) in "failed to read directory" error

- cmd/serve/webdav/webdav.go
Mapping/Accessing WebDAV share on windows.
This will allow a user to mount webdav shares on windows, it is only a documentation change.
> Fixes 6596 doc bug

- backend/crypt/crypt.go
- docs/content/crypt.md
rclone sync erroneously deleted folders renamed to a different case on crypts where directory name encryption was disabled and the underlying remote was case insensitive.
Example: Renaming the folder Test to tEST before a sync to a crypt having remote=OneDrive:crypt and directory_name_encryption=false could result in the folder and all its content being deleted. The following sync would correctly create the tEST folder and upload all of the content.
Additional tests have revealed other potential issues when using filename_encryption=off or directory_name_encryption=false on case insensitive remotes. The documentation has been updated to warn about potential problems when using these combinations.
https://forum.rclone.org/t/chaning-directory-case-makes-rclone-lose-it/35268
> crypt: fix for unencrypted directory names on case insensitive remotes

- lib/oauthutil/oauthutil.go
According to the OAuth2 RFC (https://www.rfc-editor.org/rfc/rfc6749#section-5.2), the server should return a 400 (or maybe sometimes 401) for a list of unrecoverable errors, such as expired refresh tokens. Rclone shouldn't still make 5 attempts to get a token in those cases. @ncw do you see any potential problem with this?
> lib/oauthutil: don't retry for probably fatal errors

- backend/oracleobjectstorage/options.go
- docs/content/oracleobjectstorage.md
yes. Fixes #6588 
- [X ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [X ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ X] I'm done, this Pull Request is ready for review :-)
> oracle-object-storage: expose the storage_tier option in config

- backend/storj/fs.go
- docs/content/overview.md
Implements the Purger interface using https://pkg.go.dev/storj.io/uplink#Project.DeleteBucketWithObjects
As the Storj client library provides a quick way for deleting only for entire buckets, for all other cases the implementation will fallback to listing and deleting individual objects.
Fixes #5346
> storj: implement purge

- cmd/cmount/mountpoint_windows.go
Note: Split from PR #6234, the single commit regarding "UNC paths" (see that PR's description for details).
> mount: do not treat \\?\ prefixed paths as network share paths on windows

- docs/content/bisync.md
This PR fixes the `#check-access` anchor link in the bisync.md document.
`#check-access-option` does not exist in bisync.md; `#check-access` does.
Improve documentation by fixing a broken anchor link.
Not to my knowledge
> Fix a broken anchor link

- .github/workflows/build.yml
This fixes the the input property `manual` in the `inputs` context of our GitHub workflow. It was introduced in #5275, see that for background.
The first change is only a small improvement: Added a `description` property, which shows a more human-readable label in the "Run workflow" dialog, and added a `type` property with value "boolean" which makes GitHub present it as a checkbox, instead of a regular text box with the text "true" set by default.
Furthermore I discovered that the value is not really a boolean, even after I added the "type: boolean" property. It is in reality always a string - either the string 'true' or the string 'false'. But this means a condition `if: ${{ github.event.inputs.manual }}` will always be met, because any non-empty string is treated as boolean true, even …
> build: fix condition for manual workflow run

- backend/oracleobjectstorage/options.go
- backend/oracleobjectstorage/oracleobjectstorage.go
Speed up operations by setting http call pacer minsleep=10ms which is in parity with s3
yes https://github.com/rclone/rclone/issues/6617
- [ X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ X] I have added tests for all changes in this PR if appropriate.
- [ X] I have added documentation for the changes if appropriate.
- [ X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ X] I'm done, this Pull Request is ready for review :-)
> oracle-object-storage: speed up operations by setting pacer minsleep=10ms in parity with s3

- docs/content/bisync.md
This changeset documents my learnings after having encountered a
failure I reported in the rclone forum[[0]].
I may be a fool for having failed to understand the previous
documentation, but I am likely not the only fool to get snared by
it.
This PR therefore adds details to clarify what the user must do in
order to allow `--check-access` to succeed.
While at it, I've also added some basic documentation for
`--check-filename`.
[Yes][0]
[0]: https://forum.rclone.org/t/bisync-check-file-check-failed/35682
> docs: Improve bisync check-access & check-filename

- docs/content/drive.md
* Updates OAuth consent screen instructions to include adding scopes for backup purposes (create, edit and delete files).
* Updates instructions to keep app in testing mode (appropriate for most users). The previous instructions suggested this, but we don't need to "publish" the app at all in order to proceed with this step.
Updates some documentation surrounding creating a user client-id and some makes changes to accommodate differences I encountered on the OAuth Consent screen flow.
No, but happy to make changes as required.
> docs: update drive.md create client-id instructions

- fs/accounting/stats.go
- fs/accounting/stats_test.go
- fs/parseduration.go
- fs/parseduration_test.go
Part 1: Integer overflow would lead to ETA such as "-255y7w4h11m22s966ms", as reported in #6381. Now the value will be clipped at the maximum "292y24w3d23h47m16s", and it will be shown as "-".
- I would like to show the Unicode symbol for infinity, "∞", for this situation, but I'm worried it will cause issues in some consoles (especially Windows, with code page nightmare etc). Don't know if there are any other comparable uses of Unicode symbols in output from rclone? Tree command probably, but maybe that is a somewhat unconventional command with limited use, compared to the stats output, so less important with compatibility. Maybe "**" could serve as an ascii version of the infinity symbol, or perhaps it will look a bit "noisy". I landed on just showing "-", which is the same as already …
> Avoid negative ETA values for very slow speeds

- docs/content/drive.md
I was not aware that "testing" mode applications have a short token grant time when updating the original instructions with the new OAuth application flow. This resulted in me having to refresh the token every week. I have restored the original instructions to publish the application and warning for the most part, but added a blurb about testing mode as well.
No, but happy to discuss or make changes.
> docs: update drive.md instructions

- cmd/serve/http/http.go
- cmd/serve/http/http_test.go
- docs/content/commands/rclone_serve_http.md
Implement --auth-proxy for 'rclone serve http'. Mostly copied from the implementation of `rclone serve webdav`.
https://github.com/rclone/rclone/issues/6779
https://forum.rclone.org/t/make-backend-configuration-configurable-per-http-request-on-serve-http/36202/3
- I've copied it from `serve webdav`. Couldn't find any tests to copy 🙈
> Implement --auth-proxy for 'rclone serve http'

- backend/onedrive/onedrive.go
- backend/uptobox/uptobox.go
- vfs/vfsflags/filemode.go
I split off the bugfixes from #6555 to try to get them into a rclone a bit faster. This fixes two issues, one is parseInt trying to store a 64 width int into a 32 width one and some MustCompile regex strings for URLs that have some bugs that could be exploited.
> all: Apply codeql fixes

- cmd/serve/docker/options.go
Upon remount an empty fs option leeds to a parsing error and thus does not recreate the volume after docker restart
rclone volume plugin does not remount crypt volume on docker restart #6769
I have checked that in case the fs option is passed, the value must be != ""
- [n/a] I have added documentation for the changes if appropriate.
> docker volume plugin restoreState: skip fs option if empty - fixes #6769

- docs/content/bisync.md
Small clarification/rephrase on the `--resync` flag according on the behavior I understood reading the docs.
Please, check if this way to explain it make sense. I was very confused by the former statement:
> a newer version of a file on the Path2 filesystem will be overwritten by the Path1 filesystem version
- Will the _"newer version [...] be overwritten by"_?
- Isn't the newer version overwriting the older? This was my main confusion.
Hope this helps,
Cheers!
---
No
> docs(bisync): Small clarification on `--resync`

- backend/mega/mega.go
- go.mod
- go.sum
Some ISPs throttle HTTP connections, this causes transfers to become very slow.
The go-mega backend recently implemented an option to use https instead for transfers, which this commit adds an option to enable.
it also updates the go-mega library.
No
> backend: MEGA - Add "Use HTTPS" for transfers option

- cmd/cmd.go
- cmd/tree/tree.go
- lib/terminal/terminal.go
On Windows this makes sure console mode `ENABLE_VIRTUAL_TERMINAL_PROCESSING` is enabled on the rclone process, by using `GetConsoleMode`/`SetConsoleMode` functions from Windows API. This mode is default in many cases, e.g. when using the Windows Terminal application, but in other cases it relies on a registry setting:
```
[HKEY_CURRENT_USER\Console]
"VirtualTerminalLevel"=dword:00000001
```
(I'm still confused as to exactly how this works; when it is default enabled and not, as can be seen from the discussions in the linked PR and forum thread, but seems certain that it is not always enabled by default and therefore it is better to set it explicitly on the process).
Since rclone version 1.61.0 the tree command uses ANSI color sequences in output by default, and this lead to issues in some …
> Enable console virtual terminal sequences processing (ANSI/VT100 colors)

- backend/drive/drive.go
- backend/drive/drive_internal_test.go
Before this change, if a "--drive-stop-on-upload-limit" was set, rclone would not stop the upload if a "storageQuotaExceeded" error occurred.
This fix now checks for the "storageQuotaExceeded" error and "--drive-stop-on-upload-limit", and fails fast.
https://forum.rclone.org/t/google-drive-add-ability-to-stop-on-storagequotaexceeded/36290
Command:
```sh
rclone copy my-drive1:Test.mkv my-drive2: -P --drive-stop-on-upload-limit
```
*Before*
```
2023-03-06 16:49:31 ERROR : Test.mkv: Failed to copy: googleapi: Error 403: The user's Drive storage quota has been exceeded., storageQuotaExceeded
2023-03-06 16:49:31 ERROR : Attempt 1/3 failed with 1 errors and: googleapi: Error 403: The user's Drive storage quota has been exceeded., storageQuotaExceeded
2023-03-06 16:49:34 ERROR : Test.mkv: Failed …
```
> drive: Make --drive-stop-on-upload-limit to respond to storageQuotaExceeded

- cmd/size/size.go
for `rclone size` documentation, 
change `Google Drive` to `Google Docs`
the docs needs a small tweak, from `Google Drive` to `Google Docs`
https://forum.rclone.org/t/storage-used-remotely/36802/5
> Update size.go documenation, change "Google Drive" to "Google Docs"

- README.md
- backend/webdav/api/types.go
- backend/webdav/webdav.go
- docs/content/_index.md
- docs/content/overview.md
- docs/content/webdav.md
This provider:
- supports the `X-OC-Mtime` header to set the mtime
- calculates SHA1 checksum server side and returns it as a `ME:sha1hex` prop
To differentiate the new hasMESHA1 quirk, the existing hasMD5 and hasSHA1
quirks for Owncloud have been renamed to hasOCMD5 and hasOCSHA1.
Fixes #6837
---
Add a WebDAV provider for Fastmail Files that understands the way it provides SHA1 hashes, so that it can be used with `--checksum`.
#6837
> webdav: add "fastmail" provider for Fastmail Files

- .github/workflows/build.yml
```
*: Matches zero or more characters, but does not match the / character. For example, Octo* matches Octocat.
**: Matches zero or more of any character.
```
(https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)
https://github.com/rclone/rclone/pull/6854#issuecomment-1472299615
> build: run workflow even if tag/branch name contains slash

- backend/sftp/sftp.go
When using ssh-agent to hold multiple keys, it is common practice to configure openssh to use a specific key by setting the corresponding public key as the `IdentityFile`. This change makes a similar behavior possible in rclone by having it parse the `key_file` config as the public key when `key_use_agent` is `true`.
rclone already attempted this behavior before this change, but it assumed that `key_file` is the private key and that the public key is specified in `${key_file}.pub`. So for parity with the openssh behavior, this change makes rclone first attempt to read the public key from `${key_file}.pub` as before (for the sake of backward compatibility), then fall back to reading it from `key_file`.
Fixes #6791
As above.
#6791
> sftp: also try reading pubkey from keyfile when using ssh-agent

- .github/workflows/build_publish_beta_docker_image.yml
* Fixed an issue added in https://github.com/rclone/rclone/pull/6698 where the pipeline references a non-existing dockerfile
* Renamed the workflow to make it clear that this is the pipeline for beta container images
* Removed the "workflow_dispatch" trigger for this workflow as it appears to be unused
#5319 
- [ x ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ x ] I have added tests for all changes in this PR if appropriate.
- [ x ] I have added documentation for the changes if appropriate.
- [ x ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ x ] I'm done, this Pull Request is ready for review :-)
> # 5319 Fix dockerfile reference in beta image pipeline

- cmd/ncdu/ncdu.go
It refactors the handling of our `Draw` function, the tcell `Screen.Show` and `Screen.Sync` functions, the tcell resize event and the tcell `Ctrl-L` keyboard event.
This change should make it smoother and changes more instantaneous.
This also renames the `ncdu.Show` function to `ncdu.Run`, to reduce confusion with `Screen.Show`.
n/a
> cmd/ncdu: refactor redraw handling

- cmd/help.go
- cmd/rcd/rcd.go
- cmd/serve/http/http.go
- cmd/serve/restic/restic.go
- cmd/serve/webdav/webdav.go
- fs/rc/rcflags/rcflags.go
- lib/http/auth.go
- lib/http/auth_test.go
- lib/http/server.go
- lib/http/server_test.go
- lib/http/template.go
- lib/http/template_test.go
This change addresses two issues with commands that re-used flags from common packages:
1) cobra.Command definitions did not include the command specific
prefix in doc strings.
2) Command specific flag prefixes were added after generating
command doc strings.
#6675
> cmd/rcd: Fix command docs to include command specific prefix (#6675)

- vfs/help.go
- vfs/vfsflags/vfsflags.go
This change adds a section to the help to clarify how exactly the --vfs-cache-max-age flag affects caching
Going off of the discussion in #5793
> Docs: add section about --vfs-cache-max-age - Fixes #5793

- cmd/bisync/testdata/test_check_access_filters/scenario.txt
- cmd/check/check.go
- cmd/cryptcheck/cryptcheck.go
- cmd/serve/sftp/sftp.go
- cmd/test/test.go
- cmd/touch/touch.go
I have left out two suggestions:
* `synching` → `syncing` (too intrusive so I feel it would need a merge request of its own)
* a few occurrences of `crypted` → `encrypted` (they would have changed the command)
No.
> cmd: fix typos found by codespell

- docs/content/commands/rclone_check.md
- docs/content/commands/rclone_cryptcheck.md
-Mention default number of parallel checks when running rclone check/cryptcheck.
-Link documentation of option `--checkers` for detailed information.
Dont know
> Docs: add info about # of parallel checks for rclone check/cryptcheck

- fs/accounting/transfer.go
- fs/backend_config.go
- fs/operations/operations_test.go
- fs/rc/rc.go
Not sure about the `thess` → `these` and `Likey` → `Likely` changes. Please double-check.
By the way, codespell suggested to change `Unknwon` → `Unknown` here:
https://github.com/rclone/rclone/blob/3b4a57dab954fbbaecf692f1814e9372e7692c95/fs/config/configfile/configfile.go#L12
I haven't changed anything, of course, but I thought I'd mention that https://github.com/Unknwon/goconfig reads:
> **IMPORTANT**
> 
> - This library is under bug fix only mode, which means no more features will be added.
> - I'm continuing working on better Go code with a different library: [ini](https://github.com/go-ini/ini).
No.
> fs: fix typos found by codespell

- .golangci.yml
- fs/config/configfile/configfile.go
Testing the `misspell` linter in golangci-lint: Activates the spell-checking linter `misspell` available with golangci-lint, and fixes reported issues on current codebase, as well as exclude comment in one one place where there is a false positive.
> According to docs, by default it only checks comments in .go files, and must be configured to check entire source files for it to detect errors in strings. But the golangci-lint integration is always checking entire source ("Treat Go source files as a plain text by misspell: it allows detecting issues in strings, variable names, etc.", [ref](https://github.com/golangci/golangci-lint/blob/master/CHANGELOG.md#june-2019)). Strings are way more important than comments, at least in rclone, to get all the help texts correct, which are also used for …
> Add misspell linter to build pipeline

- .golangci.yml
- backend/box/box.go
- go.mod
- lib/jwtutil/jwtutil.go
golang.org/x/oauth2/jws is deprecated
> this package is not intended for public use and might be removed in the future. It exists for internal use only. Please switch to another JWS package or copy this package into your own source tree.
github.com/golang-jwt/jwt/v4 seems to be a good alternative, and was already an implicit dependency.
Box backend is affected. Code change in common lib/jwtutil as well as backend/box, but only box implementation uses jwtutil I think.
❗ Untested ❗
> Use jwt-go (golang-jwt) instead of deprecated jws (x/oauth2/jws)

- backend/webdav/webdav.go
This adds the config argument `--webdav-pacer-min-sleep` which specifies the http-request rate limit, keeping the previous default of 10ms. Reducing this value can be very beneficial when synchronizing small files.
Yes; https://forum.rclone.org/t/webdav-with-persistent-connections/37024/10
the autogenerated documentation seems to cover this change appropriattely, and I believe the change is trivial enough that it doesn't need any additional tests :>
> webdav: make pacer minSleep configurable

- backend/sftp/sftp.go
Add an option `host_key_algorithms` to the SFTP backend such that you can specify `--sftp-host-key-algorithms` as a list of SSH host key algorithms in preference order. For example:
```
--sftp-host-key-algorithms ssh-ed25519,ssh-rsa
```
This can be useful when working with hosts that have a non-standard SSH implementation or when you have a particular preference for a type of SSH host keys.
Yes but not by me.
I found this [forum thread](https://forum.rclone.org/t/simple-sftp-connection-fails-with-eof/35065/5) and I have the same issue with the SFTP backend against a Remarkable running dropbear SSH. While I agree with comments by `ncw` in that thread that this is potentially an issue on the server side I would much prefer a client side fix given that the server side is a proprietary …
> backend: allow specifying SSH host key algorithms to use for sftp

- docs/content/docs.md
- fs/config/configfile/configfile.go
- fs/config/configfile/configfile_test.go
See commit messages and issues linked from those.
The following example should also illustrate the changes.
Given symbolic link:
```
tempconfig.txt -> tempconfig/temp/tempconfig.txt
```
Then:
```
./rclone -vv config create yyy local --config=tempconfig.txt
2023/04/04 16:42:36 DEBUG : rclone: Version "v1.63.0-DEV" starting with parameters ["./rclone" "-vv" "config" "create" "yyy" "local" "--config=tempconfig.txt"]
2023/04/04 16:42:36 DEBUG : Using config file from "/home/user/projects/rclone/tempconfig.txt"
2023/04/04 16:42:36 DEBUG : yyy: config in: state="", result=""
2023/04/04 16:42:36 DEBUG : yyy: config out: out=<nil>, err=<nil>
2023/04/04 16:42:36 DEBUG : Saving config file: /home/user/projects/rclone/tempconfig.txt
2023/04/04 16:42:36 DEBUG : Config path resolved to: …
```
> Config file save improvements

- lib/buildinfo/osversion_windows.go
I just noticed the os/kernel output from rclone version command has become verbose and repetitive:
```
rclone v1.62.2
- os/version: Microsoft Windows 10 Enterprise 22H2 (64 bit)
- os/kernel: 10.0.19045.2728 Build 19045.2728.2728 (x86_64)
```
Found the reason is the external gopsutil library started to include the UBR (Update Build Revision) in the kernel version string that we use, since version [3.22.12](https://github.com/shirou/gopsutil/releases/tag/v3.22.12).
This PR removes our own code for retrieving and appending the UBR value, and also fixes the parsing of the kernel version to simplify it to pure 4 part numeric string as before. Seems safe to assume the output string is always in format `MAJOR.MINOR.BUILD.REVISION Build BUILD.REVISION`, see: …
> version: fix reported os/kernel version for windows

- cmd/serve/restic/restic.go
I would like to react for systemd notify hooks to savely build my backup scripts.
I have an Restic Service + Restic Timer and they start Rclone before they run. I want to make it safe that the Restic API is ready before the Restic process itself starts. Therefore I want to use `Type=notify` on my Rclone.
Nope
> serve: trigger systemd notify for restic

- cmd/mountlib/help.go
Update mount documentation with guidance for macFUSE installed via macports
Adding instructions for creating symlinks to macfuse libraries installed via the macports package manager
https://github.com/rclone/rclone/issues/6807
> Update mount documentation with guidance for macFUSE installed via macports

- vfs/file.go
- vfs/write.go
- vfs/write_test.go
webdav will fail when the underlying storage is readonly and client issued a request that will modify the underlying storage. This commit will remove the invalid vfs file entry when file is closed so webdav will continue to function.
[Yes](https://github.com/rclone/rclone/issues/5702#issuecomment-964903133)
> vfs: fix invalid cache object - fixes #5702

- backend/crypt/cipher.go
- backend/crypt/cipher_test.go
- backend/crypt/crypt.go
Adds an additional option when encrypting files allowing for a custom suffix.
#6932
> crypt: adding an option to set a custom_suffix #6392

- cmd/bisync/bisync_test.go
- cmd/cat/cat.go
- docs/content/commands/rclone_cat.md
- fs/operations/operations.go
- fs/operations/operations_test.go
When using `rclone cat` to print the contents of several files, the
user may want to inject some separator between the files, such as a
comma or a newline. This patch adds a `--separator` option to the `cat`
command to make that possible. The default value remains an empty
string, `""`, maintaining the prior behavior of `rclone cat`.
Closes #6968
* https://forum.rclone.org/t/print-new-line-between-files-when-using-rclone-cat/37732/14
* https://github.com/rclone/rclone/issues/6968
> cat: adds --separator option to cat command

- backend/ftp/ftp.go
Changed "SetModTime not supported" feature to print out the information from `Errorf` to `Debugf`.
Functionality was given before, so the message could be considered more of a warning.
It was / is observed with different ftp implementations - confirmed with the implementation of `FRITZ!Box 7530 - FRITZ!OS:7.51-104920 BETA`
https://forum.rclone.org/t/ftp-fritz-box-setmodtime-is-not-supported/37781
> Making SetModTime less scary by printing as Debugf.

- backend/webdav/webdav.go
Rclone will set the modified time of the object instead of reuploading for owncloud.
Rclone forum [post](https://forum.rclone.org/t/rclone-sync-between-two-webdav-issues/14061/5).
This change is based on [owncloud issue](https://github.com/owncloud/core/issues/2542#issuecomment-15385897).
Tested against [owncloud quick evaluation](https://doc.owncloud.com/server/next/admin_manual/installation/docker/#quick-evaluation).
> webdav set modtime using propset for owncloud

- cmd/mount/handle.go
Removed unnecessary byte slice allocation for reads in mount
N/A
> mount: removed unnecessary byte slice allocation for reads

- fs/accounting/accounting_unix.go
- fs/accounting/token_bucket.go
The SIGUSR2 signal handler for bandwidth limits currently only starts _if rclone is started at a time when a bandwidth limit applies_. This means that if rclone starts _outside_ such a time, i.e. when there's no bandwidth limits, _then_ enters a time when bandwidth limits do apply, it will not be possible to use SIGUSR2 to toggle it.
This PR fixes that by always starting the signal handler, but only toggling the limiter if there is a bandwidth limit configured.
It also removes the `tb.currLimitMu` mutex because it doesn't seem to serve a purpose that `tb.mu` doesn't already do, at least from what I can see. Happy to add it back in if needed though!
No.
> fix(fs/accounting): bwlimit signal handler should always start

- cmd/mountlib/help.go
- docs/content/commands/rclone_mount.md
It used to be discussed in #6459 and fixed in #5911 and 7fbc928a19431f566b87c8c33d98fbb5099dad5f, but was overwritten by auto-generation in 01dbbff62e2470603d0c3abf4adf5c96e60cdbb5.
> docs: remove "After" in systemd mount example again

- cmd/mountlib/help.go
mount: Added _netdev to the example mount so it gets treated as a remote-fs rather than local-fs
Added _netdev to the example mount so it gets treated as a remote-fs rather than local-fs
https://github.com/rclone/rclone/pull/7075#issuecomment-1604304122
> mount: Added _netdev to the example mount

- docs/content/docs.md
- fs/config.go
- fs/config/configflags/configflags.go
- fs/operations/multithread.go
This change adds an option to buffer multithread download parts before writing to disk.
In our testing, we saw that multithreaded downloads from S3 to CIFS (as a mounted filesystem) were much slower with rclone than with the official aws cli. Interestingly, single-threaded downloads were faster than multi-threaded, albeit still far away from what our bandwidth should offer. Downloads to local disk were fine.
The end result looked like this for us:
rclone standard: ~50 MiB/s
rclone with --multi-thread-buffer-size=1M: 400MiB/s+ 
this is close to our max theoretical speed based on bandwidth (5Gib/s)
I did consider just using the already existing buffer-size option, as it does seem to to exactly the same, only for multiple transfers. However I wasn't 100% sure, and with the extra option there …
> fs: allow setting a write buffer for multithread

- cmd/listremotes/listremotes.go
- docs/content/commands/rclone_listremotes.md
"rclone listremotes" lists all the remotes in the config file and defined in environment variables. This is was clear from documentation.
> docs: listremotes also includes remotes from env vars

- docs/content/s3.md
example in the [documentation](https://rclone.org/s3/#restore) doesn't seem to work:
`rclone backend restore s3:bucket/path/to/object [-o priority=PRIORITY] [-o lifetime=DAYS]`
should be:
`rclone backend restore s3:bucket/path/to --include object [-o priority=PRIORITY] [-o lifetime=DAYS]
`
https://forum.rclone.org/t/cant-restore-files-from-aws-glacier-deep-only-directories/39258/3
> Update s3.md (documentation) - restoring single objects from glacier requires --include argument

- backend/s3/s3.go
When I use the s3 backend of Qiniu provider, setting `force_path_style` does not work, it always use virtual-host style. I need to modify the processing for Qiniu in setQuirks in rclone.
> s3: add Qiniu KODO quirks virtualHostStyle is false

- backend/dropbox/batcher.go
Fix the dropbox batcher stalling bug described in #7025 
closes #7025 
in issue #7025
> fix(dropbox): fix result chans not taken care by defer fun

- docs/content/filtering.md
The exclude flag instructions had "without" written as "with" which changes the whole meaning of how the exclude flag works.  Corrected
To correct a small typo in the example of an exclude flag. 
No.
> Fixed a small typo in filtering.md for exclude

- docs/content/mailru.md
This sentence was written at the time when backend used access token, nowadays, users need to generate and use application password instead, see #6398. The application password can be used without 2FA being turned off.
#6398
> docs: no need to disable 2FA for Mail.ru Cloud anymore

- backend/webdav/chunking.go
Make it more clear that the user has to change the configuration. The current message sounds more like a code bug that it calculated the wrong url.
https://github.com/rclone/rclone/issues/7103#issuecomment-1627773153
> Add more guidance for the user to check the config.

- backend/box/box.go
The error is:
> Error: failed to configure token with jwt authentication: jwtutil: failed making auth request: 400 Bad Request
With the following additional debug information:
> jwtutil: Response Body: {"error":"invalid_grant","error_description":"Please check the 'aud' claim. Should be a string"}
Problem is that in jwt-go the RegisteredClaims type has Audience field (aud claim) that is a list, while box apparantly expects it to be a singular string. In jwt-go v4 we currently use there is an alternative type StandardClaims which matches what box wants. Unfortunately StandardClaims is marked as deprecated, and is removed in the newer v5 version, so we this is a short term fix only. Edit: Suggested long term fix compatible with v5 here: https://github.com/rclone/rclone/pull/7116.
Fixes …
> Box: Fix reconnect failing with HTTP 400 Bad Request

- README.md
- backend/s3/s3.go
- docs/content/s3.md
> s3: Add Leviia S3 Object Storage as provider

- cmd/cmd.go
- docs/content/docs.md
- docs/content/flags.md
- fs/sync/sync.go
- fs/sync/sync_test.go
- lib/exitcode/exitcode.go
The purpose of this PR is to add dedicated exit code (10) for `--max-duration` flag.
Rclone will exit with exit code 10 if the duration limit is reached.
It will behave in similar fashion as `--max-transfer` and exit code 8.
discussed on the forum:
https://forum.rclone.org/t/max-duration-option-is-triggering-exit-with-error/39917/6
> --max-duration flag -  add new exit code (10)

- docs/content/crypt.md
As suddenly many people keep moving data to Box remote (another "unlimited" cloud story migration saga) there are frequent questions about crypt files encoding to be used. Box has 1024 max path limit but for people coming from Google it is often not enough:)
It has been tested with:
https://pub.rclone.org/base32768.zip files (`copy` all files to box and run `rclone check`)
and:
```
$ rclone test info --check-length box_remote:
maxFileLength = 255 // for 1 byte unicode characters
maxFileLength = 255 // for 2 byte unicode characters
maxFileLength = 255 // for 3 byte unicode characters
maxFileLength = -1 // for 4 byte unicode characters
```
In addition few users took risk and used it for their migration without any issues.
As a conclusion I suggest to update `crypt` docs to avoid forum …
> docs: mention Box as base32768 compatible

- cmd/mountlib/check_linux.go
- go.mod
- go.sum
fix: mount parsing for linux under the WSL layer which may contain mounts with spaces
Fixes mount parsing for linux under the WSL layer which may contain mounts with spaces.
https://forum.rclone.org/t/fatal-error-failed-to-mount-fuse-fs-cannot-read-proc-mounts-expected-integer/40034/
> fix: mount parsing for linux

- docs/content/chunker.md
Update chunker documentation to warn users that chunker will still rename and move small files below the chunk threshold. This will lead to wasted API calls, and in the case of more restricted backends like Box, can lead to a massive decrease in throughput.
https://forum.rclone.org/t/chunker-not-deactivating-for-small-files-and-wasting-api-calls/40122
#5108 (?)
> chunker: Update documentation to mention issue with small files

- cmd/test/info/info.go
Fix typo found in log error 
"log.Fatalf("no tests selected - select a test or use -all") -> log.Fatalf("no tests selected - select a test or use --all")
No.
> cmd: fix log message typo

- backend/protondrive/protondrive.go
- Fixed the sha1 issue discussed [here](https://github.com/rclone/rclone/pull/7093#discussion_r1271242878)
- Address the bug with `linux` client in the app string [here](https://github.com/rclone/rclone/issues/6072#issuecomment-1646651273) 
#6072
- [Issue 1](https://github.com/rclone/rclone/pull/7093#discussion_r1271242878)
- [Issue 2](https://github.com/rclone/rclone/issues/6072#issuecomment-1646651273)
> protondrive: fix missing file sha1 and appstring issues

- backend/smb/smb.go
This PR makes it possible to do multi-threaded / parallel writes to the SMB backend
Implement the OpenWriterAt feature by adding a OpenWriterAt function on the smb backend. It returns the smb2.File Object, which implements the WriterAtCloser interface defined in `fs/types.go`.
No
> Multi-threaded / parallel writes to SMB

- fs/rc/rc.go
- fs/rc/rcflags/rcflags.go
- fs/rc/rcserver/rcserver.go
- fs/rc/rcserver/rcserver_test.go
- lib/http/middleware.go
- lib/http/middleware_test.go
- lib/http/server.go
- lib/http/server_test.go
fix CORS issue with `rclone serve http`, `rclone serve webdav`, `rclone rcd`
discussed at [#5078](https://github.com/rclone/rclone/issues/5078#issuecomment-1607847580)
~~**Help wanted for this PR:** I am not sure how to update the auto-generated documentation. This PR removed `--rc-allow-origin` option and added new `{prefix}-allow-origin` option ([source code](https://github.com/rclone/rclone/blob/46e155ae0c4d7c667267bc2a4b49040c1eb44a65/lib/http/server.go#L126)). So the usage of `--rc-allow-origin` is not changed. I don't know if I need to update the documentation of this part. And this `{prefix}-allow-origin` also apply to `rclone serve http` and I don't know if I need to update this part.~~
edit:
I tried to run `make doc` and found everything is generated correctly.
> http: Fix CORS issue of `rc` and `serve http/webdav`

- docs/content/s3.md
When using `--s3-versions` flag rclone is relying on the file name
to work out whether the objects are versions or not. Versions' names
are created by inserting timestamp between file name and its extension.
```
9 file.txt
8 file-v2023-07-17-161032-000.txt
16 file-v2023-06-15-141003-000.txt
```
If there are real files present with the same names as versions, then
behaviour of `--s3-versions` can be unpredictable.
discussed on the forum: https://forum.rclone.org/t/cannot-copy-the-versioned-files-again-after-rclone-copy-with-s3-versions/40280/15
> docs: s3 versions names caveat

- docs/content/b2.md
When using --b2-versions flag rclone is relying on the file name
to work out whether the objects are versions or not. Versions' names
are created by inserting timestamp between file name and its extension.
9 file.txt
8 file-v2023-07-17-161032-000.txt
16 file-v2023-06-15-141003-000.txt
If there are real files present with the same names as versions, then
behaviour of --b2-versions can be unpredictable.
> docs: b2 versions names caveat

- fs/rc/jobs/job.go
- fs/rc/jobs/job_test.go
Currently we have rc api `job/list` to list backend jobs, but because user may restart backend or frontend at anytime, frontend cannot track job by `job_id` because it starts counting from `1` on every restart, so we need a new field to help track the job.
A new field `execute_id` would help. It will be generated on every restart and not changed during running. Frontend will know the `job_id` is no longer used when detect `execute_id` changes.
#7095 (waiting for discussion)
> rc: add execute-id for job-id

- backend/s3/s3.go
priority and lifetime "options" are actually mandatory
discussed on forum:
https://forum.rclone.org/t/is-rclone-backend-restore-from-aws-glacier-broken/39792
> docs: rclone backend restore

- fs/rc/rcserver/rcserver.go
- lib/http/middleware.go
- lib/http/middleware_test.go
fix CORS option, if `--allow-origin` option is not set, CORS headers should not be sent
#6433
> http: CORS should not be send if not set (#6433)

- backend/sftp/sftp.go
Before this change, rclone always expected `--sftp-path-override` to be the absolute SSH path to `remote:path/subpath` which effectively made it unusable for wrapped remotes (for example, when used with a `crypt` remote, the user would need to provide the full decrypted path.)
After this change, the old behavior remains the default, but dynamic paths are now also supported, if the user adds `@` as the first character of `--sftp-path-override`. Rclone will ignore the `@` and treat the rest of the string as the path to the SFTP remote's root. Rclone will then add any relative subpaths automatically (including unwrapping/decrypting remotes as necessary).
In other words, the `path_override` config parameter can now be used to specify the _difference_ between the SSH and SFTP paths. Once …
> sftp: support dynamic --sftp-path-override

- backend/webdav/chunking.go
Fix https://github.com/rclone/rclone/issues/7168
Co-authored-by: ncw <nick@craig-wood.com>
Co-authored-by: Paul <devnoname120@gmail.com>
Fix segmentation violations due to nil dereferences.
All credits go to @ncw for debugging and finding the mistake in `GetBody()`.
- https://forum.rclone.org/t/panic-after-updating-to-v1-63-1/40226
- https://github.com/rclone/rclone/issues/7168
> webdav: nextcloud: fix segment violation in low-level retry

- lib/http/middleware.go
- lib/http/middleware_test.go
- lib/http/server_test.go
fix behavior changes of webdav server OPTIONS reponse on commit 6c8148ef39ea51b1d4092128c598ac12c6fc1523
#6433
> http: fix webdav OPTIONS response (#6433)

- backend/swift/swift.go
Swift returns zero length for dynamic large object files when they're included in a files lookup, which means that determining their size requires `HEAD`ing each file that returns a size of zero. rclone's `--swift-no-large-objects` instructs rclone that no large objects are present and accordingly rclone should not `HEAD` files that return zero length.
When rclone is performing an `ls` / `lsf` / `lsl` type lookup, however, it continues to `HEAD` any zero length objects it encounters, even with this flag set. Accordingly, this change causes rclone to respect the flag in these situations.
NB: It is worth noting that this will cause rclone to incorrectly report zero length for any dynamic large objects encountered with the `--swift-no-large-objects` flag set.
Yep — [right …
> swift: not HEADing 0-length objects when flag set

- backend/oracleobjectstorage/byok.go
- backend/oracleobjectstorage/command.go
- backend/oracleobjectstorage/multipart.go
- backend/oracleobjectstorage/object.go
- backend/oracleobjectstorage/options.go
- backend/oracleobjectstorage/oracleobjectstorage.go
- docs/content/local.md
- docs/content/oracleobjectstorage.md
- docs/content/oracleobjectstorage/tutorial_mount.md
In OCI-SDK the multi part uploader doesn't take rclone's pacer to rate limit the part upload calls.
Also it doesn't have throttling to not read from source if the parts upload to destination is going slow. 
Fixes:
- rewrote and made multipart upload use rclone's pacer
- Added --attempt-to-resume-upload from a past ongoing multipart upload. This is helpful to skip parts already uploaded when rclone process restarts for any reason.
- Fail fast on a part failure.
- throttle the source reading parts if destination part push is throttled.
- use memory pool map for part buffers like s3 mutipart upload.
- Added a tutorial on how to mount object storage buckets as local file system and via NFS server.
> oracleobjectstorage: Use rclone's rate limiter in multipart transfers

- lib/rest/rest.go
Just a pedantic change.
From the Go docs:
> "A `nil` map is equivalent to an empty map. https://go.dev/ref/spec#Map_types
Therefore, an additional nil check for `opts.ExtraHeaders` before the loop is unnecessary because `opts.ExtraHeaders` is a `map`. Example: https://go.dev/play/p/EnnDEF7svOd
No.
> lib/rest: remove unnecessary nil check

- backend/chunker/chunker_test.go
- backend/combine/combine_test.go
- backend/compress/compress_test.go
- backend/crypt/crypt_test.go
- backend/hasher/hasher_test.go
- backend/s3/s3.go
- backend/union/union_test.go
- fs/config.go
- fs/config/configflags/configflags.go
- fs/features.go
- fs/open_options.go
- fs/operations/multithread.go
- fs/operations/multithread_test.go
- fstest/fstests/fstests.go
Following the discussions in https://github.com/rclone/rclone/pull/7061 and https://github.com/rclone/rclone/issues/7056 this change is meant to pave the way for fast parallel transfers between remotes.
It defines the interfaces suggested by @jorjao81 and implements them for the S3 and Local backend. 
Also, the s3.uploadMultipart logic was refactored to use OpenChunkWriter and ChunkWriter (s3 multi part uploads should behave the same as before).
In [https://github.com/rclone/rclone/pull/7061](https://github.com/rclone/rclone/pull/7061#issuecomment-1594949243) - @ncw suggested the following roadmap:
Therefore, the next steps would be:
Looking forward to some feedback. I'm not experienced with Go, so apologies for any (dumb) mistake. 😅
https://github.com/rclone/rclone/pull/7061 …
> Add OpenChunkWriter and ChunkWriter interfaces and refactor s3.uploadMultpart and multiThreadCopy to use them

- fs/accounting/stats.go
Currently, the average transfer speed will stop calculating 1 minute after the last queued transfer completes. This causes the average to stop calculating when checking is slow and the transfer queue becomes empty.
This change will require all checks to complete before stopping the average speed calculation.
No - I was doing an rclone transfer with a slow backend that took a while to run checks and noticed that the average transfer speed stopped updating.
I have tested this change with my slow remote, and stats continue to update past the 1 minute mark, despite it depleting the transfer queue while it ran checks.
I tried running `go test ./...` - but this currently fails for me on the `master` branch as well, so I'm waiting on CI to check tests.
> fs: Don't stop calculating average transfer speed until the operation is complete

- fs/accounting/stats.go
- fs/accounting/stats_test.go
transferTime is always 0 in JSON logs (and anything else that uses `RemoteStats()`.)
This was unintentionally broken in https://github.com/rclone/rclone/commit/04aa6969a47516643cdf9084f9cdeae320a3bb81#diff-6a0766bcecac2744ee5f6050fdd22077ff967a44fb9df9fc2711130fcde3230bL279
No - found while looking at JSON logs when using rclone
- Added unit test
- Tested locally and confirmed that --use-json-log shows transferTime counting in seconds as a float
> fs: Fix transferTime not being set in JSON logs

- .github/workflows/winget.yml
Winget Releaser now supports non-Windows runners, and `ubuntu-latest` is generally faster.
> ci: change Winget Releaser job to `ubuntu-latest`

- backend/oracleobjectstorage/multipart.go
- backend/oracleobjectstorage/object.go
- backend/oracleobjectstorage/options.go
- backend/oracleobjectstorage/oracleobjectstorage.go
- docs/content/oracleobjectstorage.md
- fstest/test_all/config.yaml
Use the new ChunkWriter interfaces for multi part uploads introduced in https://github.com/rclone/rclone/pull/7154
Yes, in https://github.com/rclone/rclone/pull/7154 and in https://github.com/rclone/rclone/issues/7056
> oracleobjectstorage: Use ChunkWriter Interfaces

- docs/content/filtering.md
"may not" can be interpreted as "is not allowed".
Replaced with "might not" in both cases to remove this ambiguity.
> "may not" -> "might not" to remove ambiguity

- backend/box/api/types.go
- backend/box/box.go
Adds polling support to the box backend, so that `--poll-interval` can be used for mounts. box can have some very restrictive API limits, so polling support helps to reduce this (as opposed to just setting a low `--dir-cache-time`).
No.
> box: add polling support

- docs/content/docs.md
clarifies how single character letter remote's names are interpreted in Windows (as drive letters)
discussed on the forum: https://forum.rclone.org/t/issue-with-single-character-configuration-on-windows-with-rclone/
> docs: single character letter remotes' names in Windows

- backend/jottacloud/jottacloud.go
jotta: added Telia Sky whitelabel (Norway)
Duplicated Telia Cloud (Sweden) changed the URLs and added teliase and teliano (instead of just telia) to differentiate
(Note that it seems like Telia Sky has issues at the moment, I'm getting `2023/08/16 07:24:52 Fatal error: failed to get oauth token: Get "https://sky-auth.telia.no/auth/realms/get/.well-known/openid-configuration": read tcp x.x.x.x:60990->185.179.129.26:443: read: connection reset by peer`)
Add Telia Sky as an config option, so you can more easily add it (instead of manually changing in URL)
https://github.com/rclone/rclone/issues/5153
https://github.com/rclone/rclone/issues/5016
> jotta: added Telia Sky whitelabel (Norway)

- backend/b2/b2.go
I came across an error when following a link generated by `rclone link`. For example, if an object is named `a & b`, the link currently looks like: `https://f000.backblazeb2.com/file/my-bucket/a & b`. Following this link returns a `400` error with:
```json
{
"code": "bad_request",
"message": "Bad character in percent-encoded string: 38 (0x26)",
"status": 400
}
```
The B2 [encoding docs](https://www.backblaze.com/docs/cloud-storage-native-api-string-encoding#url-encoding) state the following:
> When you download a file by name, you must URL-encode the file name before you append it to the download URL
> Some characters, such as "&" are safe in some contexts and not others. For consistency, Backblaze B2 requires that you percent-encode them every time.
`&` is not in `noNeedToEncode`, so we …
> b2: generate valid link when object path contains special characters

- vfs/dir.go
- vfs/dir_test.go
I noticed that when doing actions on files/directories in a rclone mounted directory that the modtime on the parent directory was never updated. [lf](https://github.com/gokcehan/lf) relies on this information to know when to refresh a directory, but as it was never updated, any changes to files would not show up. [ranger](https://github.com/ranger/ranger) seems to have the same problem.
This PR replicates the normal unix behavior (same as sshfs) which is to update the modtime of the parent directory when creating/renaming/removing files/directories.
> Update parent dir modtime on vfs actions

- backend/protondrive/protondrive.go
- docs/content/protondrive.md
Implements the [two-password mode](https://proton.me/support/switch-two-password-mode).
Feature request (or it's kind of a bug :D) from https://github.com/rclone/rclone/issues/6072#issuecomment-1704380975 and https://github.com/rclone/rclone/issues/6072#issuecomment-1704378529.
> protondrive: implement two-password mode

- fs/operations/operations.go
- fs/operations/rc.go
- fs/operations/rc_test.go
This change adds `operations/settier` to the API. It behaves in a way similar to the `rclone settier` CLI option.
A couple things I'm not sure how to best handle, would love any pointers/examples on how to make this better:
* Test case currently looks for the SetTier feature, which doesn't appear to be in the test framework, so while there is a test case, I don't think it's being properly evaluated
* In my local testing, even when the remote is set to a file, the settier is being done on the entire remote directory. I'm unsure why this is, or what the best fix is
https://forum.rclone.org/t/using-settier-with-librclone/41461/2
> rc: Add operations/settier to API

- fs/operations/multithread.go
This change fixes a minor bug in multithreaded copy that allowed more parallel streams to be used than there were chunks to transfer.
See issue https://github.com/rclone/rclone/issues/7299
> operations: ensure concurrency is no greater than the number of chunks - fixes #7299

- backend/storj/fs.go
- go.mod
- go.sum
The improved upload logic is active by default in uplink v1.12.0, so the `testuplink.WithConcurrentSegmentUploadsDefaultConfig(ctx)` call is not required anymore.
See https://github.com/rclone/rclone/pull/7198
No
> storj: update storj.io/uplink to v1.12.0

- fstest/mockobject/mockobject.go
- lib/http/serve/serve.go
- lib/http/serve/serve_test.go
Set `Last-Modified` header for files served by `--rc-serve`.
To test the changes methods `ModTime` and `SetModTime` were
implemented for `fstest/mockobject.ContentMockObject`.
Fixes #7329
> rcserver: set `Last-Modified` header for files served by `--rc-serve`

- backend/drive/drive.go
- docs/content/drive.md
- docs/content/overview.md
```
$ ./rclone hashsum md5 gsuite:empty
d41d8cd98f00b204e9800998ecf8427e  empty
$ ./rclone hashsum sha1 gsuite:empty # Previously not supported
da39a3ee5e6b4b0d3255bfef95601890afd80709  empty
$ ./rclone hashsum sha256 gsuite:empty # Previously not supported
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  empty
```
Fix #7327
> drive: add support of SHA-1 and SHA-256 checksum

- vfs/vfs.go
- vfs/vfscommon/options.go
- vfs/vfsflags/vfsflags.go
Add vfs/refesh recursive=true flag so it can run w/o needing rc on mount.
closes #6830
> vfs: add refresh flag

- backend/s3/s3.go
When doing S3 multipart uploads, the OpenOption array was not passed to uploadMultipart and openChunkWriter.  
No
> s3: fix OpenOptions being ignored in uploadMultipart with chunkWriter

- lib/http/template.go
Makes the following go strings functions available to be used in custom markup templates for HTTP and WebDAV server functions:
- contains
- hasPrefix
- hasSuffix
This will allow users who specify their own custom markup template for HTTP and WebDAV server to use those strings functions to help them modify how their server pages look.  
https://forum.rclone.org/t/cannot-use-strings-functions-in-user-defined-go-template-for-serve-http/36205
> lib/http: export basic go strings functions

- .github/workflows/build.yml
- .gitignore
- Makefile
- bin/cross-compile.go
- bin/resource_windows.go
- docs/content/install.md
- go.mod
- go.sum
- librclone/README.md
Refactor windows .exe resource (version information and icon) handling, to make it easier (and more flexible) to use with local builds. Will also try to make it usable for building librclone.dll.
This succeeds #6467
> Easier generation of version information and icon resources on Windows

- backend/webdav/webdav.go
- cmd/serve/webdav/webdav_test.go
- docs/content/webdav.md
- fstest/testserver/init.d/TestWebdavRclone
Fixes #7160
This change adds `rclone-serve` as one of the vendors for WebDAV backend. Only the following attributes are set:
- canStream = `true`
- useOCMtime = `true`
Briefly discussed in github issue [#7160 ](https://github.com/rclone/rclone/issues/7160)
> webdav: added a "rclone" WebDAV vendor

- backend/hdfs/fs.go
- backend/hdfs/hdfs.go
Users can now input a list of namenodes when writing config for hdfs remotes.
This is required when you have multiple namenodes in your hdfs cluster and cannot be certain which namenodes will be in 'standby' or 'active' states.
- [✅] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [✅] I have added tests for all changes in this PR if appropriate.
- [✅] I have added documentation for the changes if appropriate.
- [✅] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [✅] I'm done, this Pull Request is ready for review :-)
> Hdfs namenode list fix

- docs/content/install.sh
The install script at [rclone.org/install.sh](https://rclone.org/install.sh) leaves temp files behind, which [increases docker image size](https://forum.rclone.org/t/install-sh-leaves-temp-files-around-inflating-docker-image-size/42940)
https://forum.rclone.org/t/install-sh-leaves-temp-files-around-inflating-docker-image-size/42940
- [ x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ n/a] I have added tests for all changes in this PR if appropriate.
- [ n/a] I have added documentation for the changes if appropriate.
- [ x] I'm done, this Pull Request is ready for …
> install.sh: Clean up temp files in install script

- Makefile
`install -t` doesn't exist on BSD.
flip the arguments since we only have one.
> Makefile: use POSIX compatible install arguments

- lib/http/middleware.go
- lib/http/middleware_test.go
Fixes #7444
Enables the HTTP methods used with WebDAV protocol. It allows requests to rclone WebDAV issued from web browsers, which are currently blocked by CORS policy.
#7444
> #7444 enable WebDAV methods with CORS

- fs/fshttp/dialer.go
- fs/fshttp/http.go
The original `ctx` parameter of func  `dialContext`  is the context of `http request`.
The func `NewDialer` requires the `context of fs` in order to create the `Dialer` using the user-specified `--timeout` and `--contimeout` flasgs.
So add a new parameter `fsCtx` .
None.
> fs/fshttp: use fs ctx instead of request ctx

- backend/smb/connpool.go
- go.mod
- go.sum
Before this change the IP address of the server was used in the SMB connect request (see CloudSoda/go-smb2#18).
Depending on the server configuration this could lead to servers responding differently, e.g., `\\hostname\share` is available, but `\\ip\share` is not.
The updated library now can pass the hostname instead.
The signature of the `Dial*` methods was changed by the library and `connpool.go` updated accordingly.
Fixes rclone#6672
Issue: rclone#6672
Underlying issue: CloudSoda/go-smb2#18
> smb: fix shares not listed by updating go-smb2

- docs/content/s3.md
It was discussed here:
https://forum.rclone.org/t/s3-rclone-v-1-52-0-or-after-permission-denied/21961
But this was not written in the docs. It took me quite few hours to overcome this issue. I didn't know the "permission denied" reason. In the end, I had to use CloudTrail to find out what exactly rclone was trying to do. Then I googled it and only then found the above forum link.
(personally, I added the flag. But this is up to the user to decide what to do)
In my opinion, it should be part of the docs (maybe even with a link to the forum).
Thanks!
> Doc change: Add the CreateBucket permission requirement for AWS S3

- backend/s3/s3.go
- backend/s3/s3_test.go
Currently rclone hangs when IPv4 route to S3 is unavailable (e.g. no IPV4 interface or no IPV4 route to internet ).  This change adds S3 IPv6 "dualstack" endpoint support . Option = `use_dual_stack` [bool] .   Default S3 endpoints are IPv4 NOT IPv6
See AWS docs on IPv6:
"To make a request to an S3 bucket over IPv6, you need to use a dual-stack endpoint."
* https://docs.aws.amazon.com/AmazonS3/latest/userguide/ipv6-access.html
* https://docs.aws.amazon.com/AmazonS3/latest/userguide/dual-stack-endpoints.html
Starting Feb, EC2 will charge for public IPv4 addresses & NAT traffic.  More AWS users will be using rclone & S3 on IPV6
1. Run test from a host with IPv6 address. 
1. If the host has IPv4 address,  use security-group, routing table or firewall to block IPv4 traffic (e.g. outbound …
> Add S3 IPv6 "dualstack" endpoint support . Option = "use_dual_stack" [bool] 

- backend/amazonclouddrive/amazonclouddrive.go
- backend/box/box.go
- backend/hidrive/hidrive.go
- backend/jottacloud/jottacloud.go
- backend/onedrive/onedrive.go
- backend/pcloud/pcloud.go
- backend/premiumizeme/premiumizeme.go
- backend/sharefile/sharefile.go
- lib/oauthutil/renew.go
Before this change, calling the `oauthutil.NewRenew` func may cause goroutine leaks.
This change adds a `Shutdown` method to allow the caller to exit the goroutine to avoid leaks.
None.
> oauthutil: add Shutdown method to avoid goroutine leaks

- backend/azurefiles/azurefiles.go
Azure files are not working because of the invalid base URL. Now it's "core.windows.net", but according to documentation (proved with testing), it should be "file.core.windows.net" - see https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview (Azure Files  - `https://<storage-account>.file.core.windows.net`)
> azure-files: fix storage base url

- librclone/README.md
> docs/librclone: the newer and recommended ucrt64 subsystem of msys2 can now be used for building on windows

- backend/hasher/commands.go
- backend/hasher/hasher.go
- backend/hasher/hasher_internal_test.go
- backend/hasher/hasher_test.go
- lib/kv/bolt.go
When `f.opt.MaxAge` == `0`, `f.db` is never set, however several methods later assume it is set and attempt to access it, causing an invalid memory address error. This change fixes the issue in a few spots (there may still be others I haven't yet encountered.)
No.
> hasher: fix invalid memory address error when MaxAge == 0

- fstest/test_all/config.yaml
- lib/readers/limited.go
Fix multi-stream copy for rclone, [7532](https://github.com/rclone/rclone/issues/7532), [3942](https://github.com/rclone/rclone/issues/3942).
Yes, [7532](https://github.com/rclone/rclone/issues/7532).
> fix ftp multi-thread copy

- lib/oauthutil/oauthutil.go
The field `raw` of `oauth2.Token` may be an uncomparable type(often map[string]interface{}), causing `*token != *ts.token` expression to panic(comparing uncomparable type ...).
The semantics of comparing whether two tokens are the same can be achieved by comparing accessToken, refreshToken and expire to avoid panic.
None.
> oauthutil: avoid panic when `*token` and `*ts.token` are the same

- docs/content/downloads.md
Adds rclone OS requirements list and latest rclone versions known to be working with specific historical OS releases.
Discussed on the forum:
https://forum.rclone.org/t/rclone-1-65-1-runtime-exception-error-crash-immediately-after-running-the-command/44051
Fixes: #7571
> docs: add rclone OS requirements

- cmd/bisync/bilib/canonical.go
- cmd/bisync/cmd.go
- cmd/bisync/help.go
- cmd/bisync/operations.go
- docs/content/bisync.md
(This PR is dependent on #7410 -- only 3 of the commits are new 🙂 )
Before this change, bisync used the "canonical" Fs name in the filename for its listing files, including any {hexstring} suffix. An unintended consequence of this was that if a user added a backend-specific flag from the command line (thus "overriding" the config), bisync would fail to find the listing files it created during the prior run without this flag, due to the path now having a {hexstring} suffix that wasn't there before (or vice versa, if the flag was present when the session was established, and later removed.) This would sometimes cause bisync to fail with a critical error (if no listing existed with the alternate name), or worse -- it would sometimes cause bisync to use an old, incorrect listing (if old …
> bisync: normalize session name to non-canonical (and docs edits) - fixes #7423

- cmd/bisync/cmd.go
- cmd/bisync/deltas.go
- cmd/bisync/listing.go
- cmd/bisync/lockfile.go
- cmd/bisync/march.go
- cmd/bisync/operations.go
- cmd/bisync/queue.go
- docs/content/bisync.md
(This PR is dependent on #7410, #7497, and #7498 -- only 2 commits are new 🙂 )
Before this change, bisync had no mechanism to gracefully cancel a sync early and exit in a clean state. Additionally, there was no way to recover on the next run -- any interruption at all would cause bisync to require a --resync, which made bisync more difficult to use as a scheduled background process. 
This change introduces a "Graceful Shutdown" mode and --recover flag to robustly recover from even un-graceful shutdowns. Details are documented thoroughly in the commit messages, and [the docs](https://github.com/nielash/rclone/blob/bisync-recover/docs/content/bisync.md#--recover).
- #7470
- #7332
- [How to reduce need for bisync::resync?](https://forum.rclone.org/t/how-to-reduce-need-for-bisync-resync/31067) …
> bisync: Graceful Shutdown, --recover from interruptions without --resync

- cmd/serve/restic/restic.go
- cmd/serve/restic/restic_test.go
We've discovered in https://github.com/restic/restic/issues/4612 that rclone returns a "not found" error instead of an "internal server error" if listing a directory fails. This is very problematic as since restic 0.16.0 a "not found" error while listing a directory is treated like an empty directory. Consequently, the `prune` command can end up believing that there are no snapshots if an error occurs while listing the snapshots and wipe the entire repository.
The second commit modifies the error handling while retrieving a file, such that it only returns "not found" if there's a corresponding error. A future restic version will stop retrying "not found" errors (see https://github.com/restic/restic/pull/4520) and therefore needs to be able to distinguish permanent errors like "not found" …
> serve restic: Fix error handling

- backend/seafile/webapi.go
This PR fixes an error in the Seafile backend implementation.
A Seafile server can be configured to use a relative url as `FILE_SERVER_ROOT` (e.g.: `/seafhttp` instead `https://seafile.example.com/seafhttp`) in order to support more than one hostname/ip (see https://github.com/haiwen/seahub/issues/3398#issuecomment-506920360).
The current backend implementation always expected an absolute download/upload url, resulting in an `unsupported protocol scheme` error. With this PR it supports both absolute and relative.
No
> Seafile: Fix download/upload error when FILE_SERVER_ROOT is relative

- backend/quatrix/quatrix.go
This change does not actually affect uploads. Just to be right according to definition of Content-Range in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range#range-end
Content-Range is inclusive according to MDN
No
> quatrix: fix Content-Range header

- backend/dropbox/dropbox.go
- backend/googlephotos/api/types.go
- backend/googlephotos/googlephotos.go
- backend/pikpak/api/types.go
- backend/pikpak/pikpak.go
The CI lint test has recently started complaining about struct fields named `Id` instead of `ID`, and failing because of this. This change should fix it.
No.
> backend: rename variables to fix CI lint test failures

- cmd/bisync/cmd.go
- cmd/bisync/operations.go
- cmd/bisync/queue.go
- cmd/cmd.go
- docs/content/bisync.md
- fs/config.go
- fs/config/configflags/configflags.go
Before this change, bisync supported `--retries` but not `--retries-sleep`. This change adds support for `--retries-sleep`. It also fixes an issue that caused bisync to retry more times than necessary.
- #7555
> bisync: add support for `--retries-sleep` - fixes #7555

- fs/operations/check_test.go
- fs/operations/operations.go
- fs/sync/sync.go
Two fixes for integration tests, discussed on #7591.
After this, I think we should just be down to `mailru`, `jottacloud`, and `linkbox`.
- #7591
> sync: use `operations.DirMove` instead of `sync.MoveDir` for `--fix-case`, fix `TestApplyTransforms`

- docs/content/webdav.md
This is a drive-by commit to fix a heading problem under the "Provider Notes" section. Thanks!
The heading levels in the WebDAV documentation were slightly messed up.
No, it is a single character change in documentation.
> Fix a heading level in webdav.md documentation

- backend/webdav/webdav.go
Basically every time you use the chunks on webdav it shows an unnecessary message, i just change to show that message only on debug mode
https://forum.rclone.org/t/webdav-chunk-upload-notice/44395/2
> Fixing webdav chunks upload message

- cmd/bisync/bisync_test.go
The flushCache() function has a bug that causes it to never actually flush the cache. Specifically, it checks whether DirCacheFlush is nil, but never calls it.
The tests are already passing without flushing the dir cache, so this commit just deletes flushCache() and its call sites.
Fixes rclone/rclone#7623
Clarify the bisync tests by removing an accidentally misleading function.
> bisync: delete flushCache() function from tests

- cmd/mountlib/mount.md
- cmd/nfsmount/nfsmount.go
- cmd/serve/nfs/filesystem.go
- cmd/serve/nfs/handler.go
- cmd/serve/nfs/nfs.go
- cmd/serve/nfs/server.go
This fixes a critical bug in `nfsmount` / `serve nfs` on macOS (#7503), and also fixes two more minor bugs (effective deadlock on external unmounting, and `--volname` being ignored). 
- #7503 
- https://forum.rclone.org/t/rclone-v1-65-0-release/43100/25?u=scuba-tech
- https://forum.rclone.org/t/how-to-use-nfs-mount-on-macos-sonoma/44203/3?u=nielash
- #7072
> nfsmount: fix writing files via Finder on macOS (and other bugs) - fixes #7503

- backend/swift/swift.go
This optimizes the Swift backend by avoiding unnecessary container versioning checks during the update process. The check is only required for large objects with a non-empty list of segments, which could be a rare case depending on scenarios.
N/A
> swift: Avoid unnecessary container versioning check

- cmd/cmount/mount.go
- cmd/mountlib/mount.md
- fs/operations/check.go
- vfs/dir.go
- vfs/vfs.md
- vfs/vfs_case_test.go
- vfs/vfscommon/options.go
- vfs/vfsflags/vfsflags.go
Before this change, the VFS layer did not properly handle unicode normalization, which caused problems particularly for users of macOS. While attempts were made to handle it with various `-o modules=iconv` combinations, this was an imperfect solution, as no one combination allowed both NFC and NFD content to simultaneously be both visible and editable via Finder.
After this change, the VFS supports `--no-unicode-normalization` (default `false`) via the existing `--vfs-case-insensitive` logic, which is extended to apply to both case insensitivity and unicode normalization form.
This change also adds an additional flag, `--vfs-block-norm-dupes`, to address a probably rare but potentially possible scenario where a directory contains multiple duplicate filenames after applying case and …
> vfs: fix unicode normalization on macOS - fixes #7072

- cmd/bisync/bisync_test.go
- cmd/bisync/testdata/test_all_changed/golden/test.log
- cmd/bisync/testdata/test_basic/golden/test.log
- cmd/bisync/testdata/test_check_access/golden/test.log
- cmd/bisync/testdata/test_check_access_filters/golden/test.log
- cmd/bisync/testdata/test_check_filename/golden/test.log
- cmd/bisync/testdata/test_createemptysrcdirs/golden/test.log
- cmd/bisync/testdata/test_extended_char_paths/golden/test.log
- cmd/bisync/testdata/test_extended_filenames/golden/test.log
- cmd/bisync/testdata/test_filters/golden/test.log
- cmd/bisync/testdata/test_filtersfile_checks/golden/test.log
- cmd/bisync/testdata/test_ignorelistingchecksum/golden/test.log
- cmd/bisync/testdata/test_normalization/golden/test.log
- cmd/bisync/testdata/test_rclone_args/golden/test.log
- cmd/bisync/testdata/test_rmdirs/golden/test.log
- fs/config/configflags/configflags.go
- fs/operations/operations.go
- fs/operations/operations_test.go
- fs/sync/sync.go
- fs/sync/sync_test.go
Before this change, directory modtimes (and metadata) were always synced from src to dst, even if already in sync (i.e. their modtimes already matched.) This potentially required excessive API calls, made logs noisy, and was potentially problematic for backends that create "versions" or otherwise log activity updates when modtime/metadata is updated.
After this change, a new `DirsEqual` function is added to check whether dirs are equal based on a number of factors such as ModifyWindow and sync flags in use. If the dirs are equal, the modtime/metadata update is skipped.
For backends that require `setDirModTimeAfter`, the "after" sync is performed only for dirs that could have been changed by the sync (i.e. dirs containing files that were created/updated.)
Note that dir metadata (other than …
> sync: don't set dir modtimes if already set

- backend/combine/combine.go
- docs/content/bugs.md
- fs/dir_wrapper.go
- fs/operations/operations.go
`operations.CopyDirMetadata` was failing with:
```
internal error: expecting directory string from combine root '' to have SetMetadata method: optional feature not implemented
```
if the `dst` was the root directory of a `combine` upstream. This is because combine was returning a `*fs.Dir`, which does not satisfy the `fs.SetMetadataer` interface.
Here's one proposed solution, but feel free to toss it if you have a different one in mind 🙂 
Also, I didn't check, but it seems possible that Union and other similar backends might need a similar fix.
No, I just noticed it tonight.
> `combine`: fix `CopyDirMetadata` error on upstream root

- fs/operations/operations.go
- fs/operations/operations_test.go
Before this change, `operations.DirMove` would fail when moving a directory, if the src and dest were on different upstreams of a `combine` remote.
The issue only affected `operations.DirMove`, and not `sync.MoveDir`, because they checked for server-side-move support in different ways.
`MoveDir` checks by just trying it and seeing what error comes back. This works fine for `combine` because `combine` returns `fs.ErrorCantDirMove` which `MoveDir` understands what to do with.
`DirMove`, however, only checked whether the function pointer is `nil`. This is an unreliable way to check for `combine`, because `combine` does advertise support for `DirMove`, despite not always being able to do it.
This change fixes the issue by checking the returned error in a manner similar to `sync.MoveDir` and …
> `combine`: fix `operations.DirMove` across upstreams - fixes #7661

- backend/onedrive/api/types.go
- backend/onedrive/metadata.go
- backend/onedrive/metadata.md
- backend/onedrive/onedrive.go
- backend/onedrive/onedrive_internal_test.go
- docs/content/onedrive.md
- docs/content/overview.md
- fs/log.go
This change adds support for metadata on OneDrive. Metadata (including permissions) is supported for both files and directories.
See the [included docs](https://github.com/nielash/rclone/blob/8d85a7337ab2f0dbcbeff4db5fc9d227edf78c77/docs/content/onedrive.md#metadata) for many more details!
> onedrive: add metadata support

- backend/drive/drive.go
- backend/drive/drive_internal_test.go
This command executes a list query in Google Drive’s native query language and returns id, name pairs for any matches. It’s useful for locating files quickly in folders with a large number of files, where rclone’s normal list command is slow due to client-side filtering.
No
> drive: backend query command

- fs/parseduration.go
- fs/parseduration_test.go
Enhanced the UnmarshalJSON method for the Duration type to correctly handle the special string 'off' and ensure large integers are parsed accurately without floating-point rounding errors. This resolves issues with setting and removing the MinAge filter through the rclone rc command.
Fixes #3783
Thank you very much for contributing code or documentation to rclone! Please
fill out the following questions to make it easier for us to review your
changes.
You do not need to check all the boxes below all at once, feel free to take
your time and add more commits. If you're done and ready for review, please
check the last box.
This Pull Request introduces enhancements to the `Duration` type's `UnmarshalJSON` method within the `fs` package to correctly handle the special string "off" and ensure …
> Improve JSON Unmarshalling for Duration Type in fs Package

- docs/content/sftp.md
Discussed on the forum:
https://forum.rclone.org/t/can-rclone-be-made-to-work-with-an-sftp-server-confining-users-to-an-sftp-jail-and-no-login/44931
- [ x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
> docs: sftp, clarify `shell_type = none` and `ssh = ` behaviour

- docs/content/protondrive.md
> docs: Proton Drive, correct typo

- backend/b2/b2.go
- backend/compress/compress.go
- backend/crypt/crypt.go
- fs/operations/copy.go
- vfs/read.go
Improves the error message to include the names of the source and destination filesystems, when the source and destination file hashes differ after copying.
For example, if we are copying a file from the local filesystem to Amazon S3 and the file hashes are different after copying, then currently, we'll get the following error message:
> corrupted on transfer: md5 hash differ "eb260e9ae827821beceeed4104f0ad89" vs "59d0d19fc45ca69230d858f60a5557f8"
After this improvement, the error message will be:
> corrupted on transfer: md5 hash differ. source(local): "eb260e9ae827821beceeed4104f0ad89", destination(s3): "59d0d19fc45ca69230d858f60a5557f8"
I couldn't see an existing test for this error, let me know if you want me to try and add one.
I also noticed that the following error in the same …
> operations: improve error message when source and destination hashes differ after copying - fixes #5268

- backend/s3/s3.go
I can can reproduce this with other compatible S3 backend. Try to fix it. 
fix panic when using `--s3-copy-cutoff=0` 
When use CopyCutoff=0, it just similar to set chunk-size as original object and do server side copy
https://github.com/rclone/rclone/issues/7391
> s3: validate CopyCutoff size before copy

- backend/linkbox/linkbox.go
- backend/linkbox/linkbox_test.go
- fstest/fstests/fstests.go
LinkBox API does not allow searching by more than 25 Unicode characters in the name, for this reason it is currently impossible to work with files and folders named longer than 8 Unicode chars (if encoded in base32). This fix queries all files in a long named directory and checks names there one by one, thus solving the issue.
#7542
> linkbox: fix work with names longer than 8-25 Unicode chars.

- cmd/all/all.go
- cmd/gitannex/gitannex.go
- cmd/gitannex/gitannex.md
- cmd/gitannex/gitannex_test.go
- cmd/gitannex/run-git-annex-testremote.sh
This PR adds a new subcommand named "gitannex", aka "git-annex-remote-rclone-builtin" when invoked via a symlink.
This accomplishes milestone 1 from issue #7625: "minimal support for the external special remote protocol".
-----
To add a shim program that enables git-annex to interact with rclone remotes.
* #7625 
* https://forum.rclone.org/t/new-subcommand-for-git-annex-remote/44546
> cmd/gitannex: Add the gitannex command

- backend/memory/memory.go
- fstest/fstests/fstests.go
Before this change, the `Memory` backend's `Copy` method created a `dst` object that referenced the `src`'s `objectData` by pointer instead of making a copy. While this minimized memory usage, an unintended consequence was that subsequently mutating the `src` (such as changing the `modtime`) would inadvertently also mutate the `dst`, and vice versa.
This change fixes the issue and adds a test.
No.
> `memory`: fix dst mutating src after server-side copy

- backend/memory/memory.go
- backend/memory/memory_internal_test.go
Before this change, the `Memory` backend had the potential to deadlock under certain conditions, if the `ListR` callback required locking the `b.mu` mutex. This was the case with `operations.Purge`, because `Memory` has no `Purge` method, and the fallback option does:
https://github.com/rclone/rclone/blob/ca903b9872790921ae85dee316ca1800657281c4/fs/operations/operations.go#L1126
which potentially starts removing objects before the listing has completed.
This change fixes the issue by ensuring the mu is unlocked for the duration of `fn`.
No.
> `memory`: fix deadlock in `operations.Purge`

- backend/memory/memory.go
- fstest/fstests/fstests.go
Before this change, `List` would return incorrect directory paths (relative to the wrong root) if the Fs root pointed to a subdirectory. For example, listing dir `a/b/c/d` of remote `:memory:` would work correctly, but listing dir `c/d` of remote `:memory:a/b` would not, and would result in `Entry doesn't belong in directory %q (contains subdir)` errors.
This change fixes the issue and adds a test to detect any other backends that might have the same issue.
No.
> `memory`: fix incorrect list entries when rooted at subdirectory

- backend/ulozto/ulozto.go
- backend/ulozto/ulozto_test.go
Remove the workarounds for uloz.to's file size. 
The combination of large files, absence of `Content-Length` header, and chunked encoding triggers the issue. 
- files under 2.5G are uploaded fine as demonstrated. 
- setting the `Content-Length` either fixes the issue (non-negative value), or triggers a 400 if the file size is not known (-1). 
- removing chunked encoding does nothing (if `Content-Length` is set), or triggers a 415 (if `Content-Length` is not specified)
This currently means we still run into the issue with large files if rclone doesn't know their size beforehand. Such scenario is presumably very rare though, and explicitly setting the size to -1 isn't handled properly in rclone's multipart generation code. 
https://github.com/rclone/rclone/pull/7552
> Remove the temporary Uloz.to filesize limit

- docs/content/drive.md
Help people handle an issue which might be difficult to understand otherwise.
If you have recursive shortcuts (pointing to a parent folder) in a google drive, rclone is doing infinite recursion, never ending and filling the disk. Even if you ask not to get shortcuts content. 
See https://forum.rclone.org/t/trying-to-backup-a-google-drive-ends-up-filling-my-disk-with-recursive-stuff/44601/2
> drive: add an  indication in case of recursive shortcuts in documentation

- fs/config/ui.go
Instead of:
```
Choose a number from below, or type in your own fs.Enum[github.com/rclone/rclone/backend/local.timeTypeChoices] value.
Press Enter for the default (mtime).
1 / The last modification time.
\ (mtime)
2 / The last access time.
\ (atime)
3 / The creation time.
\ (btime)
4 / The last status change time.
\ (ctime)
time_type>
```
Then:
```
Choose a number from below, or type in your own value of type mtime|atime|btime|ctime.
Press Enter for the default (mtime).
...
```
Another less visible example is, instead of:
```
Enter a encoder.MultiEncoder value. Press Enter for the default (Slash,LtGt,DoubleQuote,Colon,Question,Asterisk,Pipe,BackSlash,Ctl,RightSpace,RightPeriod,InvalidUtf8,Dot).
```
Then:
```
Enter a value of type Encoding. Press Enter for the default …
```
> Show more user friendly names of custom types in config ui

- cmd/bisync/bisync_test.go
- cmd/bisync/resolve.go
- cmd/bisync/testdata/bisync_vscode_debuggers_launch.json
Several fixes for the `bisync` integration tests:
- use unique `initdir` and `datadir` for each subtest so concurrent tests don't interfere with each other
- remove dots from dir names for bucket backends
- ignore messages specific to `cache` backend
- skip fix-case tests on backends that can't fix-case
- don't expect `{hashtype} differ` messages on backends with no hash types
- print timestamps in UTC local
More fixes will still be needed, but this should hopefully fix a good portion of them.
- https://github.com/rclone/rclone/issues/7665
> bisync: several fixes for integration tests

- docs/content/s3.md
Context: I work for Cloudflare.
Some time ago I added a note about `no_check_bucket` being required for R2 object-level tokens onto https://developers.cloudflare.com/r2/examples/rclone/ in https://github.com/cloudflare/cloudflare-docs/pull/11438
This is required for non-admin tokens due to rclone sending a PUT to buckets as part of the object upload flow.
This change adds the same note to the rclone docs as well, to reduce friction and confusion across the board.
P.S. Bonus: is this something that can be baked into rclone as a quirk or not? For now documentation will suffice.
It was not, sorry! Let me know if that is needed.
> docs: Add R2 note about no_check_bucket

- .gitignore
- docs/content/flags.md
- docs/content/rc.md
- fs/rc/rc.go
- fs/rc/rcflags/rcflags.go
- fs/rc/rcserver/rcserver.go
- fs/rc/rcserver/rcserver_test.go
- fs/rc/rcserver/testdata/golden/testmodtime.html
By default, set `ModTime` for directories and files served by `--rc-serve`.
A new flag `--rc-serve-no-modtime` allows to disable this behavior.
Fixes #7335
> rcserver: set `ModTime` for dirs and files served by `--rc-serve`

- backend/b2/b2_internal_test.go
- fstest/fstest.go
This PR expands test coverage of the `b2` backend, particularly for the new `cleanup` and `cleanup-hidden` commands introduced in https://github.com/rclone/rclone/pull/7656.
Yes - see https://github.com/rclone/rclone/pull/7656#issuecomment-1994967987.
> b2: Add tests for new `cleanup` and `cleanup-hidden` backend commands.

- backend/onedrive/metadata.go
- backend/onedrive/metadata.md
- backend/onedrive/onedrive.go
- backend/onedrive/onedrive_internal_test.go
- fs/log.go
Before this change, the `--metadata-mapper` was called twice if an object was uploaded via multipart upload with `--metadata` and `--onedrive-metadata-permissions write` or `read,write`. This change fixes the issue.
No.
> `onedrive`: fix `--metadata-mapper` called twice if writing permissions

- backend/hdfs/fs.go
- backend/webdav/webdav.go
- cmd/bisync/bisync_test.go
More fixes for integration tests:
- use `fstest.RandomRemote` to create the root level directory
- fix parsing of canonical name for connection string remotes
- `hdfs`: fix `f.String()` not including subpath
- `webdav`: fix `SetModTime` erasing checksums on `owncloud` and `nextcloud`
- #7665
> bisync: more fixes for integration tests

- cmd/mountlib/mount.go
- cmd/mountlib/mount.md
- cmd/rcd/rcd.go
- cmd/serve/dlna/dlna.go
- cmd/serve/dlna/dlnaflags/dlnaflags.go
- cmd/serve/docker/docker.go
- cmd/serve/ftp/ftp.go
- cmd/serve/http/http.go
- cmd/serve/nfs/nfs.go
- cmd/serve/proxy/proxy.go
- cmd/serve/restic/restic.go
- cmd/serve/s3/s3.go
- cmd/serve/sftp/sftp.go
- cmd/serve/webdav/webdav.go
- lib/http/auth.go
- lib/http/server.go
- lib/http/template.go
- vfs/vfs.go
To ensure there is an empty line between text and a following heading. Because some consumers (like pandoc) may otherwise not parse the Markdown correctly.
The challenge here is when combining different help string snippets, e.g. common http and vfs help into a specific serve command's help. I think we have tried to make sure string constants containing help snippets contain an empty line at the end, so that simple concatenation `help1 + help2` will always give correct result, but there was some not conforming to this. However an additional challenge is that some help snippets are read from markdown file using `go:embed`. To make the use of these consistent with others, without having to remember to add `\n` constants when concatenating these or something like that, I wrapped a function …
> Ensure empty line between text and a following heading

- cmd/bisync/bilib/output.go
Fixes `logrus.StandardLogger().Writer()` not getting closed in `CaptureOutput` (used on tests). Might be part of the story with the goroutine leaks, but probably not all of it.
- https://github.com/rclone/rclone/pull/7718#issuecomment-2040185347
> bisync: fix io.PipeWriter not getting closed on tests

- docs/content/filtering.md
Fix typo: moved misplaced double quotation mark.
No.
> docs: fix typo in filtering.md

- .gitattributes
Not at all important, but it avoids some git noise.
Go consistently uses `LF` when writing `go.mod` and `go.sum` files. Git on Windows by default transforms text files to `CRLF`. This means git clone writes `go.mod` and `go.sum` as `CRLF`, if updating them with e.g. `go mod tidy` go will rewrite them with `LF`, and then git will show them as different and warn if adding them to staging:
```
warning: in the working copy of 'go.mod', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'go.sum', LF will be replaced by CRLF the next time Git touches it
```
> Add go mod and sum to gitattributes for consistent line endings

- fs/rc/rcserver/rcserver.go
- fs/rc/rcserver/rcserver_test.go
> fs rc: fixes incorrect Content-Type in HTTP API - fixes #7726

- docs/static/css/custom.css
> Add left and right padding to prevent icon truncation

- cmd/ncdu/ncdu.go
prevent quitting ncdu when pressing 'escape' or 'q' - dedicating that to closing the box
Ctrl-C will still quit
>  ncdu: Do not quit on Esc 

- cmd/genautocomplete/genautocomplete_bash.go
As requested, here is a PR containing some changes that present
a fuller functionality of the `genautocomplete_bash` via its docs.
It's a bit more of a re-write than the changes that the issue I had
raised originally suggested would be needed, but I think I have
"covered all the bases" now.
> Remove Ubuntu-ism from text: clarify non-root use

- .github/workflows/build.yml
Starting with actions/setup-go@v4 (we currently use v5), it incorporates caching of build and modules, and the separate actions/cache step is superfluous.
> build: remove separate go module cache step as its done by setup-go

- fs/accounting/stats.go
> fs accounting: Add deleted files total size to status summary line - fixes issue #7190

- cmd/bisync/bisync_test.go
- skip test if config string contains a space
- avoid starting tests we don't have time to finish (to prevent all-or-nothing timeouts)
- https://github.com/rclone/rclone/pull/7743#issuecomment-2057250848
> bisync: yet another round of integration test fixes

- backend/http/http.go
> backend http: Adding no-escape flag for option to not escape URL meta characters in path names - fixes issue #7637

- backend/ulozto/ulozto.go
The change fixes uloz.to's handling of leading and trailing slashes in root paths, as reported in #7796.
Yes, said #7796.
> ulozto: Fix handling of root paths with leading / trailing slashes.

- docs/content/docs.md
Updated exit code 9 definition to include that it requires the use of the "--error-on-no-transfer" flag with a link to that section.
Update documentation
No
> Exit Code 9

- backend/onedrive/api/types.go
- backend/onedrive/metadata.go
- backend/onedrive/metadata.md
- backend/onedrive/onedrive_internal_test.go
- docs/content/onedrive.md
Two fixes related to `onedrive` metadata permissions:
- [onedrive: skip writing permissions with 'owner' role](https://github.com/rclone/rclone/commit/b4dad4094a3524ec6da092a5337243712da7a7b0)
- [onedrive: fix references to deprecated permissions properties](https://github.com/rclone/rclone/commit/131933eb1490d463073f9b2d49d349e52f8ea93c)
No.
> `onedrive`: fix metadata permissions

- .github/workflows/build.yml
Version 5 removes Go cache management, and therefore also options skip-pkg-cache and skip-build-cache, because the cache related to Go itself is already handled by actions/setup-go. Now it only caches golangci-lint analysis. Our solution in https://github.com/rclone/rclone/pull/7776 therefore needed to be changed.
> Bump golangci/golangci-lint-action from 4 to 6

- lib/oauthutil/oauthutil.go
When an external OAuth flow is being used (i.e. a client ID and an OAuth token are set in the config), a client secret should not be set. If one is, the server may reject a token refresh attempt.
But there's no way to clear out a backend's default client secret via configuration, since empty-string config values are ignored.
So instead, when a client ID is set, we should clear out any default client secret, since it wouldn't apply anyway.
No - I was just debugging why my OAuth tokens weren't being refreshed correctly when using the Drive backend, and it led me here.
I did file #7825 for tracking purposes though.
> oauthutil: clear client secret if client ID is set

- lib/http/serve/dir.go
Add the `Content-Length` to the html response when `http serve http ...` is executed
NA
> Added content-length header when html file is served

- .github/workflows/build.yml
- Makefile
- cmd/gitannex/e2e_test.go
- cmd/gitannex/gitannex.go
- cmd/gitannex/gitannex.md
- cmd/gitannex/gitannex_test.go
- cmd/gitannex/layout.go
This change adds support for the repo layouts defined by  [git-annex-remote-rclone](https://github.com/git-annex-remote-rclone/git-annex-remote-rclone). This should enable git-annex users with external remotes of type "rclone" to switch to "rclone-builtin" without needing to retransfer content. It also adds e2e compatibility tests in an attempt to verify this claim!
Issue #7625
> cmd/gitannex: Add layout modes for compatibility

- backend/webdav/webdav_internal_test.go
- fs/config/configfile/configfile_test.go
Fix new lint issues reported by golangci-lint v1.59.0:
> Error return value of `fmt.Fprintf` is not checked (errcheck)
> Fix new lint issues reported by golangci-lint v1.59.0

- cmd/gitannex/gitannex.go
- cmd/gitannex/gitannex.md
- cmd/gitannex/gitannex_test.go
The main purpose is to simplify setup for users.
First, this PR adds aliases to the existing config parameters so users can use the same config names as <https://github.com/git-annex-remote-rclone/git-annex-remote-rclone>.
Secondly, this updates the command documentation.
* It mentions that new versions of git-annex support `type=rclone`, so it's possible to skip the whole symlink business.
* It drops duplicative description of config parameters, instead showing users how to use the `--whatelse` option of `git annex initremote`.
* It rewrites setup steps for clarity, improves formatting, etc.
Issue #7625
> cmd/gitannex: Add config parameter synonyms for compat, update command documentation

- lib/file/file_windows.go
This change enables `rclone` to read/write from/to files/directories in situations where:
* The existing security context has `SeBackupPrivilege` and/or `SeRestorePrivilege` delegated ***and*** enabled\*.
* The existing security context _does not_ have explicit access to the files/directories in question.
_Note:_ This is an advanced use option. It will have absolutely no impact in most cases. For more information, please see the following:
* https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea
* https://learn.microsoft.com/en-us/windows/win32/secauthz/privilege-constants (see: `SE_BACKUP_NAME` and `SE_RESTORE_NAME`)
* https://forum.rclone.org/t/rclone-sebackupprivilege-file-flag-backup-semantics/45339
* https://github.com/rclone/rclone/pull/7877
\* At this …
> Including `FILE_FLAG_BACKUP_SEMANTICS` in calls to `CreateFile`.

- backend/pikpak/api/types.go
- backend/pikpak/helper.go
- backend/pikpak/pikpak.go
This PR includes several attempts to improve upload reliability and to resolve potential file conflicts:
* Checking upload status: Implemented `getTask()` to verify successful completion on the server-side for each upload.
* Cancelling uploads on errors: Uploads encountering errors are cancelled to remove residual files.
* Forced & Minimum Sleep:
* Based on experiments, a forced delay(500ms) is introduced after uploads to ensure server-side updates register (minimal impact on total execution time).
* Minimum sleep for pacer increased from 10ms to 100ms to resolve server errors.
* Removed `uploadByForm()`: This method is less reliable for a large number of small files. We now solely use `uploadByResumable()`.
#7787
> pikpak: improve upload reliability and resolve potential file conflicts

- backend/protondrive/protondrive.go
Improves the authentication flow. Previously it considered empty strings as proper values, which led to a wrong attempt ending with HTTP error 401.
Related to #7864. It does not fix the final problem with HTTP error 422, but not having 401 beforehand helps staying under the radar of incorrect API usage.
> protondrive: don't auth with an empty access token

- backend/dropbox/dropbox.go
This lets you, for example, use shared folders without mounting them into your home namespace first, as long as you know their namespace ID.
(The --dropbox-shared-folders flag could thus be changed to not need to mount the shared folder first, but I'm not doing that here as it's a behavior change, who knows, maybe somebody relies on it.)
This also allows access to your Dropbox Backups hidden namespace once you figure out what its namespace ID is.
> dropbox: add option to override root namespace

- backend/s3/s3.go
When getting an object by specifying a `versionId` in the request, if the specified version is a delete marker, it returns `405 (Method Not Allowed)`, instead of `404 (Not Found)` which would be returned without a `versionId`.
See https://docs.aws.amazon.com/AmazonS3/latest/userguide/DeleteMarker.html
Before this change, we were only looking for `404` (and not `405`) to determine whether the object exists. This meant that in some circumstances (ex. when Versioning is enabled for the bucket and we have a non-null `X-Amz-Version-Id`), we deemed the object to exist when we should not have.
After this change, `405 (Method Not Allowed)` is treated the same as `404 (Not Found)` for the purposes of `headObject`.
- https://forum.rclone.org/t/bisync-rename-failed-method-not-allowed/45723/13
> `s3`: fix 405 error on `HEAD` for delete marker with `versionId`

- backend/s3/s3.go
Fixes incorrect region on Magalu provider for br-ne1 in s3.go.
Looks like there was a typo in the word `Northeast` and the incorrect subdomain for the region as per https://docs.magalu.cloud/docs/terraform/how-to/provider-region/
I don't know, I just stumbled upon it by accident and decided to propose a fix because it seemed quick while I had the context.
> Fix incorrect region on Magalu provider Help value

- backend/sftp/sftp.go
The SFTP protocol (and the golang sftp package) internally uses uint32 unix time for expressing mtime. Hence it is a waste of memory to store it as 24-byte time.Time data structure in long-lived data structures. So despite that the golang sftp package uses time.Time as external interface, we can re-encode the value back to the original format and save memory.
Save memory when mounting sftp backends. In my specific circumstances this simple change saves hundreds of MB of RAM.
No.
I do not believe tests are necessary, as the only values that make sense in the context of sftp would already be within the range of uint32. As such, there should be no externally observable changes.
> sftp: use uint32 for mtime

- backend/pikpak/pikpak.go
This prevents local source files from buffering when calculating custom hash for uploads.
N/A
> pikpak: non-buffered hash calculation for local source files

- backend/local/local.go
- docs/content/overview.md
- lib/encoder/encoder.go
- lib/encoder/encoder_test.go
- lib/encoder/internal/gen/main.go
- vfs/vfscache/cache.go
Fix the way to disable encoding by introducing a new type `Raw` to solve #7456 and #6098.
See #7456 and the changes on the document for details.
The behavior of `None` was not changed to keep backward compatibility.
And fix vfs cache encoding described in #7760
The problem is when we create and write cache, we use the "OS" encoded ("OS" encoding is hardcoded for different operating systems, not specified by users).
But when we copy it to the remote (backend), we use local.Fs, which accept a name already encoded in "Standard" way.
So we need to send a "Standard" encoded name.
However, the "minimum setup" mentioned in #7760 has not been resolved. See my comment in it for details.
But it's an edge case.
> fix issues related to encoding

- cmd/serve/s3/backend.go
- cmd/serve/s3/list.go
- cmd/serve/s3/s3.go
- cmd/serve/s3/s3_test.go
- cmd/serve/s3/server.go
- cmd/serve/s3/testdata/mybucket/foo/bar.txt
- cmd/serve/s3/testdata/mybucket/lorem.txt
- cmd/serve/servetest/servetest.go
- go.mod
- go.sum
POC for https://github.com/rclone/rclone/issues/7645
Requires: https://github.com/rclone/gofakes3/pull/3
> [POC] Implement `--auth-proxy` for 'serve s3'

- cmd/mountlib/mount.go
- lib/systemd/notify.go
#7540 has been annoying me for quite a long time, so I decided to try my hand at a fix. It turned out to be surprisingly simple - just move the sd-notify calls out of `(m *MountPoint) Wait()` and into the command `Run` handlers used by the `mount` commands in `NewMountCommand`. 
~~I also made some minor changes to the `serve docker` command, so that the `READY=1` notification is only sent _after_ the socket is created and a connection is made. This means that if there are any units with an `After` dependency on the rclone unit, they will only be started once the socket exists and is accepting connections.~~ Split to #7954
Fixes #7540
> systemd: prevent unmount rc command from sending a STOPPING=1 sd-notify message

- backend/ulozto/api/types.go
Fixes #7960
Uploading large files to uloz.to yielded an error message because the actual size was larger than could be possibly stored in the Size field.
I will check the checklist later.
#7960
- [] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [] I have added tests for all changes in this PR if appropriate.
- [] I have added documentation for the changes if appropriate.
- [] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [] I'm done, this Pull Request is ready for review :-)
> Change SendFilePayloadResponse.size type to int64

- docs/content/hasher.md
Add a line to the "other operations" block to indicate that the hasher overlay will apply auto-size and other checks for all commands.
Clarify behaviour of hasher overlay for non-hashsum commands
https://forum.rclone.org/t/copy-sync-checksum-download/44088/8
> docs: clarify hasher operation

- fs/fshttp/http.go
- fs/fshttp/http_test.go
In corporate environments, client certificates have short life times for added security, and they get renewed automatically. This means that client certificate can expire in the middle of long running command such as `mount`.
This commit adds a simple timestamp check to automatically reload the certificate if it has been renewed on disk.
No
> [fs/http] Reload certificates when they change

- backend/alias/alias_internal_test.go
- backend/cache/cache_internal_test.go
- cmd/bisync/bisync_test.go
- cmd/help.go
- cmd/listremotes/listremotes.go
- fs/config/config.go
- fs/config/flags/flags.go
- fs/config/rc.go
- fs/config/rc_test.go
- fs/config/ui.go
- fs/config/ui_test.go
- fs/filter/filter.go
- fs/filter/glob.go
- fs/filter/glob_test.go
- fs/filter/rules.go
- fs/rc/rcserver/rcserver.go
- fstest/fstests/fstests.go
The main purpose is to add support for filtering the output from `listremotes` command, as discussed in the forum. Some additional, somewhat related, features were also added, namely ordering and json output. During extended testing of this command, some issues and inconsistencies within the fs/filter and fs/config libs, which the listremotes command depends on, were discovered and improved.
Now to the details: First the improvements to listremotes, as these are the most user-facing part, then later some details regarding the changes in fs libs - although these commits comes first in the PR as some of they create a foundation for some of the listremote improvements.
Improvements to listremotes:
- Including source of the remote definition in the `--long` output format, i.e. if it was …
> Listremotes filtering

- cmd/listremotes/listremotes.go
The format was changed to include the source attribute in #7404, but that is now reverted and the source information is only shown in json output.
> Make listremotes long output backwards compatible - fixes #7995

- backend/webdav/webdav.go
- cmd/rc/rc.go
- cmd/serve/webdav/webdav.go
- docs/content/webdav.md
- fs/fshttp/http.go
This adds a new optional parameter to the backend, allowing to specify a path to a unix domain socket to connect to, instead the specified URL.
If the parameter is set, we use `fshttp.NewClientCustom` to modify the HTTP transport, to use a dialer connecting to the unix domain socket path specified for that backend.
The URL itself is still used for the rest of the HTTP client, allowing host and subpath to stay intact.
This allows using rclone with the webdav backend to connect to a WebDAV server provided at a Unix Domain socket:
```
RCLONE_WEBDAV_UNIX_SOCKET_PATH=/path/to/my.sock \
RCLONE_WEBDAV_URL=http://localhost \
rclone sync mydir :webdav:/somewhere
```
This allows using rclone with the webdav backend to connect to a WebDAV server provided at a Unix Domain socket. …
> webdav: introduce unix_socket_path

- cmd/gendocs/gendocs.go
A few minor improvements to command docs layout:
- Command docs for root rclone command (https://rclone.org/commands/rclone/) did not outdent header levels, so it was inconsistent with the rest (including different toc that included the top level command etc).
- Command docs (except root rclone command) had the "# SEE ALSO" header as top level header, same as the primary command header (e.g. "# rclone copy"), and it would therefore not be shown in toc.
- Make option group headers sub-headers of the command's own "Options" header. Previously these were at the same level, e.g. copy command had headers: Headers, Copy Options, Important Options, etc. Then it could be a bit confusing what the first "Headers" section contains compared to the rest.
- The line "See the [global flags …
> Minor improvements to command docs layout

- backend/swift/swift.go
- lib/ranges/ranges.go
We upgraded our minimum Go version in commit ca24447090. We can now use the built-in `min` and `max` functions directly.
Reference: https://go.dev/ref/spec#Min_and_max
> refactor: replace min/max helpers with built-in min/max

- fs/config/configfile/configfile.go
- go.mod
- go.sum
Due to reasons I cannot control, my company's thrift party repository system does not allow case conflicting files.  e.g. it will reject a commit that has
* `Foo/file1.txt`
* `foo/file2.txt`
The correct go package for [Unknwon/goconfig](https://github.com/Unknwon/goconfig) is shown on the README as
```
go get github.com/unknwon/goconfig
```
I am using a package that transitively depends on rclone.  `unknwon/goconfig` is already in my repository.
> Rename Unknwon/goconfig to unknwon/goconfig

- cmd/bisync/listing.go
- docs/content/bisync.md
Before this change, bisync proactively converted modtime precision when greater than what the destination backend supported. 
This dates back to a time before bisync considered the `modifyWindow` for same-side comparisons. Back then, it was problematic to save a listing with `12:54:49.7` for a backend that can't handle that precision, as on the next run the backend would report the time as `12:54:50` and bisync would think the file had changed. So the truncation was a workaround to anticipate this and proactively record the time with the precision we expect to receive next time.
However, this caused problems for backends (such as `dropbox`) that round instead of truncating as bisync expected.
After this change, bisync preserves the original precision in the listing (without conversion), …
> bisync: don't convert modtime precision in listings - fixes #8025

- docs/content/docs.md
- fs/operations/copy.go
This PR changes the randomly generated suffix for partial files into stable ones, based on the sources fingerprint.
This brings some advantages:
- Less duplicated partial files by SIGTERM interrupts & re-runs
- Enables the possibility to [resume uploads](https://github.com/rclone/rclone/issues/87#issuecomment-2305902532)
- Part of [this comment](https://github.com/rclone/rclone/issues/87#issuecomment-2305902532) of #87 
- Was initially part of #7949 but [splitted out during discussion](https://github.com/rclone/rclone/pull/7949#issuecomment-2227520700)
> operations: copy: generate stable partial suffix

- backend/yandex/yandex.go
- docs/content/yandex.md
Hey there, it's been a long time since I've done anything on rclone but since I've once again some time to work on OSS projects and rclone seems to be in need for some more maintainers I'll try to look into this again. 
This is another take on the User-agent change implement here #7659. It seems to help with upload speeds for the yandex backend. The user agent is shamelessly plugged from an official yandex disk client. I've decided to make it an option `--yandex-spoof-ua` but enabled it by default.
> Implement custom user agent for yandex. May help with upload speeds

- docs/content/local.md
Paths referring to volume name/guid was documented as not supported, but actually it became supported with our custom MkdirAll introduced with https://github.com/rclone/rclone/pull/5401 first included in rclone v1.57.0. Example usage:
```
rclone sync folder "\\?\Volume{a224c74f-da87-c295-3b90-cde0f64a29cc}\folder"
```
This PR updates the documentation accordingly. We have an open issue where the example above came from, reporting it does not work - but now it does.
In other words:
Closes https://github.com/rclone/rclone/issues/3864
https://github.com/rclone/rclone/issues/3864
https://forum.rclone.org/t/using-hash-instead-of-drive-letters/47553
> Document that paths using volume guids are supported

- lib/file/mkdir_other.go
- lib/file/mkdir_windows.go
- lib/file/mkdir_windows_go122_test.go
- lib/file/mkdir_windows_test.go
Starting with go1.22 the standard os.MkdirAll has improved its handling of volume names, and as part of that it now stops recursing into parent directory if it is a volume name (see: https://github.com/golang/go/commit/cd589c8a73415afbf94a8976f20cbed9d4061ba6). This is similar to what was our main change and reason for creating a custom version. When building with go1.22 or newer we can therefore stop using our custom version, with the advantage that we automatically get current and future relevant improvements from golang. To support building with go1.21 the existing custom version is still kept, and therefore also our wrapper function file.MkdirAll - but it now just calls os.MkdirAll with go1.22 or newer on Windows.
See #5401, #6420 and acf1e2df84a350b7a86d7672d749dfb1ba090a44 for …
> Use builtin MkdirAll with go1.22 instead of our own custom version for windows

- docs/content/release_signing.md
Ensure that the status code return when verifying gpg signature is not swallowed when verifyin file hashes
Propose a fix for issue #8024 
Same result in the "good" case :
```
gpg: Signature made Fri Jun 14 18:37:03 2024
gpg:                using DSA key FBF737ECE9F8AB18604BD2AC93935E02FF3B54FA
gpg: Good signature from "Nick Craig-Wood <nick@craig-wood.com>" [unknown]
Primary key fingerprint: FBF7 37EC E9F8 AB18 604B  D2AC 9393 5E02 FF3B 54FA
rclone-v1.67.0.tar.gz: OK
$ echo $?
0
```
Same result in the "bad hash" case :
```
gpg: Signature made Fri Jun 14 18:37:03 2024
gpg:                using DSA key FBF737ECE9F8AB18604BD2AC93935E02FF3B54FA
gpg: Good signature from "Nick Craig-Wood <nick@craig-wood.com>" [unknown]
Primary key fingerprint: FBF7 37EC E9F8 AB18 604B  D2AC 9393 5E02 FF3B 54FA …
```
> docs: more secure two-step signature and hash validation

- backend/swift/swift.go
- go.mod
- go.sum
With the enhancement in version [v2.0.3](https://github.com/ncw/swift/releases/tag/v2.0.3) of ncw/swift library, `about` command can now get Total and Free space info from swift remotes that support this feature (ex. [Blomp storage](https://www.blomp.com/cloud-storage/))
Pull request [#186](https://github.com/ncw/swift/pull/186) in ncw/swift
> swift: add total/free space info in about command.

- cmd/serve/docker/options.go
vfs-read-chunk-streams option  is not checked in docker volume plugin 
@ncw
> add missing vfs-read-chunk-streams in  docker vol driver

- .github/workflows/build_publish_release_docker_image.yml
The recent v1.68 release build failed. Replacing `ilteoood/docker_buildx` with `docker/build-push-action` can resolve the issue. A successful build was performed at https://github.com/ttionya/rclone/actions/runs/10832095295.
https://github.com/rclone/rclone/issues/8062
> Fix the failure in building the release Docker image

- backend/opendrive/opendrive.go
- backend/opendrive/types.go
- docs/content/overview.md
Adds basic "about" support to the Opendrive backend to display more useful free/available stats
Not that I know of.
> opendrive: add "about" support to opendrive backend

- backend/zoho/api/types.go
- backend/zoho/zoho.go
- backend/zoho/zoho_test.go
- docs/content/zoho.md
This started out as a continuation of #7007 and supersedes it but I decided to go a bit further. This also implements the newer "large file" upload API which seems to perform much better.
I've also decided to rework how upload works in general. Files are now uploaded with a temporary name and renamed to their final name after the upload completes. This should get rid of all the encoding related integration test failures since Zoho actually supports most special characters - just not in the upload api.
There is however a big downside to this, the upload + delete + rename method does break file version history.
Also happens to fix #5995
Nope
> zoho: use download server and large file upload API

- cmd/bisync/cmd.go
- cmd/bisync/operations.go
- cmd/cmd.go
- cmdtest/cmdtest_test.go
- docs/content/bisync.md
- docs/content/docs.md
- lib/exitcode/exitcode.go
According to rclone [documentation](https://rclone.org/docs/#list-of-exit-codes), exit code 1 is for "syntax or usage" and 2 is for "not otherwise categorised" errors. However, in current implementation, exit code 2 will never be returned (*with one exception in bisync, see below), and in reality exit code 1 will be used for anything other than the "otherwise categorised" errors - exit code 1 is the *default* for unsuccessful returns.
There seem to be a more or less convention for exit codes in Linux/shell world,  maybe some specifically for bash:
- Values between 0 and 255
- 0 is for success
- 1 is for general errors
- 2 is usage errors, invalid options or missing arguments.
- Values above 125 are specifically used by the shell (bash), e.g. when program is terminated on response to a …
> Changes to exit codes

- Makefile
- bin/make_backend_docs.py
To prevent `make docs` from creating a directory named `$HOME`.
Yes
Fixes #8092
> Makefile: Prevent `doc` recipe from creating dir named '$HOME'

- backend/googlecloudstorage/googlecloudstorage.go
- docs/content/googlecloudstorage.md
To be able to use short-lived [access tokens](https://cloud.google.com/docs/authentication/token-types#access) with the gcs backend.  
GCP documentation about short-lived tokens can be found here: [Create short-lived credentials](https://cloud.google.com/iam/docs/create-short-lived-credentials-direct)  
This feature is used by our systems using [Vault/OpenBao](https://developer.hashicorp.com/vault/docs/secrets/gcp#impersonated-accounts) as the token generator.  
I didn't find any discussion or issue open
> gcs: add access token authentication

- fs/cache/cache.go
- fs/cache/cache_test.go
- fs/rc/cache_test.go
- lib/cache/cache.go
Three related bug fixes identified on https://forum.rclone.org/t/hasher-with-gdrive-backend-does-not-return-sha1-sha256-for-old-files/44680/9?u=nielash
1. `fs/cache`: fix parent not getting pinned when remote is a file
2. `hasher`: fix error from trying to stop an already-stopped db
3. `hasher`: look for cached hash if passed hash unexpectedly blank
`2` and `3` are specific to `hasher`, but `1` might possibly explain some unexplained behavior in other backends.
Before this change, when `cache.GetFn` was called on a _file_ rather than a directory, two cache entries would be added (the file + its parent) but only one of them would get pinned if the caller then called `Pin(f)`. This left the other one exposed to expiration if the `ci.FsCacheExpireDuration` was reached. This was problematic …
> `fs/cache`: fix parent not getting pinned when remote is a file & `hasher`: look for cached hash if passed hash unexpectedly blank 

- backend/drive/drive.go
- backend/drive/drive_internal_test.go
- docs/content/drive.md
Add markdown as a supported import/outport conversion for Google Drive, now that Google supports it.
No
I see my IDE has also trimmed some trailing spaces. LMK if I should remove these.
> drive: add support for markdown format

- .github/workflows/build.yml
GitHub has improved the handling of boolean inputs in workflow in recent year(s). Using the `inputs` context they can be retrieved as proper boolean types, and GitHub Web GUI now shows them using a checkbox rather than a generic text box field. Previous work on the same code is #6719, and before that #5275.
> Build workflow cleanup

- cmd/serve/dlna/dlna_util.go
On the current master (4db09331c), the DLNA `loggingResponseWriter` prints output disregarding the configured log level. For example (the default log level is `NOTICE`):
```
$ go run . serve dlna ~/Videos
2024/10/06 14:03:25 NOTICE: Config file "/home/simon/.config/rclone/rclone.conf" not found - using defaults
2024/10/06 14:03:25 NOTICE: Local file system at /home/simon/Videos: Serving HTTP on 0.0.0.0:7879
2024/10/06 14:03:25 NOTICE: DLNA server on :7879: Started SSDP on wlp2s0
2024/10/06 14:03:25 NOTICE: DLNA server on :7879: Started SSDP on enp1s0f0
2024/10/06 14:03:45 INFO  : /ctl: <redacted>:35340 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse" 
2024/10/06 14:03:45 INFO  : /static/rclone-120x120.png: <redacted>:35342 GET 206
```
After the change in this PR, the …
> dlna: fix loggingResponseWriter disregarding log level

- backend/s3/s3.go
Added `eu-south-1` to Wasabi region list. Reference: https://docs.wasabi.com/docs/what-are-the-service-urls-for-wasabi-s-different-storage-regions
I'm not aware of any discussion.
> Add Wasabi eu-south-1 region

- .gitignore
- backend/local/local.go
- backend/local/local_internal_test.go
- cmd/cmount/fs.go
- cmd/mount/dir.go
- cmd/mount/file.go
- cmd/mount2/fs.go
- cmd/mount2/node.go
- fs/fs.go
- vfs/dir.go
- vfs/file.go
- vfs/vfs.go
- vfs/vfs.md
- vfs/vfscommon/options.go
- vfs/vfstest/file.go
- vfs/vfstest/fs.go
- vfs/vfstest/os.go
Add mount / vfs symlink support
Please, note that it has only been tested with storj backend on linux.
Especially, macOS, windows were not tested.
Please do test those platforms and any other backends !!!
https://github.com/rclone/rclone/issues/2975
The whole work has been (trashed mostly) refactored. They were flaws in the previous implementation, especially trying to use truncated names in the vfs dir internal nodes  names which lead to inconsistency when it comes to push changes to the remotes.
For this reason, the refactoring went in 2 parts:
1. Add symlinks support in the VFS itself, in the form of always storing symlinks with the .rclonelink suffix, those being regular files.
The VFS Readlink and Symlink additions allow support for symlinks, even if the --links command line switch …
> Support for symlinks in mount / vfs

- docs/content/filtering.md
Inline comments in a "--filter-from" file effectively remove the filter on that line (with directories in my hands). As far as I can tell this behavior isn't documented/warned and doesn't throw errors.
[PR requested](https://forum.rclone.org/t/inline-comments-effectively-remove-filter-in-filter-from/48301) in forum.
> docs: instructs avoiding inline comments in a filter-file

- backend/s3/s3.go
Like some other S3-compatible providers, Storj does not currently implements UploadPartCopy and returns NotImplemented errors for multi-part server side copies.
This patch works around the problem by raising --s3-copy-cutoff for Storj to the maximum. This means that rclone will never use multi-part copies for files in Storj. This includes files larger than 5GB which (according to AWS documentation) must be copied with multi-part copy. This works fine for Storj.
See https://github.com/storj/roadmap/issues/40
No
> s3: Storj provider: fix server-side copy of files bigger than 5GB

- lib/http/context.go
- lib/http/middleware.go
- lib/http/server.go
- lib/http/server_test.go
This commit removes the bypass of authentication for requests coming from Unix sockets in the rclone serve functionality. This change addresses security concerns when behind a reverse proxy, where skipping authentication can expose sensitive endpoints. It ensures that authentication checks are consistently applied
> Disable Automatic Authentication Skipping for Unix Sockets

- bin/backend-versions.sh
- bin/upload-github
- fstest/testserver/init.d/docker.bash
* head -number is not allowed by POSIX.1-2024:
- https://pubs.opengroup.org/onlinepubs/9799919799/utilities/head.html
- https://devmanual.gentoo.org/tools-reference/head-and-tail/index.html
Make rclone's scripts more POSIX compliant.
No.
> POSIX head/tail invocations

- backend/pcloud/pcloud.go
- backend/pcloud/writer_at.go
This PR stabilizes the situation of bigger files and multi-threaded uploads.
The root cause boils down to the old "fun" property of pclouds fileops API: sessions are bound to TCP connections.
This forces us to use a http client with only a single connection underneath.
With large files, we reuse the same connection for each chunk.
If that connection interrupts (e.g. because we are talking through the internet), all chunks will fail.
The probability for latter one increases with larger files.
As the point of the whole multi-threaded feature was to speed-up large files in the first place, this change pulls the client creation (and hence connection handling) into each chunk.
This should stabilize the situation, as each chunk (and retry) gets its own connection.
Additionally, the default …
> plcoud: openWriterAt: make client/fd handling atomic - fixes #8147

- backend/oracleobjectstorage/options.go
Compartment OCID is needed only to list buckets. If a bucket is already created, compartmentid is not needed to list objects.
https://github.com/rclone/rclone/issues/8174
- [X ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
> oracleobjectstorage: make specifying compartmentid optional

- vfs/vfs.go
--vfs-used-is-size is broken. This PR fixes it.
https://github.com/rclone/rclone/issues/8220
> vfs: with --vfs-used-is-size value is calculated and then thrown away - fixes #8220

- cmd/mountlib/mount.go
mounting will always fail when rclone is installed from the snap package manager.
But the error message generated when trying to mount from a snap install was not
very good. Improve the error message.
Should prevent more bugreports like https://github.com/rclone/rclone/issues/8208
(I spent an hour on that bugreport.. Time wasted that wouldn't be if the error message was better)
discussed in issue #8208.
> cmd/mountlib: better snap mount error message

- backend/box/box.go
- backend/drive/drive.go
- backend/dropbox/dropbox.go
- backend/googlecloudstorage/googlecloudstorage.go
- backend/googlephotos/googlephotos.go
- backend/hidrive/hidrive.go
- backend/jottacloud/jottacloud.go
- backend/mailru/mailru.go
- backend/onedrive/onedrive.go
- backend/pcloud/pcloud.go
- backend/pikpak/pikpak.go
- backend/premiumizeme/premiumizeme.go
- backend/putio/putio.go
- backend/sharefile/sharefile.go
- backend/yandex/yandex.go
- backend/zoho/zoho.go
- bin/test_backend_sizes.py
- docs/content/onedrive.md
- fs/config/config.go
- lib/oauthutil/oauthutil.go
This change implements OAuth Client Credential flow for the OneDrive backend.
OAuth Client Credential flow will allow rclone to use permissions directly associated with the Azure AD Enterprise application, rather that adopting the context of an Azure AD user account.
As a quick fix, this has been implemented within the onedrive backend code. A more elegant solution would be to implement this within the oauthutil module.
This has been discussed in #6197.
https://github.com/rclone/rclone/issues/6197
> Implement one drive client credentials

- docs/content/rc.md
- lib/http/server.go
Did not change from ` --cert string` to ` --cert file` etc, as suggested, as I think that would require some considerable amount of work in central parts of the config packages etc, but reformulated the descriptions a bit to hopefully make the intentions more clear.
Also includes a few additional minor cleanups, e.g. an incorrect formatting (see the trailing `) under "Socket activation" in https://rclone.org/commands/rclone_serve_http/:
>  (and ignore any arguments passed by --addr`).
Fixes #8232
> Mention in serve tls options when value is path to file

- fs/rc/jobs/job.go
- fs/rc/jobs/job_test.go
Fix in extreme cases, when the job is executing finish(), the listener added by calling OnFinish() will never be executed.
This change should not cause compatibility issues, as consumers should not make assumptions about whether listeners will be run in a new goroutine
> rc/job: use mutex for adding listeners thread safety

- docs/content/rc.md
https://rclone.org/rc/ started talking about what commands you can send, without explaining how to actually send them.
Fixes #8252.
> docs: Document --url and --unix-socket on the rc page

- backend/b2/api/types.go
- backend/b2/b2.go
Add the capability to set and view the new b2 daysFromStartingToCancelingUnfinishedLargeFiles lifecycle rule.
See: 
https://www.backblaze.com/blog/effortlessly-managing-unfinished-large-file-uploads-with-b2-cloud-storage/  
https://www.backblaze.com/docs/cloud-storage-lifecycle-rules
I have no experience with go at all, but since it's just a simple property, I had no issue just matching the existing implementation. After a quick build and test, it seems to work well.
Doesn't look like it! Came across it, and it seemed like a recent change, and when searching for issues, prs, or forum I didn't find anything.
> b2: add daysFromStartingToCancelingUnfinishedLargeFiles lifecycle rule

- backend/s3/s3.go
- docs/content/s3.md
Amazon has renamed their `Glacier` tier to `S3 Glacier Flexible Retrieval`
The 'formerly' tag is only shown on already created objects in S3 interface. Not in pricing page.
https://aws.amazon.com/s3/pricing/
I feel `Glacier storage class` is not descriptive enough given the new naming, and can lead to confusion. Atleast for me it was not clear when viewing the pricing chart.
```diff
-  6 / Glacier storage class
+  6 / Glacier Flexible Retrieval storage class
\ (GLACIER)
```
No.
```tests
=== RUN   TestVersionLess
--- PASS: TestVersionLess (0.00s)
=== RUN   TestMergeDeleteMarkers
--- PASS: TestMergeDeleteMarkers (0.00s)
=== RUN   TestIntegration
fstests.go:442: Using remote "TestS3:"
fstests.go:463: Didn't find "TestS3:" in config file - skipping tests
--- PASS: TestIntegration (0.00s)
=== …
```
> s3: rename "Glacier" to "Glacier Flexible Retrieval"

- cmd/serve/docker/options.go
This change fixes a bug in the `rclone serve docker` command where specifying the `gid` option incorrectly assigned the value to the UID field instead of the GID field. 
The issue occurred because the code handling the `gid` case mistakenly reused the same assignment logic as the `uid` case. This fix ensures that the value is assigned to the correct field (`GID`) in the VFS options.
This issue appears to have been introduced in the changes from Pull Request [#8010](https://github.com/rclone/rclone/pull/8010).
At https://github.com/rclone/rclone/pull/8010/commits/29f8fa316009805402cdd9e413aeb5d4064cec1d, it changed from `vfsOpt.GID = ...` to `vfsOpt.UID = ...`
```diff
-		vfsOpt.GID = uint32(intVal)
+		if err == nil {
+			if intVal >= 0 && intVal <= math.MaxUint32 {
+				vfsOpt.UID = …
```
> Fix incorrect GID assignment in "gid" option for rclone serve docker

- backend/local/about_windows.go
- lib/terminal/hidden_windows.go
This will only search Windows System directory for the DLL if name is a base name (like "advapi32.dll"), which prevents DLL preloading attacks.
To get access to NewLazySystemDLL imports of syscall needs to be swapped with golang.org/x/sys/windows.
Source: https://pkg.go.dev/golang.org/x/sys/windows#NewLazyDLL
> Replace Windows-specific NewLazyDLL with NewLazySystemDLL

- go.mod
- go.sum
- lib/buildinfo/osversion.go
- lib/buildinfo/osversion_windows.go
v4 is the latest version with bug fixes and enhancements. While there are 4 breaking changes in v4, they do not affect us because we do not use the impacted functions.
Note: Due to the library's versioning policy, v4.24.5 is the first v4 release https://github.com/shirou/gopsutil/releases/tag/v4.24.5.
> build: update `github.com/shirou/gopsutil` to v4

- docs/content/docs.md
- docs/content/flags.md
This PR adds a brief description of the `stringArray` parameter descriptor to flags.md, pointing out that there is actually no such thing as a string array for flag parameters, and that the user would have to repeat the flag for each string. 
See also: https://forum.rclone.org/t/questions-about-include-and-filter-and-stringarray/1638/2
> docs: explain the stringArray flag parameter descriptor

- lib/batcher/options.go
To ~~delete~~ deprecate an unused option in lib/batcher/.
I found that lib/batcher/ defines a `batch_commit_timeout` config, which is picked up by the dropbox and googlephotos backends, but couldn't find a struct field anywhere that hooks up to it.
With `git log -S`, I found that the code using the `BatchCommitTimeout` field was deleted in a1a8c21c709c1051df18d2b94e9eeecc158c7bc2, and then the struct field itself was deleted in b94806a1430172419bd945340611068bcaf6ff00. But the option's definition stuck around and so did the documentation, e.g. [RCLONE_DROPBOX_BATCH_COMMIT_TIMEOUT](https://github.com/rclone/rclone/blob/f8d782c02de5e42c354f281b4f32c4128fa5db1e/docs/content/dropbox.md?plain=1#L466-L469)!
> lib/batcher: Deprecate unused option: batch_commit_timeout

- backend/internetarchive/internetarchive.go
We want to start using rclone inside of the Internet Archive to upload files!
The goal of this PR is to bring support for item metadata fields for the Internet Archive backend. This is used to set collections, mediatype, item's title, etc.
It's my first time interacting with the rclone codebase, so I hope I didn't miss any obvious ways to do things. Please help me correct my work in case I did! :)
Not as far as I know.
> internetarchive: fix item's metadata support

- cmd/cmd.go
Fix issue: https://github.com/rclone/rclone/issues/8248
No, it wasn't.
> metrics: disable the metrics server if the main server is not configured to start

- backend/azureblob/azureblob.go
- docs/content/azureblob.md
Add support for `x-ms-tags` upload header. This will allow key value tags to be set for AzureBlob objects providing easier querying. 
No
> azureblob: add support for `x-ms-tags` header

- cmd/config/config.go
- fs/config/config.go
- fs/config/rc.go
Hi, I'm packaging this downstream and have a script printing logs when it shouldn't.
Is `fs.Logf` the right method to use in this context?
Thanks!
Fixes #8190
See #8190
> fs/config: fix certain logs ignoring `--quiet`

- backend/chunker/chunker.go
- backend/drive/drive.go
- backend/sugarsync/sugarsync.go
- cmd/bisync/bisync_test.go
- cmd/bisync/deltas.go
A one-line change that should hopefully fix 49 integration tests 😅 
https://github.com/rclone/rclone/commit/5f70918e2c867e0bf8c4ff38b34960738dbd4883 introduced a new `INFO` log when making a directory, which differs depending on whether the backend supports setting directory metadata. This caused false positives on the bisync `createemptysrcdirs` test.
This fixes it by ignoring that log line.
No
> bisync: fix false positive on integration tests

- fs/sync/sync.go
- fs/sync/sync_test.go
This will make rclone sync directory mtimes by default if they've changed on the src, just like it is for files. 
This works both with and without empty directories and does _not_ change any default. 
Fixes #8317
> Make rclone sync directory mtimes 

- cmd/cmd.go
for #8378
Fix https://github.com/rclone/rclone/issues/8378
Yes: https://github.com/rclone/rclone/issues/8378
Well, I guess there could be a test that runs rclone with an empty argv.  Hopefully this PR is ok without one.
> cli: don't crash if rclone is invoked without any arguments

- vfs/dir.go
- vfs/dir_test.go
The VFS directory cache layer didn't update directory properties like the last modified time at all, as the new objects were not used. The same problem is already solved for files, implement the same solution for directories.
Fixes #6335
> vfs: fix directory cache serving stale data

- backend/dropbox/dropbox.go
- fstest/test_all/config.yaml
Dropbox only allows public links with expiry for certain account types. Rather than erroring for other accounts, retry without expiry.
Without this PR, one of the Dropbox fstests can fail on certain accounts:
```
$ go test -v -remote dropboxtest: -run 'TestIntegration/FsMkdir/FsPutFiles/PublicLink'
=== RUN   TestIntegration
fstests.go:442: Using remote "dropboxtest:"
=== RUN   TestIntegration/FsMkdir
=== RUN   TestIntegration/FsMkdir/FsPutFiles
=== RUN   TestIntegration/FsMkdir/FsPutFiles/PublicLink
fstests.go:2038: 
Error Trace:	/home/vasi/src/rclone/fstest/fstests/fstests.go:2038
Error:      	Received unexpected error:
settings_error/not_authorized/...
Test:       	TestIntegration/FsMkdir/FsPutFiles/PublicLink
2025/02/15 19:28:24 ERROR : : error listing: directory not found
=== NAME …
```
> dropbox: Retry link without expiry

- cmd/gitannex/e2e_test.go
- cmd/gitannex/gitannex.go
- cmd/gitannex/gitannex_test.go
- cmd/gitannex/layout.go
- fstest/test_all/config.yaml
This enables the unit tests to run on any given backend, via the `-remote` flag, e.g. `go test -v ./cmd/gitannex/... -remote dropbox:`.
We should also port the gitannex e2e tests at some point.
Issue: #7984
> cmd/gitannex: Port unit tests to fstest

- fs/rc/rcserver/rcserver.go
- fs/rc/rcserver/rcserver_test.go
Some libraries use `application/json; charset=utf-8` as their `Content-Type`, which is valid. However we were not decoding the JSON body in that case, resulting in issues communicating parameters to the rcserver. This change improves the checks made against the provided `Content-Type`.
Not that I'm aware of.
> rcserver: improve content-type check

- cmd/copyto/copyto.go
Knowing that cat is the tool for byte slicing would have saved me a lot of time from emulating this via mount with caching minimum and direct-io.
Updating the docs with this bread-crumb so that users in the future can easily discover that `cat --offset X --count Y` is the proper sub command to get a byte slice out of large remote file.
> Documentation - Add note for using `rclone cat` for slicing out a byte range from a file, embedded in the copy-to documentation.

- cmd/gitannex/gitannex.go
- cmd/gitannex/gitannex_test.go
The "rcloneremotename" (aka "target") config parameter is now permitted
to contain (1) remote names that are defined by environment variables,
but not in an rclone config file, and (2) backend strings such as
":memory:".
This should fix some of the failing integration tests. For context:
https://github.com/rclone/rclone/pull/7987#issuecomment-2688580667
Issue https://github.com/rclone/rclone/issues/7984
> cmd/gitannex: Tweak remote parsing to accept any backend

- vfs/vfs.md
docs mention an option that doesn't exist, i assume a typo of size instead of space based on context
not that i'm aware
> docs: fix incorrect mentions of vfs-cache-min-free-size 

- backend/http/http.go
Fixes #8428 by ensuring that `http` returns the correct root when pointing to a file (as opposed to a dir).
This was formalized in https://github.com/rclone/rclone/commit/c69eb84573c85206ab028eda2987180e049ef2e4 But it appears that we forgot to update `http`, and the `FsRoot` test didn't catch it because we don't currently have an `http` integration test.
- #8428
> http: correct root if definitely pointing to a file - fixes #8428

- backend/webdav/api/types.go
- backend/webdav/webdav.go
Retry PROPFINDS when the server returns 425 Too Early.
Debugging an rclone mount with oCIS we were seeing rclone trying to delete files that were fully uploaded, but had not yet been virus scanned. oCIS returns a 425 Too Early response in that case.
> webdav backend: retry propfind on 425 status

- fs/operations/multithread.go
a simple bug fix, the `err` is nil, should use `er2`
> operations: fix call fmt.Errorf with wrong err

- cmd/copyurl/copyurl.go
- docs/content/commands/rclone_copyurl.md
Running the `rclone copyurl` command with the `--auto-filename-header` option will produce the following error:
`Fatal error: unknown flag: --auto-filename-header`
Considering the updated option `--header-filename` is also listed in the document, I assume this is a mistake. If I've misunderstood, my apologies.
Also changed 'Troublshooting' to 'Troubleshooting'.
Thank you!
A search on the `rclone` GitHub repository for `is:issue state:open "--auto-filename-header"` & `is:pr is:open "--auto-filename-header"` returns nothing, and a Google search for `"rclone" "--auto-filename-header" "error"|"fatal error"|"unknown flag"` doesn't return anything relevant. I don't believe the issue has previously been discussed.
> docs: replace option `--auto-filename-header` with `--header-filename`

- cmd/gitannex/configparse.go
- cmd/gitannex/gitannex.go
- cmd/gitannex/gitannex_test.go
With the changes in this PR, the gitannex subcommand will no longer reject remote strings with options, e.g. `"TestAzureBlob,directory_markers:"`. Previously, I only added support for options when the string named a backend.
I'm also sneaking in two improvements:
* I refactored/reorganized the code related to "config" parameters (the values received from git-annex proper, nothing to do with the `config` package).
* I made the INITREMOTE handler stricter, so that it rejects invalid layouts early on, before any transfers are attempted.
(More details in the commit messages.)
Issue #7984
https://github.com/rclone/rclone/pull/7987#issuecomment-2688580667
> cmd/gitannex: Permit remotes with options

- fs/config/ui.go
This change fixes #8480. When reading the configuration password from stdin, the original behavior of Rclone was to throw an error if the stream hit EOF before encountering a line break even if a password was provided. This change would ignore the EOF as long as the read string is not empty.
The issue #8480 presents the root cause and mentions proposed change, but no discussion has occurred yet.
> fs/config: Read configuration password from EOFed stdin - fixes #8480

- docs/content/docker.md
I think it would be nice if the readme clarifies that fuse3 vs fuse is required, or fuse is required and not fuse3.
I can't think why fuse would be chosen over fuse3 ? 
It would be good to explicitly state if fuse3 is not the correct version.
- [*] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [*] I'm done, this Pull Request is ready for review :-)
> fuse version query

- vfs/dir.go
When querying directories with large datasets, if the query duration exceeds the directory cache expiration time, the cache becomes invalid by the time results are retrieved. Every execution of _readDir triggers _readDirFromEntries, resulting in prolonged processing times.
> vfs-dir: the directory cache not effect

- cmd/authorize/authorize.go
- cmd/authorize/authorize_test.go
Before this change, the help text for 'authorize' didn't show that
the command requires at least one argument, with two optional arguments.
This made it impossible for users to know how to use the command
correctly from the help output alone.
Updated to clearly show '<fs name> [base64_json_blob | client_id client_secret]'
in the usage text.
No, this was a direct fix for an issue I encountered while using the command.
> cmd/authorize: show required arguments in help text

- backend/iclouddrive/api/drive.go
At present any created file (eg through the touch command, copy, mount etc) is read-only in iCloud. This means it cannot be edited other devices as one would reasonably expect by default.
https://forum.rclone.org/t/icloud-and-file-editing-permissions/50659
> iclouddrive: fix so created files are writable

- cmd/serve/s3/serve_s3.md
Fixed the anchor link in the documentation that points to the SSL/TLS section. This change ensures the link directs correctly to the intended section (#tls-ssl) instead of the incorrect #ssl-tls.
No functional code changes, documentation only.
> docs: fix anchor link for SSL documentation

- cmd/serve/s3/server.go
Not needed as `w.handler` is reassigned right after that.
- Nit improvement
> Remove redundant handler initialization

- docs/content/faq.md
To make it more obvious to users who don't need to configure remotes that they can create an empty `rclone.conf` file to get rid of the annoying notices after every command like:
```
2025/05/06 17:42:15 NOTICE: Config file "/Users/jgeerling/.config/rclone/rclone.conf" not found - using defaults
```
Yes, see https://forum.rclone.org/t/notice-about-missing-rclone-conf-is-annoying/51116
> Add FAQ for getting rid of the 'Config file not found' message

- backend/googlephotos/googlephotos.go
- docs/content/googlephotos.md
Google Photos has updated their allowed scopes and now the only capability that RClone can offer is to upload new photos. It will also be able to download photos, but only those that Rclone uploaded.
https://github.com/rclone/rclone/issues/8434
> googlephotos: update readOnly/Write scopes - fixes #8434

- cmd/serve/s3/list.go
Add a trailing slash to s3 ListObjectsV2 response because some clients expect a trailing forward slash to distinguish if the returned object is a directory.
Reference: https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html
Fixes #8464
- [/] I have added tests for all changes in this PR if appropriate. --> I have not enough go skills to write appropriate tests
> cmd serve s3: fix ListObjectsV2 response

- README.md
- backend/s3/s3.go
- docs/content/_index.md
- docs/content/s3.md
- fstest/test_all/config.yaml
Introduce a FlashBlade Object Storage provider with preset quirks.
Pure Storage FlashBlade is an enterprise object storage platform that provides S3-compatible APIs. This change adds FlashBlade as a new provider option in the S3 backend.
Before this change, FlashBlade users had to use the "Other" provider with manual configuration of various compatibility flags. This often resulted in suboptimal performance due to conservative default settings.
After this change, users can select the "FlashBlade" S3 provider and get an optimal configuration:
- ListObjectsV2 enabled for better performance
- AWS-compatible multipart ETags for reliable transfers
- Proper handling of "AlreadyOwnedByYou" bucket creation responses
- Path-style URLs by default (virtual-host style with DNS setup)
- Unsigned …
> Introduce FlashBlade Object Storage provider

- cmd/copy/copy.go
- cmd/copyto/copyto.go
- cmd/move/move.go
- cmd/moveto/moveto.go
- cmd/sync/sync.go
- fs/operations/logger.go
- fs/operations/operationsflags/operationsflags.go
- fs/operations/operationsflags/operationsflags.md
This enables the logger parameters (`--combined`, `--missing-on-src` etc.) for the `rclone copy` and `move` commands (as well as their `copyto` and `moveto` variants) akin to `rclone sync`. Warnings for unsupported/wonky flag combinations are also printed, e.g. when the destination is not traversed but `--dest-after` is specified.
I have not yet added the requisite documentation to the features yet as I wanted to check back whether this is a good way to go about it first. I aimed for factoring out the commonalities for this feature rather than copying it all over the place, but I'm not sure if I put things in the best spot they can be.
Issue: #8115
> Implement logger parameters for `copy`, `copyto`, `move` & `moveto`

- docs/content/onedrive.md
Microsoft has moved AAD (and technically deprecated it), and now requires a free, but verified, Azure account to create your own client id. The docs are currently pointing to an older interface that has completely deprecated creating new apps.
Briefly: https://github.com/rclone/rclone/issues/8027
I found corrected instructions were posted to the rclone forums here: https://forum.rclone.org/t/ondrive-personal-client-id-and-key-creation-changed-help-needed/47383/21
I was able to make a client ID sync to my personal OneDrive account this evening via the link from the forum.
> docs: update OneDrive client ID instructions to current Azure AD portal - fixes #8027

- backend/b2/b2.go
- backend/b2/b2_internal_test.go
Currently, `versionAt` is ignored from the `NewObject` API, which means that when retrieving an object with `versionAt` always the latest version is returned, or no object if it was soft deleted.
This is evident when using rclone with restic. 
Example
```
$ rclone serve restic --b2-version-at 2025-05-08T10:00:00 b2:my-backups
```
```
$ restic --no-lock --repo rest:http://127.0.0.1:8080/ restore latest
Load(<data/689e1dbc45>, 1958097, 65019165) failed: <data/689e1dbc45> does not exist
ignoring error for /mybackup.txt: ReadFull(<data/689e1dbc45>): <data/689e1dbc45> does not exist
```
No, initially I thought it was a configuration issue on my side, but when I found out that it was not I was already in the place where to fix it.
> fix: add b2 versionAt support to NewObject api

- backend/webdav/webdav.go
When I use rclone to copy files from local storage to a owncloud compatible webdav server, if the specific object exists on the remote and its checksum differs from the local object, the modified time of the remote object doesn't change. If the checksums match, rclone will update remote's modified time to be the modified time of local object.
Send the modified time of local object in `X-OC-Mtime` header.
This regression is introduced in [0b96713](https://github.com/rclone/rclone/commit/0b9671313b14ffe839ecbd7dd2ae5ac7f6f05db8).
> webdav: send the modtime of local object instead of remote

- fs/operations/check.go
On code inspection I noticed that the reported number of differences and errors after a check operation would always the same. It reports `"%d differences found"` using `accounting.Stats(ctx).GetErrors()`, followed by `"%d errors while checking"` using the exact same parameter, only difference is that "differences" is always reported while "errors" is only reported if `>0`. I cannot see a reason why this should be of any importance.
> Check: Report differences and error counts separately

- docs/content/changelog.md
- docs/content/docs.md
I think consistently using `#` prefixed header format for headers - at any level - is best. I find the alternative format for level 1 and 2 headers, `====` and `-----`, is often just confusing - at least the level 2 which is typically mixed in between other level headers. And at least when, as was the case in the usage docs, there is a mix of both - inconsistent use of both variants of level 2 header format.
The situation in docs.md was:
- The level 1 header is written as:
> \# Usage
- Some level 2 headers:
> Configure
> \---------
- Other level 2 headers:
> \## Metadata support {#metadata}
- And, obviously, all lower level headers in the only supported format:
> \### Valid remote names
Edit: When running [markdownlint](https://github.com/DavidAnson/markdownlint) with default …
> Use consistent markdown heading syntax

- backend/s3/s3.go
To addresses a potential memory leak in the S3 backend where 
strings extracted from large API responses were keeping the entire 
response in memory. The issue occurs because Go strings share underlying 
memory with their source, preventing garbage collection of large XML 
responses even when only small substrings are needed.
#8683
> backend/s3: Fix memory leak by cloning strings #8683

- backend/smb/connpool.go
- backend/smb/kerberos.go
- backend/smb/kerberos_test.go
Depends on https://github.com/rclone/rclone/pull/8559
This PR enhances the **SMB** backend in Rclone to automatically refresh Kerberos credentials when the associated `ccache` file is updated. Previously, credentials were only loaded once per path and cached indefinitely, which caused issues when service tickets expired or the cache was renewed on the server.
**Changes**
- Track the `mtime` (modification time) of each Kerberos ccache file.
- Reload the credentials and Kerberos client only if the file's `mtime` has changed.
- Avoid redundant reloads by caching both client and load errors.
- Refactor function calls to allow test injection.
- Add a unit test to validate reload behavior when the ccache file is modified.
> smb: refresh Kerberos credentials when ccache file changes

- fs/operations/rc.go
when posting to rclone remote control api endpoinit "operations/check", "oneWay" key in json payload always got ignored, and rclone always perform a bi-direction check. it turn out to be rcCheck function in rclone/fs/operations/rc.go getting the wrong key("oneway") in json payload, which should be "oneWay".
change
`oneway, _ := in.GetBool("oneway")`
to
`oneway, _ := in.GetBool("oneWay")`
fix the problem
https://forum.rclone.org/t/rclone-rcd-operations-check-api-ignore-oneway-true/51939
- [✔] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [✔ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [✔ ] I'm done, this Pull Request …
> fs: fix operations/check api endpoint ignoring "oneWay" parameter.

- backend/pikpak/pikpak.go
Previously, we didn't adequately account for PikPak's behavior of creating numbered copies (e.g., `filename (1).ext`) when a name collision occurred during server-side file copy or move operations. This oversight could lead to data discrepancies.
This commit implements a more robust conflict resolution mechanism to prevent such issues and ensure consistent data when files are copied or moved within PikPak.
N/A
> pikpak: improved handling of file conflicts during copy/move

- fs/config/rc.go
- fs/config/rc_test.go
Add a call to unlock the configuration file
https://forum.rclone.org/t/librclone-rpc-encryption-configuration/50761
https://forum.rclone.org/t/askpassword-in-remote-control/50768/2
> add rc call to unlock config

- fs/config/rc.go
- fs/config/rc_test.go
The remote call `config/listremotes` sends nil
> listremotes should send an empty array

- backend/local/local.go
Fix symlink listing with `--copy-links` enabled.
https://github.com/rclone/rclone/issues/8737
> local: fix --copy-links on Windows when listing Junction points

- docs/content/faq.md
Make the FAQ entry about `SSL_CERT_FILE` and `SSL_CERT_DIR` env vars more clear.
https://github.com/rclone/rclone/pull/1977#issuecomment-3201961570
> FAQ: specify the availability of SSL_CERT_* env vars

- docs/content/docs.md
Reading the docs, I wondered how this can be achieved.
Might not be wanted as part of the docs, though.
> Add note how to easily add date as suffix in bash

- docs/content/docs.md
This PR fixes a minor grammar issue in the rclone subcommand documentation.  
The original sentence used a double article:
"A subcommand is a the rclone operation required (e.g. sync, copy, ls)."
I found the "a the" combination a bit jarring while reading, so it has been corrected to:
"A subcommand is an rclone operation required (e.g. sync, copy, ls)."
This improves clarity and readability for users without changing the meaning.
No, this is a small documentation correction.
> Docs: Clarify subcommand description in rclone docs

- cmd/bisync/bisync_test.go
Fixes for bisync integration tests broken by https://github.com/rclone/rclone/commit/9e200531b1490000656031c42fff4d95477e1b46.
- https://github.com/rclone/rclone/pull/8770#issuecomment-3241792807
> bisync: ignore expected "nothing to transfer" differences on tests

- cmd/test/makefiles/makefiles.go
- cmd/test/makefiles/speed.go
Run speed test to try and work in a given time budget, uploading randomly created files to the remote then downloading them again.
Fixes #3198
> test speed: adds command to test a specified remotes speed

- cmd/bisync/bisync_test.go
Two fixes for bisync integration tests on `koofr` and `chunker`.
@ncw For the `chunker` issue (which I think I tracked down), it should be noted that there is an underlying bug in `operations` that this PR does _not_ fix, but just side-steps. 
The bug is that `operations.Move` (per its function comment) is supposed to be only accounted as a check. But on backends like `S3` which can `Copy` but not `Move`, the move falls back to server-side copy and ends up getting counted as a transfer anyway, even when `isTransfer == false`.
https://github.com/rclone/rclone/blob/99e8a63df2528e4fd470821095cbeb32e8a827a3/fs/operations/operations.go#L413-L416
https://github.com/rclone/rclone/blob/99e8a63df2528e4fd470821095cbeb32e8a827a3/fs/operations/operations.go#L506 …
> bisync: fix koofr and chunker integration tests

- cmd/bisync/listing.go
Before this change, rclone could crash during `modifyListing` if a rename's `srcNewName` is known but not found in the `srcList` (`srcNewName != "" && new == nil`). This scenario should not happen, but if it does, we should print an error instead of crashing.
On #8458 there is a report of this possibly happening on `v1.68.2`. It is unknown what the underlying issue was, and whether it still exists in the latest version, but if it does, the user will now see an error and debug info instead of a crash.
- #8458
> bisync: fix error handling for renamed conflicts

- backend/local/local.go
- backend/local/local_internal_windows_test.go
Before this change, Rmdir (and other commands that rely on Rmdir) would fail with "Access is denied" on Windows, if the directory had FILE_ATTRIBUTE_READONLY. This could happen if, for example, an empty folder had a custom icon added via Windows Explorer's interface (Properties => Customize => Change Icon...). 
However, Microsoft docs indicate that "This attribute is not honored on directories."
https://learn.microsoft.com/en-us/windows/win32/fileio/file-attribute-constants#file_attribute_readonly
Accordingly, this created an odd situation where such directories were removable (by their owner) via File Explorer and the rd command, but not via rclone.
An upstream issue has been open since 2018, but has not yet resulted in a fix. https://github.com/golang/go/issues/26295
This change gets …
> `local`: fix `rmdir` "Access is denied" on windows - fixes #8363

- cmd/serve/http/http.go
- lib/http/server.go
Noticed that serve http didn't print out a link when started, unlike the other the commands.
> serve http: fix: logging url on start

- cmd/authorize/authorize.go
- cmd/authorize/authorize_test.go
- docs/content/box.md
- docs/content/drive.md
- docs/content/dropbox.md
- docs/content/googlecloudstorage.md
- docs/content/googlephotos.md
- docs/content/hidrive.md
- docs/content/onedrive.md
- docs/content/pcloud.md
- docs/content/premiumizeme.md
- docs/content/putio.md
- docs/content/remote_setup.md
- docs/content/sharefile.md
- docs/content/yandex.md
- docs/content/zoho.md
- docs/layouts/chrome/navbar.html
- fs/config/authorize.go
I found the https://rclone.org/remote_setup page a bit outdated, so I updated it, as well as some small updates to the related https://rclone.org/commands/rclone_authorize/ page and others.
PS: The https://rclone.org/remote_setup page is not listed in the "Docs" drop down menu, it is only linked to from the FAQ page and some backend docs pages. Should we list it?
> Remote setup doc improvements

- backend/jottacloud/jottacloud.go
- docs/content/jottacloud.md
Some background - if my investigations are correct:
- "MediaMarkt" is a German company that (according to wikipedia) operates in Germany, Austria, Belgium, Hungary, Italy, Luxembourg, Netherlands, Poland, Portugal (2004 - October 1st 2025 - turned into Darty (Fnac)), Spain, Switzerland, Turkey.
- In Germany, they offer a cloud service through the name "Let's Go Cloud" ("LET'S GO CLOUD powered by Jottacloud bei MediaMarkt").
- I already added support for this in #8855, and it was discussed in #8852.
- "MediaMarkt Cloud" is a service they offer in Spain, Poland, Netherlands, Belgium and Luxembourg.
- They seem to basically share the same service; all use domain mediamarkt.jottacloud.com and realm "mediamarkt". They can also use the same client_id and scopes as other whitelabels.
- There are …
> Add support for MediaMarkt Cloud as a Jottacloud whitelabel service

- backend/swift/swift.go
- backend/swift/swift_test.go
- fstest/testserver/init.d/TestSwiftAIO
- fstest/testserver/init.d/TestSwiftAIO.d/remakerings
- fstest/testserver/init.d/TestSwiftAIOsegments
- fstest/testserver/testserver.go
Ensure that if we need to create a segments container it uses the same storage policy as the root container.
Fixes #8858
> swift: If storage_policy isn't set, use the root containers policy
